### ISSUE TITLE
Charges and Recent Transaction section shows 'null' in TextView.

### ISSUE THREAD

**Issue by rahul-jha98** [openMF/self-service-app#1000]
**Summary:**

In the charges section, if currency symbol is not present user will see null in UI.
Like "null 50" will be shown as Due amount. 

**Expected behaviour:**

If the symbol is available for the currency then show the symbol. If it is not available, show the currency code like INR, AFN etc. 
I think," **INR 50**" is better than "**null 50**" if rupee symbol is not present.

**Observed behaviour:**

We see "**null 50**" if no currency symbol is present.

**Device and Android version:**

Moto G5 Plus, Android 8.1

**Screenshots:**

![screenshot_20190122-080824](https://user-images.githubusercontent.com/29267275/51510277-7c9e9600-1e22-11e9-871e-d613c1bb5194.png)

**Comment by rahul-jha98** [comment]
@luckyman20 Shall I begin working on it?

**Comment by rahul-jha98** [comment]
@luckyman20 I see that the same problem exists in Recent Transactions Section of the app.

Should I solve it in the fix for this issue or make a new issue for it?

![screenshot_20190122-140936](https://user-images.githubusercontent.com/29267275/51522828-41b35700-1e50-11e9-93b6-1de9954b1c7b.png)

**Comment by luckyman20** [comment]
Update the issue for that.
