### ISSUE TITLE
FAB Disappears in fragment transition

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1001]
**Summary:**

When the user checks loan accounts, then if he scrolls and goes to another section, then on returning he cant see the FAB.

**Screenshots:**
![videotogif_2019 01 22_15 27 00](https://user-images.githubusercontent.com/38163725/51527612-d8851100-1e5a-11e9-87e8-68948bfdb90f.gif)

**Comment by shiv07tiwari** [comment]
@luckyman20 I want to work on this issue.

**Comment by devansh-299** [comment]
@shiv07tiwari Can I work on this issue?

**Comment by luckyman20** [comment]
@devansh-299 Go ahead if this is still reproducible.
