### ISSUE TITLE
Share highlighted in NavDrawer after cancelling the share option

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1004]
**Summary:**
Share highlighted in NavDrawer after cancelling the share option
**Steps to reproduce:**
Open Nav Drawer and select share
Cancel when you get options
**Expected behaviour:**
Home should be highlighted
**Observed behaviour:**
Share is highlighted

**Comment by shiv07tiwari** [comment]
@luckyman20 I want to work on this issue.

**Comment by luckyman20** [comment]
Unable to reproduce this issue.
