### ISSUE TITLE
Invalid Link in share option

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1005]
**Summary:**

We have a wrong linking of string which results in wrong share option link.

**Steps to reproduce:**

Share the app, and click on message link

**Expected behaviour:**
It should open App store page to download the app.
**Observed behaviour:**

Invalid page.
**Device and Android version:**

**Comment by shiv07tiwari** [comment]
@luckyman20 I want to work on this issue.

**Comment by luckyman20** [comment]
Please share the screenshot for same.

**Comment by shiv07tiwari** [comment]
![img_20190123_151836](https://user-images.githubusercontent.com/38163725/51597870-4a745d80-1f22-11e9-8cb9-268b29c79972.jpg)

**Comment by shiv07tiwari** [comment]
Here, we see that the link is broken.

**Comment by luckyman20** [comment]
Go ahead.
