### ISSUE TITLE
User profile opens twice 

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1010]
**Summary:**

User profile opens twice when quickly opened twice.

**Steps to reproduce:**

Home 

Quickly Click on user profile twice.

**Expected behaviour:**
Profile should open once.

**Observed behaviour:**
Profile opens twice.

**Comment by shiv07tiwari** [comment]
@luckyman20  I want to fix this.

**Comment by therajanmaurya** [comment]
As I said earlier this is not an issue. Intent opening with animation that give small time window to do any action and if you will click again. It will open again. 

If you want to fix this then make the view disable after the first click.

**Comment by shiv07tiwari** [comment]
@therajanmaurya This issue is similar to https://github.com/openMF/mifos-mobile/pull/1036
That one was accepted, so can this be taken as a bug ?
