### ISSUE TITLE
Open Source license opens twice

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1012]
**Summary:**

Open source license opens twice when clicked twice rapidly.

**Steps to reproduce:**

About -> click on license twice rapidly.

**Expected behaviour:**
It should open only once

**Observed behaviour:**
It opens twice.

**Comment by shiv07tiwari** [comment]
@luckyman20 I want to work on this.

**Comment by therajanmaurya** [comment]
This is not an issue. It is normal behavior. If you will try to click on any button in any app twice before opening the app. It will intent twice.
