### ISSUE TITLE
LogOut is highlighted after cancellation.

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1014]
**Summary:**

LogOut is highlighted after cancellation.

**Steps to reproduce:**

Click on Logout -> click somewhere outside the dialog box.

**Expected behaviour:**

Home should be highlighted.

**Observed behaviour:**

LogOut is highlighted.

**Comment by shiv07tiwari** [comment]
@luckyman20 I want to fix this.

**Comment by shiv07tiwari** [comment]
@miPlodder @therajanmaurya To fix this, we have 2 options : 
1. Disable the dialog box to close if clicked outside the box.
2. Override the ontouch event for dialog box.
Which should I apply ?

**Comment by shiv07tiwari** [comment]
![videotogif_2019 02 18_13 05 52](https://user-images.githubusercontent.com/38163725/52934993-1e5fc700-337e-11e9-873c-879dbfb5f35c.gif)
@luckyman20 Added GIF.
In first try, the cancel button is pressed, which perfectly highlights the home.
In second try, area outside the dialog box is clicked, in which logout is highlighted.

**Comment by luckyman20** [comment]
Do not allow the user to click outside the dialog box.
