### ISSUE TITLE
Diaplay currency in Home Screen

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1015]
**Summary:**

As a user, I want that my home screen should display amount as well as currency for loans and savings.
Right now it doesnt show the currency.

**Steps to reproduce:**

Home screen

**Expected behaviour:**

Show the currency

**Observed behaviour:**

No currency displayed.

**Comment by shiv07tiwari** [comment]
@luckyman20 I want to add this feature.

**Comment by devanshi7799** [comment]
@shiv07tiwari  Can i work on this issue?
