### ISSUE TITLE
Toolbar title in Add Beneficiary activity changes on screen rotation

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1018]
**Summary:**
When screen rotation is enabled the toolbar text changes.

**Steps to reproduce:**
1. From Home click on  ```Beneficiaries``` option.
1. Click on Fab and choose ```Add``` option.

**Expected behaviour:**

The toolbar name should be  **Add Beneficiary**.

**Observed behaviour:**

The toolbar name changes to **Mifos Mobile**

**Device and Android version:**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Screenshots:**

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/43827236/51617689-c2f31280-1f52-11e9-8055-abc75e02b1b9.gif)

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue.

**Comment by RajaVamsi11** [comment]
@Starcode71Ooze What are the credentials you are using to log in in the self-service app? Given credentials in the wiki are not working.

**Comment by ShivangiSingh17** [comment]
@RajaVamsi11  I am also facing the same problem.Credentials mentioned in wiki are not working now.

**Comment by ShivangiSingh17** [comment]
@RajaVamsi11 did you get the application working back after staging?

**Comment by RajaVamsi11** [comment]
No

**Comment by geekanamika** [comment]
Issue already resolved in #1022
