### ISSUE TITLE
Feature Help

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#102]
**Summary:**

There is no feature for help.

![image](https://cloud.githubusercontent.com/assets/5724482/23497977/86daefe4-ff4b-11e6-95a0-75e627aa072e.png)

Add an item in navigation drawer Help and add Google Maps and above UI.

**Comment by dilpreet2028** [comment]
I would like to work on this

**Comment by immabhay** [comment]
I would like to work on this issue. @therajanmaurya

**Comment by therajanmaurya** [comment]
Go ahead 👍

**Comment by therajanmaurya** [comment]
Added in #105
