### ISSUE TITLE
Scroll function is not available on screen rotation

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1024]
**Summary:**
On screen rotation in Add Beneficiary section the scroll option is not available and the screen is just set to some limited options.

**Steps to reproduce:**
1. From Home screen, click on ```Beneficiaries``` 
1. Click on Fab option.
1. Enable screen rotation.

**Expected behaviour:**
 On screen rotation in Add Beneficiary section all the select mode options **Add**, **Scan** and **Upload QR** should be available.

**Observed behaviour:**
On changing orientation only **Add** and **Scan** options are seen on the screen.

**Device and Android version:**

Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Screenshots:**
![noscroll](https://user-images.githubusercontent.com/43827236/51783658-189e0980-2163-11e9-89c5-f34c3811d51b.gif)

**Comment by ShivangiSingh17** [comment]
Please I would like to work on this issue.

**Comment by ShivangiSingh17** [comment]
@RajaVamsi11 Setting an app to work in one mode is not a flexible way to solve a problem. Also it a user constraint.

**Comment by RajaVamsi11** [comment]
@ShivangiSingh17 Can you please refer this [link](https://medium.com/mindorks/case-study-40-top-android-apps-have-locked-orientation-7c242f795006).

**Comment by luckyman20** [comment]
@ShivangiSingh17 I agree wtih @RajaVamsi11, such apps should only exist in portrait mode.

**Comment by ShivangiSingh17** [comment]
@luckyman20 sure. 
In that case we need to have constraint on all the activities as well.

**Comment by luckyman20** [comment]
@ShivangiSingh17 We can do it in one go. Can you please open another issue for that (if not existing already)?

**Comment by rchtgpt** [comment]
So we don't require scroll function in landscape mode anymore, do we ?

**Comment by ShivangiSingh17** [comment]
@luckyman20, there was an issue for a particular fragment but there was a lot of clashes and finally it was closed. I will open a new open for the whole application. That will be a better.

**Comment by ShivangiSingh17** [comment]
@rachittt since we are restricting the whole application to work in the portrait mode, I don't think there is a need for scroll function in landscape mode anymore.

**Comment by luckyman20** [comment]
@ShivangiSingh17 closing this issue as discussed.
