### ISSUE TITLE
Application loses data inserted by the user

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1027]
**Summary:**
When the user adds information the application shows a pop-up for been updated but the information is lost on returning back. 

**Steps to reproduce:**
1. From Accounts, slide to Loan section.
1. Choose any approval pending account(marked with yellow sider).
1. Click on three vertical dots present on top right  corner and choose View guarantor.
1.Click on  Fab button.Upgrade.  

**Expected behaviour:**

Guarantor information added  by user should be present.

**Observed behaviour:**

Guarantor information added  by user is lost.

**Device and Android version:**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Screenshots:**
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/43827236/51826418-0069ee00-230d-11e9-97f6-e13b2a0bce66.gif)

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue.

**Comment by prashantkh19** [comment]
The guarantors shown in the app are hardcoded, the server response to list the guarantors is an empty list and creation of new guarantors is not supported in the API. So, there is a need to update the API.
