### ISSUE TITLE
Error loading client

### ISSUE THREAD

**Issue by razorahul** [openMF/self-service-app#1039]
**Summary:**

I have tried the Master/Development branch. After it successfully logs in it redirects to client list activity. There its getting 400/401 response from the server.

**Steps to reproduce:**

Login

**Expected behaviour:**

client list
**Observed behaviour:**

Error loading client list.
**Device and Android version:**

Pixel 2XL android version 9

**Comment by ShivangiSingh17** [comment]
@razorahul it might be due to the upgrading of the application to the version 17.07.01.Did you tried staging?

**Comment by razorahul** [comment]
@ShivangiSingh17 I have setup mifos on Ubuntu. And trying to access it through this app from a AVD.

**Comment by luckyman20** [comment]
Issue does not exist anymore.
