### ISSUE TITLE
Modify error handling in ClientAccountsFragment

### ISSUE THREAD

**Issue by YashishDua** [openMF/self-service-app#1041]
**Summary:**

When there is an error in a request at AccountsFragment which further calls `showError`. However instead of showing error once it shows thrice unnecessarily.

**Steps to reproduce:**

Make any sort of error while making a network request in Accounts Fragment.

**Expected behavior:**

Single Toast showing an error.

**Observed behavior:**

3 consecutive Toast messages unnecessarily.

**Comment by luckyman20** [comment]
It looks a good catch, just keep in mind that do not implement Toast, instead use Snackbar.

**Comment by abhin2149** [comment]
Can I work on this issue ?

**Comment by luckyman20** [comment]
@YashishDua Are you working on this issue?

**Comment by luckyman20** [comment]
Issue does not exist anymore.
