### ISSUE TITLE
Code refactoring in ClientAccountsFragment

### ISSUE THREAD

**Issue by YashishDua** [openMF/self-service-app#1042]
**Summary:**

Many functions like showSavingsAccounts have poor code structure and repetition.

**Expected behavior:**

More clean structure and optimized code.

**Comment by luckyman20** [comment]
Please explain a bit more.

**Comment by YashishDua** [comment]
![screen shot 2019-03-04 at 3 58 03 pm](https://user-images.githubusercontent.com/20666950/53727478-5abf1700-3e96-11e9-8366-ae9c00adb708.png)
Above is one example where code refactoring is required. We unnecessarily find fragment twice which adds to up to latency.

![screen shot 2019-03-04 at 3 59 28 pm](https://user-images.githubusercontent.com/20666950/53727551-83471100-3e96-11e9-9059-1aa3c8c7dd93.png)
This function also needs refactoring. In a particular case, three times error is shown. We should make sure once an error is shown, it must not be shown again.

There is a lot to refactor. I would request if we start from this class.

**Comment by ritikaofc** [comment]
Please assign me this issue.

**Comment by luckyman20** [comment]
This issue does not exist after the Kotlin migration.
