### ISSUE TITLE
App crashes without internet while Applying for loan

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1051]
**Summary:**
When the internet is off while clicking on Submit Loan, then App crashes, which should be handled in a graceful manner.
**Steps to reproduce:**

Apply for loan -> Submit loan (Without loan)

**Expected behaviour:**
User should get a message that internet is not available.

**Observed behaviour:**

App crashes.

**Screenshots:**

![videotogif_2019 02 19_01 16 12](https://user-images.githubusercontent.com/38163725/52973620-a7114e00-33e4-11e9-8ff7-e6ab3a36c848.gif)

**Comment by amitYadavDev** [comment]
@shiv07tiwari is it still open?

**Comment by luckyman20** [comment]
Unable to reproduce this issue anymore.
