### ISSUE TITLE
App fails to detect the default language of the mobile and open the app in the default language.

### ISSUE THREAD

**Issue by atm1504** [openMF/self-service-app#1056]
**Summary:**
App fails to detect the default language of the app and open it in the default language of the mobile.

**Steps to reproduce:**
By using locale function, we can easily determine the default language of the mobile, and open that translated version of the app.

**Expected behaviour:**

The app should be able to detect the default language of the mobile, and open it in that version.

**Observed behaviour:**

Suppose, the default language of my mobile is Hindi. If I open the app, I find english version of the app instead of Hindi. This shows, that the app has failed to detect the language of my mobile.

**Comment by atm1504** [comment]
I want to work on this issue.

**Comment by prashantkh19** [comment]
Since no pull request has been sent yet, I would like to work on it.
