### ISSUE TITLE
Add a confirmation dialog in forgot pin.

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1057]
**Summary:**

When user clicks on forgot pin, he is directed to login page.

**Expected behavior:**

He should get a confirmation dialog.
https://github.com/openMF/mobile-wallet/issues/327

**Comment by shambu2k** [comment]
Is this for GCI??

**Comment by santoshconflux** [comment]
@shambu2k , No, Because @shiv07tiwari already sent PR.
