### ISSUE TITLE
Toast is coming in english when I have different language setup in the app.

### ISSUE THREAD

**Issue by atm1504** [openMF/self-service-app#1065]
**Summary:**

Toast is coming in english when I have different language setup in the app.

**Steps to reproduce:**
Write the strings of the toast in the string file

**Expected behaviour:**

The app should display toast in the language the app has been setup.

**Observed behaviour:**

Currently, the app is showing the toast in english only.

**Screenshots:**
![whatsapp image 2019-02-22 at 6 51 10 pm](https://user-images.githubusercontent.com/43731599/53245372-8b9f8f00-36d3-11e9-8abd-b1bd075e4c1d.jpeg)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by atm1504** [comment]
I am working on this issue

**Comment by luckyman20** [comment]
Duplicate issue.
