### ISSUE TITLE
"Beneficiaries" coming in two line.

### ISSUE THREAD

**Issue by atm1504** [openMF/self-service-app#1066]
**Summary:**

On opening the app, the word "Beneficiaries" is coming in 2 lines. Its looking very odd.

**Steps to reproduce:**

Remove the default padding in the layout, and replace it by giving margin in the imageview.

**Expected behaviour:**

The word "Beneficiaries" should come in 1 line.

**Observed behaviour:**

The word "Beneficiaries" is coming in 2 lines.

![beneficiaries](https://user-images.githubusercontent.com/43731599/53247043-5ba6ba80-36d8-11e9-8ba9-64f59eee7b33.jpeg)

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by atm1504** [comment]
I am working in this issue

**Comment by OHassini** [comment]
Hi : ) I just fixed this issue in [this](https://github.com/openMF/mifos-mobile/pull/1234) pull request.
