### ISSUE TITLE
feat: Change App Icon

### ISSUE THREAD

**Issue by vikasdesale** [openMF/self-service-app#107]
**Summary:**
The App still uses Android App default icon. 

**Steps to reproduce:**

Apps Menu on Phone

**Expected behavior:**

Need App Icon related to Application.

**Observed behavior:**

Default Android App Icon

**Device and Android version:**
ALL

**Screenshots:**
<img src="https://cloud.githubusercontent.com/assets/12857075/23519398/c2afe1ea-ff9c-11e6-9252-8e4106f9bf63.png" width="250" height="450"/>

**Comment by code-dagger** [comment]
Can I work on this?

**Comment by vikasdesale** [comment]
Hi @immabhay look at pull request #112

**Comment by hardik124** [comment]
@therajanmaurya  i am new here , can i work on this?

**Comment by therajanmaurya** [comment]
Fixed in #138
