### ISSUE TITLE
Selecting time filter in account transactions does not update start and end date.

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/self-service-app#1072]
**Summary:**

When a time filter is selected, start and end date should be updated for better user experience and complete design.

**Steps to reproduce:**

Accounts->Select an active account->Transactions->Select radio button filter

**Expected behaviour:**

Start and end date should be updated for better UI design.

**Observed behaviour:**

It doesn't get updated.

**Device and Android version:**

Redmi Note 3

**Screenshots:**
![screenshot_2019-02-26-23-59-14-196_org mifos mobilebanking](https://user-images.githubusercontent.com/34986121/53437075-b155cc80-3a22-11e9-8a20-1d0963d599de.png)

**Comment by prashantkh19** [comment]
I would like to take up this issue.
