### ISSUE TITLE
Wrong Toast message in Recent Transactions

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/self-service-app#1073]
**Summary:**

Opening Recent Transactions shows "No more transactions available" on opening. It should only be prompted when a list is scrolled down.

**Steps to reproduce:**

Navigation Drawer->Recent Transactions

**Expected behaviour:**

The toast message should be shown only when a list is scrolled down.

**Observed behaviour:**

The toast message is shown.

**Device and Android version:**

Redmi Note 3

**Screenshots:**
![screenshot_2019-02-27-00-06-40-873_org mifos mobilebanking](https://user-images.githubusercontent.com/34986121/53437787-676de600-3a24-11e9-86d6-f63ccae4a4c4.png)

**Comment by apoorva-mk** [comment]
I'd like to work on this issue.

**Comment by nikhil-sachdeva** [comment]
I'm already working on it. @apoorva-mk

**Comment by amitYadavDev** [comment]
@nikhil-sachdeva is it fixed or can i work on this?
