### ISSUE TITLE
UI changes in Help Fragment

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/self-service-app#1074]
**Summary:**

A BottomNavigationView is implemented in the help fragment. While call and email opens intents outside the app for their respective jobs. Find Locations replaces a fragment which is a correct practice for bottom navigation.

**Steps to reproduce:**

Nav Drawer->Help

**Expected behaviour:**

The app should have FABs or Material Design buttons suiting the theme of the app. According to Material Design and Google Developer guidelines, Bottom Navs are to be used to "switch between top-level content views with a single tap." References : [link1](https://material.io/develop/android/components/bottom-navigation-view/) [link2](https://developer.android.com/reference/android/support/design/widget/BottomNavigationView)

**Observed behaviour:**

A bottom nav is implemented.

**Device and Android version:**

Redmi Note 3

**Screenshots:**
![screenshot_2019-02-27-17-26-15-187_org mifos mobilebanking](https://user-images.githubusercontent.com/34986121/53489234-afd5e400-3ab6-11e9-9f72-6d1936fd9437.png)

**Comment by nikhil-sachdeva** [comment]
@miPlodder would like to know your views on this.

**Comment by devanshi7799** [comment]
@nikhil-sachdeva Can i work on this?

**Comment by deecodesss** [comment]
I'll be  working on this
