### ISSUE TITLE
Consistent UI for Apply for Loan with no internet.

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/self-service-app#1075]
**Summary:**

With no internet, all the other screens show the same screen as the first screenshot, while the Apply for Loan shows a different screen.

**Steps to reproduce:**

Turn off data/wifi -> Apply for Loan

**Expected behaviour:**

The design should be consistent.

**Observed behaviour:**

Inconsistent design.

**Device and Android version:**

Redmi Note 3

**Screenshots:**
![screenshot_2019-02-27-17-13-45-118_org mifos mobilebanking](https://user-images.githubusercontent.com/34986121/53524281-fd793d80-3b04-11e9-861c-81c0225a80c7.png)

![screenshot_2019-02-27-17-13-40-713_org mifos mobilebanking](https://user-images.githubusercontent.com/34986121/53524256-f0f4e500-3b04-11e9-962e-6b36296e1bf2.png)

**Comment by shiv07tiwari** [comment]
@nikhil-sachdeva Their is already a PR for same. https://github.com/openMF/mifos-mobile/pull/1053

**Comment by kmanikanta335** [comment]
can i work on this issue @PratyushSingh07  ?

**Comment by PratyushSingh07** [comment]
Sure, go ahead @kmanikanta335

**Comment by kmanikanta335** [comment]
@PratyushSingh07 pls review it

**Comment by Maan-Sharma** [comment]
hey anyone is work on it
