### ISSUE TITLE
Add Beneficiary window open up twice

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1076]
**Summary:**
On double tapping the fab, the Add Beneficiary window opens up twice. 

**Steps to reproduce:**
Navigation Drawer>Manage Beneficiaries>Double tap fab

**Expected behaviour:**
On clicking the fab the ```Add Beneficiary``` window should open only once. 

**Observed behaviour:**
Add Beneficiary window opens twice on double taping the fab    

**Device and Android version:**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue.

**Comment by shiv07tiwari** [comment]
https://github.com/openMF/mifos-mobile/issues/1012#issuecomment-459598019
@ShivangiSingh17 I think this is a similar issue.

**Comment by ShivangiSingh17** [comment]
Shall I proceed working on this because double tapping on button should not open the window twice. It is not a user stable platform if such a thing happens.

**Comment by shiv07tiwari** [comment]
As per the mentors it is not a valid issue.
To some extent I also agree with it as opening of an activity twice shows that the app is comparatively slow. 
So adding a flag just to prevent the double intent action basically hides the slow performance, whereas we can try to improve the application speed.
Just an opinion.

**Comment by ShivangiSingh17** [comment]
@therajanmaurya shall I proceed working on this issue?

**Comment by luckyman20** [comment]
Unable to reproduce this issue.
