### ISSUE TITLE
Hardcoded text is present

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1078]
**Summary:**
Hardcoded text is present in menu_transfer.xml file. 

**Steps to reproduce:**
On inspecting the code we find a hardcoded text.

**Device and Android version:**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Comment by RajaVamsi11** [comment]
@ShivangiSingh17 This issue has been solved in the #1060 . Please make sure that you read previous issues before making a issue and working on it.
