### ISSUE TITLE
fix:Doesn't support orientation change

### ISSUE THREAD

**Issue by vikasdesale** [openMF/self-service-app#108]
**Summary:**
Doesn't show landscape orientation on rotation of device by the user.

**Steps to reproduce:**

rotate device 

**Expected behavior:**

on rotation change app orientation to landscape. 
  
**Observed behavior:**

only shows portrait orientation on device rotation.

**Device and Android version:**
ALL 

**Screenshots:**
-

**Comment by therajanmaurya** [comment]
Yes, I know. Can you please propose your way of implementing.

**Comment by vikasdesale** [comment]
sir, I would like to use Parcelable and saveInstanceState to implement this feature.This is because app using Parcelable previously so easy to get and save data when screen rotates.
I will start with all
  1.login activity
  2.Navigation Drawer Menus
     i.Tabs on Fragment(Accounts) 
                tabs on click details screens
                   1.saving account details(Activity)
                   2.Loan Account Details(Activity)
                          i.loan summary activity   
                   3.Saving Account actvity             
    ii.RecentTransaction Fragment (doen't have any functionality onClick)
    iii.Charges Fragment(doesn't have any functionality onClick)

 sir @therajanmaurya
             The only problem is How would I keep track of GitHub repository. because I think It takes many commits. Do I need to make the separate issue for each screen? 

Thanks and Regards
Vikas Desale

**Comment by dilpreet96** [comment]
@therajanmaurya We would also have to refract screens for landscape orientation.

**Comment by therajanmaurya** [comment]
@dilpreet96 Please look this issue and check app is supporting orientation for every feature.

**Comment by dilpreet2028** [comment]
Okay @therajanmaurya

**Comment by imGurpreetSK** [comment]
Anyone working on this issue?
@dilpreet96 I would like to start with this.

**Comment by therajanmaurya** [comment]
@GurpreetSK95 Welcome to the community but this issue is resolved here https://github.com/openMF/self-service-app/pull/398.
