### ISSUE TITLE
Incorrect message is displayed in snackbar  

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1087]
**Summary:**
While applying for loan if we enter a principal amount greater or lesser than 10000.00 then a snack bar pops up showing incorrect message.

**Steps to reproduce:**
From the Home screen click on ```Apply for Loan```.

**Expected behaviour:**
Snack bar should show a valid message.

**Observed behaviour:**
Message displayed in bar is *Enter principal amount between 10000.00 and 10000.00*

**Device and Android version:**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Comment by ShivangiSingh17** [comment]
I would like to work on this.

**Comment by amitYadavDev** [comment]
@ShivangiSingh17 is it open, can i work on this?

**Comment by ShivangiSingh17** [comment]
@amit6663 I am on it. Will be sending the PR soon.

**Comment by amitYadavDev** [comment]
> @amit6663 I am on it. Will be sending the PR soon.

How long @ShivangiSingh17

**Comment by ShivangiSingh17** [comment]
Within the next 24hrs. If I am unable to do, you can work on it.

**Comment by amitYadavDev** [comment]
> Within the next 24hrs. If I am unable to do, you can work on it.

@ShivangiSingh17 time is over, now may I work on the issue?

**Comment by ShivangiSingh17** [comment]
Yeah sure
Go ahead

**Comment by ShivangiSingh17** [comment]
@amit6663 are you working on it?

**Comment by amitYadavDev** [comment]
> @amit6663 are you working on it?

yes

**Comment by luckyman20** [comment]
Unable to reproduce this issue.
