### ISSUE TITLE
message should be displayed when user is successfully logged in

### ISSUE THREAD

**Issue by theabhishekavi** [openMF/self-service-app#1088]
**Summary:**

There should be a message when passcode is successfully saved and user is logged in.

**Steps to reproduce:**

Log in using a passcode

**Expected behaviour:**

When passcode is successfully entered there should be a message. 

**Observed behaviour:**

There is no message displayed when a passcode is successfully entered

**Device and Android version:**

Android Version:- 8.1.0

**Comment by theabhishekavi** [comment]
@therajanmaurya should it be implemented?

**Comment by theabhishekavi** [comment]
there are some activity like MifosPassCodeActivitywhich can only be read. how can we write and make changes in them? can you please guide me?

**Comment by shiv07tiwari** [comment]
@theabhishekavi When the login in successful, he is already getting into a Home Screen, which shows that Login is successful. So, I think their is no use of the message.
Am I missing something ?

**Comment by therajanmaurya** [comment]
Shifted to Library Repo: https://github.com/openMF/mifos-passcode/issues/24
