### ISSUE TITLE
Withdrawal and Deposit filter should be added in savings account transaction

### ISSUE THREAD

**Issue by theabhishekavi** [openMF/self-service-app#1096]
**Summary:**

There should be a filter based on withdrawal and deposit

**Steps to reproduce:**

 Open view transactions in saving account account section

**Expected behaviour:**

Based on months there should be one more filter of withdrawal,deposit

**Comment by prashantkh19** [comment]
I would like to work on this.

**Comment by prashantkh19** [comment]
I would like to work on it. I am thinking of making the filter similar to the Account filter.

**Comment by luckyman20** [comment]
Solved in #1184
