### ISSUE TITLE
App crashes when screen is rotated

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1103]
**Summary:**

When the screen is rotated, the app crashes in portrait mode.

![videotogif_2019 03 11_17 48 36](https://user-images.githubusercontent.com/38163725/54123595-2911f700-4426-11e9-9d91-a0deb287523c.gif)

**Comment by RajaVamsi11** [comment]
@shiv07tiwari As soon as #999 will merge, the issues related to screen rotation will fix automatically. There is no need to worry about this type of issues.

**Comment by ShivangiSingh17** [comment]
@shiv07tiwari the app does not crash and works properly when rotated. There might be some build error because I worked on orientation and my app didn't crash.
