### ISSUE TITLE
 App crashes when Contact Us number clicked from the Savings Account and back button pressed.

### ISSUE THREAD

**Issue by apoorva-mk** [openMF/self-service-app#1104]
**Summary:**

 App crashes when Contact Us number clicked from the Savings Account and back button pressed.

**Steps to reproduce:**

How can we reproduce the issue?
- Login to your mifos app
- Click on Accounts
- Click on any account
- Click on the Contact Us number at the bottom
- Press the back button

**Expected behavior:**

It should take user back to the account details page. This behavior is not seen in the main home page activity.  

**Observed behavior:**

The app crashes and when opened again it displays the home page

**Device and Android version:**

Redmi Y2

Android Version : 8.1.0

**Relevant GIF**

![mifos](https://user-images.githubusercontent.com/42450012/54190716-63d56700-44da-11e9-9744-b1950adefb0e.gif)

**Comment by apoorva-mk** [comment]
I'm working on this issue

**Comment by RajaVamsi11** [comment]
@apoorva-mk Can you please add GIF for the above issue.

**Comment by apoorva-mk** [comment]
Hey @RajaVamsi11 I have added the relevant gif.

**Comment by RajaVamsi11** [comment]
@apoorva-mk Looks like a valid issue.
