### ISSUE TITLE
Limits for Phone No, Account number in SignUp page

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1107]
**Summary:**

As the phone numbers are constrained to be 10 digits, and our Account number is also of fixed digits, we should add a check for that before the Sign Up.

**Steps to reproduce:**

Sign Up process

**Expected behaviour:**

User should not be able to Sign Up if the values dont match the size limit.

**Observed behaviour:**

User can Log In at any value.

**Comment by RajaVamsi11** [comment]
@shiv07tiwari I think phone number maximum digits should be 15.

**Comment by shiv07tiwari** [comment]
@RajaVamsi11 Generally the phone numbers are of 10 digits, and then we can add a country code section. Am I missing the logic as to why it should be 15 ?

**Comment by RajaVamsi11** [comment]
@shiv07tiwari  10 digits mobile is for India and some countries. Mobile number digits vary from countries.
Here is the example:
Minimum Length is 4 for Saint Helena (SH, +290)
Maximum Length is 13 for Austria (AT, +43) 

So many of the applications use 15 digits to be standard length. Even mobile wallet project use 15 digits as a maximum limit.

**Comment by shiv07tiwari** [comment]
@RajaVamsi11 Thanks that's a helpful piece of information. I'll make it 15.

**Comment by therajanmaurya** [comment]
No, I don't agree with the fact that phone number hast to 10 digits, we are not building the product for India. it is a global product. and phone number vary according to country.

So we are going to use a country picker library and use it.
