### ISSUE TITLE
Repeated options in add beneficiary if not added.

### ISSUE THREAD

**Issue by apoorva-mk** [openMF/self-service-app#1111]
**Summary:**

If beneficiary not created and the try again button is pressed the account type drop down list shows the same options but repeated again. Every time this is repeated the list options keep getting repeated and copied. Additionally if the repeated options are clicked the app crashes.

**Steps to reproduce:**

- Open Beneficiaries
- Click on Add
- Enter an invalid beneficiary
- Submit beneficiary
- Press try again
- Open the Select Account Type drop down list ( options keep getting repeated every time )

**Expected behavior:**

List options should remain the same.

**Observed behavior:**

List options keep duplicated with every attempt.

**Device and Android version:**

Redmi Y2
Android 8.1.0

**Screenshots:**

![mifos3](https://user-images.githubusercontent.com/42450012/54472964-634d1100-47f7-11e9-990a-acd6bcdb044e.gif)

**Comment by apoorva-mk** [comment]
I would like to work on the issue.

**Comment by shiv07tiwari** [comment]
@apoorva-mk Why did you close this issue ?
If you are not working on this, i really wish to work on this one.

**Comment by apoorva-mk** [comment]
@shiv07tiwari I closed it because this has been raised in another issue but those changes haven't been merged. I was about to work on it but closed it since it has already been raised.

**Comment by apoorva-mk** [comment]
@shiv07tiwari I closed it because this has been raised in another issue but those changes haven't been merged. I was about to work on it but closed it since it has already been raised.

**Comment by shiv07tiwari** [comment]
@apoorva-mk Okay.
