### ISSUE TITLE
App crashes if home button pressed when applying for loan

### ISSUE THREAD

**Issue by apoorva-mk** [openMF/self-service-app#1118]
**Summary:**

If home button pressed when applying for loan the app crashes.

**Steps to reproduce:**

- Click on Apply for Loan
- Press home button and try to reopen app

**Expected behaviour:**

App should resume activity when opened again

**Observed behaviour:**

App crashes when opened again

**Device and Android version:**

Redmi Y2
Android Version 8.1.0

**GIF:**

![mifos5](https://user-images.githubusercontent.com/42450012/54491700-725ebc80-48e6-11e9-9fdd-509c71617143.gif)

**Comment by AathmanT** [comment]
Are you working on this issue?

**Comment by apoorva-mk** [comment]
Hey @AathmanT I am working on this issue. Will let you know in case I discontinue working on it.

**Comment by AathmanT** [comment]
Ok @apoorva-mk

**Comment by prashantkh19** [comment]
@apoorva-mk are you still on it? If not, I would like to work on it.

**Comment by apoorva-mk** [comment]
@prashantkh19  you may work on this.

**Comment by prashantkh19** [comment]
Thanks, I am on it.

**Comment by devansh-299** [comment]
@prashantkh19  if the issue hasn't been resolved  then shall I work on this?

**Comment by gururani-abhishek** [comment]
Hey, @jawidMuhammadi I tried to reproduce this but the app doesn't crash anymore. Here's a video for ref : 

https://github.com/openMF/mifos-mobile/assets/59947871/d69dfa17-904a-49e6-88c7-079e3f701bc4

we can close this issue.

**Comment by luckyman20** [comment]
@gururani-abhishek Thanks for notifying.
