### ISSUE TITLE
'Cannot attach empty file' on sharing QR code

### ISSUE THREAD

**Issue by vansha10** [openMF/self-service-app#1119]
**Summary:**

On sharing QR code from account details, 'cannot attach empty file' is received in the email app.

**Steps to reproduce:**

Accounts -> Select an active/approved account -> QR code -> Share

**Device and Android version:**

OnePlus 5
Android 9

**Screenshots:**
![ezgif-1-ad49d55aa6f8](https://user-images.githubusercontent.com/29632425/54494872-ca0c2080-4904-11e9-998b-14ebea2df1b1.gif)

**Comment by shiv07tiwari** [comment]
@vansha10 I tried this and the file is getting attached in gmail, whatsapp, etc. 
Which email client are you using ?

**Comment by vansha10** [comment]
I tried in both Inbox and Gmail.
Maybe its something related to phone/OS?
Also, not facing this all the time. This error occurred about 3 out of every 4 times when I tried this.

**Comment by luckyman20** [comment]
Does not exist anymore.
