### ISSUE TITLE
Add No internet page for Applying for new Savings Account 

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1123]
**Summary:**
When we have no internet, we should show a "Internet not available" page
**Steps to reproduce:**

**Expected behaviour:**

"Internet not available" page

**Observed behaviour:**

Page  opens, and pressing submit results in crash

**Comment by SkroX** [comment]
hey @shiv07tiwari I would like to work on this issue. Let me know if it is not been done by anyone else. Thank you.

**Comment by luckyman20** [comment]
Unable to reproduce this issue.
