### ISSUE TITLE
Confirmation dialog while changing the password

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1125]
**Summary:**

Changing the password is a big decision, so their should be a dialog box to confirm it
**Steps to reproduce:**

**Expected behaviour:**
Confirmation dialog

**Observed behaviour:**

Password changes directly

**Comment by jatinkumarg** [comment]
Hey, I have added a PR https://github.com/openMF/mifos-mobile/pull/1169

Let me know if there are any changes required.

**Comment by devanshi7799** [comment]
Can i work on this issue?

**Comment by rchtgpt** [comment]
i don't think there is a need of a confirmation dialog as the user has already typed the password for the second time to give his/her confirmation.
