### ISSUE TITLE
License toolbar violates the design pattern

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1127]
**Summary:**

The open source section has a black toolbar, which violates the design pattern of the app and doesn't look good.

**Expected behaviour:**

Colour pattern should be constant

**Observed behaviour:**
Toolbar is of black colour.

![Screenshot_2019-03-18-22-18-38-896_org mifos mobilebanking](https://user-images.githubusercontent.com/38163725/54551979-16269600-49d5-11e9-80f3-5055a2f037aa.png)

**Comment by elirehema** [comment]
Am working on this

**Comment by elirehema** [comment]
@geekanamika we got design policy issue

**Comment by geekanamika** [comment]
@elirehema I didn't get your comment, can you please explain?

**Comment by elirehema** [comment]
@geekanamika i meant the design policy violation not privacy policy.

**Comment by luckyman20** [comment]
Unable to reproduce this issue.
