### ISSUE TITLE
Text not visible in Guarantor section

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1128]
**Summary:**
The text for date is barely visible

![Screenshot_2019-03-18-21-49-32-380_org mifos mobilebanking](https://user-images.githubusercontent.com/38163725/54552288-c3011300-49d5-11e9-8e09-25b9a2ceb4f6.png)

**Comment by miPlodder** [comment]
@shiv07tiwari Closing this as it's not a legit issue. We have used the same colour at many places. What the contract between the color does is makes human visibility more focus on the focus text, not the secondary text. If the contrast becomes less, this wouldn't be true.

**Comment by shiv07tiwari** [comment]
@miPlodder Just wondering, was this a legit issue ?
I mean shall I look for more such places in the app where the visibility of the text is low ?
