### ISSUE TITLE
Account Number accepts letters while adding Beneficiary

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/self-service-app#1129]
**Summary:**

Account number field should be "number" type.

**Steps to reproduce:**

Add a beneficiary

**Expected behaviour:**

Only numbers should be accepted.

**Observed behaviour:**

Letters are accepted as well

**Device and Android version:**

Redmi Note 3

**Screenshots:**

![Screenshot_2019-03-18-23-48-35-744_org mifos mobilebanking](https://user-images.githubusercontent.com/34986121/54553966-5e47b780-49d9-11e9-9dc8-ae73e2fe37d4.png)

**Comment by shubhamofbce** [comment]
is it still open?? i would like to work on this

**Comment by geekanamika** [comment]
Closing this issue as per comment by @therajanmaurya on PR #1139
