### ISSUE TITLE
Issues in Transaction receipt and preview

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1134]
**Summary:**

Their are some issues in transaction receipt and transaction review - 
1. No currency with amount
2. Full account numbers are not shown. (1 is shown for 0000000001)

**Steps to reproduce:**

Make a transaction
![Screenshot_2019-03-20-23-22-22-219_org mifos mobilebanking](https://user-images.githubusercontent.com/38163725/54726126-af9da580-4b97-11e9-91f9-3813222ef7ce.png)

**Comment by miPlodder** [comment]
@shiv07tiwari Work on it, its a good issue and needs to resolved. Also this might persist at other places also in the app where Account Number is displayed.

**Comment by shiv07tiwari** [comment]
@miPlodder Sure. I will look into it and try to solve them as quickly as possible
