### ISSUE TITLE
Use of Vector Drawable Instead of 5 PNGs

### ISSUE THREAD

**Issue by doomers** [openMF/self-service-app#114]
**Summary:**

replace 5 PNGs with Vector Drawables

**Steps to reproduce:**

Create Vector Drawables(SVGs) of the same PNGs.

**Expected behavior:**

App should use be using Vector Drawables instead of PNGs.

**Observed behavior:**

App is using 5 PNGs for every drawable resource instead of which a single SVG which will handle all resolutions by itself, can be used.
**Device and Android version:**

MOTOROLA MOTO G- Android 5.1.1  
 Yes,  i am using the stock version

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by doomers** [comment]
I have done it.
Shall I send a PR?

**Comment by therajanmaurya** [comment]
G0 ahead Send PR.

**Comment by therajanmaurya** [comment]
@doomers It will be great, if you will fix your commit message and try to follow the commit style guideline. https://github.com/openMF/self-service-app/wiki/Commit-Style-Guide

**Comment by doomers** [comment]
Sure I will , tomorrow with proper guidelines provided by you

**Comment by hardik124** [comment]
@therajanmaurya can I take up this issue ?

**Comment by doomers** [comment]
@hardik124 i have already done that. see #124
