### ISSUE TITLE
Improper message is displayed in the snackbar

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1140]
**Summary:**
On entering a very small amount of the form 0.00X (X can be any digits up to 10 or more precision), an error message is displayed in the snack-bar under ```Transfer``` section. It displays the error code and name which is not in user understandable form. 

**Steps to reproduce:**
Under Transfer section, enter amounts beginning with double zeroes as the decimal digits, like 0.001, 0.00326448 or 0.00793586517 etc.

**Expected behaviour:**

The error message should convey the actual meaning of the error, easily understandable by the user.

**Observed behaviour:**

The error message gives the error code and technical name of the error which may not be clear to the user, like, "500,error":"Internal Server Error" .

**Device and Android version:**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Screenshots:**
![dooo](https://user-images.githubusercontent.com/43827236/54831513-7755ae80-4ce0-11e9-9a90-4da65d32b02f.png)

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue.

**Comment by devanshi7799** [comment]
@ShivangiSingh17 i would like to work on this if it is yet not solved

**Comment by luckyman20** [comment]
Not able to reproduce this issue.
