### ISSUE TITLE
App crash on clicking on any account in accounts list

### ISSUE THREAD

**Issue by aayushsingla** [openMF/self-service-app#1143]
**Summary:**
App crashes when you click on any account in accounts list

**Steps to reproduce:**
Click on Savings in account overview and then click on any account.

**Expected behaviour:**
App shall not crash

**Observed behaviour:**

**Device and Android version:**
Redmi note 4 running on Android Nougat and MIUI 10.

**Screenshots:**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31629114/54861354-b837dc80-4d4d-11e9-824c-5d146a48a9f4.gif)

![Screenshot_2019-03-23-09-17-34-822_com miui bugreport](https://user-images.githubusercontent.com/31629114/54861333-51b2be80-4d4d-11e9-96ab-20ac3871a746.png)

**Will you like to work on this issue?**
Yes

**Comment by aayushsingla** [comment]
Mostly this crash is due to server returning null for some certain lists fields in TImeline Model which Kotlin is unable to parcel due to some bug in it. Though the bug was fixed in kotlin version 1.1.60, some people including me are still facing it in 1.3.21 and 1.3.11. 
This link for the discussion: https://stackoverflow.com/questions/46875178/how-to-use-null-with-kotlin-parcelize and https://stackoverflow.com/questions/48350776/kotlins-parcelize-throws-npe-on-writetoparcel?fbclid=IwAR3_ALodP___B6h2v5T9x4guTO5S1GV2UhqLopbvATFwTHtlsbfStHKwiAY

**Comment by shiv07tiwari** [comment]
@aayushsingla I am facing the same issue. @miPlodder @therajanmaurya

**Comment by aayushsingla** [comment]
Fixed in latest release
