### ISSUE TITLE
Clicking on Add Beneficiary should open Add Beneficiary Activity 

### ISSUE THREAD

**Issue by aayushsingla** [openMF/self-service-app#1145]
**Summary:**
Clicking on Tap to add Beneficiary should open Add beneficiary activities.

**Steps to reproduce:**
Go to- Home Screen -> Beneficiaries  -> click on tap to add beneficiary(visible when there are no beneficiaries)

**Expected behavior:**
Add Beneficiary Activity should open 

**Observed behavior:**
Nothing Happens

**Device and Android version:**
Redmi note 4 running on android Nougat and MIUI 10

**Will you like to work on this issue?**
Yes

**Comment by shiv07tiwari** [comment]
@aayushsingla It is basically for the FAB button available on the screen.

**Comment by aayushsingla** [comment]
Sorry, my wrong.
