### ISSUE TITLE
Centralise the account number text

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1153]
The text for account number should also be in centre so as to improve the UI.
![Screenshot_2019-04-03-11-32-57-405_org mifos mobile](https://user-images.githubusercontent.com/38163725/55456461-b64f0280-5604-11e9-8c13-7da1753b048e.png)

**Comment by jatinkumarg** [comment]
Hey, I added a PR https://github.com/openMF/mifos-mobile/pull/1168 

Let me know if there are any changes required.

**Comment by RajaVamsi11** [comment]
@jatinkumarg I think you should ask the author or mentor before working on the issue and sending a PR.
