### ISSUE TITLE
Hide password icon

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1155]
![Screenshot_2019-04-03-11-39-53-364_org mifos mobile](https://user-images.githubusercontent.com/38163725/55573199-1211ac80-5727-11e9-8daf-b57e980b04af.png)

The icon which displays hide password can be replaced with something like this - which is a globally accepted icon for the same
![Screenshot from 2019-04-04 22-17-12](https://user-images.githubusercontent.com/38163725/55573365-6f0d6280-5727-11e9-80fe-d18f764af5d6.png)

**Comment by shubhamofbce** [comment]
I would like to work on this issue @shiv07tiwari ?? May i

**Comment by refactor-droidyy** [comment]
@shiv07tiwari which icon to replace for this I am unable to get it.
![](https://user-images.githubusercontent.com/38163725/55573365-6f0d6280-5727-11e9-80fe-d18f764af5d6.png)

**Comment by shiv07tiwari** [comment]
@shubhamofbce @refactor-droidyy The icon I added in the issue description.

**Comment by refactor-droidyy** [comment]
@shiv07tiwari this can be solved by making changes to 
https://github.com/openMF/mifos-passcode/ 
for the same as you mentioned. Is this correct to what I am thinking in order to solve this issue since all the files related to this are in read mode.

**Comment by geekanamika** [comment]
Issues related to Passcode should be pointed to https://github.com/openMF/mifos-passcode/ as @refactor-droidyy  mentioned :)
