### ISSUE TITLE
The app does not exits when pressed back button in Passcode Activity

### ISSUE THREAD

**Issue by balanikaran** [openMF/self-service-app#1157]
**Summary:**

The passcode activity should allow the user to exit the app when the user hits the back button.

**Steps to reproduce:**

Open the app, when the app asks for the passcode, press back button.

**Expected behavior:**

Exit the app.

**Observed behavior:**

Nothing happens.

**Device and Android version:**

Any

**Screenshots:**

N/A

**Comment by prashantkh19** [comment]
@krnblni I am able to exit the app by pressing the back button. Could you provide some specific case when you are not able to do so?
