### ISSUE TITLE
The app crashes while applying for a loan for the second loan product.

### ISSUE THREAD

**Issue by balanikaran** [openMF/self-service-app#1159]
**Summary:**

The app crashes while applying for a loan for the second loan product.

**Steps to reproduce:**

Open "Apply for a loan" >> Select "test1" from drop down of Loan Product >> Recreate the activity >> Crash

**Expected behavior:**

The app must retain the filled values and don't crash.

**Observed behavior:**

CRASH

**Device and Android version:**

OnePlus 5
Android 9.0

**Screenshots:**

N/A

**Comment by prashantkh19** [comment]
Yeah, I tried to reproduce the issue. I would like to work on it. Shall I? @krnblni

**Comment by devansh-299** [comment]
@krnblni  I can reproduce a similar issue , Apply for loan --> Select 1 st loan product --> Small business , app crashes . Shall I work on this?

**Comment by balanikaran** [comment]
Yes, please go ahead. 👍

**Comment by amitYadavDev** [comment]
@krnblni  can i work on this issue?

**Comment by devansh-299** [comment]
> @krnblni can i work on this issue?

@amit6663 this issue has already been addressed in #1212
