### ISSUE TITLE
Empty Snackbar in signup

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#1172]
**Summary:**

An empty message snackbar is shown in sign up

**Expected behaviour:**

A proper error message

**Observed behaviour:**

Blank message

![videotogif_2019 04 16_20 11 40](https://user-images.githubusercontent.com/38163725/56219288-1bced480-6084-11e9-974b-5108da70620c.gif)

**Comment by shubhamofbce** [comment]
I want to work on this issue?? Can I??

**Comment by prashantkh19** [comment]
@shubhamofbce Yes, you may work on this.

**Comment by shubhamofbce** [comment]
I think the issue is already resolved . Please close this issue . I tried with all the corner cases in the signup form but nowhere i got any empty SnackBar. All the logics were also correct.

**Comment by shubhamofbce** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45156638/63215730-85e9aa00-c148-11e9-9765-ae57d9078420.gif)

**Comment by shubhamofbce** [comment]
Please close this issue @shiv07tiwari @prashantkh19
