### ISSUE TITLE
Feature Loan Account Transactions

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#119]
**Summary:**

Add feature for Loan Account Transactions.

**Expected behavior:**

Open any active or closed account and there will be button "Transactions". Add feature to show the loan transactions.

**Observed behavior:**

There is only toast showing.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

![image](https://cloud.githubusercontent.com/assets/5724482/23550171/b45667a6-0035-11e7-8cdf-9b97af7b8f02.png)

**Note: API END Point is https://demo.openmf.org/fineract-provider/api/v1/self/loans/{loanId}?associations=transactions**

You can in browser https://demo.openmf.org/fineract-provider/api/v1/self/loans/29?associations=transactions&tenantIdentifier=default&pretty=true (Enter demo credentials)

**Comment by dilpreet2028** [comment]
I would like to work on this

**Comment by therajanmaurya** [comment]
Go ahead 👍

**Comment by dilpreet2028** [comment]
Added in #126
