### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1191]
**Summary**
The app crashes after I entered the pin correctly. During this I had an active internet connection

**Steps to reproduce:**

Open the app ,enter your pin and after that one may encounter this issue

**Expected behaviour:**

The app should have logged me in and should have displayed the home fragment

**Observed behaviour:**

The app just crashed unexpectedly

**Device and Android version:**
Xiaomi Poco F1 ( Android 9 Pie)

**Screenshot:**

![Screenshot_2019-08-20-13-29-54-002_com mi android globallauncher](https://user-images.githubusercontent.com/46667021/63328969-b438d680-c34e-11e9-9b92-4aed697616e8.png)

**Comment by prashantkh19** [comment]
@devansh-299 Try re-installing the application
