### ISSUE TITLE
java.lang.NumberFormatException: For input in beneficiary 

### ISSUE THREAD

**Issue by rabih716** [openMF/self-service-app#1192]
This issue has been raised before here 
https://github.com/openMF/mifos-mobile/issues/829#issue-322972736
but since then, the code has been updated and it looks like the bug is back.

**Steps to reproduce:**
Add a new beneficiary 

**Expected behaviour:**
I added 100 as the transfer limit but its being sent to the server as string 100.0

**Comment by vibhusharma101** [comment]
@luckyman20 @devansh-299   can I work on this issue?

**Comment by devansh-299** [comment]
@vibhusharma101 I think only @luckyman20 can give you the approval

**Comment by luckyman20** [comment]
Please attach screenshot and explain the bug properly.

**Comment by divyank00** [comment]
![IllegalException](https://user-images.githubusercontent.com/50913976/107004414-4091c000-67b4-11eb-975c-55509629acc3.png)

@luckyman20 Adding beneficiary and update beneficiary needs amount as Integer

**Comment by luckyman20** [comment]
Not able to reproduce this anymore.
