### ISSUE TITLE
#API variant

### ISSUE THREAD

**Issue by gokul500** [openMF/self-service-app#1194]
API 'variant.getPreBuild()' is obsolete and has been replaced with 'variant.getPreBuildProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPreBuild(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

**Comment by elirehema** [comment]
According to Gradle 3.5.0 [Release Notes](https://developer.android.com/studio/releases/gradle-plugin#3-5-0)

>**Known issues**
When using Kotlin Gradle plugin 1.3.31 or earlier, you might see the following warning when building or syncing your project:
`WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced
         with 'variant.getPackageLibraryProvider()'.`
To resolve [this issue](https://youtrack.jetbrains.com/issue/KT-30784), upgrade the plugin to version 1.3.40 or higher.

**Comment by elirehema** [comment]
Am working on this
