### ISSUE TITLE
No response on clicking change passcode in settings activity

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1201]
**Summary:**

Clicking on change passcode on Settings Activity does not do anything

**Steps to reproduce:**

Settings -> Change Passcode

**Expected behaviour:**

Should direct to window where one can change passcode

**Observed behaviour:**

Does nothing

**Device and Android version:**

Xiaomi Pocof1
Android 9
Stock rom

**Comment by geekanamika** [comment]
Hi @devansh-299 I checked in development codebase & looks like there's no code available for changing passcode in SettingsFragment. I am working to fix this bug. Thanks 😊

**Comment by amitYadavDev** [comment]
hi sir @devansh-299,
I want to work on this issue.

**Comment by devansh-299** [comment]
Hi @amit6663 ,  @geekanamika has already made a pull request that solves the issue .

**Comment by gururani-abhishek** [comment]
@jawidMuhammadi this issue can be closed. Now the app has a proper change passcode feature.
