### ISSUE TITLE
App crashes when orientation is changed 

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1206]
**Summary:**

App crashes when orientation is changed  when a person is on Home Activity

**Steps to reproduce:**

Go to home screen --> Change the orientation

**Expected behaviour:**

App should have handled the orientation change without crashing

**Observed behaviour:**

The app crashed

**Device and Android version:**

Xiaomi Poco F1
Android 9
Stock rom

**Screen Recording:**

![GIF-191023_115250](https://user-images.githubusercontent.com/46667021/67363839-d2f45d00-f58b-11e9-9712-63206098b045.gif)

**Comment by Grandolf49** [comment]
I would like to work on this issue

**Comment by devansh-299** [comment]
@Grandolf49  I am already working on it

**Comment by Grandolf49** [comment]
> @Grandolf49 I am already working on it
Oh even I solved it. Should I create a pull request?

**Comment by devansh-299** [comment]
> > @Grandolf49 I am already working on it
> > Oh even I solved it. Should I create a pull request?

**Comment by amitYadavDev** [comment]
hi sir/ma'am @devansh-299 can i work on this issue?

**Comment by devansh-299** [comment]
Hi @amit6663 , I think @Grandolf49 has already put up a pull request that solves the issue. But still you can discuss with @Grandolf49 if any further changes are required

**Comment by amitYadavDev** [comment]
@Grandolf49 any help from me or u completed this issue?

**Comment by Grandolf49** [comment]
@amit6663 I have already put up a pull request for this issue

**Comment by luckyman20** [comment]
Issue is already solved.
