### ISSUE TITLE
No fingerprint authentication available, only passcode authentication

### ISSUE THREAD

**Issue by Grandolf49** [openMF/self-service-app#1208]
**Summary:**

There is no fingerprint authentication but only passcode.

**Expected behaviour:**

When the app asks for passcode, the user should also be able to authenticate using his fingerprint

**Observed behaviour:**

The PassCode feature only asks for passcode user saved.

**Device and Android version:**

OnePlus 6
Android 10
stock ROM

**Comment by shambu2k** [comment]
##### Can I add this feature??  I've done it in one of my apps

**Comment by KartikPant12** [comment]
@shiv07tiwari  can I work on this issue??

**Comment by devanshi7799** [comment]
If no one is working on this issue , I would like to work on this issue.

**Comment by shitesh2607** [comment]
Can I work this issue?

**Comment by PratyushSingh07** [comment]
can i take up this issue?
