### ISSUE TITLE
Pressing back on transfer process fragment is not handled and null values are shown

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1210]
**Summary:**

* Pressing back on Transfer Process Fragment is not handled properly unlike the cancel button which is handled properly
* Null values are shown in Transfer Process Fragment instead of sender's and receiver's account number

**Steps to reproduce:**

Go to Third party transfer --> Fill details 

**Expected behaviour:**

* Back button pressing should be properly handled like cancel button is being handled
*Account numbers of sender's and receiver's should have been displayed in Tranfer Process fragment

**Device and Android version:**
Xiaomi Poco F1
Android 9
Stock rom

**Screen Recording:**

![GIF-191025_153003](https://user-images.githubusercontent.com/46667021/67563010-7afd5800-f73d-11e9-930d-8bab2d780e3b.gif)

**Comment by vibhusharma101** [comment]
@devansh-299  can I work on this if this is still open?

**Comment by devansh-299** [comment]
@vibhusharma101 #1211 already addresses this issue
