### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by edcable** [openMF/self-service-app#1213]
**Summary:**

Summarize your issue in one sentence (what goes wrong, what did you expect to happen).

**Steps to reproduce:**

How can we reproduce the issue?

**Expected behaviour:**

What did you expect the app to do?

**Observed behaviour:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by PiyushSharma99** [comment]
I would like to work on this sir.

**Comment by geekanamika** [comment]
@PiyushSharma99 This is a test issue, an example to demonstrate how an issue should be created on the repository.

**Comment by Jaikishan-Saroj** [comment]
I would like to work on it sir !

**Comment by ShivangiSingh17** [comment]
@Jaikishan-Saroj its a test issue and there is nothing to work on over it. You can choose to work on the other created issues.
