### ISSUE TITLE
User cannot edit Profile Picture

### ISSUE THREAD

**Issue by Grandolf49** [openMF/self-service-app#1214]
**Summary:**

User cannot edit Profile Picture in User Details fragment. Nothing happens when Edit Floating Action Button is pressed.

**Steps to reproduce:**

Open App -> Click on the profile pic -> Click on Edit Icon (nothing happens)

**Expected behaviour:**

The user should be able to change his profile picture.

**Observed behaviour:**

Nothing happens when clicked on edit icon

**Device and Android version:**

Android 10
OpenPlus 6 
Stock Rom

**Comment by elirehema** [comment]
@santoshconflux @Grandolf49 can i work on this ?

**Comment by Grandolf49** [comment]
@elirehema sure go ahead

**Comment by elirehema** [comment]
@Grandolf49 am wating for response on this https://github.com/openMF/android-client/issues/1182#issuecomment-555524888

**Comment by Grandolf49** [comment]
> @elirehema sure go ahead

@elirehema  i already replied :)

**Comment by elirehema** [comment]
> > @elirehema sure go ahead
> 
> @elirehema i already replied :)

If we implement this it gonna conflict with the issue i've shared with you above try to check my comment in the link provided above.

**Comment by luckyman20** [comment]
@elirehema Please do not work on this since it has been added as GCI task list.

**Comment by OHassini** [comment]
Change it locally or even in the server ?

**Comment by rachittt** [comment]
@luckyman20 can i work on this?

**Comment by luckyman20** [comment]
Unable to reproduce.

**Comment by elirehema** [comment]
> Unable to reproduce.

@luckyman20 I think the PR was merged and closed.

**Comment by luckyman20** [comment]
@elirehema Can you please refer to the Pull Request number here?
