### ISSUE TITLE
Developer login credentials please...

### ISSUE THREAD

**Issue by raunak-many-ac** [openMF/self-service-app#1215]
Username: selfservice
Password: Password@123

or

Username: mifos
Password: password

none of them are working

**Comment by Grandolf49** [comment]
> Username: selfservice
> Password: Password@123
> 
> or
> 
> Username: mifos
> Password: password
> 
> none of them are working

1st credential is incorrect
Username: selfservice
Password: password

**Comment by ashwinkey04** [comment]
Can we add this in the README? I had to search for a while to find this
