### ISSUE TITLE
There is couple of slight issues related to the keyboard in login/signup pages.

### ISSUE THREAD

**Issue by myselfanuj** [openMF/self-service-app#1217]
**Summary:**

Whenever the user tapping anywhere on the screen there is no shutdown of the keyboard on login/signup page. This affects the user experience.

**Steps to reproduce:**
  Just tap anywhere on the screen after opening the keyboard in login/Signup.

**Expected behavior:**
   There should be shutting down of keyboard after tapping anywhere on the screen

**Observed behavior:**

  Whenever the user tapping elsewhere on the screen there is no shutdown of the keyboard on 
  login/signup page

**Device and Android version:**
    Vivo V5
    Android 7.0

**Screenrecording:**

<img src = "https://raw.githubusercontent.com/myselfanuj/Issues-Recording/master/openMF/Recording.gif" height = "500">

**Comment by gururani-abhishek** [comment]
@jawidMuhammadi , this can be closed as the signup keyboard issue is solved in this PR : #2019 
And for other screens we agreed to avoid heavy operation required and hence didn't deem the feature fit. #2115 , #2116

**Comment by luckyman20** [comment]
@gururani-abhishek Thanks for reporting.
