### ISSUE TITLE
Change passcode should open option to change the passcode of the app

### ISSUE THREAD

**Issue by GOVINDDIXIT** [openMF/self-service-app#1220]
**Summary:**

Change passcode should open option to change the passcode of the app

**Steps to reproduce:**

Open Setting menu, Clicking on change passcode is doing nothing

**Expected behavior:**

1. It should open a menu to change the passcode of the app
2. Open existing passcode fragment on clicking change passcode and update the passcode of the app

**Observed behavior:**

Clicking on change passcode is doing nothing

**Device and Android version:**

Android 9
Redmi Note 5 Pro
MIUI 10

**Screenshots:**

Open Setting menu, Clicking on change passcode is doing nothing

**Comment by GOVINDDIXIT** [comment]
@santoshconflux This issue is for GCI

**Comment by devansh-299** [comment]
Already reported under #1201

**Comment by GOVINDDIXIT** [comment]
@devansh-299 Thanks the issue can be moved under GCI category for more priority

**Comment by geekanamika** [comment]
Solved in #1202 . So, closing this issue :)
