### ISSUE TITLE
Improve the UI of the homescreen

### ISSUE THREAD

**Issue by GOVINDDIXIT** [openMF/self-service-app#1223]
**Summary:**

There is a scope of UI improvement in the home screen of the app
Icons can be made smaller
Visit [this](https://dribbble.com/shots/7587490-MOLLET-Wallet-app-UI-Kit/attachments/372728?mode=media) for reference

**Steps to reproduce:**

Open the app

**Expected behaviour:**

Icons can be made smaller, Othe UI improvements will be appreciated

**Observed behaviour:**

Currently, the home screen has a scope of UI improvements

**Device and Android version:**

Android 9
Redmi Note 5 Pro
MIUI 10

**Screenshots:**

Open the app

**This issue is for GCI Students**

**Comment by devansh-299** [comment]
Can I work on this issue?

**Comment by luckyman20** [comment]
@GOVINDDIXIT Can you please be more specific on what things you want to improve?

**Comment by GOVINDDIXIT** [comment]
@luckyman20 updated.

**Comment by refactor-droidyy** [comment]
@GOVINDDIXIT can I work on this ?

**Comment by GOVINDDIXIT** [comment]
@refactor-droidyy The above issue is for GCI Students. You can look for other non-GCI issues

**Comment by shambu2k** [comment]
Can I work on the UI ??

**Comment by luckyman20** [comment]
@shambu2k We would have loved seeing working on this issue but this issue is only meant for Google Code-in participants.

**Comment by shambu2k** [comment]
> @shambu2k We would have loved seeing working on this issue but this issue is only meant for Google Code-in participants.

Please update the tags.. this wasn't under the GCI tags

**Comment by gururani-abhishek** [comment]
Hey, @jawidMuhammadi we can update this issue by providing the latest home screen styling that we want to adhere to.

**Comment by luckyman20** [comment]
UI of homepage has been updated since.
