### ISSUE TITLE
App Info button on Login screen

### ISSUE THREAD

**Issue by jddeep** [openMF/self-service-app#1224]
**Summary:**

There should be an app info for first-time users and basic info which they should know in order to login in the mobile app.

**Steps to reproduce:**
Install the app and land on the Login screen.

**Expected behaviour:**
There should be an App info button on Login screen.

**Observed behaviour:**

Not enough information and steps for first time users.

**Device and Android version:**
 
Android Pi
**Example Screenshots**
<img src="https://user-images.githubusercontent.com/43133646/69494114-b1b1c400-0edd-11ea-99d5-574f72da7901.png" width=300 />

**Issue for GCI 2019**

**Comment by geekanamika** [comment]
@jddeep Can you Add some UI example to specific about submission requirement for GCI?

**Comment by PiyushSharma99** [comment]
@jddeep @geekanamika I would like to work on this as part of GCI. When should I make a PR?

**Comment by jddeep** [comment]
@PiyushSharma99 GCI begins on December 2. Please do make a PR during that time period. Thanks.

**Comment by PiyushSharma99** [comment]
@jddeep @santoshconflux I would like to work on this next. I have submitted a PR for my previous task. Please review and approve that asap. Thank you!

**Comment by santoshconflux** [comment]
@PiyushSharma99 , what is the PR which you already sent?

**Comment by PiyushSharma99** [comment]
@santoshconflux Here it is - https://github.com/openMF/mifos-mobile/pull/1233

**Comment by deecodesss** [comment]
Is this issue still open?
