### ISSUE TITLE
Update library dependencies and build tools, configure build variant

### ISSUE THREAD

**Issue by jddeep** [openMF/self-service-app#1226]
**Summary:**

Update library dependencies and build tools versions to correct and latest ones.
Irradicate sync and build errors + warnings.
Issues with build variant.

**Steps to reproduce:**

Clone the project and build it.

**Expected behaviour:**

The build should be successful without any dependency warnings or errors.

**Observed behaviour:**

Dependency warnings, build tools outdated, build variant issues.

**Device and Android version:**

Android Pi.

 **Issue for GCI**

Beginner level

**Comment by PiyushSharma99** [comment]
@jddeep @geekanamika I would like to work on this as part of GCI. When should I make a PR?

**Comment by santoshconflux** [comment]
@PiyushSharma99 , The contest begins for students on December 2, 2019

**Comment by PiyushSharma99** [comment]
Okay @santoshconflux Thanks. Will do likewise. You can assign me on this issue.

**Comment by geekanamika** [comment]
@PiyushSharma99 GCI works a little differently. You need to "Claim" a task on the GCI portal to work on any issue. 
Let's wait for GCI to begin & If you are participating as a GCI student, feel free to claim this task & then work on this issue :)
