### ISSUE TITLE
Remove hardcoded strings from xml layout files

### ISSUE THREAD

**Issue by jddeep** [openMF/self-service-app#1227]
**Summary:**

Remove hardcoded strings resources from xml layout files.

**Steps to reproduce:**

Go through the project codebase and layout files.

**Expected behaviour:**

Remove hardcoded resources from xml layout files.

**Observed behaviour:**

Move hardcoded strings to strings.xml file

**Device and Android version:**

Android Pi.

**Issue for GCI**

Beginner level.

**Comment by luckyman20** [comment]
Fixed in #1258
