### ISSUE TITLE
Logining into the app

### ISSUE THREAD

**Issue by C9-Neo** [openMF/self-service-app#1228]
When I am attempting to register I do not receive a successful registration prompt and I have been unable to login to the app to use it.

**Comment by Grandolf49** [comment]
Use these credentials to log in:
Username: selfservice
Password: password

**Comment by C9-Neo** [comment]
Thanks, I will try that

**Comment by C9-Neo** [comment]
Okay thanks that worked, but how do I register my own account and credentials? I would like to customize the profile picture and name of the user.

**Comment by C9-Neo** [comment]
@Grandolf49 Do you know how the registration works?

**Comment by gptshubham595** [comment]
@Grandolf49
Hey That is not working can you provide another login id pass

**Comment by santoshconflux** [comment]
@gptshubham595 , @C9-Neo :+1: 
1) Login here: https://mobile.openmf.org/#/home  (username: mifos, password: password).
2) Go to Clients menu and click on Clients and then click on Create Client. Provide all mandatory inputs and submit it.
3) Then in the client page, go to 'More' menu and click on 'Create Self Service User'.
4) Provide the inputs and submit it. 
5) In the self- service mobile app, login with the credentials provided while creating self service user.

**Comment by C9-Neo** [comment]
Thanks for the response! I just created the user but failed to login, do I need to update the application on my device? Thanks in advance for the response @santoshconflux

**Comment by C9-Neo** [comment]
@Grandolf49 I am unable to login with these credentials anymore. @santoshconflux  I can't log in at all

**Comment by rchtgpt** [comment]
@C9-Neo @gptshubham595 try
username: testing
password: password

**Comment by C9-Neo** [comment]
@rachittt Same thing as the selfservice login. After a while of the "logging in" spinner, a toast appears without an error message. That even happens with the new user I created
