### ISSUE TITLE
Remove hardcoded dimens from xml layout files

### ISSUE THREAD

**Issue by geekanamika** [openMF/self-service-app#1231]
**Summary:**

Remove hardcoded dimen resources from xml layout files. 

**Steps to reproduce:**

Go through the project codebase and layout files.

**Expected behaviour:**

Remove hardcoded dimen resources from xml layout files.

**Observed behaviour:**

Move hardcoded dimension(ex: 10dp) to dimens.xml file

**Device and Android version:**

Android Pi.

**Issue for GCI**

Beginner level.

**Comment by amitYadavDev** [comment]
Hi ma'am @geekanamika ,
I want to work on this issue, can I?

**Comment by zoman-anamika** [comment]
@amit6663 already solved during GCI :)

**Comment by amitYadavDev** [comment]
any reply @geekanamika ?

**Comment by devansh-299** [comment]
@amit6663 this issue is under GCI category , you may work on other issues that are not tagged under this category

**Comment by Jaikishan-Saroj** [comment]
Mam I want to Work on this issue.
May I able to take this issue? @geekanamika

**Comment by ShivangiSingh17** [comment]
@Jaikishan-Saroj the issue is tagged under GCI and also the 2 PRs created above solves the issue mentioned.

**Comment by anthonrodgrs01** [comment]
I want to work on this issue, Can I

**Comment by spacemonkey1101** [comment]
is this issue open? can I be assigned?

**Comment by omprakashcs01** [comment]
can I work on  this project

**Comment by AditiKamath** [comment]
is this issue still open? can I be assigned?

**Comment by dmdbilal** [comment]
Is this issue still open ?

**Comment by deecodesss** [comment]
If this is still open can I work on this? @geekanamika
I've already solved this issue, just need to make a pr.
