### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ShanmugamArusamy** [openMF/self-service-app#1239]
**Summary:**

Unable to login , getting invalid authentication error , it is urgent we have demo
User Name : selfservice
Password : password

**Comment by devansh-299** [comment]
Try these credentials

User Name : testing
Password : password

**Comment by fidelsam1992** [comment]
Both username used to work before, but now I'm getting this error on both : 
Invalid authentication details were passed in api request

**Comment by fidelsam1992** [comment]
A solution to overcome this is to follow the steps here to create a new self-service account : 
https://github.com/openMF/mifos-mobile/issues/1228#issuecomment-560235204
