### ISSUE TITLE
Setting the application to work only in portrait mode

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1241]
**Summary:**
Right now the application has many bugs when working with the screen rotation from portrait to landscape. So it is better to restrict the application to work only in the portrait mode as it solves many issues and helps the application to function smoothly.

**Expected behaviour:**
The application to work in portrait mode only.

**Would you like to work on this issue?**

**Comment by Saransh0905** [comment]
Hey @ShivangiSingh17 , I would like to solve this issue ,can you guide me how to proceed?

**Comment by luckyman20** [comment]
@Saransh0905 This issue is for GCI students.

**Comment by Saransh0905** [comment]
I am working on this issue.

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi, I think this just restricts the user experience, we can close it down and start targeting(and we have already in the past few months) the activities that misbehave when Orientation is changed.
