### ISSUE TITLE
Add ldrtl and ldltr layouts

### ISSUE THREAD

**Issue by elirehema** [openMF/self-service-app#1248]
**Summary:**

Since mifos mobile applications support both  LTR languages and  RTL(right-to-left) languages like Arabic. The specific layouts i.e  "layout-direction-right-to-left" and "layout-direction-left-to-right"  for RTL languages should be added to [supportRtl](https://developer.android.com/guide/topics/manifest/application-element.html#supportsrtl).

**Comment by anujji1999** [comment]
Can i work on this issue?

**Comment by elirehema** [comment]
Go on @anujji1999
