### ISSUE TITLE
Replace Toasts with Snackbars on Login

### ISSUE THREAD

**Issue by laxyapahuja** [openMF/self-service-app#1263]
## Summary

When you login to the app, you see a toast instead of a snackbar which is provided in the utils (Toaster).

## Steps to reproduce

Fill in the username and password -> Login -> Notice the toast
Fill in the wrong username and password -> Login -> Notice the toast

## Expected Behaviour

The message is shown in a snackbar.

## Observed Behaviour

The message is shown in a toast.

## Device and Android Version

Android 9, Mi A3

## Screenshots
<img src="https://user-images.githubusercontent.com/31318248/71734279-925d6d80-2e71-11ea-801b-d4e894a8740e.png" width=300/>
<img src="https://user-images.githubusercontent.com/31318248/71734285-96898b00-2e71-11ea-9f55-b2e75a7872c1.png" width=300/>

**Comment by rchtgpt** [comment]
@laxyapahuja You must be aware that a snackbar disappears when the activity finishes. Therefore, the material guidelines suggest us to not use a snackbar (and use a toast instead) to display a message, when there is a change in the activity. Hence, i don't think it is necessary to switch to a snackbar.

**Comment by laxyapahuja** [comment]
@rachittt if you look at the first screenshot, the message appears in the same activity and it doesn't move to another activity :) I agree with the second case though but I've seen a trend of replacing toasts with Toasters throughout the project so thought about posting an issue.

**Comment by rchtgpt** [comment]
For the first case:
It is always recommended to use the Toast class for displaying system messages. I think that the toast message in the first case is pertaining to the system, so do you think there is an actual need to replace it with a snackbar? Because I feel it is important to comply with the guidelines as well

**Comment by laxyapahuja** [comment]
@rachittt The user also needs to know what the reason is behind him/her not being able to log in. It's **not** entirely a system message. Either the message can be reframed to something like "Invalid username or password." or we can keep the same message but in a snackbar. It depends on what a project maintainer suggests but a snackbar (Toaster) is indeed needed. :)

**Comment by amitYadavDev** [comment]
can i work on this issue? @laxyapahuja

**Comment by luckyman20** [comment]
UI Enhancement issue. Not really required.
