### ISSUE TITLE
UI/UX enhancement

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1266]
**Summary:**

The design of the home fragment duplicates the working of navigation drawer to a certain extent. The home fragment can instead be used to provide other certain important information to the user

**Steps to reproduce:**

* Open the app
* Go to home 

**Expected behaviour:**

Home fragment should provide more information to the user  like recent transactions etc .

**Device and Android version:**

Xiaomi PocoF1
Android9
Stock rom

**Comment by luckyman20** [comment]
Old issue. The design has been changed since.
