### ISSUE TITLE
Add About Us Screen

### ISSUE THREAD

**Issue by code-dagger** [openMF/self-service-app#127]
**Summary:**
Add about us screen to the application.

**Steps to reproduce:**
How can we reproduce the issue?

**Expected behavior:**
Application should open About Us screen on clicking about us menu in navigation drawer list.

**Observed behavior:**
Application only updates the app bar title of the application to About Us, but doesn't open any About Us screen (activity/fragment).

**Device and Android version:**
Redmi Note 3 - Android 6.0

**Screenshots:**
![screenshot_2017-03-04-22-34-30-865_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16591761/23580605/d8fdac22-012a-11e7-8882-d9b6d86530c1.png)

**Comment by immabhay** [comment]
@therajanmaurya I would like to work on this if you can assign me this.

**Comment by shivamarora96** [comment]
@therajanmaurya I would also love to work on this. Kindly describe the content that should appear in About us screen?

**Comment by Subhankar29** [comment]
Can I Claim the issue?

**Comment by shivamarora96** [comment]
@therajanmaurya  can i work on this ?

**Comment by itsamitgoel** [comment]
@therajanmaurya sir is anyone working on this issue? if not, i would like to take it up.

**Comment by therajanmaurya** [comment]
Already fixed
