### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1272]
**Summary:**

'Pay To' field accepts empty entries and the spinner is empty which is not good at all.
'Pay From' field accepts empty entries and the spinner is empty which is not good at all.

App crashes,
On following actions:
Transfer->Transfer->Continue->Continue->App Crashed

**Expected behaviour:**

Give an error after pressing continue if the field was empty and if it succeeds,
Ask for Amount

**Observed behaviour:**

![Desktop_20200118233021](https://user-images.githubusercontent.com/50913976/72668394-30ddf700-3a4c-11ea-9fda-c08fd0ac2183.gif)

**Device and Android version:**

One Plus 6
Android Version- Android Q

I would like to work on this!

**Comment by luckyman20** [comment]
Unable to reproduce this issue anymore.
