### ISSUE TITLE
No verification to change the password

### ISSUE THREAD

**Issue by shaljais01** [openMF/self-service-app#1276]
**Summary:**

There is no verification or authentication needed to change the password, if the app is open then anyone can change the password.

**Steps to reproduce:**

Click on the profile pic -> We are guided to user details fragment -> Click on change password button -> anyone can change the password

**Expected behaviour:**

An OTP should be send to the mobile number and on entering the OTP the user can change the password.

**Observed behaviour:**

No such authentication is provided

**Device and Android version:**

Android 6.0
Motorola E3 Power

**Comment by shaljais01** [comment]
Can I please work on this issue?

**Comment by divyank00** [comment]
I guess it should ask for current password and if it is correct then only update, why send otp.

**Comment by shaljais01** [comment]
Yes, @divyank00 you are right! It should ask for current password, So can I work on the issue?

**Comment by devansh-299** [comment]
@shaljais01 Can I work on this issue?

**Comment by shaljais01** [comment]
@devansh-299 I am working on this issue

**Comment by debarghya472** [comment]
has this issue been resolved?

**Comment by shaljais01** [comment]
@debarghya472 I am working

**Comment by Him887** [comment]
has this issue been resolved? or i can work on this??
