### ISSUE TITLE
User Cant Update his/her Profile

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1277]
**Summary:**

The update button in profile is disabled.

**Expected behaviour:**

Able to update profile

**Observed behaviour:**

Cant update

**Device and Android version:**

One plus 6
Android Q

**Screenshots:**

![Desktop_20200119141245](https://user-images.githubusercontent.com/50913976/72677767-19435480-3ac6-11ea-8fe6-b64d8c3a3392.gif)

**Comment by divyank00** [comment]
I would like to work on this?

**Comment by shaljais01** [comment]
@divyank00 I have already opened #1275 issue for editing user details

**Comment by divyank00** [comment]
Ya i didnt observe it!

**Comment by shaljais01** [comment]
No Problem, it happens :)

**Comment by divyank00** [comment]
Can i work on this?
