### ISSUE TITLE
What user details can be updated?

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1278]
**Summary:**

Which fields from profile of user can be changed?
Like activation Date cant be changed, but Username can change.

**Device and Android version:**

One plus 6
Android Q

**Screenshots:**

![WhatsApp Image 2020-01-19 at 2 47 35 PM](https://user-images.githubusercontent.com/50913976/72678320-b4d6c400-3aca-11ea-96cc-e45993c7924a.jpeg)

**Comment by falayy** [comment]
Hi @divyank00 , what is the issue here? or what do you think should be done?

**Comment by divyank00** [comment]
Should I add a FAB to update user info
