### ISSUE TITLE
 unable to change password.

### ISSUE THREAD

**Issue by devanshi7799** [openMF/self-service-app#1280]
**Summary:**
Unable to change password if language is other than English

**Steps to reproduce:**
Settings-->Language-->change Language-->Click on change Password 

unable to change
**Expected behaviour:**

Password must be changed 

**Observed behaviour:**
When the application language is set to language other than English, we cannot change the password

**Device and Android version:**
Vivo Y51L

**Screenshots:**
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/51824493/72683678-537d1800-3aff-11ea-9b13-8a58330fdd34.gif)

**Comment by divyank00** [comment]
Can i work on this?

**Comment by falayy** [comment]
did you squash your commit? @divyank00

**Comment by divyank00** [comment]
> did you squash your commit? @divyank00

Yeah, it's visible in pull request but not here  Could you help me!
