### ISSUE TITLE
Unable to change passcode

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1282]
**Summary:**

Unable to change passcode.

**Expected behaviour:**

Allow to change passcode
**Observed behaviour:**

No CHange

**Device and Android version:**

One plus 6
Android Q

**Screenshots:**

![Desktop_20200119224530](https://user-images.githubusercontent.com/50913976/72685196-becde680-3b0d-11ea-8599-e0f675cec28a.gif)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by laxyapahuja** [comment]
Duplicate of #519 and already fixed in #1202

**Comment by divyank00** [comment]
Yeah!
