### ISSUE TITLE
unable to change passcode which is used to login in app.

### ISSUE THREAD

**Issue by vibhusharma101** [openMF/self-service-app#1284]
**Summary:**

I am able to change password but unable to change passcode, It is unresponsive.
**Steps to reproduce:**

What did you expect the app to do?
I except the app to open a new activity to change the passcode.

**Observed behaviour:**
There is nothing happening on clicking of the change passcode button.

**Device and Android version:**
Device Oppo Rmx1811 

@luckyman20 @geekanamika  can I Work on this issue?

**Comment by divyank00** [comment]
Duplicate of #519 and already fixed in #1202

**Comment by divyank00** [comment]
@vibhusharma101 So close this issue. Have a great day!

**Comment by vibhusharma101** [comment]
Already solved
