### ISSUE TITLE
Nothing happened after clicking surveys button in home activity

### ISSUE THREAD

**Issue by vibhusharma101** [openMF/self-service-app#1285]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39101226/72689326-42033280-3b36-11ea-9732-d7a04743f49b.gif)

**Summary:**

Surveys button is not functional.

**Expected behaviour:**
New activity must open after clicking surveys button in home activity

**Observed behaviour:**
Nothing happened on clicking surveys button

**Device and Android version:**
Device Oppo Rmx1811

I Want to work on this issue, If someone explains me how should the surveys activity functions and the layout of the survey activity. @luckyman20

**Comment by arunikayadav42** [comment]
I want to work on this issue. Please help me get started :)

**Comment by falayy** [comment]
maybe it's not functional because the feature hasn't been implemented.

**Comment by falayy** [comment]
HI @luckyman20  && @devansh-299  can we discuss the survey feature as a whole and what feature needs to be added so we can work on it?

**Comment by devansh-299** [comment]
> 
> 
> HI @luckyman20 && @devansh-299 can we discuss the survey feature as a whole and what feature needs to be added so we can work on it?

@corneliuze as far I know there's no backend support for surveys till yet. I guess this can be added to this year's to do list

**Comment by falayy** [comment]
That sounds like a plan, thanks, @devansh-299

**Comment by arunikayadav42** [comment]
Is this issue open? Please help me get clear about it :)

**Comment by falayy** [comment]
> Is this issue open? Please help me get clear about it :)
Talk to the mentors to close it.

**Comment by miPlodder** [comment]
Redundant of https://github.com/openMF/mifos-mobile/issues/582
