### ISSUE TITLE
FAB Button disappears

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1287]
**Summary:**

Fab button disappears in account section

**Steps to reproduce:**

Go to Accounts, swipe to Loan, swipe to Share, and then swipe back to loan or saving, the FAB button disappears.

**Expected behaviour:**

What did you expect the app to do?

The FAB button to reappear

**Device and Android version:**

One plus 6
Android Q

**Screenshots:**

![Desktop_20200121103129](https://user-images.githubusercontent.com/50913976/72777182-c9d26500-3c3a-11ea-8b1f-9cc8c4d3991f.gif)

**Comment by laxyapahuja** [comment]
Duplicate of #1001

**Comment by laxyapahuja** [comment]
Fixed in #1270

**Comment by divyank00** [comment]
Yeah😅
