### ISSUE TITLE
Login Button text Color to White

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#129]
**Summary:**

Change the Login button color to white because button text color is not making sense with our current theme.

**Comment by dilpreet2028** [comment]
Will be sending a quick PR

**Comment by therajanmaurya** [comment]
Go ahead👍, I have fixed a lot in code. Please force pull. Otherwise, you may get conflicts.

**Comment by dilpreet2028** [comment]
I just got confused with the summary given as it says " Login button colour to white" .. sorry for that ..
Fixed in #130

**Comment by therajanmaurya** [comment]
Fixed in #130
