### ISSUE TITLE
bug: User details Edit FAB button unfunctional

### ISSUE THREAD

**Issue by jddeep** [openMF/self-service-app#1293]
**Summary:**

User details Edit FAB button unfunctional.

**Steps to reproduce:**

Click on the User name in the home page. You will be directed to user details page.

**Expected behaviour:**

Remove the global FAB button and individual edit options should be available for necessary fields.

**Observed behaviour:**

Unfunctional.

**Device and Android version:**

Android 9

**Screenshots:**

<img src="https://user-images.githubusercontent.com/43133646/73048031-c4c12000-3e9d-11ea-9ed7-70bf0d09c7a1.png" width=300/>

**Comment by jddeep** [comment]
@luckyman20 @santoshconflux @geekanamika Can I work on this?

**Comment by luckyman20** [comment]
@jddeep You have to check if API for edit profile is available or not.

**Comment by jddeep** [comment]
> @jddeep You have to check if API for edit profile is available or not.

@luckyman20 Where can i find more details about checking the API in our app? Any features or screens in the app you can say which uses similar functionality?

**Comment by jddeep** [comment]
If editing profile is available(from api response) we can allow users to edit certain fields and update.

**Comment by Saransh0905** [comment]
@jddeep This issue is already mentioned in #1275

**Comment by jddeep** [comment]
@Saransh0905 The idea may be similar of both the issues. But the idea/approach of the resolution mentioned here (see the Expected behaviour section) is different. But the PR made to this issue will undoubtedly close #1275 as well.

**Comment by luckyman20** [comment]
No Fab button exist according to latest design.
