### ISSUE TITLE
bug: Keyboard settings for Account number field in Add beneficiary

### ISSUE THREAD

**Issue by jddeep** [openMF/self-service-app#1294]
**Summary:**

bug: Keyboard settings for Account number field in Add beneficiary

**Steps to reproduce:**
add n
Go to Third Party transfer -> Beneficiary -> Add -> Add beneficiary page

**Expected behaviour:**

Number type keyboard should pop up only for entering numerical digits

**Observed behaviour:**

Plain text type keyboard appears

**Device and Android version:**

Android 9

**Screenshots:**

<img src="https://user-images.githubusercontent.com/43133646/73048969-e079f580-3ea0-11ea-9929-1e2cf525dfca.png" width=300/>

**Comment by jddeep** [comment]
@luckyman20 @santoshconflux @geekanamika Can I work on this?

**Comment by luckyman20** [comment]
I am not sure if account number will always be in numeric characters only.

**Comment by jddeep** [comment]
> I am not sure if account number will always be in numeric characters only.

Hmm..if that is the case then we can keep it maybe if we are confident that account numbers can have text as well.

**Comment by luckyman20** [comment]
The thing is with little modification they can be in alpha-numeric (in case they are numeric only) so this wouldn't make sense then.
