### ISSUE TITLE
bug: passcode screen content should be centered along all devices

### ISSUE THREAD

**Issue by jddeep** [openMF/self-service-app#1295]
**Summary:**

bug: passcode screen should be centered along all devices.

**Steps to reproduce:**

Open the app once logged in.

**Expected behaviour:**

passcode screen content should be centered along all devices.

**Observed behaviour:**

passcode screen content was at upper portion of the screen.

**Device and Android version:**

Android 9

**Screenshots:**

<img src="https://user-images.githubusercontent.com/43133646/73083249-da136a00-3ef0-11ea-8cf0-e312acb0df7b.png" width=300/>

I would work on it.

**Comment by jddeep** [comment]
@luckyman20 @santoshconflux @geekanamika thoughts?

**Comment by ayushraj0309** [comment]
Hey @luckyman20 @santoshconflux @geekanamika , can i work on this one??

**Comment by luckyman20** [comment]
This is a issue of passcode library.
