### ISSUE TITLE
Apply for loan icon should be unique.

### ISSUE THREAD

**Issue by OHassini** [openMF/self-service-app#1299]
**Summary:**
It would be better to make the apply for loan icon in the Home activity unique, not similar to the accounts icon (as in mifos mobile cn app)
**Steps to reproduce:**
Just visit the home activity
**Expected behaviour:**
The apply for loan icon should be unique.
**Observed behaviour:**
The apply for loan icon is similar to the accounts icon.
**Device and Android version:**
This isn't related to android versions in any way.
**Screenshots:**
<img src="https://lh3.googleusercontent.com/2M_OdSUjmXAb_4yFwu-nVHTSo644Ov1xOTTYKuqhLReGMrwTUaAI4snpBPCo1O4q5WpdxbizwODInSkyrbZXNHVv5Qq2W8gllZSRumyZisvCYqQ_BmoES_1RqB7HWdP-jKCmaqBpuJNnWPDQf6ZuC6zGEnip-gAmabEJO8m8aJ0f7MB89DgO_VtafnD3bt1K-OsZVpCxrFBgVkIWrOvJlKxS14_pP9TNxLLZT4mEWY4zgZJOWGLnKo-AZdcpIaQQFZnziEBz9-aJXrL1xjdlnT2YFv52GjWuVOb-hyCwfPe4vsDLVOAZE9hH9EgZdVSYmHVrBlRRjTVFVeNsW8sK-q9ZO106g-HfgELtSVgG5qPe11PjgDs1ZzuO8zTbXgjzX-AK79OJjKMv23u8m64U8pBeWUKJ56CU1Hie9flZUTPSZsDA1j3OyNk_4rj9E9Mbq8rKhtrFzKFSCw-4rJDpd4SHX2Q3TY31AWcmkpO0FNmhw8-Ke6HQMnwyVPyvUsSt_yALorAK9R2QX265DvehAVODZXkQD3nXAHxHCf1OoOPxohSWax3HkGeu_BqTGmIbY4P07b24VmSYalr0FS3ilSyQoaHfVXjI0u_jw_N5wNifC2X6n7PGN7Jx8UhM1po2Avw0jdq0OYUj-bhNsTtLjtJNhG0toWEoUves64TxrSmNxR3E4M6nqUI=w561-h625-no" width="300" />

**Comment by OHassini** [comment]
@luckyman20 @geekanamika I would like to work on this !

**Comment by gururani-abhishek** [comment]
@jawidMuhammadi, let's open this issue for a newcomer. The PR that might solve this doesn't provide ss for the new changes made.

**Comment by vyukti13** [comment]
@OussEmaDevCode  
I want to work on this issue

**Comment by luckyman20** [comment]
@vyukti13 You may work on this issue.

**Comment by vyukti13** [comment]
Hi @OussEmaDevCode @luckyman20
I am unable to push the code could you please guide me. 
**remote: Permission to openMF/mifos-mobile.git denied to vyukti13.**

**Comment by luckyman20** [comment]
I would encourage you to read our [contributing guidelines](https://github.com/openMF/mifos-mobile/blob/development/.github/CONTRIBUTING.md#pull-requests) first to get an idea of how git things work in an open-source project.

If you have any other queries, you can comment here and ask, or you can reach out to me at gchirag@apache.org.

**Comment by vyukti13** [comment]
Thank you the help @luckyman20 
I have raise a PR
