### ISSUE TITLE
The contact us section is in the home fragment

### ISSUE THREAD

**Issue by OHassini** [openMF/self-service-app#1300]
**Summary:**
As in almost every major app out there, the contact us section should be in the about us fragment (or the help fragment in some rare cases).
The home fragment's main purpose is to be a sort of a dashboard and the contact us section doesn't add up to that main functionality.
**Steps to reproduce:**
Just visit the home activity
**Expected behaviour:**
The contact us section should be in the about us fragment.
**Observed behaviour:**
The contact us section is in the home fragment.
**Device and Android version:**
This isn't related to android versions in any way.
**Screenshots:**
<img src="https://lh3.googleusercontent.com/wAcfDdUqocsFrR0g0nmmEqqOvBFjrCWHHtXSjJRCfDIuBkpiWYT5zzHr2-j7bJG0a_ZWcnHvbEe0SgMv7UEbRZX6FlYl6pmsCukBxV4ks7UrLLMnjfPxh9Q953fsFn1N2FWiyTy2fy4CyLINV4D2VCq6kZqQeKrMDLq_r22Hus36_oeALcKVR90_IxtfnBhtR6WDKGDto6HNYPFpNwKORgPfzE14KTz7Ium4-00xY6rwX4Tk7bPCTUbHzhPW6AnbztkD0hBUm5SLCMk8jFGEWtG4p0Y1mgUnJQB0Ig8IrBG0oQBfFtGvvkgV03WQKJRhyn-0eWFyqoveMJQa8HyrXchDfpSlT3WxPY7a4VXl14kNcxkJSJhXOAy0NlVAYHp1FXqokPl8O0Qb2zKKnVh2J5Rl6hmG2X02lTbkWafphEn_hq4JvLnahABFDimJvEilmxp2XpfPUs2RnNhW6cBAsZtQOU2zFa5yEkLMKk3fy39UJgqidjrJRwBnhfNX1Y4ZBWmlTmP5C9dEUthAO1ohT3YPxZvPyfCVly5dEnUi3FPPVfR37SEZby1zccCB41k2b2MIWI50W3ruMMQi54LvWX-oN4WDanHa2uHqP6x5nOr0PVAofvdE69_NfJtIBwdnoY8lD5wyrWM_nxAQs3OWh_rdSAImqvYWcS8LY9Ivub6OzwnY030sofg=w352-h625-no" width="300" />

**Comment by OHassini** [comment]
@luckyman20 @geekanamika I would like to work on this !

**Comment by devansh-299** [comment]
Nice idea, but what about the empty space at the bottom?

**Comment by OHassini** [comment]
There isn't going to be empty space (in most devices)

**Comment by Bhavnaharitsa** [comment]
@OussEmaDevCode  @luckyman20  this feature seems good...can we have it in mobile_wallet as well? If so, I would like to work on it
