### ISSUE TITLE
Redesigning home screen

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1303]
**Summary:**

Currently the home screen layout looks very dated . The layout can be redesigned to provide better user experience 

**Steps to reproduce:**

Go to home fragment

**Proposed Design**

![image](https://user-images.githubusercontent.com/46667021/73392346-aaed6600-42ff-11ea-9210-bbfcc66b3375.png)

**Comment by devansh-299** [comment]
What are your thoughts @luckyman20 @geekanamika ?

**Comment by OHassini** [comment]
@devansh-299 Amazing design !!! seems like all the changes are there !!!!

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 Amazing design !!! seems like all the changes are there !!!!

Thanks @OussEmaDevCode for your suggestions :)

**Comment by Grandolf49** [comment]
@devansh-299 Good design. I think it's high time that we need to upgrade the UI of the application as it looks very out dated.

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 Good design. I think it's high time that we need to upgrade the UI of the application as it looks very out dated.

Thanks, just waiting for the mentor's approval

**Comment by devansh-299** [comment]
@naman14 @therajanmaurya  @luckyman20 what are your thoughts?

**Comment by jawidMuhammadi** [comment]
It would be much better if the icons in the bottom navigation bar are in minium standard width and height (24dpX24dp) and contain a label too. Take a look in this material desing guidelines please: https://material.io/components/bottom-navigation/# thanks

**Comment by devansh-299** [comment]
@jawidMuhammadi thank you for the suggestions, I will keep this in mind if I ever implement this design
