### ISSUE TITLE
there is no option for password forgot

### ISSUE THREAD

**Issue by amitYadavDev** [openMF/self-service-app#1304]
**Summary:**
there is no option for password forget
Summarize your issue in one sentence (what goes wrong, what did you expect to happen).

**Steps to reproduce:**
add an option to reset password through mobile number and email id
How can we reproduce the issue?

**Expected behaviour:**

What did you expect the app to do?

**Observed behaviour:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**
![Screenshot_20200130-222829](https://user-images.githubusercontent.com/45551012/73472042-83a3a100-43b2-11ea-8deb-81220deac55c.png)
Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

will I work on this?
yes.

**Comment by falayy** [comment]
I think you should have a discussion with the backend developers to ask if  forgot password feature was implemented

**Comment by amitYadavDev** [comment]
> I think you should have a discussion with the backend developers to ask if forgot password feature was implemented

@corneliuze can you give me channel of backend developers?

**Comment by falayy** [comment]
Well, I have no idea about that just reach out to people on gitter

**Comment by devanshi7799** [comment]
@amit6663 i would also like to work on this issue

**Comment by jawidMuhammadi** [comment]
Hey @devanshi7799 are you working on this issue. I would also like to work on it.

**Comment by devanshi7799** [comment]
@jawidMuhammadi You can on this  :)

**Comment by amitYadavDev** [comment]
@naman14 due to my continuous assessment I was busy now I continue with my full energy.

**Comment by ShivangiSingh17** [comment]
#718

**Comment by amitYadavDev** [comment]
already created #718
