### ISSUE TITLE
Skip passcode 

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1309]
**Summary:**

Currently when user chooses to skip passcode login then he needs to login via usual username and password but still after that user is greeted with "Set-Up Passcode" screen every time he tries to use the app . So if a user doesn't want to set up passcode ever this screen shouldn't be displayed for him/her until and unless he/she changes her mind.

**Steps to reproduce:**

* Clear data of app (if not running for the first time)
* Login in into the app
* Press "Skip" on the setup passcode screen -> Complete rest of the process
* Relaunch the app -> fill login details
* See that setup passcode screen appears everytime

**Expected behaviour:**

The setup passcode screen shouldn't be displayed everytime until and unless user wants to setup/use passcode verification

**Observed behaviour:**

The setup passcode screen is displayed every time the user tries to login in into the app if he doesn't want passcode login

**Device and Android version:**

Xiaomi PocoF1
Android 9
Stock Rom

**Comment by devansh-299** [comment]
@luckyman20  @geekanamika I would like to work on this issue

**Comment by amitYadavDev** [comment]
@naman14 can i work on this issue?

**Comment by Him887** [comment]
IS the issue fixed?? or  I can work on it??

**Comment by luckyman20** [comment]
@devansh-299 has already sent a Pull Request for this issue @amit6663 @Him887

Sorry, but you guys may like to fix some other issue.

**Comment by luckyman20** [comment]
I would also like to open a discussion here if we really need this feature. Almost all the apps in the market have a mandatory passcode thing. If the user has the intent to keep this app, then this is a huge time saver for them.

Thoughts? @gururani-abhishek @jawidMuhammadi
