### ISSUE TITLE
Adding Unit Tests 

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1310]
**Summary:**
Unit tests are not present for some files.
Adding Unit Tests for:
- AddGuarantorPresenter
- HelpPresenter
- HomePresenter
- QrCodeImportPresenter
- SavingsAccountApplicationPresenter

**Would you like to work on this issue?**
Yes

**Comment by miPlodder** [comment]
Anyone whosoever is interested in picking these issues can write a Unit test for any missing class. [Use Jacoco for it]

**Comment by ReCodee** [comment]
@miPlodder can i work on this issue??

**Comment by miPlodder** [comment]
@ReCodee Yes, go ahead

**Comment by luckyman20** [comment]
We will be adding unit tests during GSoC'23. Will create detailed issues later.
