### ISSUE TITLE
Incorrect icon shown

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1316]
**Summary:**

When user tries to open user profile in absence of internet connection, the message shown contains incorrect icon.

**Steps to reproduce:**

* Login into the app
* Turn off mobile data/Wifi
* Open user profile 
* See the screen being displayed

**Expected behaviour:**

The icon should be replaced with an appropriate one

**Screenshots:**
![WhatsApp Image 2020-02-05 at 4 50 05 PM](https://user-images.githubusercontent.com/46667021/73837498-9fd29280-4837-11ea-9047-58595223b9fa.jpeg)

**Comment by vrsandeep1** [comment]
Can I work on this bug?

**Comment by som23ya** [comment]
hey can i work on this?

**Comment by devansh-299** [comment]
@som23ya yeah, please go ahead

**Comment by som23ya** [comment]
i propose to recreate it this way. should i push the request?

![image](https://user-images.githubusercontent.com/43650322/74188331-378b1300-4c74-11ea-9f44-5e6c93e34e66.png)

**Comment by devansh-299** [comment]
> 
> 
> i propose to recreate it this way. should i push the request?
> 
> ![image](https://user-images.githubusercontent.com/43650322/74188331-378b1300-4c74-11ea-9f44-5e6c93e34e66.png)

yeah, I think this is perfect

**Comment by som23ya** [comment]
@devansh-299 Travis CI - Pull Request , Failing after 11m — Build Failed , what should i do to correct this? any idea?

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 Travis CI - Pull Request , Failing after 11m — Build Failed , what should i do to correct this? any idea?

@som23ya I have mentioned the changes required in PR section
