### ISSUE TITLE
message should be displayed when no accounts are found after search

### ISSUE THREAD

**Issue by dubeyaayush07** [openMF/self-service-app#1319]
**Summary:**

Currently when the search returns an empty list a blank screen is displayed, I am thinking we should display a no accounts found message instead

**Screenshots:**

<img src="https://user-images.githubusercontent.com/30518564/73918030-b84db600-48e6-11ea-8575-95960d0e15b4.jpg" height="50%" width="50%" >

**Comment by falayy** [comment]
@devansh-299  Let me work on this

**Comment by dubeyaayush07** [comment]
@corneliuze I am already working on this

**Comment by falayy** [comment]
Alright.

**Comment by falayy** [comment]
Ensure you ask the code maintainers for go-ahead before working on an issue
