### ISSUE TITLE
To implement the passcode feature so that user do not have to enter Username and Password Again And Again.

### ISSUE THREAD

**Issue by shivamarora96** [openMF/self-service-app#132]
**Summary:**
To implement the passcode feature so that user do not have to enter Username and Password Again And Again.

**Steps to reproduce:**
login with username & pass and simply close that app then open it again and you will see the login screen.

**Expected behavior:**
After successful login, app should prompt the user to set the security code (4-digit Numeric). After this whenever user reopened the app it should only ask for the security code instead of re-typing the username and password again and again.

**Observed behavior:**
App is asking for Password and Username again and again that led to poor UX/UI and it's quite annoying.

**Device and Android version:**
Android 6.0.1

**Screenshots:**
![screenshot_2017-03-05-00-18-50-502_in co bankofbaroda mpassbook](https://cloud.githubusercontent.com/assets/20308009/23598752/760575a8-0262-11e7-8f1d-5f079305e8b8.png)

**Comment by shivamarora96** [comment]
@therajanmaurya  I would like to work on this.

**Comment by shivamarora96** [comment]
Kindly assign me this issue.

**Comment by therajanmaurya** [comment]
Looks great, Go ahead 👍. Please follow app material styles for now.

**Comment by shivamarora96** [comment]
ok

**Comment by therajanmaurya** [comment]
You can make this quick, So I will review and try to add in this release.

**Comment by shivamarora96** [comment]
I am working on it and Complete this by the end of the day.Since its my first commit to the repo hence i need a little more time to deal with the codebase.

Surely i will make it by the end of the day

**Comment by shivam21** [comment]
hi,i would like to work on thiis issue.

**Comment by shivamarora96** [comment]
@shivam21 I have already implemented it.See PR

**Comment by shivamarora96** [comment]
@therajanmaurya Help needed!
1.when i hit this api not getting response! it says unautherized Access or Not found Errors
2.does access_token starts with Basic ? or its simply b64coded
3.getting error while hitting api.Is this url correct ? beacuse at wiki some other url is mentioned.
https://demo.openmf.org/fineract-provider/api/v1/self/userdetails?access_token={access_token}

Please reply quickly
Thankyou

**Comment by shivamarora96** [comment]
@therajanmaurya  kindly check this Api, getting error when i hit this api.
https://demo.openmf.org/fineract-provider/api/v1/self/userdetails?access_token={access_token}

**Comment by dilpreet2028** [comment]
@shivamarora96 why do you need to use this api in this feature ? And are you working on this issue ?

**Comment by shivamarora96** [comment]
@dilpreet96 so as to authenticate using access_token and load client in the homeactivity, beacuse without authrntication clients cannot be loaded.

**Comment by shivamarora96** [comment]
Basically what i am doing is starting the app with splash screen where passocode status is checked. If status not set then login activity is opened and authentication is done using username and password after this user goes to passcodeactivity where je can set the new passcode.Since authentication is already done so clients can be loaded Easily.(Till this i have implemented it)

But when passcode is already set then from splash screen user goes to Passcode activity without going to LoginActivity.Problem arises here, to load client i need to authenticate user hence through accesstoken i will authenticate and load client but api is giving error.

I've already  completed all the stuff above but since api isnt responding therefore client cannot be loaded

@dilpreet96

**Comment by shivamarora96** [comment]
Waiting for rajanmaurya's reply. @dilpreet96
@therajanmaurya ?

**Comment by code-dagger** [comment]
@shivamarora96 what I was thinking that when the user is logging in into the application for the first time, after successful authentication we should store the username and password in SharedPreferences and prompt the user to Add passcode security code and the next time the user opens the application if first asks for passcode and then checks if the SharedPreference has username and password if it has it then performs the authentication from server from that username/password and after authentication saves the token for that session only and for implementing this thing we also need a logout functionality in the application. So that if the user logs out of the application the details from sharedPreferences will be deleted and even the passcode too. @therajanmaurya If I wrong somewhere please correct me.

**Comment by anant-dev** [comment]
@therajanmaurya I agree with @shivamarora96  we should use Shared Preferences to remember user.
If Shared Preferences is the way ahead to implement this do assign me this issue.

**Comment by dilpreet2028** [comment]
@immabhay Saving username and password will not be a good way of doing things rather we should save clientId and authenication token only (which is already getting saved) 
@shivamarora96 you just need to remove preferncehelper.clear() which is clearing all the user credentials  and check for usertoken and client id if present then just go to the passcode activity and allow user to enter the passcode otherwise show the login screen with add passcode activity

**Comment by anant-dev** [comment]
@therajanmaurya  We can have a remember me option on the login screen to facilitate this feature .
![screenshot_2017-03-17-16-10-59-716](https://cloud.githubusercontent.com/assets/13196029/24039962/0c30208c-0b2d-11e7-9fe4-21d6da08f7bd.jpeg)

**Comment by Pritom14** [comment]
@anant-dev since it is a banking transaction app , so I think keeping a remember me option won't be helpful because if the user is logged in and someone else has his/her phone in which the app is installed then it might prove to be bad. 
What's your say?

**Comment by anant-dev** [comment]
@Pritom14 Yes I agree with your concern. Then the approach suggested by @shivamarora96 is correct as in India banking apps are using this feature to keep the credentials of the user safe.

Or we can just remember the username and not the password (which the user will only have to put). This will not need an additional api or screen.
@therajanmaurya @Pritom14 What do you say?

**Comment by shivamarora96** [comment]
@dilpreet96 @immabhay @anant-dev  @Pritom14 Guys dont change the method  suggested by me because the way i explained things has already been discussed with @therajanmaurya .See PR discussions.

Secondly, @dilpreet96 i have already removed clear method from homeActivity.
If you know how to access user from access_token then please help me with api, because api is giving me error.(Login is necessary to call load client)

Third, i have already just implemented this task by making a passcode activity , passcode view and passcode presenter.Almost the issue is solved just waiting for @therajanmaurya reply for how to get User from api using access_token beacause that api is giving error.

**Comment by ashish05182001** [comment]
Hello
@therajanmaurya @shivamarora96 @dilpreet96 @immabhay 
I have another idea for doing this task without using any api and with proper authentication.
At first time of user login I will save the username and password of user in the app itself. Then I can put a check to see the user is logged in first time or not by using shared preferences. Then there wont be any need to login again and again by the user. Also I can put passcode screen in between .

@therajanmaurya can i send a PR for one time login?

**Comment by dilpreet2028** [comment]
Added in #339
