### ISSUE TITLE
SUBMIT LOAN ERROR

### ISSUE THREAD

**Issue by HilaryKinyua** [openMF/self-service-app#1321]
This is the error am  receiving after clicking the SUBMIT LOAN button the datatable [Approval Notes] needs to be filled in before the current action can be proceeded.
Anyone with a solution to this error

**Comment by CapTen101** [comment]
Please describe the issue completely in accordance with the issue guidelines as written [here](https://github.com/openMF/mobile-wallet/blob/master/.github/CONTRIBUTING.md)

**Comment by ShivangiSingh17** [comment]
Can you please attach the screenshot of the same

**Comment by HilaryKinyua** [comment]
This is a sample screenshot of the error am getting in my app while trying to acquire the loan`
![Screenshot_20200210-090948](https://user-images.githubusercontent.com/22560606/74125251-d3217280-4be5-11ea-87f7-79dd6481059e.png)
`

**Comment by devansh-299** [comment]
> ![Screenshot_20200210-090948](https://user-images.githubusercontent.com/22560606/74125251-d3217280-4be5-11ea-87f7-79dd6481059e.png)

@HilaryKinyua your attachment is inaccessible, please attach it again

**Comment by HilaryKinyua** [comment]
![Screenshot_20200210-090948](https://user-images.githubusercontent.com/22560606/74147479-5fe32500-4c14-11ea-9781-ea4d385eab0b.png)

This is a sample screenshot of the error am getting in my app while trying to acquire the loan

**Comment by luckyman20** [comment]
Issue does not exist anymore.
