### ISSUE TITLE
Cancel manual login in PassCodeActivity does not work

### ISSUE THREAD

**Issue by dubeyaayush07** [openMF/self-service-app#1322]
**Summary:**

When the manual login dialog is cancelled in the `PassCodeActivity`, even though the user is not redirected to login manually the app does not recognize the user's passcode. This happens because in `MifosPasscodeActivity` `clearTokenPreferences` is called before `startLoginActivity`. I think we should get rid of the login dialog altogether because making the cancel dialog work would entail modifying `MifosPasscodeActivity`.

**Steps to reproduce:**

In the `PassCodeActivity` press 'forgot passcode, login manually' then cancel the dialog then try logging in with your passcode. 

**Screen Recording**
<img src="https://user-images.githubusercontent.com/30518564/74011111-0200d400-49ad-11ea-9370-99b19fc9c363.gif" height="60%" width="60%">

**Comment by dubeyaayush07** [comment]
I would like to work on this

**Comment by devansh-299** [comment]
@dubeyaayush07 I don't think removing the dialog itself is a good idea. The issue seems genuine, maybe you can try to find another way to fix this issue

**Comment by dubeyaayush07** [comment]
@devansh-299 I think we should not modify MifosPassCodeActivity as it is a generic class, and in PassCodeActivity setting the preferences after cleaning them seems awkward and redundant. While I was looking for a work-around I looked into mifos-wallet and they are kind of dealing with it the same way directly starting the Login activity. Any suggestions?

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 I think we should not modify MifosPassCodeActivity as it is a generic class, and in PassCodeActivity setting the preferences after cleaning them seems awkward and redundant. While I was looking for a work-around I looked into mifos-wallet and they are kind of dealing with it the same way directly starting the Login activity. Any suggestions?

Yeah setting the preferences again won't be a good idea but still removing dialog box itself still doesn't seem to be a good idea as I myself found it useful at times.

**Comment by dubeyaayush07** [comment]
@devansh-299  We will have to set the preferences again as they are needed for the PassCodeActivity to work the other option is to modify MifosPassCodeActivity which I am reluctant to do as all of these mifos app have this activity in common and modifying it would entail changing code in other apps too. Still I will see If I can find a work-around.

**Comment by luckyman20** [comment]
Covered in #2105
