### ISSUE TITLE
What is the name given to the loan repayment activity 

### ISSUE THREAD

**Issue by HilaryKinyua** [openMF/self-service-app#1328]
I am trying to whitelabel the application to meet my needs and can't find out the name given to the repay loan activity. Someone to help me see this activity

**Comment by devansh-299** [comment]
@HilaryKinyua I am not able understand the problem. Can you please use the template and be more precise?

**Comment by som23ya** [comment]
you can-
go to navigation menu- click on file , search for the desired activity. I guess there are two loan repay activities.

**Comment by HilaryKinyua** [comment]
@som23ya  which one specifically should be used for the purpose of loan repayment

**Comment by luckyman20** [comment]
Not an issue.
