### ISSUE TITLE
refactor Loan Repayment Schedule

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#133]
**Summary:**

Refactor Loan Repayment UI.

![image](https://cloud.githubusercontent.com/assets/5724482/23601323/e6d96754-0270-11e7-9537-bb53cb054be0.png)

How to navigate to the feature.
switch to loan accounts -> click on active account -> you can view repayment schedule.

**Comment by Pritom14** [comment]
Can I work on this?

**Comment by dilpreet96** [comment]
I would like to work on this

**Comment by therajanmaurya** [comment]
@Pritom14 Yes You can.

**Comment by Pritom14** [comment]
Thank you , I will try to send the PR as soon as I am done

**Comment by Pritom14** [comment]
@therajanmaurya can I get the api ?

**Comment by therajanmaurya** [comment]
@Pritom14 It's already implemented, In this issue you have to change the UI of the feature.

**Comment by Pritom14** [comment]
Okay

**Comment by therajanmaurya** [comment]
I have updated the description check again.

**Comment by dilpreet2028** [comment]
Can I work on this issue

**Comment by therajanmaurya** [comment]
Go ahead 👍

**Comment by dilpreet2028** [comment]
Added in #150
