### ISSUE TITLE
Loan Repayment

### ISSUE THREAD

**Issue by HilaryKinyua** [openMF/self-service-app#1330]
After applying for loan how can one repay his or her loan using mifos-mobile.Please someone to explain this it's urgent
I want to know how one can make payment of loan applied for

**Comment by Hilary325** [comment]
This is a great question! I'm thinking about applying for a stormgrams loan. Usually I don't run into debts, but I want to promote my business and didn't find investors. I heard about mifos-mobile, but I'm clueless about its work. So, I agree that it would be awesome if someone explained it here.

**Comment by luckyman20** [comment]
Not an issue.
