### ISSUE TITLE
Keywords disappear when the user clicks the option

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1332]
**Summary:**
After clicking certain options under the Help section activity some of the words disappear from the screen when they are clicked.

**Steps to reproduce:**
Under Help section, click on "Leave an email" and "Find Locations" option.

**Screenshots:**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43827236/74587751-7d512e00-501c-11ea-933c-2b00957404d3.gif)

**Device and Android version**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0
**Would you like to work on this issue?**
Yes

**Comment by jawidMuhammadi** [comment]
Hi @ShivangiSingh17  would you mention the device features which you have tested on it. I tried to reproduce the same as you have described but it is working as expected in Pixel 3 API 29 Emulator.

**Comment by ShivangiSingh17** [comment]
Updated

**Comment by luckyman20** [comment]
Issue does not exist anymore.
