### ISSUE TITLE
User details section 

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1333]
**Summary:**
User details are not visible until the user image is clicked.

**Expected behaviour:**
The user details should be shown even when the the name in clicked.

**Observed behaviour:**
The user details are not visible if you click on any other thing other than the user image.

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue.

**Comment by areebmomin** [comment]
@ShivangiSingh17 can i work on this issue

**Comment by ShivangiSingh17** [comment]
@areebmomin it works fine now. There is no such issue in the application anymore. You can try replicating the issue, its not there.

**Comment by s-ayush2903** [comment]
If the issue no longer exists, it should better be closed. What are your
thoughts on this?

**Comment by ShivangiSingh17** [comment]
@areebmomin you can work on this issue.
