### ISSUE TITLE
Loan transactions Recycler view

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1337]
**Summary:**

The loan transactions recyclerview does not cover the entire screen which ideally it is supposed to do . Currently it covers only the area required area to contain the items inside it. Hence swiping across them results in bad user experience

**Steps to reproduce:**
* Go to accounts -> Loan tab
* Select any disbursed loan
* Tap on Transactions

**Expected behaviour:**

Ideally the recycler view should have covered the entire remaining portion of the screen

**Device and Android version:**

Xiaomi PocoF1
Android 9
Stock Rom

**Comment by jawidMuhammadi** [comment]
I would like to work on this issue. But I am facing a problem. I followed your provided steps to reproduce 
Click Account -> Click on Loan Tab -> Click on any item of recycler view, nothing is happening.
Testing on Pixel 3 API 29 emulator. Any idea why, please help with this @devansh-299 . Thanks

**Comment by devansh-299** [comment]
@jawidMuhammadi first follow the below steps then you can interact with recyclerview  and can reproduce the issue

* In Android Studio go to `build.gradle` at Project level
* Change `supportLibraryVersion = '1.1.0'` to `supportLibraryVersion = '1.0.0'`

**Comment by jawidMuhammadi** [comment]
Thanks for your detailed help. I did solve your raised issue (#1337)

**Comment by jawidMuhammadi** [comment]
@devansh-299 When raising PR should I revert the change in `biuld.gradle` or not?

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 When raising PR should I revert the change in `biuld.gradle` or not?

@jawidMuhammadi actually even I also don't know what exactly should be done. I myself though do not revert the changes done in  `build.gradle` file

**Comment by jawidMuhammadi** [comment]
#Fix #1340

**Comment by luckyman20** [comment]
Issue does not exist anymore.
