### ISSUE TITLE
 creating account

### ISSUE THREAD

**Issue by som23ya** [openMF/self-service-app#1341]
**Summary:**
Introduction of more help section on  creating account fragment. If the user encounters any problems during creating account, an easy understandable guideline page should appear. 

**Steps to reproduce:**

How can we reproduce the issue?

**Expected behaviour:**

TO BE MORE REACHABLE.

**Observed behaviour:**
The app get confusing to new clients.

**Device and Android version:**

nexus 5, motorola g6

![image](https://user-images.githubusercontent.com/43650322/74477530-75d13e00-4ed1-11ea-9d6c-fa5e2a61d560.png)

**Comment by som23ya** [comment]
i would be working on this one.

**Comment by falayy** [comment]
Hi @som23ya , well-done, I think you should talk with the project maintainers if there would be a need for this and for approval ofcourse.

**Comment by som23ya** [comment]
@corneliuze who are the project maintainers and mentors currently?

**Comment by falayy** [comment]
well, I don't know but I tag @devansh-299 every time

**Comment by devansh-299** [comment]
> 
> 
> well, I don't know but I tag @devansh-299 every time

well, I am not a mentor xD
