### ISSUE TITLE
country code picker

### ISSUE THREAD

**Issue by som23ya** [openMF/self-service-app#1342]
**Summary:**
A drop down list of country codes appearing for phone numbers while creating account

**Expected behaviour:**

TRADITIONAL INPUT OF PHONE NUMBERS.

**Device and Android version:**

nexus 5, motorola g6

![image](https://user-images.githubusercontent.com/43650322/74478270-0eb48900-4ed3-11ea-98e4-341ee33ea382.png)

**Comment by som23ya** [comment]
I would be working on this.

**Comment by falayy** [comment]
Hi @som23ya  are you still working on this?

**Comment by jawidMuhammadi** [comment]
Hey, @corneliuze  it has been more than 15 days she has not raised any PR regarding this. So you can start work on it.

**Comment by som23ya** [comment]
@corneliuze @jawidMuhammadi i had my examination so couldn't commit uptil now. I m still working on it  :)

**Comment by rutvik-panchal** [comment]
Can i work on this issue?

**Comment by PratyushSingh07** [comment]
@som23ya can i work on this?
