### ISSUE TITLE
proposed UI for surveys

### ISSUE THREAD

**Issue by som23ya** [openMF/self-service-app#1343]
**Summary:**
Currently, the survey feature has no functionality. I would to propose some to it.
**Expected behaviour:**

NO functionality.

**Device and Android version:**

nexus 5, motorola g6

**Comment by som23ya** [comment]
I would be working on this.

**Comment by devansh-299** [comment]
@som23ya  this issue has already been pointed out many times. Also as far as I know currently there's no back-end support for surveys

**Comment by ShivangiSingh17** [comment]
Can you go please through this:
https://github.com/openMF/mifos-mobile/issues/841
