### ISSUE TITLE
change password UI

### ISSUE THREAD

**Issue by som23ya** [openMF/self-service-app#1344]
**Summary:**
user can directly change password without acknowledgement of current one.

verification with current password should be implemented first.

I would like to design a mockup UI for this.

**Device and Android version:**

nexus 5, motorola g6

![image](https://user-images.githubusercontent.com/43650322/74480876-b7fd7e00-4ed7-11ea-8bdf-fadbeb41d4d4.png)

**Comment by som23ya** [comment]
I would like to design a mockup UI for this.

**Comment by deecodesss** [comment]
I would be taking up on this
