### ISSUE TITLE
Shared Preference for auto login functionality

### ISSUE THREAD

**Issue by som23ya** [openMF/self-service-app#1345]
**Summary:**

Once the app is exited, it gets automatically logged out.

**Steps to reproduce:**

Use Shared Preference for auto login functionality. When users log in to your application, store the login status into sharedPreference and clear sharedPreference when users log out.

**Device and Android version:**

moto g6, nexus 5

**Comment by som23ya** [comment]
I would be working on this one.

**Comment by som23ya** [comment]
This is risky ,as it raises security issues. Should this be implemented?

**Comment by jawidMuhammadi** [comment]
I think it is not a good idea to save the user's credentials in SP and implement auto-login; as you know it is a banking app and credentials are very sensitive data. To make login easier we already providing an optional feature of setting 4 digit passcode for users. But still, if you want to implement this, I would suggest you first talk with any mentors about it.
