### ISSUE TITLE
toast prompt on change password, slow internet

### ISSUE THREAD

**Issue by som23ya** [openMF/self-service-app#1346]
When slow or no internet connection is there, no toast or prompt appears, in change the password section. 

Error message should be displayed to user.

device moto g6, nexus 5.
![image](https://user-images.githubusercontent.com/43650322/74483221-09a80780-4edc-11ea-927d-9b1d8a79188a.png)

**Comment by som23ya** [comment]
i would be working on this.

**Comment by neeraj0403** [comment]
@som23ya are u working on this issue?

**Comment by som23ya** [comment]
@neeraj0403 yes, i m.  :)
