### ISSUE TITLE
App crashes when user clicks on last item of Purpose of Loan spinner

### ISSUE THREAD

**Issue by jawidMuhammadi** [openMF/self-service-app#1347]
**Summary:**
On apply for loan fragment after selecting any item from Loan Product spinner when you select the last item from the _Purpose of Loan spinner_, App crashes.

**Steps to reproduce:**

- Go  to Home Screen -> Tap on Apply for Loan
- Click on Select Loan Product spinner -> Select any item you want
- Click on Purpose of Loan spinner -> Select the last time.

**Expected behaviour:**
When you select last item from Puropose of Loan spinner app should not crash.

**Device and Android version:**
Pixel 3 API 29
Android Q (10)
Emulator

**Comment by jawidMuhammadi** [comment]
I will be working on it.

**Comment by devansh-299** [comment]
@jawidMuhammadi this issue has already been solved #1212

**Comment by jawidMuhammadi** [comment]
@devansh-299 I did have searched about this issue to know is it exists or not but I have not checked your code. Yeah, it has already been solved. So should I close the bug?
