### ISSUE TITLE
UI Enhancement in Loan Summary.

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#135]
**Summary:**

UI enhancement in Loan Summary 

![image](https://cloud.githubusercontent.com/assets/5724482/23605076/52c1ea76-0281-11e7-8e12-261cef3acd80.png)

About the status if the account check savings account summary implementation.

**Comment by Pritom14** [comment]
can I work on this?

**Comment by rahulbabbar1** [comment]
I would like to work on this.

**Comment by therajanmaurya** [comment]
@Pritom14 This is not the way of working. Please pick only one issue at a time.
I can not assign you another issue till that you will complete the previous one.

**Comment by therajanmaurya** [comment]
@rahulbabbar1 yes you can, Go ahead 👍

**Comment by rahulbabbar1** [comment]
okay.
