### ISSUE TITLE
Adding support  for Turkish and Persian languages

### ISSUE THREAD

**Issue by jawidMuhammadi** [openMF/self-service-app#1351]
**Summary:**
The app does not support Turkish and Persian languages. By adding support for these two languages we can reach many people in need from Turkey, Azerbaijan, Turkmenistan, Iran, Tajikistan, and Afghanistan.

**Comment by jawidMuhammadi** [comment]
Should I work on this? If it is something necessary I can translate to these languages very well; because Persian is my native language and Turkish is the language that I have studied for 5 years during my high school and have a Gold Medal from Turkish International Olympiads.

**Comment by miPlodder** [comment]
I don't see any requirement for additional language support. Hence closing it.
