### ISSUE TITLE
Blank screen shown when filtering returns no results

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1356]
**Summary:**

Currently when there are no transactions related to a savings account a blank screen is shown. This can rise either because of certain filters being applied or no transactions were made at all 

**Steps to reproduce:**

* Go to accounts ->Savings account
* Select any approved account
* Tap on transactions
* Apply filters to get no search results/choose a savings account that had no transactions

**Expected behaviour:**

Message should have been displayed using `sweetUIErrorHandler`  

**Observed behaviour:**

A blank screen is shown

**Screenshots:**

![WhatsApp Image 2020-02-15 at 11 33 54 PM](https://user-images.githubusercontent.com/46667021/74592999-f36d8900-504c-11ea-8dbf-4bdb231f0d17.jpeg)

**Comment by luckyman20** [comment]
Unable to reproduce this issue.
