### ISSUE TITLE
ApplySavingsFragment 's UI refactor proposal

### ISSUE THREAD

**Issue by jawidMuhammadi** [openMF/self-service-app#1361]
**Summary:**
I want to redesign the ApplySavingsFragment's UI. Here are the reasons why:

1. Current screen design does not follow material design guidelines like margins and spacings
2. In landscape orientation, the screen is not scrollable and also not able to see the submit button in 
 small screens 
3. Submit button's height becomes very small in larger devices
4. A redundant card view has been added in the screen

**Steps to reproduce:**

- Go to accounts -> Savings tab
- Click on Add FAB

**Expected behaviour:**

To provide a good UX to our user it is very important to follow Material Desing guidelines

**Observed behaviour:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

Pixel 3, API 29
Android Version 10 (Q)
Emulator

**Screenshots:**

**Current design**

![Screenshot_1581931045](https://user-images.githubusercontent.com/49963168/74639630-3c7c2500-5194-11ea-9349-9fc804998cd5.png)

![Screenshot_1581931073](https://user-images.githubusercontent.com/49963168/74639661-49991400-5194-11ea-9253-1d30c4f64c13.png)

*My refactored propose design*

![Screenshot_1581929586](https://user-images.githubusercontent.com/49963168/74639743-70efe100-5194-11ea-84c2-a68f8e1d74bc.png)

**Comment by jawidMuhammadi** [comment]
Dear @naman14 @therajanmaurya @luckyman20 what are your thoughts? If you approve and agree with it. I would like to implement it. Thanks

**Comment by deecodesss** [comment]
I would be taking up on this issue
