### ISSUE TITLE
Apply for Loan UI refactor proposal 

### ISSUE THREAD

**Issue by jawidMuhammadi** [openMF/self-service-app#1362]
**Summary:**

I would like to refactor UI  for ApplyLoanFragment. Because the current design does not follow the Material Design guidelines in both RTL and LTR languages.

**Steps to reproduce:**

- Go to accounts -> Loan tab
- Click on Add FAB

**Expected behaviour:**

It is very important to follow material design guidelines to make the app look awesome and provide smooth and clear UX for users.

**Device and Android version:**
1. Large device: 

        Pixel 3, API 29
        Android Version 10 (Q)
        Emulator

2. Small device:

        Samsung Galaxy, E5
        Android Lollipop version  5.0

**Screenshots:**

![Screenshot_1581935977](https://user-images.githubusercontent.com/49963168/74647621-fe85fd80-51a1-11ea-9b63-6923b649543b.png)

**In RTL Languages like Arabic**

![Screenshot_1581936005](https://user-images.githubusercontent.com/49963168/74647656-1067a080-51a2-11ea-9bbb-22a278cc4855.png)

**In smaller devices**

![Screenshot_2020-02-17-01-28-13 (1)](https://user-images.githubusercontent.com/49963168/74647731-368d4080-51a2-11ea-8087-1948844552a1.png)

**And my proposed UI**
 
![Screenshot_1581935858](https://user-images.githubusercontent.com/49963168/74647830-69cfcf80-51a2-11ea-8daa-651c83c927c8.png)

**Comment by jawidMuhammadi** [comment]
Dear @naman14 @therajanmaurya @luckyman20 what are your thoughts? If you approve and agree with it. I would like to implement it. Thanks

**Comment by jawidMuhammadi** [comment]
The proposed UI Background should be white. During desing, I have forgotten to change from greyish to white.

**Comment by deecodesss** [comment]
I'll be taking up on this issue.
