### ISSUE TITLE
clicking back button in navigation drawer items completely exiting App

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#137]
by clicking back button in the layout of  any item in navigation drawer( Recent transactions,charges,help...etc) it's closing complete app, it will be better if we go first to home screen(Accounts screen) and then closing app...

@therajanmaurya can you please look at this issue...
if this issue is considerable ,i would like to work on this issue..

**Comment by therajanmaurya** [comment]
Go ahead 👍

**Comment by shivam21** [comment]
hi,i would like to work on this issue

**Comment by dilpreet2028** [comment]
@therajanmaurya PR already merged, closing issue
