### ISSUE TITLE
Add Dark/ Night Mode 

### ISSUE THREAD

**Issue by iamsharad98** [openMF/self-service-app#1370]
**Summary:**

The night mode in app will enhance the user experience and it will reduce eye strain at night.

**Screenshots:**
Some example screenshots of apps using night mode
![ios-13-dark-mode-1200x1084](https://user-images.githubusercontent.com/26202526/75096865-d9422680-55c9-11ea-905e-8a9ada92d2c3.jpg)

**Comment by iamsharad98** [comment]
I would like to work on this feature.

**Comment by devansh-299** [comment]
@anonghostteamz I think @prashantkh19 had already successfully implemented this feature during his GSoC'19 period

**Comment by iamsharad98** [comment]
But I don't find this feature anywhere in-app, so maybe it's incomplete or not accepted by the organisation so, may I give it a try?

**Comment by ShivangiSingh17** [comment]
This issue is already raised in another issue. Can you please close this issue to avoid the duplication of the same issue.
