### ISSUE TITLE
Unable to login after updating api endpoint 

### ISSUE THREAD

**Issue by HilaryKinyua** [openMF/self-service-app#1380]
Someone to clearly explain how we should change the endpoints because after updating the endpoints the app is not logging in.
I even went ahead to change the following codes to our endpoints:
public static final String API_ENDPOINT = "mobile.openmf.org";
public static final String API_PATH = "/fineract-provider/api/v1/self/";
public static final String PROTOCOL_HTTPS = "https://";

Still not working.

**Comment by iamsharad98** [comment]
This issue is already open in #1378 then why you recreate this issue.

**Comment by HilaryKinyua** [comment]
I recreated it because it was never solved
