### ISSUE TITLE
Flash on/off option in qr code scanner

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1381]
**Summary:**

Similar to Mifos-Wallet, the flash functionality while scanning the qr code should be implemented here also as this can prove to be very beneficial in certain conditions

**Steps to reproduce:**

* Go to Add beneficiaries
* Tap on Scan

**Expected behaviour:**

Flash functionality should have been implemented

**Comment by falayy** [comment]
Hi @devansh-299, I was thinking, I could hop on this.

**Comment by devansh-299** [comment]
> Hi @devansh-299, I was thinking, I could hop on this.

I actually solved this in  #1382

**Comment by falayy** [comment]
oh alright, let me review then.
