### ISSUE TITLE
Update the UI design of EditProfile

### ISSUE THREAD

**Issue by iamsharad98** [openMF/self-service-app#1384]
**Summary:**

The design of the fragment user profile looks too old and not enhancing the user interface.

**Expected behaviour:**
The UI design should look good for first-time users.

**Device **
Mi Note5 Pro 

**Screenshots:**
**The UI design right now**:-

<img src="https://user-images.githubusercontent.com/26202526/75596906-93e59380-5ab8-11ea-8ce6-05cdfe717ec6.jpeg" width="200" height="400" />

### 1.
<img src="https://user-images.githubusercontent.com/26202526/75790721-99312f80-5d91-11ea-9205-62ca49eee46e.jpeg" width="200" height="400" />
### 2.
<img src="https://user-images.githubusercontent.com/26202526/75790634-7bfc6100-5d91-11ea-9628-9a0ceccc68df.jpeg" width="200" height="400" />

**Comment by iamsharad98** [comment]
I would like to work on this issue

**Comment by jawidMuhammadi** [comment]
Hey, @anonghostteamz before starting to refactoring any UI or proposing any please make Mock design which should show the final look of the exact screen. During designing keep in mind that we have to follow an exact design pattern to the entire app to keep consistency which is very important.

**Comment by iamsharad98** [comment]
Okay, @jawidMuhammadi I will add the screenshot in my PR and I always design UI by taking the previous design pattern in my mind. BTW thanks for the suggestion.

**Comment by devansh-299** [comment]
@anonghostteamz can you please first attach the screenshot of your design scheme because as @jawidMuhammadi said its important to follow one design scheme throughout the application.
You can use [Figma](https://www.figma.com/) etc for the same

**Comment by iamsharad98** [comment]
@jawidMuhammadi @devansh-299 I already designed the UI and only I need to resolve some issues. 
I update my issue and add screenshots of my design, check it out.

**Comment by jawidMuhammadi** [comment]
@anonghostteamz  Why you have added all those different icons and how did you find them?  Would you give us some more details about it?
 Please note that icons play a very important role, once we use an icon for a specific title than we have to use the same across all our products on mobile and web. In the future when you decide to make some important UI changes, first please discuss with the community and tell why you want to refactor it,  what is wrong with the current one, and how your change is going to make a difference from UX and UI perspectives for users by keeping consistency. Thanks.

**Comment by jawidMuhammadi** [comment]
Please make sure to use the same color for hints or titles as it is used on other screens and the icon style also should be filled or bordered according to other icons in the app. You have used different styles of icons and different colors for titles and icons too which does not follow material design guidelines.

**Comment by devansh-299** [comment]
@anonghostteamz before you start working on the issue, according to me it would be better to first consult with the mentors

**Comment by iamsharad98** [comment]
Okay, @devansh-299 can you share me the mail or something using which I can contact the mentors. Because, as I saw, everyone here working on issues without any permissions. But if I get any contact email then definitely, I first consult with mentors and then start contributing.

**Comment by luckyman20** [comment]
Design has changed since.
