### ISSUE TITLE
Improvements in source code

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1385]
**Summary:**

The source code of mifos-mobile still has scope of being improved in terms of refactoring, code documentation, and reducing boilerplate.

**Scope of Improvement:**

* Documentation of Presenters and some fragments
* Reduction in boilerplate by using functions
* Reduction in line of code
* Use of `else if` instead of multiple `if`

**Comment by luckyman20** [comment]
I think we should have some guidelines regarding documenting code.

Thoughts? @jawidMuhammadi @gururani-abhishek

**Comment by luckyman20** [comment]
Code is migrated to Kotlin.
