### ISSUE TITLE
Could not create a new account with the lastest development branch code

### ISSUE THREAD

**Issue by souravmunjal** [openMF/self-service-app#1391]
**Summary:**

Could Not create a new account with the create account

**Steps to reproduce:**

1. Go to create account page.
2. Fill the Details
3. Giving error "Client not found with basic details"

Lenovo K5 (Android Version Lollipop 5.0)
version from the manufacturer or a custom ROM?

**Screenshots:**
![Screenshot_2020-03-07-21-53-15](https://user-images.githubusercontent.com/30770269/76147323-22fa3900-60c1-11ea-830f-3f09d140f39f.png)

**Comment by souravmunjal** [comment]
@devansh-299 could you please look into this?

**Comment by devansh-299** [comment]
> @devansh-299 could you please look into this?

@souravmunjal for creating a self service user, first you need to create an account from the MifosX webapp then you can register from the mobile app using the account number and other details that you got. If you want to login for developer purpose, you can login using the these credentials
Username: 299devansh
Password: password
