### ISSUE TITLE
ViewGuarantor - recyclerview doesnot fill entire screen

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1394]
**Summary:**

The recyclerview inside the ViewGuarantorFragment doesnot fill the entire screen because of which animation for reaching the bottom of recyclerview appears in the middle of the screen

**Steps to reproduce:**
* Go to any loan that hasn't been approved
* Go to menu -> View Guarantor

**Expected behaviour:**

The recyclerview should have completely filled the screen

**ScreenRecording:**
![GIF-200309_011204](https://user-images.githubusercontent.com/46667021/76169921-2239d380-61a3-11ea-8b16-1eddff001f80.gif)

**Comment by ankurxshukla** [comment]
Working on it.

**Comment by rutvik-panchal** [comment]
> Working on it.

@ankurxshukla 
Are you still working on it, if not then can I work on it?

**Comment by rutvik-panchal** [comment]
@devansh-299 I think it's been a long time and @ankurxshukla has not raised any PR regarding this issue, Can I work on it?
