### ISSUE TITLE
Scrolling functionality is not available

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1399]
**Summary:**
The scrolling is not available thereby restricting the complete view of the details.

**Steps to reproduce:**
Under the ```Accounts``` section, click on ```Loan``` .

**Expected behaviour:**
User should be able to scroll through the whole content available.

**Observed behaviour:**
The scroll functionality is not available.

**Device and Android version:**
Android 8.1.0
Funtouch OS_4.0

**Would you like to work on this issue?**
Yes

**Comment by devansh-299** [comment]
@ShivangiSingh17 this problem has already been solved. Sync your fork of the project with the upstream

**Comment by ShivangiSingh17** [comment]
Its already in the sink and the issue still exists. I can't find this issue been addressed anywhere?

**Comment by devansh-299** [comment]
You mean that `recyclerview` is not scrolling?

**Comment by luckyman20** [comment]
Unable to reproduce this issue.
