### ISSUE TITLE
Invalid email

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1400]
**Summary:**
When the user inputs the email address, invalid email address is also getting accepted and not showing the error message of invalid email inputed by the user.

**Steps to reproduce:**
While creating a new account, input the email  ```.......@gmail.com```

**Expected behaviour:**
The error message should be shown about the invalid input. 

**Observed behaviour:**
The address error is not displayed in the message. 

**Device and Android version:**
vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Would you like to work on this issue?**
Yes

**Comment by rutvik-panchal** [comment]
@ShivangiSingh17 
There is validation for the email input field already.

**Comment by ShivangiSingh17** [comment]
@rutvik-panchal validation exists but the mentioned issue arises and the condition needs to be mentioned in the codebase. Please reproduce and issue and check.

**Comment by rutvik-panchal** [comment]
> @rutvik-panchal validation exists but the mentioned issue arises and the condition needs to be mentioned in the codebase. Please reproduce and issue and check.

Reproduced with the latest branch of development, it's working fine for me as expected.
