### ISSUE TITLE
Qr code icon different than the rest

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1401]
**Summary:**

The qr code icon inside SavingsAccountDetails and LoanAccountDetails fragment has different color than rest of the icons displayed on the screen

**Steps to reproduce:**

* Go to Loan/Savings account that has been approved
* Observe the icons

**Expected behaviour:**

Like other icons, the qr code icon should be blue and white

**Observed behaviour:**

Oddly it has grey-white color scheme

**Screenshots:**

![WhatsApp Image 2020-03-09 at 8 14 41 PM](https://user-images.githubusercontent.com/46667021/76225662-da6a8900-6242-11ea-97e1-0ae0e4a44206.jpeg)

**Comment by rutvik-panchal** [comment]
@devansh-299 Would like to work on this issue, Are you working on it?

**Comment by devansh-299** [comment]
> @devansh-299 Would like to work on this issue, Are you working on it?

No, I am not working on this issue. You can work on it

**Comment by rutvik-panchal** [comment]
> No, I am not working on this issue. You can work on it

Working on it.
