### ISSUE TITLE
Invalid authentication Details passed to API

### ISSUE THREAD

**Issue by HilaryKinyua** [openMF/self-service-app#1407]
After updating mifos mobile to work with my endpoint say for example my endpoint is ="42.345.154.28/Xyz_company" in the BaseURL.java  and also changing The file SelfServiceInterceptor.java DEFAULT_TENANT to default instead of mobile am getting this error while trying to login Invalid authentication Details passed to API. 

I have already created the self service user and assigned that user the selfservice role and also created a username and a password for that user. 
Am using the correct details to login the user.
Somebody to assist me to resolve this issue please.

**Comment by CodyHarsh** [comment]
Yes, I have also had the same problem so here are the id's from which you can log in
Username: 299devansh
Password: password
