### ISSUE TITLE
Error in EditText View on Login Page doesn't get removed on entering data

### ISSUE THREAD

**Issue by virajpatel2411** [openMF/self-service-app#1408]
Summary : If user clicks on login button without entering the username and password i.e leaving both fields empty then error is shown. When user clicks on the username field to enter valid data the error doesn't get removed. Same is the case with password field.

Steps to reproduce : Listener is to be kept so that clicking on the respective field, the error of the respective field gets removed.

Expected behaviour : Once error is shown, user learns that username and password has to be entered so if he/she clicks on the respective fields the respective errors should be removed.

Observed behaviour : On clicking the respective username and password fields, the errors doesn't get removed.

Device and Android version : One Plus 6 (Android 10)

Screenshots :
![1](https://user-images.githubusercontent.com/36664384/76529436-485bbe00-6498-11ea-992e-a1579dcfa148.jpeg)

**Comment by virajpatel2411** [comment]
I will work on this issue @virajpatel2411

**Comment by gururani-abhishek** [comment]
It's been a long time since the last PR, I'll be researching and taking up this issue.

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi, please review this PR.
