### ISSUE TITLE
Improper UI in Login page

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1409]
**Summary:**
The UI on the login page is not proper.
**Steps to reproduce:**
On the login page without filling any of the fields click on the ```Login``` button and notice the blockage of the ```password``` field heading from the bottom.

**Expected behaviour:**
The **password** field should be properly placed.

**Observed behaviour:**
Due lack of spacing the password field is not placed properly and effects the UI.

**Device and Android version:**
Vivo 1724
Android 8
**Would you like to work on this issue?**
Yes

**Comment by AntonAsmirko** [comment]
Can I work on this issue?

**Comment by AntonAsmirko** [comment]
Is the problem in biasing the password field when user clicks login button?

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi, I think this has already been resolved in some other UI revamp. I'm attaching the screenshot when I did the "steps to reproduce"  
<img width="356" alt="Screenshot 2023-03-16 at 14 22 32" src="https://user-images.githubusercontent.com/59947871/225565023-697082b3-e453-49ab-a674-215690cd60e4.png">


Password field isn't blocked anymore, I think the issue can be closed now.

**Comment by jawidMuhammadi** [comment]
@gururani-abhishek Thanks for the screenshot, did you test it on the latest code from the master branch?

**Comment by gururani-abhishek** [comment]
@jawidMuhammadi I tested it on the latest code from "development" branch.
