### ISSUE TITLE
Add name of user in NavBar Header.

### ISSUE THREAD

**Issue by m-murad** [openMF/self-service-app#141]
**Summary:**
Like most of the apps we should add name of the User in the NavBar Header.

**Expected behavior:**
The NavBar Header does not have the name of the user who has logged in.

**Observed behavior:**
The NavBar Header has not text.

**Device and Android version:**
Moto G4 Plus, Android 7

**Comment by m-murad** [comment]
@therajanmaurya 
Should I send a PR?

**Comment by m-murad** [comment]
@therajanmaurya 
What about this one?

**Comment by therajanmaurya** [comment]
@free4murad It's not fixed, We have to add a feature in for showing the client detail.
Checkout https://github.com/openMF/self-service-app/issues/64 and let me know, If you wanna pick.

**Comment by shivam21** [comment]
I want to work on this issue.Please assign me this

**Comment by therajanmaurya** [comment]
fix in #290
