### ISSUE TITLE
Improper warning message is shown

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1410]
**Summary:**
Warning message shown at the ```Create an account``` page is misleading and needs to be improved.
**Steps to reproduce:**
While creating the new account click directly on the ```Register``` button without any input of data.

**Expected behaviour:**
All the **Required** fields should be display the warning message at a time instead of showing separately field by field. 
**Observed behaviour:**
When the user clicks register button without any input of data, the required fields are not shown together as it happens while logging in. 
**Device and Android version:**
Vivo 1724
Version 8

**Would you like to work on this issue?**
Yes

**Comment by AntonAsmirko** [comment]
I am working on this issue

**Comment by ShivangiSingh17** [comment]
@AntonAsmirko I created the issue and I am already working on it.

**Comment by shreyashcode** [comment]
Is the issue resolved ? I want to work on it.
