### ISSUE TITLE
Back button pressed moves the app directly to the home screen

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1411]
**Summary:**
When the user clicks on the back button from  the ```Change password``` activity it gets redirected to the home screen.
**Steps to reproduce:**
Open ```Settings``` and select ```Change password``` option and press the back button.

**Expected behaviour:**
The back navigation should redirect to the Settings main activity.

**Observed behaviour:**
When the user clicks back button from the change password activity, the user is redirected to the home screen.

**Device and Android version:**
Vivo 1724
Android Version 8.1.0

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue.

**Comment by devansh-299** [comment]
@ShivangiSingh17 I addressed this issue in #1313 and thus this problem has already been solved.
Thus this issue shouldn't be reproducible on the latest commit
