### ISSUE TITLE
Change the Help icon in Nav Bar

### ISSUE THREAD

**Issue by m-murad** [openMF/self-service-app#142]
**Summary:**
The `About Us` and `Help` icons are the same.

**Expected behavior:**

The icons should be different. The `About Us` icon is fine but we can replace the `Help` icon with an appropriate one given in Android Icon assets.

**Device and Android version:**

Moto G4 Plus, Android 7

**Screenshots:**
![screenshot_20170307-032550](https://cloud.githubusercontent.com/assets/17262180/23631877/e6da20f2-02e5-11e7-84b3-b5c89512c285.png)

**Comment by m-murad** [comment]
@therajanmaurya 
Should I send a PR.

**Comment by therajanmaurya** [comment]
Yeah Go ahead 👍

**Comment by therajanmaurya** [comment]
Added in #144
