### ISSUE TITLE
Improper Error display in AddBeneficiaryFragment

### ISSUE THREAD

**Issue by virajpatel2411** [openMF/self-service-app#1421]
**Summary:**

Improper Error display in AddBeneficiaryFragment

**Steps to reproduce:**

Add proper touch listeners to remove errors on typing in the field.

**Observed behaviour:**
![1](https://user-images.githubusercontent.com/36664384/76842355-23809580-6860-11ea-98a3-5c9bc41ed452.jpeg)

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

One Plus 6
Android 10

**Comment by ShivangiSingh17** [comment]
The issue doesn't exist in the application.
![issue](https://user-images.githubusercontent.com/43827236/82731561-788bcc80-9d25-11ea-92d7-5cdfd96f45ce.jpg)

**Comment by ShivangiSingh17** [comment]
@virajpatel2411 close it.
