### ISSUE TITLE
RecentTransaction items are unnecessarily clickable.

### ISSUE THREAD

**Issue by m-murad** [openMF/self-service-app#143]
**Summary:**
In `Recent Transactions` fragment the list items are clickable. On clicking theses items the ripple effect can be seen but nothing happens. This confuses the user if every thing is working fine or not.

**Expected behavior:**
The ripple effect should be disabled so that there is no confusion.

**Observed behavior:**
The ripple effect creates confusion if some other activity has to open.

**Device and Android version:**
Moto G4 Plus, Android 7

**Comment by m-murad** [comment]
@therajanmaurya 
Should I send a PR?

**Comment by hardik124** [comment]
I think it's better to leave it like that , because later there could be a transaction detail fragment which will open  when user clicks on a transaction.

**Comment by therajanmaurya** [comment]
@hardik124 You are right, In future, we will implement Transaction Details Fragment. That's why I did not remove the ripple effect.

**Comment by therajanmaurya** [comment]
Closing Now.

**Comment by m-murad** [comment]
@therajanmaurya  @hardik124 
Sure if in near future we are implementing the feature then we should keep it.
But if we are planning an early release (before implementing the feature) then Think we should remove it.
Let me know if you change your mind.
