### ISSUE TITLE
No dividers in Savings Account Transaction RecyclerView

### ISSUE THREAD

**Issue by rutvik-panchal** [openMF/self-service-app#1434]
**Summary:**

There are no dividers in transaction recycler view 

**Steps to reproduce:**

Accounts -> Savings -> Transactions

**Expected behaviour:**

There should be dividers between the transactions.

**Observed behaviour:**

There are no dividers between the transactions.

**Device and Android version:**

Vivo V17
FunTouch OS_9.2

**Screenshots:**

I am attaching a collage of both the current and proposed views for it.

![CollageMaker_20200318_172729703](https://user-images.githubusercontent.com/39809059/76958703-38cbf180-693e-11ea-90b6-003c702f35de.jpg)

**Comment by rutvik-panchal** [comment]
I am working on it.

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi, now the UI is totally revamped, I think this issue can be closed. 

<img width="359" alt="Screenshot 2023-03-23 at 00 45 01" src="https://user-images.githubusercontent.com/59947871/227012783-0bcd8845-1580-43e6-b2da-91cc0e65a498.png">
