### ISSUE TITLE
Improper color of Application components

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1437]
**Summary:**

Certain components of the application make use of the default color `accent` provided by the Android Studio. This affects the uniformity of the application color-scheme.

**Steps to reproduce:**

* Go to Apply for loan and click on data picker. Observe the color of the date picker.
![WhatsApp Image 2020-03-21 at 10 44 51 PM(2)](https://user-images.githubusercontent.com/46667021/77232236-cf5e1400-6bc5-11ea-974b-aad4064bc86e.jpeg)

* Go to Accounts - observe the floating action bar color
![WhatsApp Image 2020-03-21 at 10 48 04 PM(1)](https://user-images.githubusercontent.com/46667021/77232292-21069e80-6bc6-11ea-9c48-08e12fd9cd64.jpeg)

* Observe the color of OK button on the snackbar
![WhatsApp Image 2020-03-21 at 10 48 04 PM](https://user-images.githubusercontent.com/46667021/77232294-2237cb80-6bc6-11ea-8fc1-ba5afabadc51.jpeg)

**Expected behaviour:**

All the above-mentioned components should have their color set as the primary color of the application

**Comment by rutvik-panchal** [comment]
Can I work on this issue?

**Comment by devansh-299** [comment]
> Can I work on this issue?

Yes
