### ISSUE TITLE
Cannot login/register the app

### ISSUE THREAD

**Issue by moegreenfs** [openMF/self-service-app#1448]
**Summary:**

I have try to login/register in android studio emulator and i also downloaded the app in Google Play to do the same thing but failed

**Steps to reproduce:**

-

**Expected behaviour:**

To enter the app by login or register

**Observed behaviour:**

Nothing. Cannot enter by both method

**Device and Android version:**

PIXEL 3 XL Api 22

**Screenshots:**

![WhatsApp Image 2020-03-26 at 6 23 51 PM](https://user-images.githubusercontent.com/62697003/77636407-04d07c00-6f8f-11ea-97c6-2cbd70684638.jpeg)

![WhatsApp Image 2020-03-26 at 6 23 51 PM (1)](https://user-images.githubusercontent.com/62697003/77636414-0732d600-6f8f-11ea-9f08-866da5c1a42d.jpeg)

                                                     The white toast appear without text

![WhatsApp Image 2020-03-26 at 6 23 51 PM (2)](https://user-images.githubusercontent.com/62697003/77636411-069a3f80-6f8f-11ea-8d32-a44cb19b68a2.jpeg)

                                                                Error when registering

Did in phone. Any kind of help or solution is very appreciated. Thank you in advance

**Comment by moegreenfs** [comment]
@devansh-299 please help me sir to look in this problem

**Comment by devansh-299** [comment]
Hi @moegreenfs you will need to change your API_ENDPOINT to any of these:
* staging.mifos.io
* mobile.mifos.io
* demo.mifos.io
and then you can log in with 299devansh/password credentials

API_ENDPOINT specification can be found at `/app/src/debug/java/org/mifos/mobile/api/BaseURL.java`

**Comment by moegreenfs** [comment]
@devansh-299 for register sir how can i make my own account?

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 for register sir how can i make my own account?

@moegreenfs you can check out this [wiki-page](https://github.com/devansh-299/mifos-mobile/wiki/Create-Self-Service-User)

**Comment by ShivangiSingh17** [comment]
@moegreenfs can you close this issue as the info is already updated in the wiki.

**Comment by rchtgpt** [comment]
Closing this issue as the solution is provided in the wiki-page.
