### ISSUE TITLE
Removing uneccessary files

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1449]
**Summary:**

The source code of the application has unreachable code that can be deleted safely without affecting the current state of the application. These files are:

**Account Overview Related Code**
The purpose served by the Account Overview Fragment has already been achieved by the Home Fragment. Hence we can delete the below files:
*  `mifos-mobile/app/src/main/java/org/mifos/mobile/ui/activities/AccountOverviewActivity.java`
* `mifos-mobile/app/src/main/java/org/mifos/mobile/ui/fragments/AccountOverviewFragment.java`
* `/home/devansh299/projects/android_dev/mifos-mobile/app/src/main/res/layout/fragment_account_overview.xml`

**New  Home Fragment Design**
The below specified Home Fragment and its layout file are currently not being used and hence can be safely deleted 
*  `/mifos-mobile/app/src/main/java/org/mifos/mobile/ui/fragments/HomeFragment.java`
* `/mifos-mobile/app/src/main/res/layout/fragment_home_ui.xml`
 

**Expected behaviour:**

The unreachable code and layout files should be deleted so as to reduce the application size without affecting the current state of the application

**Comment by IShahnawazShaikh** [comment]
I am working on this. @devansh-299

**Comment by devansh-299** [comment]
> I am working on this. @devansh-299

@imshahnawazdevil since this issue involves deleting the existing code, I think it would be better to ask mentor/maintainer's approval before going ahead

**Comment by IShahnawazShaikh** [comment]
@satyan may I work on this issue ?

**Comment by spacemonkey1101** [comment]
is this issue open? can I be assigned?

**Comment by deecodesss** [comment]
I'll be working up on this issue.
