### ISSUE TITLE
make a document more readable

### ISSUE THREAD

**Issue by areebmomin** [openMF/self-service-app#1466]
**Summary:**

Need to add a word under 'Screenshots' heading to make it readable.
[https://github.com/openMF/mifos-mobile/blob/development/.github/ISSUE_TEMPLATE.md](url)

**Need of change:**
To make this document more readable for new contributors.

**Comment by areebmomin** [comment]
# https://github.com/openMF/mifos-mobile/pull/1464  Pull Rrequest

**Comment by s-ayush2903** [comment]
Issue Title is completely unsemantic and also, explain the need for this change. Just remove the .md mention of PR from here, linking it from PR will work fine

**Comment by s-ayush2903** [comment]
Go through the previously merged PRs and the successfully closed issues for more references

**Comment by s-ayush2903** [comment]
> Just remove the .md mention of PR from here, linking it from PR will work fine

By this I expected you to remove [this comment](https://github.com/openMF/mifos-mobile/issues/1466#issuecomment-626366554) that is in the markdown format as that particular comment is useless when you've linked the issue via a PR.

Still, I'm seeing the Issue title to be unsemantic, change it as well

**Comment by areebmomin** [comment]
Please guide how to write a correct issue title @s-ayush2903

**Comment by s-ayush2903** [comment]
Follow [this comment](https://github.com/openMF/mifos-mobile/issues/1466#issuecomment-626367516)
