### ISSUE TITLE
No message on login if internet is not connected

### ISSUE THREAD

**Issue by Rishabhk07** [openMF/self-service-app#147]
**Summary:**

In login activity if we login with no internet access, login dialog shows and returns to login activity, here we can give user a snackBar or toast with "No internet connection" message.

**Steps to reproduce:**

Step1: enter correct username and password 
Step2: give no internet access to your phone
Step3: press Login 
Step4: Login Dialog shows and returns to same activity

**Expected behavior:**

even before attempting to login, it should check for network connectivity and give appropriate message if internet connection is not present

**Observed behavior:**

even if internet connectivity is not present it attempts to login, dialog shows and after some time returns to same activity.

**Device and Android version:**

Android Version 7.1.1 , Stock Android

**Screenshots:**

![screenshot_20170307-170930](https://cloud.githubusercontent.com/assets/8939938/23655368/c475d7fc-035a-11e7-855a-fc59e050f67a.png)

![screenshot_20170307-170940](https://cloud.githubusercontent.com/assets/8939938/23655374/c8d23d04-035a-11e7-9cf8-a3667b345a86.png)

@therajanmaurya I would like to work on this, please assign me this issue

**Comment by therajanmaurya** [comment]
great catch, Go ahead  👍.

**Comment by therajanmaurya** [comment]
@Rishabhk07 I think we do not have Connection Utils. Use this https://gist.github.com/emil2k/5130324

**Comment by Rishabhk07** [comment]
@therajanmaurya cool, will use this and send the PR 👍

**Comment by therajanmaurya** [comment]
Put this Connection Utils class in utils package.

**Comment by Rishabhk07** [comment]
okay, with the same name or with ConnectionUtils name ?

**Comment by shivam21** [comment]
Hi,I would like to work on this issue.please aaign it to me.

**Comment by Rishabhk07** [comment]
@shivam21 Hey, i have fixed this issue and sent the PR but thanks for your interest.
