### ISSUE TITLE
Improper margin given to textview in an activity

### ISSUE THREAD

**Issue by areebmomin** [openMF/self-service-app#1470]
**Summary:**

In 'Apply for loan' activity the margin given to text-view is lacking left margin.

**Steps to reproduce:**

Add a start and left margin so that the text-view can align in the center.

**Expected behaviour:**

The text-view in the activity must be aligned in the center of the screen.

**Device and Android version:**

Device: MI 6A
Android version: oreo 8.1
ROM: Custom ROM  

**Would you like to work on this issue?**
Yes

**Screenshots:**

This version does not contain left margin:
![issue_before](https://user-images.githubusercontent.com/43715712/81845816-f4a43a00-9505-11ea-9540-f402344e890c.png)

After applying left margin:
![issue_after](https://user-images.githubusercontent.com/43715712/81845989-3e8d2000-9506-11ea-9b7b-12ff5b69713d.png)

**Comment by deecodesss** [comment]
I'll be taking up on this issue!

**Comment by oyehanif** [comment]
i am working on this task.
