### ISSUE TITLE
Feat: Add application introduction slider

### ISSUE THREAD

**Issue by devansh-299** [openMF/self-service-app#1473]
**Summary:**

We can add an introduction slider to the application to give basic insights into what the self-service application aims to provide to the users. These slides can also be used to ask for necessary permissions from the users for the functioning of the application

**Comment by Taruns123** [comment]
I would like to work on this but can you give a more clear idea about it . @devansh-299  do you want me to put some activities which will give the user a walkthrough of the application when he opens the application for the very first time?

**Comment by francisguchie** [comment]
@Taruns123  I am excited to see the out come of this please work on it

**Comment by luckyman20** [comment]
Similar issue to #1383.
