### ISSUE TITLE
Create matrix of APIs that are consumed.

### ISSUE THREAD

**Issue by edcable** [openMF/self-service-app#1479]

**Comment by edcable** [comment]
Link to subfeature: https://mifos.productboard.com/feature-board/planning/features/4699424

**Comment by ashwinkey04** [comment]
I would like to work on this @miPlodder

**Comment by ashwinkey04** [comment]
Update: I have created a [Google sheet](https://docs.google.com/spreadsheets/d/1gR84jZzLF-mM0iRw5JyeMAsHMK6RQPK0vyDmNAY9VhE/edit?usp=sharing) with the first set of API calls which I found working as of now.

**Comment by miPlodder** [comment]
@edcable Can you take a look at it and close this issue
