### ISSUE TITLE
Login (Ivalid JSON Body)

### ISSUE THREAD

**Issue by zahoor-saleem** [openMF/self-service-app#1484]
**Summary:**

Unable to login from application and same user login in web successfully.

**Steps to reproduce:**

Create User from web and try to login from application

**Expected behaviour:**

Authorized user should login successfully and navigate to the dashboard screen

**Observed behaviour:**

Empty Toast message is displaying on screen.
Invalid JSON in BODY message received in response and same user successfully login on web.

Request:
 https://mobile.mifos.io/fineract-provider/api/v1/self/authentication?username=mifos_user&password=password

Response Body:
{"timestamp":1590748961499,"status":500,"error":"Internal Server Error","message":"Invalid JSON in BODY (no longer URL param; see FINERACT-726) of POST to /authentication: ","path":"/fineract-provider/api/v1/self/authentication"}

**Device and Android version:**

Emulator : Goolge Pixel 2, Android OS: 8.1.0

**Comment by qamarmukhtar** [comment]
Summary:

Unable to login from application and same user login in web successfully.

me to having same problem

**Comment by francisguchie** [comment]
I get the same challenge at the moment yet i thought this was updated

**Comment by miPlodder** [comment]
@ashwinkey04 Correct me if I'm wrong, this issues is solved as a part of this https://github.com/openMF/mifos-mobile/pull/1516.

Confirm this, so that I can close this issue?

**Comment by ashwinkey04** [comment]
> @ashwinkey04 Correct me if I'm wrong, this issues is solved as a part of this #1516.
> 
> Confirm this, so that I can close this issue?

Yes @miPlodder. I have solved it in #1516
