### ISSUE TITLE
Adding dependency for user image

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1489]
**Summary:**
Adding CircleImage view dependency for better appearance of user image on the profile.

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi, when we already use Shapeable Image View material components to set the shape of our user profile image, I think we can close this issue? 


Attaching a screenshot for reference,
<img width="601" alt="Screenshot 2023-03-23 at 00 05 54" src="https://user-images.githubusercontent.com/59947871/227004509-c67e7b69-3f5e-4f81-90ff-98e44713df10.png">

**Comment by jawidMuhammadi** [comment]
Thank you for confirming this @gururani-abhishek
