### ISSUE TITLE
No warning message when going back in info forms

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1492]
**Summary:**
While filing the form if the user presses back button, no warning message is displayed and the info filled by the user is lost.

**Steps to reproduce**
Fill details to ```Create an account``` and backpress without clicking on Register button.

**Expected behaviour:**
While filing forms, on leaving the page there should be a message displayed.

**Observed behaviour:**
No warning message is shown.

**Device and Android version:**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Comment by akarshmishraa** [comment]
Is there anyone working on this issue? I would like to work on this...

**Comment by ShivangiSingh17** [comment]
@akarshmishraa you can work on this. I am not working on this at the moment.

**Comment by sachin-0102** [comment]
@ShivangiSingh17 Can I work on this issue?

**Comment by ShivangiSingh17** [comment]
@sachin-0102 go ahead!

**Comment by atharva137** [comment]
@ShivangiSingh17  can I work on this issue  ?
