### ISSUE TITLE
Back press to dismiss the soft keyboard

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1499]
**Summary:**
While using the application if the user wants to dismiss the soft keyboard then we need to press the back button and then only the board disappears. Instead, the keyboard should dismiss on tapping anywhere on the back screen.

What did you expect the app to do?
Dismiss the soft keyboard when tapping anywhere on the back screen.

**Device and Android version:**
Vivo 1724
Android 8.1.0
Funtouch OS_4.0

**Comment by Sparsh1212** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by gururani-abhishek** [comment]
I'll be taking this issue, it's been a long time since the last PR. I'll research and fix this.

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi, please have a look : )
