### ISSUE TITLE
Home screen UI redesign

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1500]
**Summary:**
The Home screen of the application can be improved. 
1. The view for services
2. The split of names can be avoided.

**Screenshots:**
![rsz_home](https://user-images.githubusercontent.com/43827236/84671231-be167080-af44-11ea-81a0-f3f3f23e18db.png)

**Comment by kitoalone** [comment]
hi ShivangiSingh17 , how to login now

**Comment by ShivangiSingh17** [comment]
@bountherngpls you can refer wiki for it.

**Comment by kitoalone** [comment]
I can do it

**Comment by deecodesss** [comment]
I'll be taking up on this.
