### ISSUE TITLE
mifos-mobile

### ISSUE THREAD

**Issue by kitoalone** [openMF/self-service-app#1519]
is this app still usable?

**Comment by ShivangiSingh17** [comment]
@bountherngpls yes

**Comment by ShivangiSingh17** [comment]
Also while creating issue please follow the issue template.

**Comment by kitoalone** [comment]
Yes i'm hete

**Comment by kitoalone** [comment]
Thanks for comment @ShivangiSingh17  ,now... i'm can't login and can't create user in mifos-mobile app, can you help me, please...😓

**Comment by kitoalone** [comment]
done
