### ISSUE TITLE
FAB for adding Savings or loan account disappears 

### ISSUE THREAD

**Issue by ashwinkey04** [openMF/self-service-app#1530]
**Summary:**

- FAB for adding Savings or loan account disappears 

**Steps to reproduce:**

- Open Accounts. Switch to Loan tab and then Share tab
- Come back to Loan tab/ Saving tab. The FAB will not appear again

**Expected behaviour:**

- FAB must re-appear on coming back to Loan/Saving tab

**Observed behaviour:**

FAB disappears instead of re-appearing

**Device and Android version:**

Lenovo Vibe K5 - Viper OS 8.1.0

**Screenshots:**

<img src="https://raw.githubusercontent.com/ashwinkey04/mygitbin/master/assets/mifos-fab-issue.gif" width=450>

**Comment by Him887** [comment]
Can I work on this issue??

**Comment by ashwinkey04** [comment]
@Him887 I have solved this already on the PR mentioned above
