### ISSUE TITLE
NO "Rate The App" dialog appears while using the app

### ISSUE THREAD

**Issue by Him887** [openMF/self-service-app#1536]
**Summary:**

No pop up box appears to ask the user to rate the app

**How can we reproduce the issue?**

Start using the app. You will find that there is no way user bother to rate the app

**Expected behaviour:**

There should be a Pop-up dialog to ask user to rate the app.

**Device and Android version:**
Vivo V15
Android 9
Funtouch OS

**Comment by Him887** [comment]
I am working on this issue.

**Comment by Jaikishan-Saroj** [comment]
can I work on this issue? @Him887

**Comment by ShivangiSingh17** [comment]
@Jaikishan-Saroj the PR linked above solves the issue mentioned.
