### ISSUE TITLE
Adding statement feature in Recent Transactions

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#154]
As we already having Recent transactions ,We can send statement of transactions to customer email if he wants ...because i observed this feature in some banking apps....
@therajanmaurya can you please suggest me that whether this feature is addable ,if yes i would love to work on this feature.......

**Comment by therajanmaurya** [comment]
@prashanthkomuravelli Right now we do not have any API for generating the statement of the transactions.

**Comment by therajanmaurya** [comment]
Closing for now.
