### ISSUE TITLE
App Info

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#1542]
**Summary:**
Adding a separate section for App info in the application.

**Behaviour:**
Right now there is no such section. Adding this will provide workflow on the application.

**Comment by Jaikishan-Saroj** [comment]
Can i Work on it ? @ShivangiSingh17

**Comment by ShivangiSingh17** [comment]
@Jaikishan-Saroj I am already working on it.

**Comment by garvit984** [comment]
@ShivangiSingh17 Are you still working on it?

**Comment by gururani-abhishek** [comment]
It seems no one's working on this issue, I'm taking it up.
