### ISSUE TITLE
Feature Withdraw Pending Loan Application

### ISSUE THREAD

**Issue by rahulbabbar1** [openMF/self-service-app#155]
**Summary:**

Withdraw Pending Loan Application
Add the option to withdraw any pending loan option from the tool-bar menu.

Using the following API:
https://demo.openmf.org/fineract-provider/api/v1/self/loans/{loanId}?command=withdrawnByApplicant

**Comment by rahulbabbar1** [comment]
@therajanmaurya I would like to implement this.

**Comment by therajanmaurya** [comment]
@rahulbabbar1 I have to talk first about this in community.
I will talk today and let you know.

**Comment by rahulbabbar1** [comment]
@therajanmaurya any update??

**Comment by dilpreet2028** [comment]
Added in #304
