### ISSUE TITLE
The default credentials don't work

### ISSUE THREAD

**Issue by sachin-0102** [openMF/self-service-app#1550]
**Summary:**

If you try to login with the default credentials the app will show that you're not authorised

**Steps to reproduce:**

Just open the login screen and enter then default credentials available in wiki

**Expected behaviour:**

It should login

**Observed behaviour:**

I displays a toast saying "You're not authorised"

**Device and Android version:**

realme 7
android 10

**Screenshots:**

![GIF-200917_195920.gif](https://user-images.githubusercontent.com/61426967/93485287-8b538e00-f920-11ea-8f02-35ee3e4fddf0.gif)

**Comment by ShivangiSingh17** [comment]
@sachin-0102 which server are you using to login?

**Comment by sachin-0102** [comment]
@ShivangiSingh17  I don't think I had a server option anywhere... I am using the app on my personal device

**Comment by sachin-0102** [comment]
And how am I supposed to know and change the server..

**Comment by sachin-0102** [comment]
@ShivangiSingh17 please tell me about this server thing.

**Comment by ShivangiSingh17** [comment]
You can get to know about the server from the file name "BaseURL" in the project code. 
Did you install the app directly from playstore?

**Comment by sachin-0102** [comment]
No. I cloned the repo and ran it through Android Studio @ShivangiSingh17

**Comment by sachin-0102** [comment]
Alright I will look into it and tell if something comes up

**Comment by rutvik-panchal** [comment]
@sachin-0102 @Vani-j01 You can change the ENDPOINT of the API [here](https://github.com/openMF/mifos-mobile/blob/383fc562a25c88cdb16b6dfc2fdc42135b4b54bf/app/src/debug/java/org/mifos/mobile/api/BaseURL.java#L10)

You can go with any of the following instances -
1. https://staging.mifos.io/
2. https://mobile.mifos.io/
3. https://demo.mifos.io/

If possible create a self service user for yourself and login using the credentials of the same, this [link](https://github.com/devansh-299/mifos-mobile/wiki/Create-Self-Service-User#creating-a-client-on-mifosx-platform) can help you.

<hr>

Also i think we can close this issue.

**Comment by Vani-j01** [comment]
@sachin-0102  I am facing a similar issue. Did you figure out how to make it work?

**Comment by rutvik-panchal** [comment]
@Vani-j01 You can change the ENDPOINT of the API [here](https://github.com/openMF/mifos-mobile/blob/383fc562a25c88cdb16b6dfc2fdc42135b4b54bf/app/src/debug/java/org/mifos/mobile/api/BaseURL.java#L10)
You can go with any of the instances

**Comment by rutvik-panchal** [comment]
@sachin-0102 @Vani-j01 You can change the ENDPOINT of the API [here](https://github.com/openMF/mifos-mobile/blob/383fc562a25c88cdb16b6dfc2fdc42135b4b54bf/app/src/debug/java/org/mifos/mobile/api/BaseURL.java#L10)

You can go with any of the following instances -
1. https://staging.mifos.io/
2. https://mobile.mifos.io/
3. https://demo.mifos.io/

If possible create a self service user for yourself and login using the credentials of the same, this [link](https://github.com/devansh-299/mifos-mobile/wiki/Create-Self-Service-User#creating-a-client-on-mifosx-platform) can help you.

<hr>

Also i think we can close this issue.

**Comment by ShivangiSingh17** [comment]
@sachin-0102 close this issue.
