### ISSUE TITLE
Update crashlytics SDK version

### ISSUE THREAD

**Issue by ashwinkey04** [openMF/self-service-app#1553]
**Summary:**

Current crashlytics SDK version is about to be depreceated and needs to be updated 

> This version is deprecated. Details: The Fabric Crashlytics SDK is now deprecated and will continue reporting your app's crashes only until November 15, 2020. To continue getting crash reports in the Firebase console, make sure you upgrade to the Firebase Crashlytics SDK version 17.0.0+.  For more information, visit https://firebase.google.com/docs/crashlytics/upgrade-sdk. Consider switching to recommended version 17.2.2. 

**Steps to reproduce:**

Check version in build.gradle of :app module

**Expected behaviour:**

Upgrade version to 17.x.x

**Observed behaviour:**

Currently in 2.6.7

**Comment by Sparsh1212** [comment]
I am working on this.
