### ISSUE TITLE
Cannot login with given account

### ISSUE THREAD

**Issue by hardik124** [openMF/self-service-app#156]
**Summary:**

Login with credentials (selfservice,Password@123) was working fine until now , now i cannot login

**Steps to reproduce:**

Try to login using the app login page

**Expected behavior:**

To login and open HomeActivity

**Observed behavior:**

ReOpens the login page

**Device and Android version:**
6.0 , custom rom

**Comment by dilpreet2028** [comment]
I am also experiencing the same ,every endpoint is returning 404 there might be some server issues

**Comment by shivam21** [comment]
it started working now.

**Comment by therajanmaurya** [comment]
Yes, Because of down server.

Closeing this
