### ISSUE TITLE
App crashes on no internet

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/self-service-app#1566]
**Summary:**
If app is started by user without internet connection and clicked on login or register it should show toast as "Please check your internet connection" instead app crashes.

**Steps to reproduce:**

Turn off Internet/Wifi
Open app
Click on Login or fill all details in register section and click on register

**Expected behaviour:**

If app is started without internet connection and login or register is clicked it should show toast message

**Observed behaviour:**
App crashes when clicked login or register button without internet

**Device and Android version:**

Lenovo Tab 7
Android 7.0(Nougat)
Stock ROM

**Screenshots:**

**Comment by PatelVatsalB21** [comment]
Hii i am new to mifos, can i work on this issue

**Comment by rutvik-panchal** [comment]
@PatelVatsalB21 I have also encountered same issue even after login, the app crashes on no internet. 
So can we have a generic title to the issue like `App crashes on no internet.`

**Comment by PatelVatsalB21** [comment]
@rutvik-panchal it sounds good. Thank you :)
