### ISSUE TITLE
Add CI/CD GitHub Actions and remove other build checks

### ISSUE THREAD

**Issue by garvit984** [openMF/self-service-app#1568]
**Summary:**

The project currently has Travis. We need to remove this and use Github actions.
Following are the requirements:-

Generate the apk for every merged pull request and every commit on the redesign and master branch.
Build checks for every commit on any other branch.

**Comment by rutvik-panchal** [comment]
Can I work on this issue?

**Comment by Sparsh1212** [comment]
I am willing to contribute to this. Please assign this to me.

**Comment by garvit984** [comment]
@rutvik-panchal Are you still working on it?

**Comment by rutvik-panchal** [comment]
@garvit984 Yes
