### ISSUE TITLE
Dates in transaction filter

### ISSUE THREAD

**Issue by kienme** [openMF/self-service-app#157]
**Summary:**

Clicking on the filter button in transactions without setting start and end dates shows an empty result. 

**Steps to reproduce:**

Click on any item in the savings tab in home screen and select 'transactions' from the overflow menu. Tap on the filter button without setting start or end dates.

**Expected behavior:**

The expected behaviour is for the app to prompt the user to select the dates. This has been wrongly implemented in the code.

**Observed behavior:**

An empty result is returned by the filter.

**Device and Android version:**

Redmi Note 3 ; Android 6.0 Marshmallow 

**Screenshots:**

![gif_20170310_000109](https://cloud.githubusercontent.com/assets/8699390/23764817/c43ee10a-04f6-11e7-9f11-93f146ee072d.gif)

**Comment by kienme** [comment]
I can work on this. Can I fix it and send a PR?

**Comment by therajanmaurya** [comment]
Yeah Go ahead 👍

**Comment by therajanmaurya** [comment]
Yeah Go ahead 👍

**Comment by therajanmaurya** [comment]
@kienme Remove the `None` Radio button.
![image](https://cloud.githubusercontent.com/assets/5724482/23788201/7e659746-059b-11e7-85ff-6eb134d78923.png)

And add a simple button for showing all, like above

**Comment by kienme** [comment]
@therajanmaurya am I right in understanding that I should 

1) remove the 'None' radio button and 
2) add a button that resets the filter and shows all results when clicked 

Please clarify.

**Comment by therajanmaurya** [comment]
Yes

**Comment by therajanmaurya** [comment]
fixed in #165
