### ISSUE TITLE
App crashes on pressing back button on review loan page 

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/self-service-app#1573]
**Summary:**
On Review loan page if back button from toolbar or back button is pressed app crashes. Problem is with Purpose of Loan spinner

**Expected behaviour:**
It should load all selected and entered values on Submit loan page

**Device and Android version:**
Lenovo Tab7 
Android 7.0
Stock ROM

![Screenshot_20201126-235513](https://user-images.githubusercontent.com/70195106/100383299-4c8a3480-3043-11eb-8cee-0d81eceb9cfc.jpeg)
![Screenshot_20201126-235526](https://user-images.githubusercontent.com/70195106/100383311-52801580-3043-11eb-8481-36d6fde0874d.jpeg)

**Comment by PatelVatsalB21** [comment]
can i work on this issue?

**Comment by luckyman20** [comment]
Unable to reproduce this issue.
