### ISSUE TITLE
After changing language, format of language doesn't change instantly.

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/self-service-app#1575]
**Summary:**
When language is changed back from arabic type to english or hindi format remains right aligned in settings page, instead of being left aligned

**Steps to reproduce:**
Go to settings and change and change language to arabic type, i selected 4th option then againg change language back to english

**Expected behaviour:**

After changing back to english layout should return to left align

**Observed behaviour:**

English Language text was right align

**Device and Android version:**
Lenovo Tab7
Android 7

**Screenshots:**

![Screenshot_20201127-213205](https://user-images.githubusercontent.com/70195106/100467455-75b8cc80-30f8-11eb-8fa2-fcc6070d4e26.jpeg)
![Screenshot_20201127-213213](https://user-images.githubusercontent.com/70195106/100467439-718caf00-30f8-11eb-82b1-7d69582f43f5.jpeg)
![Screenshot_20201127-213225](https://user-images.githubusercontent.com/70195106/100467446-73ef0900-30f8-11eb-92df-d42a5995c870.jpeg)

**Comment by ReCodee** [comment]
@PatelVatsalB21 I guess screen recording would give a better explanation here :)

**Comment by PatelVatsalB21** [comment]
Sure
![GIF-201127_220857](https://user-images.githubusercontent.com/70195106/100470166-bf57e600-30fd-11eb-8677-33d9e79ffe16.gif)

**Comment by rutvik-panchal** [comment]
Can I work on this issue?

**Comment by PatelVatsalB21** [comment]
i am not working on it
