### ISSUE TITLE
Refactor README file

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#1576]
- Fix Batches in README file

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.
![image](https://user-images.githubusercontent.com/22195621/100521929-fe08a180-31cc-11eb-85a8-3ca254f5e305.png)

- Move below text to new Heading (under `Instruction to get the latest APK`)in README file

![image](https://user-images.githubusercontent.com/22195621/100521946-3314f400-31cd-11eb-84ba-9690d298254f.png)

**Comment by miPlodder** [comment]
It's a minor issue, anyone can pick it up and raise a PR

**Comment by rutvik-panchal** [comment]
I will do it!
