### ISSUE TITLE
Feature Profile Section

### ISSUE THREAD

**Issue by rahulbabbar1** [openMF/self-service-app#158]
**Summary:**

Add a profile section for the users, where the user can see or set his profile pic, DOB, mobile no., email id , etc.

**Comment by rahulbabbar1** [comment]
@therajanmaurya can I work on this??

**Comment by hardik124** [comment]
@therajanmaurya I will send the pull request today. Sorry for delay.

**Comment by rahulbabbar1** [comment]
Sorry, didn't know that a similar issue exist.
