### ISSUE TITLE
Wrong Date format in Charges Section

### ISSUE THREAD

**Issue by shubhamji88** [openMF/self-service-app#1604]
**Summary:**

Wrong Date format in Charges Section , if the title is long enough..

**Steps to reproduce:**

Go to Charges and see the Date

**Expected behaviour:**

Date below the title would be better . 

**Observed behaviour:**

The Date is currently in front of the title and if the title is long the format of date not correctly displayed.

**Device and Android version:**

Samsung Galaxy A50
Model number - SM-A505F
Android Version - 10

**Screenshots:**
![WhatsApp Image 2020-12-02 at 7 23 26 PM](https://user-images.githubusercontent.com/56815364/100882532-51346a00-34d5-11eb-88ed-002c8ae4e0b2.jpeg)

and i am working on it.

**Comment by ReCodee** [comment]
@shubhamji88, #1571 already addresses this issue.

**Comment by shubhamji88** [comment]
oh.. .thanks..
