### ISSUE TITLE
Change hyperlink of Github Actions in readme

### ISSUE THREAD

**Issue by Sparsh1212** [openMF/self-service-app#1615]
**Summary:**
On following the current  Github [Actions](https://github.com/openMF/mifos-mobile/actions) hyperlink in the readme, the user is navigated to the apk generated for the latest triggered workflow (that can be of any pull request which isn't merged in the development branch). 
The main idea of building APKs and saving them as artifacts was to allow people to test out the latest stable build, so it will be better if the **Actions** is linked to the merged changes. 
 like it is the case with [Actions](https://github.com/openMF/mobile-wallet/actions?query=workflow%3A"Mobile-Wallet+CI%5BMaster%2FDev%5D"+event%3Apush) of [mobile-wallet](https://github.com/openMF/mobile-wallet)

**Comment by yashraj-01** [comment]
I would like to work on this issue.
