### ISSUE TITLE
Account Number Keyboard error

### ISSUE THREAD

**Issue by ritish099** [openMF/self-service-app#1616]
**Summary:**

When in Create account activity. Account Number EditText allow us to type only "Numbers" when in Add Beneficiary Activity then EditText Account Number it allows us to type number, letters and characters.

**Steps to reproduce:**

Open Create Account activity and Add beneficiary activity

**Expected behaviour:**

Input behaviour of Both of them should be same.

**Observed behaviour:**
Input behaviour of Both of them are different.

**Device and Android version:**

Samsung J6, Android 10

**Screenshots:**

<img src="https://user-images.githubusercontent.com/54978105/101653544-6d9c4d80-3a65-11eb-8ff6-ae6fea1be226.jpg" width="333">

<img src="https://user-images.githubusercontent.com/54978105/101653563-73922e80-3a65-11eb-9580-56769aea7629.jpg" width="333">

**Comment by ritish099** [comment]
Kindly review this. Is this a good and valid issue? @miPlodder @danishjamal104 @robustTechie

**Comment by ForgottenProgramme** [comment]
Hey, @ritish099 ! 
I think it's a very good catch! 
There should be consistency in the type of keyboard that opens up for 'Account Number', based on whether the account number can have only digits or both digits and alphabets.

**Comment by ritish099** [comment]
@ForgottenProgramme Inside the app. All account numbers are containing both digits and alphabets. So I think that every keyboard which pops up for entering "Account Number" should have both digits and alphabets

**Comment by ritish099** [comment]
I checked now that someone has already solved the issue. The issue no longer exists. Closing the issue.
