### ISSUE TITLE
Feature: Turn on the flashlight while scanning QR

### ISSUE THREAD

**Issue by ritish099** [openMF/self-service-app#1620]
**Summary:**

It would be nice if flashlight turn on while scanning QR

**Steps to reproduce:**

Beneficiary->Add Beneficiary->Scan QR

**Expected behaviour:**

Flashlight not Turned on.

**Observed behaviour:**

FlashLight turn on

**Device and Android version:**

Samsung J6, Android 10

**Screenshots:**

<img src="https://user-images.githubusercontent.com/54978105/101927754-d2d57780-3bfa-11eb-9a9c-502ab7fdd6b2.jpg" width="333">

**Comment by ritish099** [comment]
Can i work on it @miPlodder

**Comment by rutvik-panchal** [comment]
@ritish099 Issue already exists #1381

**Comment by ritish099** [comment]
@rutvik-panchal Closing the issue
