### ISSUE TITLE
Redesign Home UI as per new design

### ISSUE THREAD

**Issue by yashraj-01** [openMF/self-service-app#1625]
Current UI:
<img src="https://user-images.githubusercontent.com/63469151/102207172-acae2100-3ef3-11eb-9967-5e16cabe3be7.png" width="270" height="436">

Proposed UI:
![Screenshot from 2020-12-15 16-28-16](https://user-images.githubusercontent.com/63469151/102207196-b768b600-3ef3-11eb-94c5-a2d7dbee08cd.png)

**Comment by yashraj-01** [comment]
I am working on this issue.

**Comment by deecodesss** [comment]
If no one's working on this, I'll be working on this!
