### ISSUE TITLE
In Register Activity. Validator code missing for Phone Number Field

### ISSUE THREAD

**Issue by ritish099** [openMF/self-service-app#1661]
**Summary:**

In Register Activity. Validator code missing for Phone Number Field

**Steps to reproduce:**

Go to Register Activity and try to register without entering phone number

**Expected behaviour:**

Warning should be displayed as shown for other fields

**Observed behaviour:**

No warning

**Device and Android version:**

Any

**Screenshots:**

<img src="https://user-images.githubusercontent.com/54978105/103270400-d419e900-49dd-11eb-8c0e-7f94b0698b9c.jpg" width="333">

**Comment by deecodesss** [comment]
Can I work on this issue?

**Comment by gururani-abhishek** [comment]
Hey @luckyman20, Issue has already been resolved in this pr([#1904](https://github.com/openMF/mifos-mobile/pull/1904)) Please close this issue :)
