### ISSUE TITLE
Filter error in Account Fragment

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/self-service-app#1665]
**Summary:**
When user opens Accounts tab and use filter for savings account then error layout does not disappear when filter options are changed. Also if  filters are used in loan accounts, they don't work at all. Also in both if no checkbox is checked then error layout is visible.

https://user-images.githubusercontent.com/70195106/103333078-99be5380-4a92-11eb-9b8a-5b3528703892.mp4

https://user-images.githubusercontent.com/70195106/103333185-fc175400-4a92-11eb-8b29-67c3730588c4.mp4

**Steps to reproduce:**
1 Open Accounts Tab from Home
2 Apply filters for Savings and Loan Accounts

**Expected behaviour:**
Error layout should be updated in savings account filters and List of loan accounts should be updated when filters are applied.

**Device and Android version:**
Lenovo Tab 7
Android 7

**Comment by kmanikanta335** [comment]
@PratyushSingh07 can i work on this issue ?
and Will Mifos-Mobile participate in gsoc 2024 ?

**Comment by PratyushSingh07** [comment]
Yes you can work on this @kmanikanta335
