### ISSUE TITLE
Amount column in LOAN fragment must not be in exponential form

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1678]
**Summary:**
Amount column in LOAN fragment must not be in exponential form for bigger amount

**Steps to reproduce:**
1. Open Apply for Loan fragment
2. Select a product whose initial principal amount is large, for eg. 'Tranche Loan Product'
3. Observe

**Expected behaviour:**
Principal Amount must be shown in numeric format

**Observed behaviour:**
Principal Amount is shown in exponential format

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

![WhatsApp Image 2021-01-07 at 12 09 48 AM](https://user-images.githubusercontent.com/50913976/103807915-2661a680-507d-11eb-8fa4-d2bfbe949692.jpeg)

![WhatsApp Image 2021-01-07 at 12 16 23 PM](https://user-images.githubusercontent.com/50913976/103860778-3b245580-50e2-11eb-9f82-fb0b08efd10b.jpeg)

**Comment by SekhGulamMainuddin** [comment]
Hi, @PratyushSingh07 I want to work on this issue. Please can you assign me this?

**Comment by SekhGulamMainuddin** [comment]
@therajanmaurya @PratyushSingh07 please can you assign me this issue? I want to work on this.

**Comment by PratyushSingh07** [comment]
go ahead @SekhGulamMainuddin
