### ISSUE TITLE
Unnecessary visibility of Contact Us in Saving Account Transactions

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/self-service-app#1689]
**Summary:**
As visible in image attached "Contact Us" layout is visible in transactions. It is available in SavingsAccountDetails section so it is redundant to have it here.

**Steps to reproduce:**
1 Open Savings Account Details
2 Open Transactions

**Expected behaviour:**
Contact Us should not be visible in Transactions

**Device and Android version:**
Lenovo Tab 7
Android 7

**Screenshots:**
<img width="333" alt="ss" src="https://user-images.githubusercontent.com/70195106/104349429-eb51ee00-5528-11eb-98ef-c1e889d1784b.jpeg">

**Comment by divyank00** [comment]
This doesnt seem to be a real issue

**Comment by PatelVatsalB21** [comment]
@divyank00 as you are developer you might know that importance of UI is far greater than clean code alone. And if you have used some app like Amazon you would have noticed that they don't show customer care number everywhere. Same was the case here. So this might not be an error but a bug that needs to be fixed today or tomorrow. Hope you got it. Thank you 😊

**Comment by divyank00** [comment]
> @divyank00 as you are developer you might know that importance of UI is far greater than clean code alone. And if you have used some app like Amazon you would have noticed that they don't show customer care number everywhere. Same was the case here. So this might not be an error but a bug that needs to be fixed today or tomorrow. Hope you got it. Thank you 😊

I guess this page wants to say that if you have any issue with the transactions, you can contact us

For Eg.

![Screenshot_20210115-201130__01.jpg](https://user-images.githubusercontent.com/50913976/104740612-27c25b80-576e-11eb-9b08-e5f1bc677550.jpg)

**Comment by PatelVatsalB21** [comment]
@divyank00 I got your point. But if you noticed it was page of transaction detail. Not whole list of transactions. And this issue was only for transaction list. That's why I didn't pointed at CONTACT US which is also placed on Saving Account details page, as it is fine there. Hope you got it.

**Comment by divyank00** [comment]
> @divyank00 I got your point. But if you noticed it was page of transaction detail. Not whole list of transactions. And this issue was only for transaction list. That's why I didn't points at CONTACT US which is also placed on Saving Account details page, as it is fine there. Hope you got it. 

Yeah, np😀

**Comment by miPlodder** [comment]
Redesigning of UI will should take care of it.
