### ISSUE TITLE
Refractor ChargeAppWidget 

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#170]
**Summary:**

Problem cases with wigdet :
case 1 :- When we try to add a widget on home screen without logging in the widget shows no prompt that  user needs to login first.
case 2 :- If ClientChargesFragment is not loaded then also widget shows nothing as no data is stored in the database which could be retireved by the WidgetDataProvider 
case 3:- No broadcast sent after the data is updated in DatabaseHelper due to which wigdet will not be having updated data

**Comment by dilpreet96** [comment]
@therajanmaurya I would like to work on this

**Comment by dilpreet2028** [comment]
@therajanmaurya Shall i Fix this
