### ISSUE TITLE
Missing Country Code Picker with backend functionality in Register Activity

### ISSUE THREAD

**Issue by ritish099** [openMF/self-service-app#1705]
**Summary:**

Missing Country Code Picker with backend functionality in Register Activity

**Steps to reproduce:**

Open create new account activity

**Expected behaviour:**

Phone number field should have a country code picker.

**Observed behaviour:**

Phone number field donot have a country code picker.

**Device and Android version:**

Any

**Screenshots:**

<img src="https://user-images.githubusercontent.com/54978105/106379076-8bd05b00-63cf-11eb-9ba2-4821813b0385.jpg" width="333">

**Comment by Edward1919** [comment]
I want to solve this issue

**Comment by ritish099** [comment]
@Edward1919 already PR is there...
