### ISSUE TITLE
Unable to create or update Beneficiary

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/self-service-app#1717]
**Summary:**
As user creates new beneficiary after entering all details, it shows same error, failing to create beneficiary. Same issue happens when user tries to update beneficiary

**Steps to reproduce:**
1 Go to Beneficiary Section
2 Create New Beneficiary

**Expected behaviour:**
Beneficiary should be created successfully

**Device and Android version:**
Any

**Create Beneficiary:**
https://user-images.githubusercontent.com/70195106/107857316-ccaa8400-6e53-11eb-9f0b-d0103d2faa4a.mp4

**Update Beneficiary:**
https://user-images.githubusercontent.com/70195106/107857310-c0bec200-6e53-11eb-9ff1-6e6126d9f9c2.mp4

**Comment by jawidMuhammadi** [comment]
The issue should be handled in the backend, so closing linked PRs in order to clean up the project
