### ISSUE TITLE
Notification icon disappears in Persian language

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1738]
**Summary:**
Notification icon disappears in Persian language

**Steps to reproduce:**
1. Open settings
2. Click on Language
3. Select the last language
4. Press the back button

**Expected behaviour:**
Notification icon on the left side of the toolbar

**Observed behaviour:**
The notification icon disappears but still, it is clickable

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

https://user-images.githubusercontent.com/50913976/108665780-be1b3700-74fb-11eb-926c-01108b9a0b92.mp4

**Comment by SekhGulamMainuddin** [comment]
Hi @PratyushSingh07 please can you assign me this issue?

**Comment by PratyushSingh07** [comment]
@SekhGulamMainuddin whats the point of asking when you have already opened the PR before being assigned the issue ?

**Comment by SekhGulamMainuddin** [comment]
> @SekhGulamMainuddin whats the point of asking when you have already opened the PR before being assigned the issue ?

Sorry for it. I'll ask it first, and after being assigned, I'll then add the pull request.
