### ISSUE TITLE
Layout issue in settings page after selecting Persian language and then choosing English

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1739]
**Summary:**
Layout issue in settings page after selecting Persian language and then choosing English

**Steps to reproduce:**
1. Open settings
2. Click on the language
3. Choose the last language
4. Then again change the language to english
5. Observe

**Expected behaviour:**
The final language should be English with a left to right structure

**Observed behaviour:**
The final language is English but with a right to left structure

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

https://user-images.githubusercontent.com/50913976/108665970-210cce00-74fc-11eb-8434-8a005c6f4594.mp4

**Comment by PatelVatsalB21** [comment]
@divyank00 this issue was already raised in #1575 please confirm before making new issue. Also please reference that issue #1740

**Comment by divyank00** [comment]
> @divyank00 this issue was already raised in #1575 please confirm before making new issue. Also please reference that issue #1740  

Oopss my bad. I will link the pr. Thanks
