### ISSUE TITLE
Help page FAQs state is forgotten on screen orientation

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1742]
**Summary:**
Help page FAQs state is forgotten on screen orientation

**Steps to reproduce:**
1. Open Help Section
2. Open any of the given FAQ
3. Rotate the screen
4. Try opening another FAQ
5. Observe

**Expected behaviour:**
The previous FAQ should close and the new one should open

**Observed behaviour:**
The previous FAQ is not closed and the new one opens

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

https://user-images.githubusercontent.com/50913976/108683628-def18580-7517-11eb-966c-a0ef388f2576.mp4

**Comment by avivijay19** [comment]
I like to work on this issue...

**Comment by PatelVatsalB21** [comment]
@avinash14022002 are you still working on it?

**Comment by avivijay19** [comment]
Yes @PatelVatsalB21,
I like to work and was working on it

**Comment by divyank00** [comment]
I am not sure whether this needs to be solved because @miPlodder said orientation changes are out of the scope

**Comment by PatelVatsalB21** [comment]
You made error so I solved it, if it is out of scope please dodge those errors. I will take care of it ahead. Thanks

**Comment by SekhGulamMainuddin** [comment]
Hi, @PratyushSingh07 I have solved this issue. Please can you assign me?

**Comment by PratyushSingh07** [comment]
This issue seems dormant. You can go ahead with it
