### ISSUE TITLE
Search Bar not occupying whole screen space

### ISSUE THREAD

**Issue by divyank00** [openMF/self-service-app#1743]
**Summary:**
Search Bar not occupying whole screen space and the edit text is closed when cross is clicked if edit text is empty

**Steps to reproduce:**
1. Open Help section
2. Click on search
3. Type something
4. Click on back button 
5. Observe

**Expected behaviour:**
1. Search bar should take the full width
2. Search bar should disappear on the first press of the back button and on second press, the fragment should close

**Observed behaviour:**
1. Search bar takes half width
2. Search bar disappears when clicked on cancel icon if the edit text is empty

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

https://user-images.githubusercontent.com/50913976/108688185-a2288d00-751d-11eb-93cd-45ee7980c2ba.mp4

**Comment by deecodesss** [comment]
Can I work on this issue?
