### ISSUE TITLE
Feature: Adding transaction details dialog in Saving Account Details

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/self-service-app#1752]
**Summary:**
As user opens Transactions list it is visble that there is list of transactions which have account balance, type of payment and other details conjusted. For better understanding of user and to get clear record there should be transaction details page for specific transaction.

**Steps to reproduce:**
1 Open Saving Account
2 Open Transaction Details
 
**Expected behaviour:**
There should be special view for transaction details of specific transaction.

**Device and Android version:**
Any

**Screenshots:**

<img width="333" src="https://user-images.githubusercontent.com/70195106/109422740-e8408d80-7a02-11eb-9cab-0ad03d22fc86.jpeg"/>

**Comment by Abhinavtdk** [comment]
@PatelVatsalB21 Hey, can u give the demo credentials you used because with the ones given in wiki, I'm not able to login
