### ISSUE TITLE
Fab behaviour rectification in Accounts

### ISSUE THREAD

**Issue by PatelVatsalB21** [openMF/self-service-app#1759]
**Summary:** 
As attached in video below when user scrolls down fab hides but does not show up itself. Also special file is made for it. It can be done with handful of code

**Steps to reproduce:** 
1 Open Accounts
2 Scroll List

**Expected behaviour:** 
Fab should show itself

**Device and Android version:** 
Any

**Screenshots:** 

https://user-images.githubusercontent.com/70195106/110131778-87dd9180-7df0-11eb-8c47-cad4863fc46b.mp4

**Comment by oyehanif** [comment]
can i work in on this task

**Comment by francisguchie** [comment]
@oyehanif  I think you can unless @PatelVatsalB21  wants to work on it as well
