### ISSUE TITLE
Apply for Loan Screen can be opened, even if Internet is not connected.

### ISSUE THREAD

**Issue by doomers** [openMF/self-service-app#176]
**Summary:**

we can open apply for loan screen in app if we are not connected to internet. 

![ss_laon](https://cloud.githubusercontent.com/assets/11586392/23829621/cc18a9d8-071c-11e7-8473-a532164cc189.gif)

**Steps to reproduce:**

in ClientAccountsFragment check on OnOptionsItemSelected that internet is connected or not using Network in Utils and snackbar using Toaster which is also in Utils.

**Expected behavior:**

if internet is not connected instead of opening ApplyforLoan Screen ,we should display a SnackBar with "Connect to internet" message.

**Observed behavior:**

If internet is not connected, we can still open Apply For Loan Screen, which doesn't make sense, because we cannot fetch  Loan Product and Loan Purpose types offline, so instead of it, asnackbar should be displayed with "Connect to Internet " message
**Device and Android version:**

MOTOROLA MOTO G4, Android 7.0 

**Screenshots:**

**Comment by ghost** [comment]
I would like to work on this issue

**Comment by doomers** [comment]
I have already done that @prashanthkomuravelli i am just waiting for @therajanmaurya to review the issue ,will send the PR after he approves.

**Comment by ghost** [comment]
@doomers i'm sorry, i thought u just raised issue

**Comment by doomers** [comment]
@prashanthkomuravelli  NO Problem

**Comment by doomers** [comment]
@therajanmaurya i would like to fix this,

**Comment by dilpreet2028** [comment]
Fixed in #300
