### ISSUE TITLE
what are the login credentials 

### ISSUE THREAD

**Issue by vinayak0505** [openMF/self-service-app#1765]
i have tried login by using this
its not working can anyone help
it says you are not authorize
#Demo Credentials

Username: mifos
Password: password

**Comment by anamansari062** [comment]
@vinayak0505 
Username: selfservice
Password: password

**Comment by PHCANALYST** [comment]
User Name and password is not working tried with Username: mifos /Password: password and Username: selfservice Password: password.

Can someone help

**Comment by oyehanif** [comment]
I try both but it's not working also not i am not getting error.

**Comment by gururani-abhishek** [comment]
@vinayak0505 there seems some licensing issues which were fixed here #1936. Now these credentials will work fine(Username : mifos, Password : password)

**Comment by ShashidharM0118** [comment]
The login credentials are still not working.

**Comment by automaticqa** [comment]
Hi guys!
It seems it doesn't work again.
Neither
Username : mifos, Password : password

Neither 
Username : selfservice, Password : password
