### ISSUE TITLE
Double click on back Button when user wants to close App

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#177]
when user double tap on back button on home screen the app will be closed.
@therajanmaurya i would like to work on this issue

**Comment by ghost** [comment]
@therajanmaurya i would like to implement this...

**Comment by ghost** [comment]
@therajanmaurya sir, as there is new HomeScreen is present now, and the PR that i sent also not merged , so can i implement this feature on new HomeScreen and send PR..

**Comment by therajanmaurya** [comment]
fix in #291
