### ISSUE TITLE
Gradle build failure error

### ISSUE THREAD

**Issue by ayushi790** [openMF/self-service-app#1781]
**Summary:**

Gradle build fail with the error : "package javax.annotation.processing does not exist"

**Steps to reproduce:**

1. Clone the repository.
2.  Open the project in android studio
3. Build the project by clicking at run button

**Expected behaviour:**
The app should run successfully

**Observed behaviour:**
Project build failed with error : "package javax.annotation.processing does not exist"

**Device and Android version:**
Any

**Screenshots:**
![screenshot](https://user-images.githubusercontent.com/43489827/123521136-67ed1900-d6d2-11eb-8dcd-2b6240b0593a.png)

**Comment by duttabhishek0** [comment]
Hey, can I work on this issue?
