### ISSUE TITLE
Gradle build failure error 

### ISSUE THREAD

**Issue by mukundpradhan-inndata** [openMF/self-service-app#1783]
**Summary:**

Gradle build failed with error Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'findbugs' not found.

**Steps to reproduce:**

1. Clone the repository.
1. Open the project in android studio
1. Gradle project sync failed. Basic functionality (e.g editing, debugging) will not work properly.

**Expected behaviour:**

The app should run successfully.

**Observed behaviour:**
Poject build failed with below error :
org.gradle.api.plugins.UnknownPluginException: Plugin with id 'findbugs' not found (Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'findbugs' not found).

**Device and Android version:**

Till not running any device.

**Screenshots:**

![image](https://user-images.githubusercontent.com/72866406/124425256-ef4b2400-dd85-11eb-899b-2c9b4346834a.png)

**Comment by nishant3721** [comment]
Mind if I work on it?

**Comment by duttabhishek0** [comment]
Hey, is this issue still there?
Cause when I tried to build it on my system, there were no issues.

**Comment by rahul-gill** [comment]
This happens sometimes with me too
