### ISSUE TITLE
Image (Mifos logo) present in the navigation drawer is not properly displayed

### ISSUE THREAD

**Issue by AbhilashG001** [openMF/self-service-app#179]
**Summary:**

The image (the Mifos logo) present in the navigation drawer is not properly displayed, it is partially cropped at the top.  

**Steps to reproduce:**

Step 1) Open the self-service android app.
Step 2) Tap on the hamburger menu.

**Expected behavior:**

The image (Mifos logo) should be properly displayed.  

**Observed behavior:**

The image (Mifos logo) is partially cropped from the top.

**Device and Android version:**

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**Screenshots:**

![screenshot_20170314-115947](https://cloud.githubusercontent.com/assets/20839661/23888871/1a3c518e-08b0-11e7-8757-54872d819499.png)

**Comment by AbhilashG001** [comment]
I would like to work on this issue.

**Comment by therajanmaurya** [comment]
Go ahead

**Comment by AbhilashG001** [comment]
@therajanmaurya, I have made appropriate changes, please review my pull request. Also kindly let me know if I have to make any further changes.
Pull request - https://github.com/openMF/self-service-app/pull/180

**Comment by AbhilashG001** [comment]
The issue was resolved.
