### ISSUE TITLE
Add License Gradle Plugin

### ISSUE THREAD

**Issue by ishan1604** [openMF/self-service-app#18]

**Comment by therajanmaurya** [comment]
@ishan1604 can you please provide some links.

**Comment by therajanmaurya** [comment]
Hi @ishan1604 do you mean to add this plugin https://plugins.gradle.org/plugin/com.github.hierynomus.license?
Or Add this https://github.com/openMF/android-client/blob/master/LICENSE.md in project root and mention in every project file like this
```
/*
 * This project is licensed under the open source MPL V2.
 * See https://github.com/openMF/android-client/blob/master/LICENSE.md
 */
```

**Comment by therajanmaurya** [comment]
Added in https://github.com/openMF/self-service-app/commit/66756b78ce3889a4d0c67f09ef86c7dd3d9d183f
