### ISSUE TITLE
You are not authorized for self service user

### ISSUE THREAD

**Issue by francisguchie** [openMF/self-service-app#1804]
Summary:
**If you try to login with the default credentials the app will show that you're not authorized**

**Steps to reproduce:**
Create a self service user using the UI of your Fineract installation 

Clone the Repo, change the server and identifier in the paths below to your liking
**app/src/release/java/org/mifos/mobile/api/BaseURL.kt**  and  **app/src/debug/java/org/mifos/mobile/api/BaseURL.kt**

companion object {
        const val API_ENDPOINT = "yourserverIP or DOMAINNAME"
        const val API_PATH = "/fineract-provider/api/v1/"
        const val PROTOCOL_HTTPS = "https://"
    }

**app/src/debug/java/org/mifos/mobile/api/SelfServiceInterceptor.kt**
    companion object {
        const val HEADER_TENANT = "Fineract-Platform-TenantId"
        const val HEADER_AUTH = "Authorization"
        const val DEFAULT_TENANT = "default"
    }

**Expected behaviour:**
It should login with a self service user that is linked to a particular client 

**Observed behaviour:**
It displays a toast saying "You're not authorized" 
Yet It allows you to log in using the username: **mifos** and password: **password** however and when you do login, the app defaults to the first client **(client Account: 000000001)** in the database (kinda strange)

**Device and Android version:**
TECNO Camon 16 Premier
android 11

**Comment by francisguchie** [comment]
@rrpawar96, @bgowda , @BLasan 
Have you encountered this ?

**Comment by francisguchie** [comment]
This issue was once opened and closed https://github.com/openMF/mifos-mobile/issues/1550 , I wonder why?

**Comment by francisguchie** [comment]
@sachin-0102 , @ShivangiSingh17, @miPlodder 
Is there something am doing wrong?

**Comment by francisguchie** [comment]
@luckyman20  is there anything I have not done well?

**Comment by luckyman20** [comment]
@francisguchie I think I will have to check it myself. Can you please help me with the server credentials?

**Comment by francisguchie** [comment]
> @francisguchie I think I will have to check it myself. Can you please help me with the server credentials?

@luckyman20  kindly check your email

**Comment by francisguchie** [comment]
@luckyman20,  @rrpawar96, @bgowda , @BLasan
I am going to close this issue, I rebase my development branch and followed the steps https://github.com/openMF/mifos-mobile/issues/1804#issue-1013857446 and it is now working
