### ISSUE TITLE
Beneficary info not loaded correctly

### ISSUE THREAD

**Issue by afk11** [openMF/self-service-app#1822]
**Summary:**

The app cannot correctly set the beneficiaryAccountOption in ThirdPartyTransferFragment

**Steps to reproduce:**

Simple, just do a transfer

**Expected behaviour:**

On the review page, clicking continue should work

**Observed behaviour:**

It returns form validation errors, that the account info is missing

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by sukarxn** [comment]
Hey @afk11 if this is still open, I'd like to take this up.
