### ISSUE TITLE
"Bad Request","message":"","path":"/fineract-provider/api/v1/self/authentication"}

### ISSUE THREAD

**Issue by pete10200** [openMF/self-service-app#1825]
@rrpawar96  I am getting below error when logging on to app:
{"timestamp":1641671332070,"status":400,"error":"Bad Request","message":"","path":"/fineract-provider/api/v1/self/authentication"}

**Comment by rrpawar96** [comment]
@pete10200 try again by removing 'self' from path i.e.  fineract-provider/api/v1/authentication

**Comment by pete10200** [comment]
I get the same error message

**Comment by pete10200** [comment]
@rrpawar96  i get the same error message if i  use this on the base url  "/fineract-provider/api/v1/authentication"

**Comment by rrpawar96** [comment]
To which server you are connected to? what is your URL and headers? @pete10200

**Comment by pete10200** [comment]
@rrpawar96 W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation: eglCreateContext: 0xaebe3fc0: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
E/FirebaseCrashlytics: Failed to retrieve settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:622027757397:android:29f731fdcd3a65a6/settings
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
D/OkHttp: --> POST https://zambuko.skyfin.live/fineract-provider/api/v1/authentication http/1.1
    Content-Type: application/json; charset=UTF-8
    Content-Length: 49
    {"password":"kennyphiri","username":"kennyphiri"}
    --> END POST (49-byte body)
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
D/OkHttp: <-- 400  https://zambuko.skyfin.live/fineract-provider/api/v1/authentication (1760ms)
    WWW-Authenticate: Basic realm="Fineract Platform API"
    vary: accept-encoding
    Content-Type: application/json
    Transfer-Encoding: chunked
    Date: Mon, 10 Jan 2022 16:23:32 GMT
    Connection: close
D/OkHttp: {"timestamp":1641831812304,"status":400,"error":"Bad Request","message":"","path":"/fineract-provider/api/v1/authentication"}
    <-- END HTTP (125-byte body)
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab28a0e0
D/EGL_emulation: eglMakeCurrent: 0xaebe3fc0: ver 2 0 (tinfo 0xab2a3150)

**Comment by rrpawar96** [comment]
@pete10200  it seems you are missing one parameter ie. ?tenantIdentifier=default parameter at the end of the url.

First use RESTCLIENT API or POSTMAN and try to authentication once you get authentication 200 ok there then use the same configuration in your request in your code here 

For example i will post my REST CLIENT screenshot here:

![image](https://user-images.githubusercontent.com/20750973/148819879-2270ad8b-1d2a-42cc-9a28-cb276d41ecce.png)

and you should change your credentials since it got in public now from logs.

**Comment by pete10200** [comment]
Without /self
![image](https://user-images.githubusercontent.com/97407144/148894797-d6c7e08a-cd42-4fc2-be24-f2faad7829d6.png)

with /self
![image](https://user-images.githubusercontent.com/97407144/148895024-220a4ad7-f7d2-41eb-9df1-82fb488c4a50.png)

without ?tenantIdentifier=
![image](https://user-images.githubusercontent.com/97407144/148895104-13d04330-6413-49f2-a150-270b21ba1252.png)


Its behaving as if the api does not exist?

**Comment by rrpawar96** [comment]
@pete10200 Earlier you was mention that community-app is working right? check how the request is passed from community-app, and then try it out here

**Comment by pete10200** [comment]
@rrpawar96 I dont know what changed but the below is now working on Postman: without self
![image](https://user-images.githubusercontent.com/97407144/148958481-da6ac1cd-48d8-46a8-bab0-057902f99983.png)

with self
![image](https://user-images.githubusercontent.com/97407144/148963305-db2ce28d-f482-4fb1-83a0-3fdc5f96a043.png)


**I have ensured that the same is on the andriod app but i keep getting the same error:**


![image](https://user-images.githubusercontent.com/97407144/148958660-4c4e7998-82b6-420d-8044-cf10fbe08c41.png)


**I have also confirmed with the community app the request is passed the same:**

![image](https://user-images.githubusercontent.com/97407144/148962068-bf9be96c-609e-46e3-b3e4-268651ef5494.png)

![image](https://user-images.githubusercontent.com/97407144/148961434-286126f8-06b0-45fc-8f6f-166aa891da93.png)

**Comment by rrpawar96** [comment]
> @rrpawar96 I don't know what changed but the below is now working on Postman: without self

Good.

 > I have ensured that the same is on the android app but I keep getting the same error:

Just check with your other parameters as well like headers by changing the tenant identifier which is in the file :
app/src/debug/java/org/mifos/mobile/api/SelfServiceInterceptor.kt  in companion object { }

**Comment by er-prince** [comment]
if you are using mifos release 18.03 & develop version of mifos mobile app  it will not work , upgrade it to 21.07 release it ill work.

**Comment by pete10200** [comment]
I am using version 21.07

**Comment by pete10200** [comment]
> 

after making this change i have managed to log on. thank you!!

**Comment by pete10200** [comment]
> > 
> 
> after making this change i have managed to log on. thank you!!



> > @rrpawar96 I don't know what changed but the below is now working on Postman: without self
> 
> Good.
> 
> > I have ensured that the same is on the android app but I keep getting the same error:
> 
> Just check with your other parameters as well like headers by changing the tenant identifier which is in the file : app/src/debug/java/org/mifos/mobile/api/SelfServiceInterceptor.kt in companion object { }

after making this change i have managed to log on. thank you!!

**Comment by rrpawar96** [comment]
@pete10200 can you please end the thread on email as well and paste the link of this issue, so if anyone in the future gets the same issue they can resolve it by going through this conversation.

**Comment by pete10200** [comment]
issue resolved, see "Bad
Request","message":"","path":"/fineract-provider/api/v1/self/authentication"}
· Issue #1825 · openMF/mifos-mobile (github.com)
<https://github.com/openMF/mifos-mobile/issues/1825>

**Comment by adityarai004** [comment]
> > @rrpawar96 I don't know what changed but the below is now working on Postman: without self
> 
> Good.
> 
> > I have ensured that the same is on the android app but I keep getting the same error:
> 
> Just check with your other parameters as well like headers by changing the tenant identifier which is in the file : app/src/debug/java/org/mifos/mobile/api/SelfServiceInterceptor.kt in companion object { }

what do i have to change
