### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by satishviswanadham** [openMF/self-service-app#1833]
**Summary:**

getting internal server error while trying to login

**Steps to reproduce:**

username : mifos 
password  : password 

when I click on login getting that issue

 this is the response I am getting 

https://demo.mifos.io/fineract-provider/api/v1/authentication?username=mifos&password=password 

 <!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Request failed.</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><hr class="line" /><h3>Apache Tomcat/9.0.48</h3></body></html>

**Comment by rahul-gill** [comment]
The demo account credentials are
username: selfservice
password: password
