### ISSUE TITLE
Improve UX implementation of Loan Account Details

### ISSUE THREAD

**Issue by karsai1993** [openMF/self-service-app#185]
Summary:
The UI implementation of LoanAccountsDetailFragment should be improved. 

Steps to reproduce:
1, After login, open LOAN tab
2, Click one of them e.g.: 000000500

Expected behavior:
The textViews should be placed in the center of their layout to have a better look on them. Additionally, in case of the value of Next Installment, there should be the currency shown as it is in case of Outstanding Balance.

Observed behavior:
TextView values are not in the center of their layout. E.g. in case of Next Installment and its value: they were too close to each other (see attached image). Value of Next Installment does not shown the currency.

Device and Android version:
Samsung Ace 3
API 17 - 4.2.2

Screenshots:
![load_account_details_wrong_ui](https://cloud.githubusercontent.com/assets/15123875/23967313/b48a7d38-09be-11e7-9087-851882167f76.png)

**Comment by karsai1993** [comment]
I have already implemented the solution. Please take a look at the attach image showing the result of my implementation. I am ready to commit and send a pull request.
![improved_load_account_details_wrong_ui](https://cloud.githubusercontent.com/assets/15123875/23967371/f231e450-09be-11e7-8f44-7ff5ea28b45e.png)

**Comment by karsai1993** [comment]
The currency symbol should be after the value, not before it. See attached image:
![newest_improved_load_account_details_wrong_ui](https://cloud.githubusercontent.com/assets/15123875/23975603/0c3899a2-09e2-11e7-9d9d-35e00ba25007.png)

**Comment by dilpreet2028** [comment]
Fixed in #332
