### ISSUE TITLE
Transfer amount Accepting '0'

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#186]
the amount field in transfer layout accepting 0 amount @therajanmaurya  i would like to fix this bug...
<img width="180" alt="screenshot_20170316-022204" src="https://cloud.githubusercontent.com/assets/14215902/23970461/de5dfc4e-09ef-11e7-9cc7-3b2008733ace.png">

**Comment by abhaymaniyar** [comment]
@prashanthkomuravelli are you working on this?

**Comment by ghost** [comment]
@abhaymaniyar i already done that but @therajanmaurya didn't said anything about that...that's why i am waiting
