### ISSUE TITLE
Update dependencies versions and make neccessary changes afterwards

### ISSUE THREAD

**Issue by rahul-gill** [openMF/self-service-app#1861]
To use the android libraries which are not added as dependencies in the app right now(e.g. constraint layout), We'll have to find the version of the library which is compatible with the libraries included in the app. 

## Why
Because latest version of the new dependencies introduces latest version of other libraries like core-ktx and app-compat as transitive dependencies which require updating Gradle and Kotlin versions and updating the compileSdk of the app.

**Comment by debz-g** [comment]
I would like to solve the dependency related issue here.

**Comment by oyehanif** [comment]
i want to work on this task

**Comment by Johnosezele** [comment]
Hey @oyehanif, are you still working on this issue?

**Comment by MohmmadHanif** [comment]
Yup i am opening my PR soon

**Comment by Maan-Sharma** [comment]
hey, can I work on it @rahul-gill

**Comment by rahul-gill** [comment]
Do it

**Comment by Maan-Sharma** [comment]
hey, @rahul-gill  can you  check this?
