### ISSUE TITLE
Too many unneccessary nullable variables

### ISSUE THREAD

**Issue by rahul-gill** [openMF/self-service-app#1862]
This is probably because of Java to Kotlin conversion. Many class properties, variables, function arguments and return type can be made non-nullable.

**Comment by sanjeev0210** [comment]
@rahul-gill has the fix for this been developed yet?

**Comment by rahul-gill** [comment]
no

**Comment by arinmodi** [comment]
@rahul-gill I have made the PR #1886, can you please review it ?

**Comment by rishujam** [comment]
Hey @rahul-gill is the issue solved?
