### ISSUE TITLE
Cannot retrieve User image

### ISSUE THREAD

**Issue by hardik124** [openMF/self-service-app#187]
**Summary:**
Cannot retrieve user Image

**Steps to reproduce:**

Make a GET request to retrieve client image in binary form
**Expected behavior:**
Should return the raw body of binary encoded  image
**Observed behavior:**
Returns 404
Retrofit Error body :-   {"developerMessage":"The requested resource is not available.","httpStatusCode":"404","defaultUserMessage":"The requested resource is not available.","userMessageGlobalisationCode":"error.msg.resource.not.found","errors":[{"developerMessage":"Image for resource clients with Identifier 1 does not exist","

**Comment by hardik124** [comment]
Also , I cannot PUT or POST image .
it returns error code 405

**Comment by sosnickm** [comment]
@therajanmaurya do you know why this could be?

**Comment by hardik124** [comment]
@therajanmaurya  shall I send a PR ? the code worked when server returned the image , but now since i cannot , it uses default image as user profile picture in case of server error.

**Comment by dilpreet2028** [comment]
@hardik124 @sosnickm @therajanmaurya it was returning a 404 as there was no image uploaded for self service client, I uploaded a demo image from Mifos X Client for self service client and now it returns the base64 value for that image.
Link: https://demo.openmf.org/fineract-provider/api/v1/self/clients/1/images?tenantIdentifier=default&pretty=true
