### ISSUE TITLE
Improvement of UX implementation in Saving Account related fragments

### ISSUE THREAD

**Issue by karsai1993** [openMF/self-service-app#189]
**Summary:**
Changes are required to improve UI implementation in Saving Account related fragments. This issue deals with three fragments: SavingAccountsDetailFragment and SavingAccountsTransactionFragment.

**Steps to reproduce:**
1, Open one of the fragments above.

**Observed and Expected behavior:**
In case of **SavingAccountsDetailFragment**:
1, ToolBar label is too long, the user cannot read it. The label should be Saving Account, after it we should implement a textview of which text is Details.
2, The user cannot see what is written in the bottom of the fragment because only the half of it can be seen. We should implement this fragment in a ScrollView.
3, On the top of the fragment, the Account Balance and its value is not in the same hight, they are floated compared to each other. It is true for Last Transaction and its value, too.
4, The text in the buttons is not in the center. They should be set to the middle of the button.
5, Comma is used in the numbers to separate integer part from fractions. We should use point as it is in Loan Account Details fragment.
6, Nominal Interest Rate does not have enough place to be read. 
7, Refactor need_help string and place the phone number in a position in which that is not separated in different lines.
8, Create explanation textviews for Nominal Interes Rate and Minimal Required Balance as they need to be shortened to fit in the layout.

In case of **SavingAccountsTransactionFragment**:
1, ToolBar label is too long, the user cannot read it. The label should be Saving Account, after it we should implement a textview of which text is Transactions.
2, Make option menu button disabled as we are currently in the fragment which that menu option button would open.
3, Refactor need_help string and place the phone number in a position in which that is not separated in different lines.
4, Implement ScrollView because in some cases there is a need for it.
5, Improve UX in adapter

**Device and Android version:**
Samsung Ace 3
API 17 - 4.2.2
**Screenshots:**
![saving_acc_details](https://cloud.githubusercontent.com/assets/15123875/23976197/7635eafe-09e6-11e7-830c-4c6e2d690147.png)
![saving_acc_transactions](https://cloud.githubusercontent.com/assets/15123875/23976196/7635718c-09e6-11e7-9d27-c49de4b54b8a.png)

**Comment by karsai1993** [comment]
I have 95% done with the implementation because making disabled the menu option button is not working 100% but I am working on it. However, I could show some image about how it and my whole solution would be looked like. Steps between the two fragments inline:
SavingAccountsDetailFragment:
![details_1](https://cloud.githubusercontent.com/assets/15123875/23980347/6a1bf79a-09ff-11e7-8758-6c5a3a700024.png)
![details_2](https://cloud.githubusercontent.com/assets/15123875/23980344/6a1ac834-09ff-11e7-85cd-a045894c582e.png)
![details_3](https://cloud.githubusercontent.com/assets/15123875/23980343/6a1a56ce-09ff-11e7-80c1-d34028b68730.png)
SavingAccountsTransactionFragment:
![transaction_1](https://cloud.githubusercontent.com/assets/15123875/23980345/6a1ac0d2-09ff-11e7-9776-294a6ae93730.png)
![transaction_2](https://cloud.githubusercontent.com/assets/15123875/23980346/6a1b8f1c-09ff-11e7-9485-828412b4ac95.png)
![transaction_3](https://cloud.githubusercontent.com/assets/15123875/23980348/6a1c64b4-09ff-11e7-8e5f-e89427cb05a9.png)
SavingAccountsDetailFragment again:
![details_3](https://cloud.githubusercontent.com/assets/15123875/23980343/6a1a56ce-09ff-11e7-80c1-d34028b68730.png)

**Comment by karsai1993** [comment]
Disabling is done but in TransactionFragment, there is a need for futher changes as the price value does not have enough place to be read. See images above.

**Comment by karsai1993** [comment]
I have managed to make the app handle better the textview in TransactionFragment. See attach image. I am ready for commit and send a PR.
![transaction_4](https://cloud.githubusercontent.com/assets/15123875/24012016/caafeb02-0a7c-11e7-90a5-6e7f5f2ec28e.png)

**Comment by dilpreet2028** [comment]
Fixed in #332
