### ISSUE TITLE
Error during Login/SignUp

### ISSUE THREAD

**Issue by Aditya-gupta99** [openMF/self-service-app#1896]
**Summary:**
Unable to login into mifos using the credentials (username : mifos  ; password : password).  

**Steps to reproduce:**

- Start the app 
- Go to login and enter the above credentails nothing happens
- this is the logcat : {"timestamp":"2023-02-01T15:33:29.740+00:00","status":400,"error":"Bad Request","path":"/fineract-provider/api/v1/self/authentication"}

**Expected behaviour:**

User should have been able to login using these credentails 

**Observed behaviour:**

I get the response when i pass the header to https://demo.mifos.community/fineract-provider/api/v1/clients
![image](https://user-images.githubusercontent.com/94394661/216088770-432bb7ee-62fb-45aa-b3d2-01a4f25eecea.png)

**Device and Android version:**

Device : OnePlus Nord<br> Android 12

**Comment by PratyushSingh07** [comment]
@Aditya-gupta99 i can solve this issue by passing header in the code
