### ISSUE TITLE
App Crashes when clicking on submit button without selecting product ID

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#1897]
**Summary:**

App crashes when u click on submit button in Apply Savings Account

**Steps to reproduce:**

https://user-images.githubusercontent.com/90026952/216305746-2822b26f-270e-4fa2-9060-20ecfcb15121.mp4

**Expected behaviour:**

An appropriate message stating "Product ID cannot be null" or something similar should be displayed

**Device and Android version:**

Device: Samsung M11
Android: 11

**Comment by PratyushSingh07** [comment]
@siebrand @vorburger can you please review this PR

**Comment by PratyushSingh07** [comment]
@siebrand @vorburger kindly review this PR

**Comment by vorburger** [comment]
@PratyushSingh07 thank you for tagging. I'm not actively contributing to this project. Are you able to find its current maintainers?

**Comment by PratyushSingh07** [comment]
> @PratyushSingh07 thank you for tagging. I'm not actively contributing to this project. Are you able to find its current maintainers?

No sir, I am not really sure who are the current maintainers

**Comment by vorburger** [comment]
Based on https://github.com/openMF/mifos-mobile/commits/development, it would appear that e.g. @IOhacker and @avikganguly01 (hey!) or @rahul-gill are currently actively involved in this repo, so they may be better positioned to review this than me.

**Comment by avikganguly01** [comment]
Other than configuration files and UI, I have no idea about this codebase as I have mostly been using this for demo purposes.
