### ISSUE TITLE
UI enhancement :Sweet alert dialog box  instead of SnackBar if internet is not connected in charges fragment

### ISSUE THREAD

**Issue by itsamitgoel** [openMF/self-service-app#190]
Summary:

if we pull to refresh data in charges fragment when internet is not connected, a snackbar shows with error message "Error loading in client charges". Instead of this , a Sweet Alert Dialog Box with same message will enhance the UI. This sweet alert dialog box will be better than  snackbar. It will make ui look more attractive.

Steps to reproduce:

Step1: login into app
Step2: go to charges fragment
Step3: give no internet access to your phone
Step4: pull to refresh data and a snackbar will appear.

Expected behavior:

A Sweet alert dialog box instead of snackbar on charges fragment will enhance the UI of app.
![ad7bb3d2-06b6-11e7-8752-bf53b24768b0](https://cloud.githubusercontent.com/assets/16203080/23983769/ecde5f1a-0a3b-11e7-930e-c5bb8ac2997e.png)

Observed behavior:

A snackbar on pull to refresh data in charges fragment
![07424d98-0583-11e7-9f58-ed310d7cc1f4](https://cloud.githubusercontent.com/assets/16203080/23983814/2d6d71ec-0a3c-11e7-8732-8f2b45514dc0.png)

Device and Android version:

Xiaomi Redmi prime 2 Android 5.1.1

@therajanmaurya i would like to work on this, please assign it to me. Thanks

**Comment by itsamitgoel** [comment]
@therajanmaurya  please review

**Comment by dilpreet2028** [comment]
Instead of showing a dialog, it would be better if we follow the implementation of PR: #300 
@therajanmaurya what do you think?
