### ISSUE TITLE
Filters aren't working properly in the Accounts section

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#1902]
**Summary:**

The filters aren't working the way they are supposed to

**Steps to reproduce:**

https://user-images.githubusercontent.com/90026952/216436584-8f528a89-1bcc-4b28-a511-385db8e3d67e.mp4

**Expected behaviour:**
The check box should be clickable and list out the appropriate results

**Observed behaviour:**

The check box isn't working and after clicking on "Filter" it shows no savings account found even though such an account exists

**Device and Android version:**

Device : Samsung M11
Android: 11

**Comment by PratyushSingh07** [comment]
I will be working on this issue

**Comment by oyehanif** [comment]
@PratyushSingh07 are you working in this issue? if you don't mind then i want to work on this issue.

**Comment by PratyushSingh07** [comment]
@oyehanif i am working on this and I will be opening a PR soon

**Comment by PratyushSingh07** [comment]
Would appreciate if someone reviews this
