### ISSUE TITLE
Duplication of items in the Loan Product section

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#1907]
**Summary:**

When I submit the Loan application for review without filling the Loan Product , the items in the Loan Product duplicates itself

**Steps to reproduce:**
- Click on Apply for loan
- Do not select any Loan Product
- Fill a Principal amount
- Click on Review then Click on Submit loan
- Go back to the previous page and now click on Loan Product
- You will see a list of duplicated items 

**Expected behaviour:**

The items in the Loan Product shouldn't duplicate itself or you shouldn't be allowed to move on to the next page unless you have selected the Loan Product

**Observed behaviour:**

https://user-images.githubusercontent.com/90026952/216999442-d237046c-04b6-44b1-87f3-da150725b5d2.mp4

**Device and Android version:**

Device: Samsung M11
Android: 11

**Comment by oyehanif** [comment]
This is available or fix ?

**Comment by PratyushSingh07** [comment]
No @oyehanif this has been resolved and the PR has been opened
