### ISSUE TITLE
App Crashes when the orientation changes to landscape

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#1909]
**Summary:**

App crashes as soon as the orientation changes to Landscape 

**Steps to reproduce:**

- open the app
- rotate the home screen to landscape

**Expected behaviour:**

Layout should have been working properly even if the orientation was changes

**Observed behaviour:**

App Crashes when changed to landscape

https://user-images.githubusercontent.com/90026952/217056176-959c0dd2-d648-491b-901e-249f14aa543a.mp4

**Device and Android version:**

Device: Samsung M11
Android: 11

**Comment by oyehanif** [comment]
Can i work on this task??
