### ISSUE TITLE
After changing the orientation, the filter dialog options are not visible.

### ISSUE THREAD

**Issue by Aditya-gupta99** [openMF/self-service-app#1914]
**Summary:**

On the Client Account page, the filter dialog bottom options are not visible when the orientation is changed to landscape.

**Steps to reproduce:**

https://user-images.githubusercontent.com/94394661/218096488-b53c13e7-21a3-4a02-9ccd-56c825767368.mp4

**Expected behaviour:**

Filter dialog bottom options are visible when the orientation is changed.

**Observed behaviour:**

It is not possible to see the filter options at the bottom of the Client Account page when the orientation is changed to landscape.

**Device and Android version:**

Device : OnePlus Nord
Android 12

**Comment by oyehanif** [comment]
i want to work on this task?

**Comment by Aditya-gupta99** [comment]
@oyehanif I have already revtified the issue and pr is open.
