### ISSUE TITLE
Could not find com.github.Raizlabs.DBFlow:dbflow-core:4.1.2

### ISSUE THREAD

**Issue by devrahul-2508** [openMF/self-service-app#1916]
**Summary:**
Could not find com.github.Raizlabs.DBFlow:dbflow-core:4.1.2 build issues
**Steps to reproduce:**
kapt "com.github.Raizlabs.DbFlow:dbflow-processor:${rootProject.dbflowVersion}"
implementation "com.github.Raizlabs.DbFlow:dbflow-core:${rootProject.dbflowVersion}"
 implementation "com.github.Raizlabs.DbFlow:dbflow:${rootProject.dbflowVersion}"

**Expected behaviour:**

A successful build without any issues

**Observed behaviour:**

Could not find com.github.Raizlabs.DBFlow:dbflow-core:4.1.2 build issues

**Device and Android version:**

Device Samsung A51 (Api Level 33) Pixel 5 (Api level 32)

**Screenshots:**

![Screenshot (143)](https://user-images.githubusercontent.com/91717339/218254588-ae2f4503-e07f-43eb-a384-9b47c34e8c43.png)

**Comment by devrahul-2508** [comment]
#1917

**Comment by jawidMuhammadi** [comment]
This issue has been fixed and not valid anymore
