### ISSUE TITLE
Even selecting dark mode, register screen was in light mode

### ISSUE THREAD

**Issue by devrahul-2508** [openMF/self-service-app#1918]
**Summary:**
Even selecting dark mode, register screen was in light mode

**Steps to reproduce:**
Select dark mode in settings and log out and click on register screen

**Expected behaviour:**
Register screen should be synchronized with dark mode

**Observed behaviour:**
Register screen was synchronized with light mode with button colours and textfield colours blushed out.

**Device and Android version:**
Device Samsung A51 (Android 13)

**Screenshots:**

<img src = "https://user-images.githubusercontent.com/91717339/218291669-2dc1295c-fcdf-415e-aaf9-be054909a895.jpg" height="500"/>

**Comment by devrahul-2508** [comment]
#1917

**Comment by devrahul-2508** [comment]
#1917

**Comment by oyehanif** [comment]
i want to work on this task?

**Comment by devrahul-2508** [comment]
Hi @oyehanif this issue has already feen fixed in #1917. Try looking for other issues

**Comment by ayushkeshri19** [comment]
I want to work on this issue

**Comment by kmanikanta335** [comment]
@PratyushSingh07 can i work on this issue

**Comment by PratyushSingh07** [comment]
@keshriAyushh are you working on this ? If not then can i assign this to @kmanikanta335 ?

**Comment by ayushkeshri19** [comment]
@PratyushSingh07 Yeah I'm working on it

**Comment by kmanikanta335** [comment]
@keshriAyushh hey are still working on it ?

**Comment by kmanikanta335** [comment]
@PratyushSingh07 can i work on it ?

**Comment by PratyushSingh07** [comment]
@keshriAyushh @kmanikanta335 I have raised PR #2459 that fixes this issue as well as #2458
