### ISSUE TITLE
Unification of Saving and Sharing Account relating CircularImageView(RecycleView) colours

### ISSUE THREAD

**Issue by karsai1993** [openMF/self-service-app#192]
**Summary:**
The CircularImageView(RecycleView) colours corresponding to the same status (active, approved, submitted and pending aproval and other) in Saving and Sharing Accunt related fragments. 

**Steps to reproduce:**
1, Open SAVING tab
2, Take a look at the colour of the circularImageView
3, Click on it and if its status is approved or other (described below), then the colour which can be seen in Saving Accounts Details is different. 

**Expected behavior:**
The CircularImageView colours should remain the same in case of each status.

**Observed behavior:**
The colours are set in two classes: SavingAccountsDetailFragment(this colours gets implemented when we have clicked one of the saving account list element) and ShareAccountsListAdapter (when we can scroll in the saving account list adapter).
As of now, the problem is with the status of approved and other which can be concluded from the source code:
In SavingAccountsDetailFragment:
if (status.getActive()) {...R.color.deposit_green...} else if (status.getApproved()) {...**R.color.blue**...}
else if (status.getSubmittedAndPendingApproval()) {...R.color.light_yellow...} else {...**R.color.black**...}
In ShareAccountsListAdapter and SavingAccountsListAdapter 
if (status.getActive()) {...R.color.deposit_green...} else if (status.getApproved()) {...**R.color.light_green**...}
else if (status.getSubmittedAndPendingApproval()) {...R.color.light_yellow...} else {...**R.color.light_blue**...}

**Device and Android version:**
Samsung Ace 3
API 17 - 4.2.2

**Screenshots:**
In case of ShareAccountsListAdapter (please, take a look at the last element on the button which is light blue coloured):
![colour_1](https://cloud.githubusercontent.com/assets/15123875/24013184/e14f3666-0a80-11e7-878f-91a10667899d.png)

After click on this item, in the SavingAccountsDetailFragment, we face a different colour:
![colour_2](https://cloud.githubusercontent.com/assets/15123875/24013224/ffaecc20-0a80-11e7-955c-b847bbdae31c.png)

**Comment by karsai1993** [comment]
I have implemented the solution. I used the the colours settings which are set in SavingAccountsDetailFragment:
if (status.getActive()) {...R.color.deposit_green...} else if (status.getApproved()) {...R.color.blue...}
else if (status.getSubmittedAndPendingApproval()) {...R.color.light_yellow...} else {...R.color.black...}
Of course, it can be changed, just please let me know.

It is set in both SavingAccountsListAdapter and ShareAccountsListAdapter. As of the first one, here is an attachment:
![colour_3](https://cloud.githubusercontent.com/assets/15123875/24013874/2128faa4-0a83-11e7-9a09-f5743126adeb.png)

I am ready to commit and send a PR.

**Comment by dilpreet2028** [comment]
Sharing and saving account have status colors according to the Mifos X Client.
@therajanmaurya I think this issue is not relevant
