### ISSUE TITLE
Gradle build failed because of some dependency issue

### ISSUE THREAD

**Issue by adityarai004** [openMF/self-service-app#1924]
**Summary:** 

no changes and mistakes during setup were from my side were done. The app did launch because of gradle build couldn't finish.

**Steps to reproduce:** 

Just setup the source code by usual steps and run the app in android studio

**Observed behavior:** 
![image](https://user-images.githubusercontent.com/86659578/220975013-f6482de0-81da-4e95-a36e-03f9eb86a6af.png)

**Comment by PratyushSingh07** [comment]
@adityarai004 this has been already solved in issue #1916 and prior to this has already been pushed in this [PR](https://github.com/openMF/mifos-mobile/pull/1901)

**Comment by adityarai004** [comment]
Done, btw how do i login am not preferring to give my original info i tried registering a fake one but it shows error
