### ISSUE TITLE
PassCodeActivity doesn't change with the theme (dark &light mode)

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#1928]
**Summary:**

In the current state the theme of the PassCodeActivity is set to  a fixed color i.e white irrespective of the dark/light mode of the mobile. 

**Steps to reproduce:**
- open the app
- see the behaviour of PassCodeActivity

**Expected behaviour:**

PassCode Activity should change to black in case of dark theme and should be white in case of light theme

**Device and Android version:**
Device : Samsung M11
Android : 11

**Screenshots:**
<table>
  <tr>
      <td><img src="https://user-images.githubusercontent.com/90026952/224384976-2f612da0-a7e3-461a-8da4-f5cf667820f8.jpeg" width=250 height=480>Current Screenshot</td>
  </table>

**Comment by PratyushSingh07** [comment]
I shall be taking up this issue

**Comment by jawidMuhammadi** [comment]
Please clarify the issue by adding screenshots and a bit clear title. Also, could you add a screenshot in the PR to show how your solution looks?

**Comment by PratyushSingh07** [comment]
@jawidMuhammadi 
- My device is currently in dark mode and the passcode activity has changed its color accordingly
<table>
    <td><img src="https://user-images.githubusercontent.com/90026952/224384951-fc2e6b1d-fa5f-43ea-a96e-3b29b1165bd6.jpeg" width=250 height=480>After the change</td>
</table>
