### ISSUE TITLE
Share Account List does not gets refreshed

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#193]
**Summary:**

On Refreshing using SwipeRefreshLayout in Accounts Fragment, Share account list does not refreshed because AccountPresenter function  `loadAccount(String accountType)` does not implements the logic for returning Share account List

**Comment by dilpreet2028** [comment]
@therajanmaurya I would like to fix this

**Comment by therajanmaurya** [comment]
Go ahead 👍

**Comment by dilpreet2028** [comment]
Fixed in #209
