### ISSUE TITLE
Can't login with demo credentials

### ISSUE THREAD

**Issue by kingbass01** [openMF/self-service-app#1936]
**Summary:**

The app won't login with demo credentials provided in the wiki

**Steps to reproduce:**

Enter the credentials username : mifos and password : password in the login page and press login

**Expected behaviour:**

Log me in into the app and allow me to access it.

**Observed behaviour:**

The app neither logs in nor shows any error.

**Device and Android version:**
Device - Poco X4 Pro 5G
Android Version - 13 with a Custom ROM

**Screenshots:**

Android Studio Logs
![log](https://user-images.githubusercontent.com/85404940/223110746-0fd8eac5-f1eb-46b5-a3e8-bed5bd1710b5.png)

![App recorded video](https://user-images.githubusercontent.com/85404940/223110589-f40dc6fa-686f-40d0-85a7-96fcc90d4545.mp4)

**Comment by PratyushSingh07** [comment]
![image](https://user-images.githubusercontent.com/90026952/223136154-c73f1c95-92fc-4333-8bd7-b6356255ce08.png)

@jawidMuhammadi  I tested the api in thunder client and I am getting back the response but I am unable to fathom its odd behaviour with the mobile app

**Comment by jawidMuhammadi** [comment]
@PratyushSingh07 Thank you for debugging and testing the API. According to this [responses](https://stackoverflow.com/a/53297674/8268896) in StackOverflow, it looks like our Server's SSL certificate has expired. Let me ping @edcable, he might be able to help to update the certificate.

**Comment by PratyushSingh07** [comment]
Happy to help @jawidMuhammadi . Besides I had some queries regarding this years Idea list, is it possible for us to discuss about that in the slack channel?

**Comment by kingbass01** [comment]
Issue Fixed
