### ISSUE TITLE
Test files not organized under package, making it  complicated  to add new tests 

### ISSUE THREAD

**Issue by NiranjanNlc** [openMF/self-service-app#1939]
**Summary:**
 the test files for the "presenter" package are not organized under the "presenter" package name. 

**Steps to reproduce:**
- Navigate to   "app/src/test/java/org/mifos/mobile"   in the repository.
- You can see whole bunch of test files of  presenter package not organized under the package name presenter 

**Expected behavior:**

Test files should be organized under the same package as the source files, so that it's easy to add tests for other packages.

**Observed behavior:**

Test files  are not organized under the same package as the source files, and adding tests for other packages ( for example : api) would create a messy file structure.

**Device and Android version:**
Its actually related to the code structure and quality 

**Screenshots:**

![image](https://user-images.githubusercontent.com/25600880/223936627-ec421402-09a7-47cb-b9f1-712d5c674d81.png)

**Comment by deecodesss** [comment]
I'll work on this

**Comment by oyehanif** [comment]
I want to work on this.

**Comment by deecodesss** [comment]
@oyehanif I'm already working on this, you can find another one:)

**Comment by sukarxn** [comment]
@deekshatw why is it still open? are you still working on it?

**Comment by deecodesss** [comment]
@SukaranG the PR has some merge conflicts, I'm working on that

**Comment by NiranjanNlc** [comment]
Its long time that  this issues being opened , so i am closing this by pull request    #2145
