### ISSUE TITLE
NullPointerException if system locale is not English

### ISSUE THREAD

**Issue by karsai1993** [openMF/self-service-app#194]
**Summary:**
The user can face with a NullPointerException when she/he wants to filter among saving account transactions.

**Steps to reproduce:**
1, Reach SavingAccountTransactionsFragment
2, Filter e.g.: for 4 months

**Expected behavior:**
The filtering should be successful.

**Observed behavior:**
NullPointerException is thrown because the in DateHelper class, in getDateAsLongFromString method, the parse calling throws ParceException because the system locale is not English by default in the user's device.
We need to set it when we define the SimpleDateFormat. If the user's device locale is set to English, than this change does not influence on in her/his case. But if not, it needs to be done to avoid getting exception and filter successfully among transactions.

**Device and Android version:**
Samsung Ace 3
API 17 - 4.2.2

**Screenshots:**
![unparseable](https://cloud.githubusercontent.com/assets/15123875/24018659/17cb1b10-0a95-11e7-9273-e959b5c7e8df.png)

**Comment by karsai1993** [comment]
I have implemented the solution:
public static long getDateAsLongFromString(String dateStr, String pattern) {
        SimpleDateFormat sdf = new SimpleDateFormat(pattern, Locale.ENGLISH);
...}
It is working as shown in attached file below:
![improved_unparseable](https://cloud.githubusercontent.com/assets/15123875/24018707/57332676-0a95-11e7-8ae5-07c70a9f2e16.png)

I am ready to commit and send a PR.

**Comment by luckyman20** [comment]
@therajanmaurya I think this isssue is  solved now. So I suggest you to close it.
