### ISSUE TITLE
App crashes when changing main mobile theme (dark & light mode)

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#1943]
**Summary:**

When we change the main mobile theme from dark to light then the app crashes. 

https://user-images.githubusercontent.com/90026952/224215297-f9ca0f91-87c2-4262-963d-b7553e8d0781.mp4

**Expected behaviour:**

App theme should have been changed by changing the mobile theme

**Observed behaviour:**

App crashes when the theme is changed from outside of the app

**Device and Android version:**
Device : Samsung M11
Android : 11

**Comment by PratyushSingh07** [comment]
I shall be taking up this issue

**Comment by lonewolf2208** [comment]
Good day @PratyushSingh07 , are you still working on this issue ?

**Comment by PratyushSingh07** [comment]
yes @lonewolf2208
