### ISSUE TITLE
Replace JCenter with mavenCentral

### ISSUE THREAD

**Issue by jawidMuhammadi** [openMF/self-service-app#1944]
**Summary:**

JCenter Maven repository is no longer receiving updates and it should be replaced with mavenCentral

**Comment by jawidMuhammadi** [comment]
@PratyushSingh07 Before starting to work on any issue, please ask the reporter of the issue or any mentor so that we can assign you or give you a green light to go ahead. This issue though has a `good first issue` label which means this is only for first-time contributors to work on it.

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi can I take this issue? I'm new here :)

**Comment by jawidMuhammadi** [comment]
@gururani-abhishek sure, go ahead :)

**Comment by rahulmangla28** [comment]
Hey @jawidMuhammadi 
I am looking forward to work on this issue. Can I start working on this issue ?

**Comment by rahulmangla28** [comment]
@jawidMuhammadi 
We cannot completely remove jcenter() as some of the dependencies such as **"com.isseiaoki:simplecropview:1.1.8"** (and many more dependencies like this) works only with jcenter(). So adding mavenCentral only for those dependencies whose latest implementations works with mavenCentral.

**Comment by jawidMuhammadi** [comment]
That is a great point, thank you for the details @rahulmangla28 🙏 👍
