### ISSUE TITLE
Update target and compile sdk version

### ISSUE THREAD

**Issue by jawidMuhammadi** [openMF/self-service-app#1945]
**Summary:**

The targetSdkVersion and compileSdkVerson should be updated to 33

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi can I take this? I'm new to the project.

**Comment by rahulmangla28** [comment]
Hey @jawidMuhammadi 
I am looking forward to work on this issue. Can I start working on this issue ?

**Comment by SekhGulamMainuddin** [comment]
Hey @jawidMuhammadi
I have updated the SDK version and also solved the nullable view receiver issue(#1956 ) in my pull request. (https://github.com/openMF/mifos-mobile/pull/2080).
This issue seems to be solved.

**Comment by beradeep** [comment]
@jawidMuhammadi I think this issue is solved. Shouldn't it be closed?
