### ISSUE TITLE
Disabling deposit and make transfer buttons for saving accounts which are not active.

### ISSUE THREAD

**Issue by shubham-1996** [openMF/self-service-app#195]
**Summary:**
In the savings tab, if we select an account whose status is not active, then I think we should disable the buttons for deposit and transfer. And even if it is required to keep them, still some changes to code is required as after we click 'Transfer', the app crashes. 

**Steps to reproduce:**
1. Go to an account whose status is not active(can be pending, needs approval etc.).
2. Click on Make a Transfer button and then after selecting from and to accounts, click Review Transfer.
3. Then, click Transfer and the app crashes.

**Screenshots:**

Current Scenario:

![screenshot_2017-03-17-03-42-42](https://cloud.githubusercontent.com/assets/10893679/24022519/01875b9c-0acd-11e7-8907-f79908511211.png)

Expected Scenraio:

We can either make the buttons completely gone : 

![screenshot_2017-03-17-03-48-31](https://cloud.githubusercontent.com/assets/10893679/24022536/1f5bd97c-0acd-11e7-84b8-711768dc6e6f.png)

Or we can disable them : 

![screenshot_2017-03-17-04-13-30](https://cloud.githubusercontent.com/assets/10893679/24022547/2f6755a8-0acd-11e7-9589-e83ee931b958.png)

**Comment by shubham-1996** [comment]
@therajanmaurya please let me know if this is a valid issue and if it is which one would you like me to commit?

**Comment by dilpreet2028** [comment]
Issue fixed in #321
