### ISSUE TITLE
Nullable View receiver in HomeFragment & HomeOldFragment causing issue

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#1956]
**Summary:**

I'm experiencing an issue in the HomeFragment & HomeOldFragment of the Mifos Mobile app. Specifically, I'm seeing the error message "e: /home/runner/work/mifos-mobile/mifos-mobile/app/src/main/java/org/mifos/mobile/ui/fragments/HomeFragment.kt: (108, 14): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type View?" when attempting to run the app.

From what I can gather, this seems to be related to a nullable receiver of type View that's being used in the HomeFragment. The error message suggests that only safe or non-null asserted calls are allowed on this type of receiver, but it doesn't seem like this is being followed in the code.

This is also the reason of the workflow failing on PR #1951 . Kindly refer [here](https://github.com/openMF/mifos-mobile/actions/runs/4393104320/jobs/7693291140)

**Comment by PratyushSingh07** [comment]
@jawidMuhammadi could you add  `good first issue` tag in this if you find this issue worth it

**Comment by oyehanif** [comment]
I want to work on this task.

**Comment by PratyushSingh07** [comment]
> I want to work on this task.

i dont think its upto me to assign this to you . Maybe @jawidMuhammadi can assign this to you and then you can start working on it

**Comment by kingbass01** [comment]
@oyehanif Are you still working on this issue?

**Comment by oyehanif** [comment]
@jawidMuhammadi Sir i have create my pr please review it there have any change or suggestion then let's us know then i will do that .

**Comment by SekhGulamMainuddin** [comment]
Hey @jawidMuhammadi 
I have updated the SDK version (issue: #1945 ) and also solved the nullable view receiver issue in my pull request. (https://github.com/openMF/mifos-mobile/pull/2080).
This issue seems to be solved.
