### ISSUE TITLE
Entire application fails to fetch the data after crash reported in issue #195

### ISSUE THREAD

**Issue by code-dagger** [openMF/self-service-app#196]
**Summary:**

Entire Application not able to fetch details from the endpoints after the application crash because of the issue reported by @shubham-1996 , Issue #195 

**Expected behavior:**

The app should display the details.

**Observed behavior:**

The entire application fails to fetch the details from the endpoints.

**Device and Android version:**

Redmi note 3 (Android 6.0) 

**Screenshots:**

![screenshot_2017-03-17-11-41-49-358_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16591761/24031141/f1eed09a-0b06-11e7-9017-7cee67696a50.png)

![screenshot_2017-03-17-11-41-44-157_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16591761/24031146/f7ed8d7e-0b06-11e7-8a9f-a7108814be0b.png)

![screenshot_2017-03-17-11-12-50-072_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16591761/24031151/00b7a7d2-0b07-11e7-990b-b61e47898e52.png)

![screenshot_2017-03-17-11-41-39-907_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16591761/24031131/e75979fa-0b06-11e7-9959-d84442ff4d4f.jpg)

![screenshot_2017-03-17-11-41-56-933_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16591761/24031133/e9934264-0b06-11e7-85a9-185ae5b74814.png)

![screenshot_2017-03-17-11-41-51-952_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16591761/24031138/ede2a01c-0b06-11e7-8b21-2c2a45bf4cc3.png)

I would like to work on this issue @therajanmaurya

**Comment by dilpreet96** [comment]
@immabhay hidding Deposit and Make Transfer button for pending accounts will help remove this bug.
@therajanmaurya what do you think?

**Comment by dilpreet2028** [comment]
Issue fixed in #321
