### ISSUE TITLE
Unit Test Fails for LoginPresenterTest

### ISSUE THREAD

**Issue by NiranjanNlc** [openMF/self-service-app#1968]
**Summary:**

In the LoginPresenterTest ,  four of the unit test fails under that of method :  testLoadCLientFails and testLoadClientUnauthorized   

**Steps to reproduce:**

 Run the LoginPresenterTest class , we shall sell the failing result for above mentioned  unit tests .

**Expected behaviour:**

All of the  seven  unit test should pass 

**Observed behaviour:**

 Test under the testLoadCLientFails and testLoadClientUnauthorized fails  with error : " message = null "  and "unfinished stubbing " 

**Device and Android version:**

Ocurred while running the unit test in IDE

**Screenshots:**
![image](https://user-images.githubusercontent.com/25600880/224612902-9689c332-f862-48b2-998e-84845b5e7c6c.png)

**Comment by oyehanif** [comment]
i'll work on this task

**Comment by NiranjanNlc** [comment]
hey @oyehanif , before i check your comment just now , i was already on the task . 
Would you please review above mentioned PR so that we can confirm we are on the right track ......
