### ISSUE TITLE
Login credentials not Working

### ISSUE THREAD

**Issue by oyehanif** [openMF/self-service-app#1972]
Login credentials is not working any one please help me to solve this issue.

https://user-images.githubusercontent.com/83781553/224759451-07beee40-6525-468e-b7b4-8d24373840fd.mp4

**Comment by francisguchie** [comment]
@oyehanif , 

please note the following 
1-Enable the self service user group under roles and permissions (groups) 
2- only users that have been tagged "self service users " can log into the system using the self service app 
3- It is advisable you create a client and make the client a self service user
4- if your email service is not activated then during creation of the self service user you have to know the password

5- by default the user in the video provided is not designed to log into the mobile app for clients 

![image](https://user-images.githubusercontent.com/22683654/224763824-5951fc66-2a75-4368-8e5d-49629c966320.png)

**Comment by francisguchie** [comment]
![image](https://user-images.githubusercontent.com/22683654/224764361-ddcc6c2f-32e3-4fa2-9da8-3698cdb59f29.png)

**Comment by gururani-abhishek** [comment]
Hey @oyehanif, it's "mifos" and "password", all lower case letters.

**Comment by oyehanif** [comment]
in my emulator it's work fine but in real device it's not working. i am put video above.

**Comment by francisguchie** [comment]
@oyehanif  & @gururani-abhishek 

Kindly follow the steps I have mentioned above if you really wish to deploy in a production environment

**Comment by gururani-abhishek** [comment]
@francisguchie, it's great to have you for such valuable inputs. Thanks man :)

**Comment by francisguchie** [comment]
@oyehanif if this is ok then we can close this issue please advise

**Comment by francisguchie** [comment]
> @francisguchie, it's great to have you for such valuable inputs. Thanks man :)

I too was helped at one time so its the power of open source
