### ISSUE TITLE
white background of mifos logo looks odd in the dark mode

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#1975]
**Summary:**

Currently the background of mifos logo is white and it remains that way even in the dark mode which makes it look kinda odd 

**Steps to reproduce:**
- open the app
- go to the login page

**Device and Android version:**
Device : Samsung M11
Android : 11

**Screenshots:**

<table>
    <td><img src="https://user-images.githubusercontent.com/90026952/224888420-31b2fe08-6016-4686-b08a-e5b9e897e60b.jpeg" width=250 height=480>Current State</td>
<td><img src="https://user-images.githubusercontent.com/90026952/224888429-5f355665-21bd-41de-a30f-cae8051d3bbb.jpeg" width=250 height=480>Proposed State</td>
</table>

**Comment by PratyushSingh07** [comment]
@jawidMuhammadi your thoughts on this? If you allow then I can open a PR to change this

**Comment by jawidMuhammadi** [comment]
@jawidMuhammadi Sure, go ahead, please.
