### ISSUE TITLE
Unit Test fails for UpdatePasswordPresenterTest

### ISSUE THREAD

**Issue by NiranjanNlc** [openMF/self-service-app#1977]
**Summary:**

In the UpdatePasswordPresenterTest  , one  of the unit test fails under that of method : updateAuthenticationToken

**Steps to reproduce:**

Run the  UpdatePasswordPresenterTest  class , we shall sell the failing result for above mentioned unit tests .

**Expected behaviour:**

All of three unit test should pass .

**Observed behaviour:**

updateAuthenticationToken test fails with the null pointer exception.

**Device and Android version:**

Produced while running unit test on IDE

**Screenshots:**
![image](https://user-images.githubusercontent.com/25600880/224915327-0f23fe57-54eb-496b-a8d9-c534076b7232.png)

**Comment by Sagar0-0** [comment]
Please close this issue, if it is resolved.
