### ISSUE TITLE
Absence of Splash Screen in the app 

### ISSUE THREAD

**Issue by ramya257** [openMF/self-service-app#198]
**Summary:**

This app lacks splash screen which is very useful for preparing any app by making background api calls.

**Steps to reproduce:**
1.Open the app
2.It directly opens the login screen

**Expected behavior:**
There must be a splash screen which can be used to validate the session and check if the user has already logged in or not which can improve the UX by simulating faster loading times.

**Observed behavior:**
As soon as the app is launched,login screen is launched and user need to enter the credentials each time he enters which is quite annoying.

**Device and Android version:**

Xiaomi Redmi Note 4 having Android Marshmallow 6.0

@therajanmaurya i would like to work on this improvement please review !

**Comment by shivamarora96** [comment]
@ramya257  Already Implemented see comments of issue #132

**Comment by ashish05182001** [comment]
@therajanmaurya Can I send a PR for this issue?

**Comment by dilpreet2028** [comment]
I dont think we need to include a splash screen.
@therajanmaurya what do you think?

**Comment by therajanmaurya** [comment]
I don't think we need splash screen, I don't find any use because we don't have OAuth 2 so for now I will put this dicuss off.
