### ISSUE TITLE
Improve UX in LoanAccountSummary

### ISSUE THREAD

**Issue by karsai1993** [openMF/self-service-app#199]
**Summary:**
The UX should be improved.

**Steps to reproduce:**
1, Open LoanAccountSummaryFragment

**Expected behavior:**
The layout should be allowed to be scrolled. All the textfields should be visible fully. The number values should be separated by thousand groups.

**Observed behavior:**
The user cannot scroll in this fragment and cannot read two textfields in portrait mode. That's why we need to create explanation textviews for them. 

**Device and Android version:**
Samsung Ace 3
API 17 - 4.2.2

**Screenshots:**
![loan_summary](https://cloud.githubusercontent.com/assets/15123875/24053985/fdf94760-0b3a-11e7-878a-330d614ebdb1.png)

**Comment by karsai1993** [comment]
The solution is implemented. See attached images.
![imp_sum1](https://cloud.githubusercontent.com/assets/15123875/24054091/50ef1b52-0b3b-11e7-91ed-9d1ec1872dd6.png)
![imp_sum2](https://cloud.githubusercontent.com/assets/15123875/24054092/50f0a0e4-0b3b-11e7-9eab-60a6a5272367.png)

**Comment by dilpreet2028** [comment]
This issue has been fixed
