### ISSUE TITLE
UI of passCodeActivity needs to be revamped

### ISSUE THREAD

**Issue by deecodesss** [openMF/self-service-app#1990]
**Summary:**
When you open the app, passCodeActivity looks odd, it needs to be revamped

**Steps to reproduce:**

open the app>Enter passcode

**Device and Android version:**
Redmi Note 10 pro (Android 12)

**Screenshots:**
![Screenshot_2023-03-15-18-10-17-716_org mifos mobile](https://user-images.githubusercontent.com/116075491/225312515-b921024a-7bdb-463b-9343-ed3ce89de677.jpg)

**Comment by oyehanif** [comment]
i am working on this task.

**Comment by deecodesss** [comment]
hey @oyehanif I'm working on this already

**Comment by deecodesss** [comment]
If I'm not able to do this, I'll lyk. @oyehanif

**Comment by PratyushSingh07** [comment]
hi @deekshatw @oyehanif i have been following mifos's codebase for a while now and the target branch for UI change is  `ui-redesign` .So, whoever is going to open a PR make sure that the branch is correct . Again its upto to the mentors but its better to keep UI changes on a separate branch

**Comment by deecodesss** [comment]
@oyehanif If you want you can work on it.

**Comment by oyehanif** [comment]
@deekshatw Okay i will Work on it!

**Comment by oyehanif** [comment]
@jawidMuhammadi in this screen we use own view library. in this case if it is mandatory then we can use other library. other view no need to redesign this screen. what is your opinion @jawidMuhammadi Sir.

**Comment by oyehanif** [comment]
@jawalmuhammadi sir can i add fingerprint option in this screen if device support finger print. what is your idea about this?

**Comment by PratyushSingh07** [comment]
> @jawalmuhammadi sir can i add fingerprint option in this screen if device support finger print. what is your idea about this?

@oyehanif i already have a PR with finger print authentication , kindly look out for existing PRs and Issues before opening one
