### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by shahnoor-khan** [openMF/self-service-app#1993]
when I was changing the language, the theme and change password title isn't getting translated from English to other languages. I attached the screenshot below which shows that.

![translation](https://user-images.githubusercontent.com/89389741/225379985-4ea221f1-b01a-447b-a848-6925c63dad9b.jpg)

**Comment by shahnoor-khan** [comment]
@jawidMuhammadi I'm new to mifos community. Can I work on this issue and translation related issues across the application?

**Comment by PratyushSingh07** [comment]
Hi @shahnoor-khan I have already opened an issue #1913  which deals with the same

**Comment by shahnoor-khan** [comment]
Hi @PratyushSingh07 I think the translation bug is present across the application and I faced this on different page. I just opened the issue because it's on different screen and highlighting them here make it easy to keep track.

**Comment by PratyushSingh07** [comment]
> Hi @PratyushSingh07 I think the translation bug is present across the application and I faced this on different page. I just opened the issue because it's on different screen and highlighting them here make it easy to keep track.

yes this is indeed present across the app and at the time I had opened the issue no one was really active over here ,hence the issue would feel incomplete to new contributors. However I have been working on this issue simultaneously for a while now , I will be opening a PR by EOW.

**Comment by shahnoor-khan** [comment]
I didn't knew it because it was not assigned to anyone and I thought no one was on it. Are you working on this screen as well ?

**Comment by PratyushSingh07** [comment]
> I didn't knew it because it was not assigned to anyone and I thought no one was on it. Are you working on this screen as well ?

yes,the root cause of the issue is same and I believe changing that will fix its behaviour throughout the app. However if I am unable to complete this task by the end of week then I shall gladly pass this on to you

**Comment by PratyushSingh07** [comment]
Meanwhile I think we should close this issue @shahnoor-khan as this seems redundant and you can just tag me on #1913 in case you need an update

**Comment by shahnoor-khan** [comment]
Okay 👍
