### ISSUE TITLE
Suggestion to Replace Butter Knife with View Binding

### ISSUE THREAD

**Issue by shahnoor-khan** [openMF/self-service-app#1998]
**Summary:**

The application uses Butter knife which is deprecated and can be replaced with View binding as Butter Knife website suggest
( http://jakewharton.github.io/butterknife/ ) and android Gradle plugin 8.0 makes Resources ids non-final by default and its suggest to not to use them as annotations.

**Comment by shahnoor-khan** [comment]
@jawidMuhammadi Are mifos looking to replace Butter Knife with View binding? if yes can I work on this issue? :)

**Comment by jawidMuhammadi** [comment]
@shahnoor-khan Thank you for the suggestion. Yes, we have received many requests to migrate it and we are investigating it, and I think migration from ButterKnife to ViewBinding might require more time and proper testing. So let's keep this issue open until we come to a decision.
