### ISSUE TITLE
Implement thousands separators

### ISSUE THREAD

**Issue by karsai1993** [openMF/self-service-app#200]
**Summary:**
As there are big numbers, thousands separators should be used to make them read easierly.

**Steps to reproduce:**
1, Take a look at any number in the app being bigger than 999.

**Expected behavior:**
Thousands separators should be used: 1,005.55 $

**Observed behavior:**
Thousands separators are not used: 1005.55 $

**Device and Android version:**
Samsung Ace 3
API 17 - 4.2.2

**Screenshots:**
See RepaymentSchedule fragment layout as example:
![repayment_schedule](https://cloud.githubusercontent.com/assets/15123875/24054443/899678d2-0b3c-11e7-8216-c06b506a5611.png)

**Comment by karsai1993** [comment]
The implementation is done. It is the outcome, shown in case of fragment above, but it is implemented to the whole app.
![imp_repayment_schedule](https://cloud.githubusercontent.com/assets/15123875/24054502/c32f9164-0b3c-11e7-8060-6f3fde230d09.png)

**Comment by dilpreet2028** [comment]
@therajanmaurya  As currency formatting is different for some countries so NumberFormat class could be used for performing this task .
