### ISSUE TITLE
Unable to build app using android studio

### ISSUE THREAD

**Issue by vladimirfomene** [openMF/self-service-app#203]
**Summary:**

I cannot run the app on my phone or the emulator because android studio cannot resolve the DaggerApplicationComponent because the com.mifos.mifosxdroid.injection.component.DaggerApplicationComponent does not exist.

**Steps to reproduce:**

Download the codebase and try to build the app using android studio

**Expected behavior:**

I expected the com.mifos.mifosxdroid.injection.component to have code 
for the DaggerApplicationComponent.

**Observed behavior:**

There is no DaggerApplicationComponent code at com.mifos.mifosxdroid.injection.component

**Device and Android version:**

**Screenshots:**
![screenshot from 2017-03-17 22-06-54](https://cloud.githubusercontent.com/assets/11140070/24064922/4f173e1c-0b5f-11e7-9d88-c7a6f1ff4302.png)

**Comment by ghost** [comment]
@vladimirfomene i think you did something wrong while building app or downloading code base, actually DaggerApplicationComponent present in code base
![screenshot 63](https://cloud.githubusercontent.com/assets/14215902/24065280/d9be864e-0b8f-11e7-9af7-2d6545a2b6a8.png)
Just try to re-download the project and rebuild it
