### ISSUE TITLE
Improve UX for Loan Account Details

### ISSUE THREAD

**Issue by vladimirfomene** [openMF/self-service-app#206]
**Summary:**

When I turn my phone in landscape mode, part of the content of this activity is cut off. I was expecting it to give me the ability to scroll down.

**Steps to reproduce:**

Go to the Loan Account Details page. Make sure your phone's orientation option is in Auto-rotate. Then hold your phone in landscape mode.

**Expected behavior:**

To have a scroll option for this activity that allows me to scroll through the content.

**Observed behavior:**

When I turned my phone in landscape mode, part of the content was cut off because my phone screen is too small to accomodate all the content.

**Device and Android version:**
Alcatel Pop4 Plus
Android version 6.0.1

**Screenshots:**
![screenshot_20170318-094120](https://cloud.githubusercontent.com/assets/11140070/24071145/3654b878-0bc3-11e7-8de9-1ccd6156215a.png)

**Comment by therajanmaurya** [comment]
fix in #207
