### ISSUE TITLE
App theme doesn't change when we change the main mobile theme

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2068]
**Summary:**

App theme remains set to the one defined in the settings section and doesn't change with the main mobile theme

**Steps to reproduce:**

Try to change the main mobile theme and then see the behaviour

**Expected behaviour:**

App theme should have changed wrt the main mobile theme

**Observed behaviour:**

https://user-images.githubusercontent.com/90026952/227758208-8f6e153a-88db-48c0-a54a-115151ca3088.mp4

**Device and Android version:**
Device : Samsung M11
Version : 11

**Comment by PratyushSingh07** [comment]
i am currently working on this issue

**Comment by RobustMj** [comment]
> i am currently working on this issue

are you still working?

**Comment by PratyushSingh07** [comment]
yes @RobustMj

**Comment by Harsh0707005** [comment]
Is it resolved?
I want to work on it

**Comment by PratyushSingh07** [comment]
It hasnt been resolved , you can work on it

**Comment by srishti-R** [comment]
This issue needs fixes in ui-library.

**Comment by PratyushSingh07** [comment]
Feel free to solve them if you want @srishti-R

**Comment by srishti-R** [comment]
@PratyushSingh07 is that library actively maintained if I create a PR there?

**Comment by PratyushSingh07** [comment]
I'm not really sure of that. However you can pick up issues from this repository, we are trying to actively maintain this project among other android projects in this organisation

**Comment by pranavkonidena** [comment]
I think this issue has been fixed, the app is changing into dark mode on change in settings. So, please close this issue

**Comment by PratyushSingh07** [comment]
@pranavkonidena I can still replicate this issue.
