### ISSUE TITLE
Screen freezes while selecting the loan product

### ISSUE THREAD

**Issue by NiranjanNlc** [openMF/self-service-app#2087]
**Summary:**

 While we select the Loan Product on Loan Application section , It seems that  the screen is freeze for the moment of time 

**Steps to reproduce:**

- From Home , tap "Apply for Loan" .
- Under select loan product ,select any of the product

**Expected behaviour:**

We can smoothly fill up the Loan Application Form without any glitch.

**Observed behaviour:**

When we select any of the product , it seems that the screen is freezed upon for the moment of time .

**Device and Android version:**

Redmii 9A, Android 10 

**Screenshots:**

https://user-images.githubusercontent.com/25600880/229477726-318fc482-88fb-4d03-b39d-677bb10771c5.mp4

**Comment by Harsh0707005** [comment]
Is this issue resolved?
I want to work on it

**Comment by amanjn38** [comment]
Is this issue resolved?
I want to work on it

**Comment by NiranjanNlc** [comment]
hi @amanjn38 , it has not been resolved yet and i have not given look to it . Please go and raise the PR for it . Thanks

**Comment by amanjn38** [comment]
@NiranjanNIc , when I am trying to login into the app, I am getting this exception 
 javax.net.ssl.SSLHandshakeException: Chain validation failed....
java.security.cert.CertificateExpiredException: Certificate expired at Tue Sep 05 17:24:23 GMT+05:30 2023 (compared to Sun Sep 24 12:34:46 GMT+05:30 2023)

Can you please update and renew the SSL certificate. Or let me know if I am making any mistake.

**Comment by NiranjanNlc** [comment]
> @NiranjanNIc , when I am trying to login into the app, I am getting this exception javax.net.ssl.SSLHandshakeException: Chain validation failed.... java.security.cert.CertificateExpiredException: Certificate expired at Tue Sep 05 17:24:23 GMT+05:30 2023 (compared to Sun Sep 24 12:34:46 GMT+05:30 2023)
> 
> Can you please update and renew the SSL certificate. Or let me know if I am making any mistake.

@jawidMuhammadi  would have a look on this issuse ......

**Comment by amanjn38** [comment]
@jawidMuhammadi Please let me know when this is resolved, I will continue working on the issue. Thank you in advance .

**Comment by SekhGulamMainuddin** [comment]
I guess this issue has been solved.

**Comment by PratyushSingh07** [comment]
were any of you able to reproduce this issue ?

**Comment by SekhGulamMainuddin** [comment]
@PratyushSingh07 this issue has been fixed.
I checked it and didn't found this issue anymore
