### ISSUE TITLE
back button doesn't work from the settings

### ISSUE THREAD

**Issue by gururani-abhishek** [openMF/self-service-app#2089]
**Summary:**

When back button button is pressed or back gesture is made from the settings nothing happens

**Steps to reproduce:**

Go to settings and try pressing the back button.

**Expected behaviour:**

On pressing back or making back gesture, the user should be redirected to the Home Screen.

**Observed behaviour:**

nothing happens on pressing back button/ or making back gesture.

**Device and Android version:**

Pixel 2

**Screenshots:**

https://user-images.githubusercontent.com/59947871/229713455-ce100896-f0fc-41e9-895e-29b18ad64a0b.mp4

**Comment by gururani-abhishek** [comment]
I'm working on this

**Comment by Mia0451** [comment]
hello, I am trying to contribute. 
one side question, are you guys using a testing-account to login into the app when do the local development, how do you get a testing account?

**Comment by PratyushSingh07** [comment]
@Mia0451 have you tried : 
username: mifos
password: password

**Comment by gururani-abhishek** [comment]
> 

Hey Mia, glad that you're trying to contribute to Mifos. 
To log-in for testing purposes use the credentials that @PratyushSingh07 provided, and if possible [join our slack channel](https://bit.ly/mifos-slack).
Also feel free to hit me up if you have other issues regarding contributing to Mifos(email : gururani.abhishek@gmail.com)

**Comment by menotnandan** [comment]
Hey, @PratyushSingh07 @gururani-abhishek  is this credential only for the emulator inside the Android studio, like when we run the code?
cause it's not working on my phone! I installed the latest version from the releases!
can you help me out with this? it will be a lot easier to track issues on the phone

**Comment by PratyushSingh07** [comment]
hi @NandanUpadhyay2611 , this should work outside the emulator as well , I have been doing the same since the last 3 months and it has worked for me everytime. 
What is the output in your logcat? Mind sharing it with us?

**Comment by menotnandan** [comment]
logcat? sorry!  I am talking about when I am trying to login into my phone! the app which I installed from releases! Help me if I am wrong somewhere? @PratyushSingh07

**Comment by gururani-abhishek** [comment]
Hi @NandanUpadhyay2611, what Pratyush meant was that if you're building the app by cloning the development branch in your Android Studio then the credentials(username : mifos, password : password) would work.
