### ISSUE TITLE
App crashes when selecting Repayment Schedule

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2096]
**Summary:**

App crashes when selecting Repayment Schedule in the loan account details

**Steps to reproduce:**

- Click on Accounts in the Home activity
- Go to the `Loan` tab
- select an active loan
- click on `Repayment Schedule`

**Expected behaviour:**

The appropriate menu should have been inflated

**Observed behaviour:**

App crashes when the above mentioned option is selected

https://user-images.githubusercontent.com/90026952/230626214-8aeb4a28-c063-4e14-b4da-0f50220a2ad4.mp4

**Device and Android version:**

Device : Samsung M11
Android: 11

**Comment by PratyushSingh07** [comment]
I am currently working on this

**Comment by gururani-abhishek** [comment]
Hey @PratyushSingh07 I came across this [while investigating this](https://github.com/openMF/mifos-mobile/issues/1354#issuecomment-1480143242).

**Comment by gururani-abhishek** [comment]
Was about to make a PR, but glad you've already made one. If you'd only give just one extra attribute(layout_width = "wrap_content") that should fix this too. Do check it out.

**Comment by PratyushSingh07** [comment]
> Was about to make a PR, but glad you've already made one. If you'd only give just one extra attribute(layout_width = "wrap_content") that should fix this too. Do check it out.

Hey @gururani-abhishek I did want to set it to wrap content but the style had already defined it as 1 dp and so I didn't want to change that

**Comment by gururani-abhishek** [comment]
> > Was about to make a PR, but glad you've already made one. If you'd only give just one extra attribute(layout_width = "wrap_content") that should fix this too. Do check it out.
> 
> Hey @gururani-abhishek I did want to set it to wrap content but the style had already defined it as 1 dp and so I didn't want to change that

style had already defined it? I guess I'm missing something, would love to be clarified.

**Comment by PratyushSingh07** [comment]
![image](https://user-images.githubusercontent.com/90026952/230670557-97c5fccb-29ae-41cc-b357-b0cb3d5ce51c.png)

Here @gururani-abhishek

**Comment by PratyushSingh07** [comment]
closing this as completed
