### ISSUE TITLE
Repayment schedule is hardly readable when the app is in dark mode

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2098]
**Summary:**

The texts in `Repayment schedule` are hardly readable when the app is in dark mode 

**Steps to reproduce:**

- open `Repayment Schedule` while the app is in dark mode

**Observed behaviour:**
<img src="https://user-images.githubusercontent.com/90026952/230674115-bdc65fa2-2cb2-48a1-a730-1b3b1a298bab.jpeg" height=620>

**Device and Android version:**

Device : Samsung M11
Android: 11

**Comment by PratyushSingh07** [comment]
Hey @jawidMuhammadi can we add `Good First Issue` label over here so that it can help first time contributors to get an open source footprint

**Comment by tanmaySinha16** [comment]
Repayment schedule screen is crashing. How to reproduce?

**Comment by PratyushSingh07** [comment]
You can check out the PR #2097 . Make the changes mentioned in this PR and then do the necessary changes. 
But make sure once you open a PR do not push the files mentioned in the above PR as it will be ambigous

**Comment by SekhGulamMainuddin** [comment]
I have made pull request solving the Issue #2097 and #2098. Please have a look at my PR #2137 @jawidMuhammadi @PratyushSingh07

**Comment by SekhGulamMainuddin** [comment]
Fixed issues #2097 and #2098 . Please have a look at my PR #2138 @jawidMuhammadi @PratyushSingh07

**Comment by kartik9417** [comment]
I will work on this issue

**Comment by SekhGulamMainuddin** [comment]
> I will work on this issue
This issue has already been fixed in PR #2101

**Comment by PratyushSingh07** [comment]
Hey @SekhGulamMainuddin repayment schedule is still unreadable in dark mode

**Comment by SekhGulamMainuddin** [comment]
ok @PratyushSingh07

**Comment by ayush290104** [comment]
Is this issue still unsolved?? I can work on this issue??

**Comment by PratyushSingh07** [comment]
yes @ayush290104 , you can work on this

**Comment by ayush290104** [comment]
@PratyushSingh07 sir, can u once see to issue 2184

**Comment by LORDhariwansh** [comment]
@jawidMuhammadi can u assign this issue to me so i can work on it.

**Comment by PratyushSingh07** [comment]
> @jawidMuhammadi can u assign this issue to me so i can work on it.

hey @LORDhariwansh i think @ayush290104 is already working on it .

**Comment by LORDhariwansh** [comment]
Hi @PratyushSingh07 I am reaching out to inquire about  open source contribution opportunities within your organization. I am particularly interested in contributing to your organization's initiatives.  
I know "Java & Android studio".
I want to know your organisations use of which technology & what resources are resources to learn that . So I can start contributing to the org.

**Comment by PratyushSingh07** [comment]
kindly refer the wiki section

**Comment by LORDhariwansh** [comment]
@jawidMuhammadi  assign this task to me

**Comment by ayush290104** [comment]
@PratyushSingh07, can you tell how to replicate this issue, it will be better if you could elaborate.

**Comment by Niranjan029** [comment]
is these issue is still open ?
