### ISSUE TITLE
In apply for loan screen the soft keyboard doesn't exit on background tap.

### ISSUE THREAD

**Issue by gururani-abhishek** [openMF/self-service-app#2103]
**Summary:**

In apply for loan screen the soft keyboard doesn't exit on background tap. This slows down the User Experience. 

**Steps to reproduce:**

While on "Apply for Loan" screen and typing using the soft keyboard tap anywhere on the screen. 

**Expected behaviour:**

Soft Keyboard should exit when tapping on the background.

**Observed behaviour:**

Soft Keyboard didn't exit.

**Device and Android version:**

pixel 2

**Screenshots:**

https://user-images.githubusercontent.com/59947871/230789677-22c7927d-04c0-4d2e-b542-9eae9325603f.mp4

**Comment by gururani-abhishek** [comment]
I'm working on this

**Comment by PratyushSingh07** [comment]
hey @gururani-abhishek wouldnt it be better to open one issue to deal with soft screen keyboard for the entire app ? In this way you can solve all of them at once and you wouldn't need to open separate issues for everyone

**Comment by gururani-abhishek** [comment]
Pretty Legit @PratyushSingh07, I raised them individually because I kinda feared if I'll increase the footprint to a lot of screens, then it might conflict with the other upcoming PRs. But thanks, got your point.

**Comment by PratyushSingh07** [comment]
> Pretty Legit @PratyushSingh07, I raised them individually because I kinda feared if I'll increase the footprint to a lot of screens, then it might conflict with the other upcoming PRs. But thanks, got your point.

Agreed , but if you decide in favour of individual issues then you can ask the mentor to add some `Good First Issues` tag. In this way it will allow newcomers to get some open source footprint . I hope you get what I am trying to convey
