### ISSUE TITLE
Unable to login after clicking on the cancel button 

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2104]
**Summary:**

In the passcode page when I click on the cancel button the dialog box is disappears but at the same time the correct passcode is also deemed incorrect and the user is unable to login with the passcode

**Steps to reproduce:**
- select the `Forgot Passcode, Login Manually` in the passcode page
- click on `cancel` when the dialogue box appears
- now try to enter the correct passcode

**Expected behaviour:**

- user should have been allowed to login after entering the correct passcode

**Observed behaviour:**

https://user-images.githubusercontent.com/90026952/230793471-506660f7-6039-42be-81c4-80d9773d3dac.mp4

**Device and Android version:**
Device : Samsung M11
Android : 11

**Comment by PratyushSingh07** [comment]
I will be working on this

**Comment by vyukti13** [comment]
@PratyushSingh07 
Can I work on this issue

**Comment by PratyushSingh07** [comment]
sure, go ahead @vyukti13
