### ISSUE TITLE
Unexpected Biometric Prompt when changing the app theme

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2106]
**Summary:**

When i try to change the app theme from the settings then I am met with an unexpected biometric prompt 

**Steps to reproduce:**
- Go to `settings`
- Click on `theme`
- change the theme 

**Expected behaviour:**
- No such biometric prompt should have popped up

**Observed behaviour:**

https://user-images.githubusercontent.com/90026952/230835964-a131ada1-85f1-4b6d-a024-76e051f3a520.mp4

**Device and Android version:**

Device: Samsung M11
Android: 11

**Comment by PratyushSingh07** [comment]
I will fix this as well

**Comment by ayush290104** [comment]
@PratyushSingh07 are u working on this is this solved??

**Comment by PratyushSingh07** [comment]
Not right now, you can go ahead with this issue

**Comment by ayush290104** [comment]
@PratyushSingh07 can u see if this issue still exists as i can't replicate this. If not, then you can close this issue.

**Comment by PratyushSingh07** [comment]
I checked this rn, this issue is persistent

**Comment by ayush290104** [comment]
Ha I also could replicate it.

**Comment by ayush290104** [comment]
@PratyushSingh07, do you have any idea what could have caused this problem. As theme changing part seems to be correct.
