### ISSUE TITLE
Implement one time login for a user 

### ISSUE THREAD

**Issue by kunalsingh3110** [openMF/self-service-app#211]
User has to enter his username and password each time he opens the app.

**Comment by kunalsingh3110** [comment]
@therajanmaurya  i will love to fix this and implement logout for each user .

**Comment by shivamarora96** [comment]
@beast-incarnate  check out issue #132 its already under process.

**Comment by dilpreet96** [comment]
@therajanmaurya this issue is not relevant.

**Comment by dilpreet2028** [comment]
Issue already exists regarding this #132
