### ISSUE TITLE
Api Endpoint has been modified

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2110]
**Summary:**

API endpoint has been changed to `demo.mifos.io` 

Below Response in the case of earlier endpoint
![image](https://user-images.githubusercontent.com/90026952/232239766-1867161e-b729-45d9-84e6-c594f0861d32.png)

Below Response in the case of modified endpoint
![image](https://user-images.githubusercontent.com/90026952/232239938-77ca194b-8478-4126-b737-c89e5d772335.png)

**Comment by gururani-abhishek** [comment]
Good Afternoon @PratyushSingh07, you can take it down now, the issue was with backend and it has been fixed after I nudged backend guys a little. XD.

**Comment by hghost50** [comment]
Hello, i can't login using my local server domain name, it displays this error: Error During logging

**Comment by PratyushSingh07** [comment]
Hello @hghost50 can you share your BaseURL.kt file

**Comment by hghost50** [comment]
What i did, was binding my local IP to my custom domain name in Ubuntu 18.04, but unfortunate i can't logging to the Mifos-mobile app. But i can use this custom domain name to access the Mifos x community and the web app. Kindly review this.
