### ISSUE TITLE
Currency symbol isn't visible 

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2126]
**Summary:**

The currency symbols in the loan charges are shown as `?` instead of the symbol that was supposed to be there

**Steps to reproduce:**

- Click on any List item in the Loan section
- Click on Loan Charges

**Expected behaviour:**

Appropriate symbol should be displayed instead of `?`

**Observed behaviour:**

![WhatsApp Image 2023-04-28 at 01 44 11](https://user-images.githubusercontent.com/90026952/234981447-5d126952-d7e6-4593-927d-b3f70fe74976.jpeg)

**Device and Android version:**

Device : Samsung M11
Android : 11

**Comment by tanmaySinha16** [comment]
I want to work on this issue.
@PratyushSingh07   Can you pls guide me how to make my first contribution.

**Comment by PratyushSingh07** [comment]
sure, go ahead
steps :
- Fork the repo
- clone the forked repo in your local system
- make a branch using the command `git checkout -b <your branch name>`
- make the changes 
- then `git add .`
- `git commit -m <your-message>`
- `git push origin <your branch name>`
- then open a PR from your repo

**Comment by PratyushSingh07** [comment]
You can also try issue #2098 . Follow the same steps mentioned above

**Comment by tanmaySinha16** [comment]
Thank you 
But as I am new to the community I don't know how to register in mifos and how to get an account number.Can you please help me out?

**Comment by PratyushSingh07** [comment]
The credientials for login are: 
Username : mifos
Password: password

If you open the `BaseURL.kt` file , you would see that the API_ENDPOINT is "demo.mifos.community" . However , you can also change the API_ENDPOINT to "demo.mifos.io" to get a different data in comparison to the previous endpoint

**Comment by hghost50** [comment]
Can i change this API_ENDPOINT, to my own domain name in my local server?

**Comment by vyukti13** [comment]
@PratyushSingh07  is this issue resolved. If not can I work on this

**Comment by PratyushSingh07** [comment]
I am not sure if you would be able to replicate this issue now since there have been some changes in the backend. But if you are able to replicate this issue then by all means please go ahead.

**Comment by vyukti13** [comment]
Yes I checked it, but in my emulator the currency symbol is visible. I think this issue no longer exist.
@PratyushSingh07 could you please suggest me any other issue to work on.
