### ISSUE TITLE
Login screen displaying wrong Toast message

### ISSUE THREAD

**Issue by aj019** [openMF/self-service-app#213]
**Summary:**

While logging i used username: mifos and password: password rather than username: selfservice and password: Password@123. On clicking login first i got a Toast "Welcome Mifos" and then i got a Toast "Failed to load client"

**Steps to reproduce:**

1) Open the app
2) Use username: mifos and password: password
3) Click on login button

**Expected behavior:**

The message should be "Failed to authenticate" since it is wrong credentials

**Observed behavior:**

On clicking login first i got a Toast "Welcome Mifos" and then i got a Toast "Failed to load client"

**Device and Android version:**

Nexus 5 API 23

**Screenshots:**
![mifos](https://cloud.githubusercontent.com/assets/7893859/24074242/dd51d522-0c2a-11e7-879a-4a19270487f8.gif)

**Comment by chaitanyaparashar** [comment]
I would work on this issue

**Comment by imGurpreetSK** [comment]
Is anyone working on this?

**Comment by dilpreet2028** [comment]
@GurpreetSK95 You can go ahead
