### ISSUE TITLE
remove the menuitem from Saving Account transaction Activity

### ISSUE THREAD

**Issue by itsamitgoel** [openMF/self-service-app#218]
**Summary:**
Remove the menuitem from Saving Account transaction Activity as we are already in transaction activity. We dont need the "transaction" menuitem

**Steps to reproduce:**
1. Goto saving account transaction activity 
2. click on the three dots present in the action bar

**Expected behavior:**
there should be no menu item in this activity as we are already in saving account transaction activty

**Observed behavior:**
we can see a menu item "Transactions" in the saving account transaction activity.There is no need of it as we are already in the transactions activity

**Device and Android version:**

Xiaomi redmi prime 2  android 5.1.1

**Screenshots:**

![screenshot_2017-03-21-13-10-51-312_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16203080/24144552/b0a7ce52-0e53-11e7-9d9d-4819881b768a.png)

**Comment by itsamitgoel** [comment]
@therajanmaurya i would like to work on this

**Comment by puneetkohli521** [comment]
@itsamitgoel resolve it and submit a pr. The option would have been copied by mistake.

**Comment by karsai1993** [comment]
@itsamitgoel I reported this bug 9 days ago and gave a solution too. See issue #189 . In the description: "2, Make option menu button disabled as we are currently in the fragment which that menu option button would open." PR (#208) was sent some days ago but a question is poped up and I am waiting for response on that.

**Comment by dilpreet2028** [comment]
This issue has already been fixed.
@therajanmaurya
