### ISSUE TITLE
Making it more user convinient

### ISSUE THREAD

**Issue by ayush290104** [openMF/self-service-app#2183]
**Summary:**
Toast message should be user friendly.

**Steps to reproduce:**
While logging in if incorrect credentials are entered.

**Expected behaviour:**
A simpler toast message should appear.

**Observed behaviour:**
A toast talking about invalid authentication request to api appears which might not be confusing for a user.
**Device and Android version:**

I am using it on Iqoo z3 android 12 on the pre-installed funtouch OS.

**Screenshots:**'
It does not allow me to take screenshots.

**Comment by ayush290104** [comment]
I am a beginer in open source and i want to learn how to contribute can you please guide me

**Comment by PratyushSingh07** [comment]
hey @ayush290104 this exact same issue has been addressed here https://github.com/openMF/mifos-mobile/issues/1986

To start off with the contribution : 
- Fork this `https://github.com/openMF/mifos-mobile` 
- Clone the forked repository in your local system 
- Create a branch using the command `git checkout -b <your-branch-name>`
- Make the necessary changes on this branch
- After the changes , add them using `git add .`
- commit them using `git commit -m "<your-message>"`
- push them using `git push origin `<your-branch-name>`
- Then on your github you find and option for `Compare & Open Pull Request`
- Finally click on `Create Pull Request`

So, I would ask you to close this issue and look at the issue that I have referenced here .
