### ISSUE TITLE
Skipping passcode

### ISSUE THREAD

**Issue by ayush290104** [openMF/self-service-app#2191]
**Summary:**
After login if I skip passcode and next time, I open the app I am not logged in.

**Steps to reproduce:**
Login to your account and skip the passcode.
Now close the app and open again.

**Expected behaviour:**
Even after skipping passcode, we should be kept login.

**Observed behaviour:**
I got logged out.

**Device and Android version:**
Device - Iqoo Z3
Android 13
On stock rom by company.
Screen Recording ->

https://github.com/openMF/mifos-mobile/assets/116818222/68fe2116-d881-4281-9087-105412aba283

**Comment by ayush290104** [comment]
@PratyushSingh07 can you see once if I can work on this

**Comment by PratyushSingh07** [comment]
This isn't an issue, after the skipping the passcode you should be redirected to login again. 
Passcode is used to provide an additional layer of security to our application.

**Comment by ayush290104** [comment]
@PratyushSingh07 
But in apps like paytm if we don't add passcode it doesn't ask for login everytime.

**Comment by PratyushSingh07** [comment]
This isn't exactly an app like paytm right? This issue deals with the security of the app and thus you need to take it up with the developers before you start working on it. I personally do not see this as an issue

**Comment by ayush290104** [comment]
okay understood.
