### ISSUE TITLE
Bug: App crashes when submit button is clicked in ApplyForLoan activity with no internet connection

### ISSUE THREAD

**Issue by itsamitgoel** [openMF/self-service-app#220]
**Summary:**
Bug: App crashes when submit button is clicked in ApplyForLoan activity with no internet connection

**Steps to reproduce:**
1. Log in the app
2. Goto Loan fragment
3. Turn off the internet connection.
4. goto "apply for loan" in the action bar(menu)
5. Click the submit button
6. the app crashes.

**Expected behavior:**
app should not crash on clicking submit button. Rather it should display some snackbar when no internet connection

**Observed behavior:**
app crashes on clicking submit button

**Device and Android version:**
Android 5.1.1  xiaomi redmi prime2

**Screenshots:**
.

**Comment by itsamitgoel** [comment]
@therajanmaurya i would like to fix this

**Comment by dilpreet96** [comment]
@therajanmaurya issue was fixed in #300 but validations for principal amount will be added.

**Comment by dilpreet2028** [comment]
Issue fixed in #300
