### ISSUE TITLE
UI Improvement in loan account details activity

### ISSUE THREAD

**Issue by itsamitgoel** [openMF/self-service-app#221]
**Summary:**
UI Improvement in loan account details activity. Whenever we click any item with orange/blue dot in loan fragment, we see imageview and textview overlapping in loan account details activity.

**Steps to reproduce:**
1. goto loan fragment
2. click any item in the list with a orange/blue dot
2. Imageview and textview overlap each other making it difficult to read.

**Expected behavior:**
imageview ans textview clearly visible

**Observed behavior:**
Imageview and textview not clearly visible.

**Device and Android version:**
redmi prime 2  Android 5.1.1

**Screenshots:**
![screenshot_2017-03-21-13-28-31-831_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16203080/24162790/983cd75a-0e8e-11e7-83ce-cbb5247d60a4.png)
![screenshot_2017-03-21-23-21-41-564_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16203080/24162789/983c4cfe-0e8e-11e7-8bb7-0cba651dcf65.png)

**Comment by itsamitgoel** [comment]
@therajanmaurya  i would like to work on this

**Comment by dilpreet2028** [comment]
This issue was fixed
