### ISSUE TITLE
Filter Button in Saving Account Transactions is invisible. 

### ISSUE THREAD

**Issue by gururani-abhishek** [openMF/self-service-app#2210]
**Summary:**

Due to its colour the filter button in Saving Account Transactions under Account is invisible.

**Steps to reproduce:**

HomeScreen -> Accounts -> click on any account -> go to Transactions -> tap on the the top right 

**Expected behaviour:**

Filter button should be visible

**Observed behaviour:**

Filter button is invisible

**Device and Android version:**

Google Pixel 2

**Screenshots:**

![Screenshot_20230716-015408](https://github.com/openMF/mifos-mobile/assets/59947871/6544cc81-b29f-4683-a41f-86b2ed05649e)

**Comment by gururani-abhishek** [comment]
if someone wants to pick it up, have a look at this PR : #2177

**Comment by gururani-abhishek** [comment]
Nobody picked it up, so I'll push the code for this today.

**Comment by vyukti13** [comment]
@gururani-abhishek  is this issue fixed. If not I want to work on it

**Comment by gururani-abhishek** [comment]
> @gururani-abhishek is this issue fixed. If not I want to work on it

I've already submitted a PR that fixes the issue.
