### ISSUE TITLE
User cannot select currency in the Apply for Loan fragment.

### ISSUE THREAD

**Issue by AbhilashG001** [openMF/self-service-app#223]
**Summary:**

User cannot select the currency in the Apply for Loan fragment. The user should be able to select a currency for a Loan Product.

**Steps to reproduce:**

Step 1) Open the self service app.
Step 2) Select the Loan tab in home screen.
Step 3) Tap on the menu anchored to the overflow button at the top-right corner and select "Apply for Loan".
Step 4) Tap on the currency field.

**Expected behavior:**

The app should display a list of currencies to choose form.

**Observed behavior:**

Currently, the user cannot select a currency.

**Device and Android version:**

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**GIF:**

![videotogif_2017 03 22_10 18 19](https://cloud.githubusercontent.com/assets/20839661/24182670/378fc4c0-0ee9-11e7-94ef-d724f8437fb0.gif)

**Comment by AbhilashG001** [comment]
I would like to work on this issue.

**Comment by dilpreet2028** [comment]
Currency is automatically fetched from the loan template and depends on the Loan product(productId) you choose so it cannot be changed.
@therajanmaurya this issue is not relevant
