### ISSUE TITLE
On exiting the application, it goes to passcode activity.

### ISSUE THREAD

**Issue by ayush290104** [openMF/self-service-app#2259]
**Summary:**
on clicking back button in home activity app navigates to the passcode activuty.

**Steps to reproduce:**

How can we reproduce the issue?
1- Go to the homepage activity.
2- Try exiting the application.
 
**Expected behaviour:**
We should simply get exited from the app.

**Observed behaviour:**
It went to passcode activity.
https://github.com/openMF/mifos-mobile/assets/116818222/2ea2df11-23e7-433e-bbf7-0dc266950060

**Device and Android version:**
Device Vivo IQOO z3
Android version 13

**Comment by shreyanshR7** [comment]
please assign this issue to me I want to work on this issue.

**Comment by PratyushSingh07** [comment]
Are you done with this issue @ayush290104 ? If you aren't working on this then I would like to take this up

**Comment by ayush290104** [comment]
@vyukti13 said that his pr solves issue but he didn't merge it yet.

**Comment by PratyushSingh07** [comment]
I am not sure which PR/issue are refering to but my latest PR #2307 fixes this issue as well as issue #2106

**Comment by ayush290104** [comment]
Did you merge that pr

**Comment by PratyushSingh07** [comment]
I have just opened #2307

**Comment by Miteshhsingla** [comment]
hey! i would like to take up this issue, i believe that there's some issue in lifecycle method of particular activity you're using, would love to work upon this. Regards.

**Comment by PratyushSingh07** [comment]
Hi @Miteshhsingla , I have already solved this issue

**Comment by Miteshhsingla** [comment]
Alright!

**Comment by Harsh0707005** [comment]
This issue has been resolved.
Kindly close the issue

**Comment by PratyushSingh07** [comment]
this issue has been resolved @ayush290104 . please close it
