### ISSUE TITLE
Color of buttons on Transfer activity is not following google material guidelines according to UI.  Make button color primary 

### ISSUE THREAD

**Issue by itsamitgoel** [openMF/self-service-app#230]
**Summary:**
Color of buttons on Transfer activity is not following google material guidelines according to UI.  WE have to make button color primary.
![screenshot_2017-03-23-03-59-53-410_org mifos selfserviceapp](https://cloud.githubusercontent.com/assets/16203080/24223708/670af7da-0f7d-11e7-8c31-c267daf89446.png)

**Comment by itsamitgoel** [comment]
@therajanmaurya i would like to fix this

**Comment by dilpreet2028** [comment]
fixed in #329
