### ISSUE TITLE
on exiting the registration page it shows continue and cancel....

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#2337]
**Summary:**
on clicking back on the registration page...it shows continue and cancel its confusing 

**Steps to reproduce:**

How can we reproduce the issue?

**Expected behaviour:**

just have yes or no according to the above statement!

**Observed behaviour:**

 continue and cancel 

**Device and Android version:**
pixel 5 and android 11

**Screenshots:**

![Screenshot (2)](https://github.com/openMF/mifos-mobile/assets/136256522/81a8f36b-2c75-45bf-82bc-a117db78e5f2)

**Comment by ghost** [comment]
I am going to work on this...I can solve it

**Comment by Harsh0707005** [comment]
Issue has been resolved.
Kindly close the issue

**Comment by ghost** [comment]
@Harsh0707005  when was the issue resolved...?
