### ISSUE TITLE
app crash while login

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#2343]
**Summary:**

When I try to log in with the default credentials, the app immediately closes (crashes).

**Steps to reproduce:**

Simply log in after installing the app on your device.

**Expected behaviour:**

The app should not close, and the user should be able to log in easily.

**Device and Android version:**

Redmi Note 8 pro 
Android Version : 11

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/91174350/8eb5c688-0d0d-46e0-8ae8-25bdf2f9d5b5

**Comment by PratyushSingh07** [comment]
Hi @nayeemdv , the reason the app is crashing is because the SSL certificate has expired. This has already been notified to the concerned party and they will resolve it soon.

**Comment by ghost** [comment]
Ok @PratyushSingh07 , should I close this issue?

**Comment by Thanush66** [comment]
@nayeemdv please close the issue it will automatically resolve...when the SSL certificate issue is resolved..

**Comment by PratyushSingh07** [comment]
@nayeemdv please do not close the issue until resolved or asked by the mentor. 
Please reopen this issue so that any newcomer would get to know of this

**Comment by Tejas-67** [comment]
Hey @PratyushSingh07 I would like to work on this issue if still open.

**Comment by PratyushSingh07** [comment]
> Hi @nayeemdv , the reason the app is crashing is because the SSL certificate has expired. This has already been notified to the concerned party and they will resolve it soon.

@Tejas-67

**Comment by PratyushSingh07** [comment]
@nayeemdv the issue has been resolved. You can now close this !! 

Demo credentials are : 
Username: mifos
Password: password
