### ISSUE TITLE
Toolbar title says Transfer when opening Deposit

### ISSUE THREAD

**Issue by aj019** [openMF/self-service-app#235]
**Summary:**

In saving account details if we click on deposit button a new activity opens in which the toolbar title is Transfer instead of Deposit.

**Steps to reproduce:**

1) Open the app
2) Go To savings 
3) Choose any saving
4) From the saving details
5) Click on Deposit

**Expected behavior:**

The app should either open an activity with the toolbar title "Deposit" or if the Activity is not present then it should simply give a Toast Deposit clicked.

**Observed behavior:**

If we click on deposit button a new activity opens in which the toolbar title is Transfer instead of Deposit.

**Device and Android version:**

Nexus 5 API 23

**Screenshots:**

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/7893859/24233817/90ae7bc4-0fba-11e7-9b19-b00be9971d4d.gif)

**Comment by aj019** [comment]
I would like to work on this issue.

**Comment by dilpreet2028** [comment]
@therajanmaurya  PR already merged, closing issue
