### ISSUE TITLE
App crashes when selecting Guarantor Type

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2356]
**Summary:**

App crashes when we try to add a guarantor 

**Steps to reproduce:**

- Go to Accounts
- Switch over to Loan Section
- Click on a loan to move to Loan Account Details
- Click on 3 vertical dots & then click on View Guarantor
- Try adding a guarantor with type either `choicea` or `choiceB`

**Expected behaviour:**

Guarantor should have been added with the specified details

**Observed behaviour:**

Guarantor isnt added and we move out of the guarantor screen
## This is to be noted that this behaviour is observed only when I choose either  `choicea` or `choiceB` . It works perfectly for rest of the `Gurantor Type`

https://github.com/openMF/mifos-mobile/assets/90026952/4bb4aebc-d899-4f6d-a9f5-1561f822f427

**Device and Android version:**

Device: Pixel 7
Android: 13

**Comment by SekhGulamMainuddin** [comment]
Hi @PratyushSingh07 can you assign me this issue. I want to work on this issue.

**Comment by PratyushSingh07** [comment]
sure , go ahead

**Comment by SekhGulamMainuddin** [comment]
Hi @PratyushSingh07 I have solved the issue, but can you specify the usage of choicea and choiceB options in Guarantor. I have changed the json file related to it and it has solved the issue.

**Comment by SekhGulamMainuddin** [comment]
And the choicea and choiceB has been added explicitly and they don't convey any sense so I think removing them will also solve the issue.
