### ISSUE TITLE
Tint of Filter icon isnt visible in dark mode

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2357]
**Summary:**

Tint of Filter icon is  on the darker side hence it isnt visible in the dark mode

**Steps to reproduce:**
- Go to Accounts
- Click on any Active Savings account from the list
- Click on Transactions
- Filter icon on the top right corner isnt visible in dark mode

**Expected behaviour:**

Filter icon on the top right corner should have been visible in dark mode

**Observed behaviour:**

 <table>
  <tr>
    <td><img src="https://github.com/PratyushSingh07/IssueHive/assets/90026952/4579b7b9-17f9-4f12-848e-aa734846ccc2" width=250 height=480></td>
    <td><img src="https://github.com/PratyushSingh07/IssueHive/assets/90026952/f23668f1-7616-4421-af19-e40f275c5da4" width=250 height=480></td>
  </tr>
</table>

**Device and Android version:**

Device: Pixel 7
Android: 13

**Comment by SekhGulamMainuddin** [comment]
Hi @PratyushSingh07 I have created a pull request #2358 to solve this issue.

**Comment by PratyushSingh07** [comment]
@SekhGulamMainuddin thanks for the PR but please ask for approval before you start working on an issue as this would lead to duplication of work

**Comment by SekhGulamMainuddin** [comment]
Ok

**Comment by SekhGulamMainuddin** [comment]
Ok
