### ISSUE TITLE
Text in snackbar isnt visible when i try to change the password

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2361]
**Summary:**

When I try to change the password , appropriate text should have been visible in the snackbar

**Steps to reproduce:**

https://github.com/openMF/mifos-mobile/assets/90026952/679f352b-5403-4821-ae61-68e102f282b5

**Expected behaviour:**

Text inside the snackbar should have been visible. 

**Device and Android version:**

Device: Pixel 7
Android: 13

**Comment by PratyushSingh07** [comment]
Please check if the text is visible in light theme as well before submitting a PR

**Comment by SekhGulamMainuddin** [comment]
Hi @PratyushSingh07 I would like to work on this isuue

**Comment by oyehanif** [comment]
@PratyushSingh07 i want to work on this issue.

**Comment by PratyushSingh07** [comment]
This issue has already been solved in PR #2364
