### ISSUE TITLE
Bug: Json displayed in snackbars instead of a correct error message

### ISSUE THREAD

**Issue by srishti-R** [openMF/self-service-app#2363]
**Summary:**
When creating an account or changing password from Settings, the snackbar message displayed is not proper and does not effectively communicate the error/cause of the error. I would like to amend this.

Summarize your issue in one sentence (what goes wrong, what did you expect to happen).

**Steps to reproduce:**

How can we reproduce the issue?

**Expected behaviour:**

What did you expect the app to do?

**Observed behaviour:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**
Samsung galaxy M31 API 30.

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**
![Screenshot_20231011-132044_Mifos Mobile_previous](https://github.com/openMF/mifos-mobile/assets/53987325/552d55e1-752a-4773-9d39-78461306241b)
![Screenshot_20231011-122041_Mifos Mobile](https://github.com/openMF/mifos-mobile/assets/53987325/068b84f9-c73c-4987-95b6-3ea1936f5187)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by amanjn38** [comment]
Is this issue still open, I would like to work on this
Thanks in advance.

**Comment by srishti-R** [comment]
> Is this issue still open, I would like to work on this Thanks in advance.

You can pick something else, there is a PR open for this.
