### ISSUE TITLE
Transaction option inside Transaction

### ISSUE THREAD

**Issue by aj019** [openMF/self-service-app#237]
**Summary:**

Inside the Transaction Screen if we click on the toolbar menu. It shows Transaction as one of the options. And when the user clicks on the Transaction option nothing happens.

**Steps to reproduce:**

Open the app
Go To savings
Go To saving details
Go To saving transactions
If you click on the toolbar menu you will get an option saying Transaction

**Expected behavior:**

There shouldn't be an option to open Transaction within transaction.

**Observed behavior:**

There is an option to open Transaction within transaction which creates a loop and nothing happens.

**Device and Android version:**

Nexus 5 API 23

**Screenshots:**

<img width="243" alt="screen shot 2017-03-23 at 11 35 15 am" src="https://cloud.githubusercontent.com/assets/7893859/24234329/bbe7da94-0fbd-11e7-8a38-4a9c303aa0df.png">

**Comment by aj019** [comment]
I would like to work on this issue.

**Comment by itsamitgoel** [comment]
@aj019 i already raised this issue ..see issue #218

**Comment by aj019** [comment]
You are right @itsamitgoel . I am closing this issue.
