### ISSUE TITLE
Snackbar instead of Toast on Filter

### ISSUE THREAD

**Issue by aj019** [openMF/self-service-app#238]
**Summary:**

In Transactions when we filter the transactions a toast is displayed which says "Filtered".Rather than Toast we should have a Snackbar.

**Steps to reproduce:**

Open the app
Go To savings
Go To saving details
Go To saving transactions
Select 3 months and click on filter 

**Expected behavior:**

A snackbar should be shown that says "Filtered"

**Observed behavior:**

A Toast is shown that says "Filtered"

**Device and Android version:**

Nexus 5 API 23

**Screenshots:**

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/7893859/24234821/510e0d1c-0fc0-11e7-95be-d4e492db5902.gif)

**Comment by aj019** [comment]
I would like to work on this issue.

**Comment by dilpreet2028** [comment]
@therajanmaurya PR already merged, closing issue
