### ISSUE TITLE
Color of buttons on Saving Account Transaction  fragment is not following google material guidelines according to UI. Make button color primary

### ISSUE THREAD

**Issue by itsamitgoel** [openMF/self-service-app#239]
**Summary:**

Color of buttons on Saving Account Transaction  fragment is not following google material guidelines according to UI. Make button color primary.

**Comment by itsamitgoel** [comment]
@therajanmaurya i would like to fix this

**Comment by dilpreet2028** [comment]
This issue has been fixed
