### ISSUE TITLE
App Theme not Changing Simultaneously when the System Theme is changed

### ISSUE THREAD

**Issue by SekhGulamMainuddin** [openMF/self-service-app#2398]
**Summary:**

The Theme of the Application does not change simultaneously when the System Theme is changed.
The App needs a restart to update the theme changes

**Steps to reproduce:**

Home Screen->Open The Navigation Menu from the left side->Open Settings->Click on Theme and Set to System Theme first.

**Expected behaviour:**

The App theme should change automatically after changing the System Theme

**Observed behaviour:**

The app's theme is not changed automatically, it needs an app restart

**Device and Android version:**

Android Emulator: Pixel 7 Pro (Android 14 - UpsideDownCake)

**Screenshots/Video:**

[theme not changing automatically wrt System Theme needs app restart.webm](https://github.com/openMF/mifos-mobile/assets/73953395/985c5a28-de23-4d51-87ad-08893d20082a)

**Comment by PratyushSingh07** [comment]
Isn't this issue the exact same as #2068 ?

**Comment by SekhGulamMainuddin** [comment]
> Isn't this issue the exact same as #2068 ?

Yes. I didn't see the #2068 issue. 
Closing this one.
