### ISSUE TITLE
Color of buttons on Apply for loan  fragment is not following google material guidelines according to UI. Make button color primary

### ISSUE THREAD

**Issue by itsamitgoel** [openMF/self-service-app#240]
**Summary:**

Color of buttons on Apply for loan  fragment is not following google material guidelines according to UI. Make button color primary

**Comment by itsamitgoel** [comment]
@therajanmaurya i would like to fix this

**Comment by dilpreet2028** [comment]
@therajanmaurya PR already merged, closing issue
