### ISSUE TITLE
Refactor: Move all the UiState Sealed Classes inside a separate new folder ex. uiStates folder

### ISSUE THREAD

**Issue by SekhGulamMainuddin** [openMF/self-service-app#2414]
**Summary:**

Move all the UiState Sealed Classes inside a separate new folder for ex. uiStates folder and then make all the changes.

**Steps to reproduce:**
You can find all the uiState Sealed classes inside the utils folder.
mifos-mobile\app\src\main\java\org\mifos\mobile\utils\

**Comment by SekhGulamMainuddin** [comment]
@PratyushSingh07 can you please assign me this issue.

**Comment by PratyushSingh07** [comment]
Thank you for opening this issue but we had planned to structure our project on the basis of features and during this refactoring we will move the ui states and other classes to their respective folders. Hence , I dont think we should be moving forward with this issue & thus I will be closing this one

**Comment by SekhGulamMainuddin** [comment]
Ok
