### ISSUE TITLE
login credential not working

### ISSUE THREAD

**Issue by Albin-jose** [openMF/self-service-app#2427]
Can you provide the correct login detail to enter the app

username - mifos
Password - password

This is not working. And please provide the correct java version and Gradle version that we need to install.

please respond ASAP

**Comment by francisguchie** [comment]
@Albin-jose  please read this explanation ===> https://github.com/openMF/mifos-mobile/issues/1972#issuecomment-1466470553

**Comment by PratyushSingh07** [comment]
Hi @Albin-jose , there was an issue with the earlier endpoint `demo.mifos.community` . Thankfully this was resolved when I changed the endpoint to `dev.mifos.io`.  You will be able to log into the app once the PR linked to this issue is merged
