### ISSUE TITLE
App Force closes in Home

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#243]
**Summary:**

On clicking on Apply for a loan , Savings accounts and shares app forces closes in Home

**Comment by dilpreet2028** [comment]
@therajanmaurya I would like to fix this

**Comment by therajanmaurya** [comment]
@dilpreet96 Let me handle then according to this I will update the idealist.  I was waiting for this.

**Comment by dilpreet2028** [comment]
Okay Sir , waiting for the idea list to be updated :)

**Comment by therajanmaurya** [comment]
fix in #244
