### ISSUE TITLE
About us screen is hadly accessible in landscape mode

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2432]
**Summary:**

- When you change the orientation of about us fragment to landscape mode , the links are no longer visible on the screen. You can scroll through the items present in about us fragment but their visible range is very limited

**Steps to reproduce:**

- open about us from side navigation

**Expected behaviour:**

- items present in about us fragment should been visible

**Observed behaviour:**

![WhatsApp Image 2023-11-04 at 11 31 45 AM](https://github.com/openMF/mifos-mobile/assets/90026952/04e2be40-3168-49b1-9575-185c5b7c1857)

**Device and Android version:**

Device: Pixel 7
Android: 14

**Comment by PratyushSingh07** [comment]
I will be working on this

**Comment by ayushkeshri19** [comment]
@PratyushSingh07 Can i work on this issue?

**Comment by PratyushSingh07** [comment]
sure, go ahead @keshriAyushh  .  Since you will be working on multiple issues make sure you keep us updated about your progress

**Comment by ayushkeshri19** [comment]
@PratyushSingh07 sure!

**Comment by ayushkeshri19** [comment]
@PratyushSingh07 I've fixed the issue.
