### ISSUE TITLE
some currencies are not visible in the accounts section

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2433]
**Summary:**

- some currencies are not visible in the accounts section namely in the saving and loan section

**Steps to reproduce:**

- open the accounts section in the home screen

**Expected behaviour:**

- currency should have been visible for all of the transacitons

**Observed behaviour:**

<table>
  <tr>
    <td><img src="https://github.com/coder2699/Dare2Change/assets/90026952/0f496bef-986f-4a71-9de9-3e1363312391" width=250 height=480></td>
    <td><img src="https://github.com/coder2699/Dare2Change/assets/90026952/41e96603-5352-4aab-b214-94a08cfdeda2" width=250 height=480></td>
  </tr>
</table>

**Device and Android version:**

Device: Pixel 7
Android : 14

**Comment by sebesti0n** [comment]
Hey @PratyushSingh07 i want to work on this, Please assign me this.

**Comment by PratyushSingh07** [comment]
yes you can work on it @sebesti0n . Before working on it please make sure if this issue is backend related or the error is due to a bug in the front end

**Comment by vyom198** [comment]
hey @PratyushSingh07   i think this  issue is backend related  

savingAccount
<img width="783" alt="Screenshot 2023-11-17 230910" src="https://github.com/openMF/mifos-mobile/assets/112750331/ca916999-3140-4da5-b3ea-19e30b158224">

SavingAccount
<img width="825" alt="Screenshot 2023-11-17 230540" src="https://github.com/openMF/mifos-mobile/assets/112750331/b5387559-aa43-4721-8a0a-d4c1084889f5">

for loanAccount  displaySymbol property is not set in loanaccountListAdapter

**Comment by rohit9625** [comment]
@vyom198 , are you working on this?

**Comment by vyom198** [comment]
> @vyom198 , are you working on this?

no , you can work on this but i think it is backend related

**Comment by kapmaurya** [comment]
@sebesti0n , are you working on this?

**Comment by AbrahamOsmondE** [comment]
hi @PratyushSingh07, I will be working on this. Appreciate it if you can assign this to me

**Comment by PratyushSingh07** [comment]
Re assigned due to inactivity

**Comment by AbrahamOsmondE** [comment]
The list of currencies is taken from a database table, whose implementation differs from tenant to tenant. The default currency list and properties can be found [here](https://github.com/apache/fineract/blob/5fa2295bd0923916d9553717f2936d422fd04fef/fineract-db/multi-tenant-demo-backups/bk_mifostenant_default.sql#L734)

It seems that MySQL does not support some of these currency symbols ([source](https://gist.github.com/voskobovich/537b2000108e4781f70b)), causing `displaySymbol` to be `null` for some currencies.

We should instead implement a fallback for these cases
