### ISSUE TITLE
When Recent Transactions is opened without connection of internet App crashes

### ISSUE THREAD

**Issue by kmanikanta335** [openMF/self-service-app#2442]
**Summary:**

When user is offline  if he opens Recent Transactions the App gets crashes instead it should show a Error layout of No Connection 

**Steps to reproduce:**

1.open mifos mobile app
2. turn off internet
3. open recent transactions

**Expected behaviour:**

It should show error layout of No Connection

**Observed behaviour:**

App crashes

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/118070186/e495debb-f380-4119-9b2e-a8fd3030ecab

**Comment by kmanikanta335** [comment]
@PratyushSingh07  can i take this issue ?

**Comment by PratyushSingh07** [comment]
Sure , go ahead @kmanikanta335

**Comment by omjeem** [comment]
@PratyushSingh07  Please assign it to me ! 
till now i set up it locally in my Android studio
but for making a new registration it asked me for Account Number where do I get it??

**Comment by PratyushSingh07** [comment]
There is already someone assigned to this issue.  
You don't have to create a new account @omjeem . Please go through the wiki page to get the demo credentials

**Comment by omjeem** [comment]
@PratyushSingh07 Thanks for the info! I'll check the wiki for demo credentials and continue working on the issue.

**Comment by ghost** [comment]
@kmanikanta335 is the issue resolved..?

**Comment by kmanikanta335** [comment]
@Thanush66 yes i am about to open a PR

**Comment by kmanikanta335** [comment]
@PratyushSingh07 pls review it

**Comment by mayank0rajput** [comment]
is this issue resolved or still open?

**Comment by PratyushSingh07** [comment]
There is already an open PR linked to this issue @mayank0rajput

**Comment by ghost** [comment]
can i take this issue sir please @PratyushSingh07

**Comment by PratyushSingh07** [comment]
> can i take this issue sir please @PratyushSingh07

I'm afraid you cannot take this issue as we already have an open PR for this

**Comment by ghost** [comment]
Why you have been in doubt  Sent from Mail for Windows From: Pratyush SinghSent: 29 December 2023 11:08To: openMF/mifos-mobileCc: Antima Mishra; CommentSubject: Re: [openMF/mifos-mobile] When Recent Transactions is opened without connection of internet App crashes (Issue #2442) can i take this issue sir please @PratyushSingh07I'm afraid you cannot take this issue as we already have an open PR for this—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by PratyushSingh07** [comment]
hey @kmanikanta335 , I dont think we can replicate this issue any more. #2469 is what we get now. Can you just cross check this in your system and let us know.

**Comment by kmanikanta335** [comment]
@PratyushSingh07 yes your are correct there is no required to replicate that issue #2469 
Yes my system is showing proper error layout this issue as shown in the above video issue1.mp4

**Comment by PratyushSingh07** [comment]
so i can close this issue and its PR ,right ?

**Comment by kmanikanta335** [comment]
@PratyushSingh07 ya sure no problem
