### ISSUE TITLE
Refresh animation rotates continuously even after everything is loaded

### ISSUE THREAD

**Issue by kmanikanta335** [openMF/self-service-app#2445]
**Summary:**

In Recent Transactions layout once all the data gets loaded the refreshing animation should get disappeared instead it rotates continuously

**Steps to reproduce:**

1.open mifos mobile
2. open recent transactions 

**Expected behaviour:**

Refreshing animation should stop after loading data

**Observed behaviour:**

Animation goes on continoulsy

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/118070186/6fb2f762-dc80-43e3-9e2f-9c1798ebf73d

**Comment by kmanikanta335** [comment]
@PratyushSingh07 can i work on it ?

**Comment by PratyushSingh07** [comment]
This is a duplicate issue. Issue #2431 deals with the same. Hence I'm closing this one
