### ISSUE TITLE
Feat : it would be better if it asks current passcode and then change the passcode...

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#2446]
**Summary:**

Summarize your issue in one sentence (what goes wrong, what did you expect to happen).

**Steps to reproduce:**
1 . set a passcode before this
- go to setting 
-change passcode

**Expected behaviour:**
asks for current passcode...

**Observed behaviour:**

doesnt asks for current passcode and directly changes the new passcode....

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by ghost** [comment]
@PratyushSingh07 Whats your view on this...

**Comment by PratyushSingh07** [comment]
Issue #2088 deals with the same @Thanush66 

I am closing this as duplicate
