### ISSUE TITLE
refactor : Migration of Help fragment from Xml to Compose view

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#2447]
**Summary:**

Compose offers a more concise and expressive syntax for UI development compared to XML.

**Comment by ghost** [comment]
@PratyushSingh07 Can you give me an overview for this..

**Comment by PratyushSingh07** [comment]
You need to check this with @jawidMuhammadi 
You can work on it if he gives you a thumbs up

**Comment by ghost** [comment]
@jawidMuhammadi Can i work on this if Yes could you please give me an overview on this to make Best pull req...

**Comment by PratyushSingh07** [comment]
Not sure if you can open the PR until jawid reviews it but if you want to practice compose and try out things locally then you can take reference from the migration of about us fragment @Thanush66

**Comment by ghost** [comment]
@PratyushSingh07 i already took reference....I couldn't understand it could you please give me an overview on it....like steps....since it was my first migration...

**Comment by PratyushSingh07** [comment]
There aren't any fixed steps for this migration. Each screen may require it's own implementation. Migrating from XML to compose is a huge task and hence it will be better to do this under the guidance of someone who is more experienced. 
My mentor and I had discussed this during GSoC that the migration of about us fragment should be taken as a reference by future contributors and you should try to do the same.  Meanwhile it will be better if you find and solve some bugs

**Comment by PratyushSingh07** [comment]
you can start working on it @Thanush66

**Comment by PratyushSingh07** [comment]
any updates @Thanush66 ?

**Comment by ghost** [comment]
@PratyushSingh07 Trying but i coudn't get it.....!

**Comment by PratyushSingh07** [comment]
alright @Thanush66 , in case you decide to pass it to others then let me know. I hope you have taken reference from the existing screens as well as the ones that are present in my open PR

**Comment by ghost** [comment]
Okay

**Comment by AvneetSingh2001** [comment]
Hey @Thanush66 , can i work on this if you are facing any issues ?
cc: @PratyushSingh07

**Comment by ghost** [comment]
@PratyushSingh07 Re-assign This..

**Comment by PratyushSingh07** [comment]
We have a few screens in compose @AvneetSingh2001 . Take guidance from those

**Comment by AvneetSingh2001** [comment]
Thanks @PratyushSingh07

**Comment by AvneetSingh2001** [comment]
Hey @PratyushSingh07 , In Help Activity, we have **HomeFragment** which can be replaced by **LocationFragment** with a **FindLocations** Button. I have written compose file in for HomeFragment, Do this Issue also covers the scope of **LocationFragment**? LocationFragment is only being used in HomeActivity, So if its not covered in current Enhancement Scope, then we can make separate activity to inflate it.

**Comment by PratyushSingh07** [comment]
why do we need to make a separate activity to inflate LocationFragment? We can open the fragment from the composable itself

**Comment by AvneetSingh2001** [comment]
@PratyushSingh07  ok got it, you want to start the composable screen from the existing HomeFragment itself, right?

**Comment by PratyushSingh07** [comment]
Yes, basically we are using fragment+compose in our approach for migration. This would essentially ask you to set the content to a composable screen instead of the XML layout. Hence in our case make a compose screen by the name of HelpScreen and set the content view of Helpfragment to follow this composable
