### ISSUE TITLE
Bug: Improper Error layout in user profile

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2450]
**Summary:**

The error layout in user profile in case of no internet isnt correct

**Steps to reproduce:**

Turn off internet and open up user profile

**Expected behaviour:**

User profile should have had no visibility and one should have only seen the error layout

**Observed behaviour:**

Right now you can see both the error layout and the user profile screen

**Device and Android version:**

Device: Pixel 7
Android: 14

**Screenshots:**
![user profile](https://github.com/openMF/mifos-mobile/assets/90026952/45e6b595-ad4e-44ef-a6f1-b13bdb6e8c90)

**Comment by therajanmaurya** [comment]
We are going to build with jetpack compose. If you are thinking to fix it so please convert with jetpack compose.

**Comment by PratyushSingh07** [comment]
I see I will work on it then @therajanmaurya

**Comment by geektan123** [comment]
// Set visibility to invisible
myView.visibility = View.INVISIBLE               
         Hey @PratyushSingh07  we can invisble the layout with the help of such command when internet is tuned off.I have an approch to solve the problem please assign to me

**Comment by PratyushSingh07** [comment]
Hey @geektan123 we will be migrating this from xml to compose and hence we wont be using your approach. I cannot assign this to you as I have already started working on it. Feel free to look out for other issues or come up with some findings of your own !!
