### ISSUE TITLE
Issue : App crashes When recent Transactions is Opened without Internet

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#2451]
App crashes When recent Transactions is Opened without Internet

**Steps to reproduce:**
1. Turn off the internet 
2. 2. Go to Recent Transactions 

It should a log There is no internet

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/136256522/f9d5ac35-ba42-41ae-9277-2caaa0b13998

**Comment by Thanush66** [comment]
@PratyushSingh07 I will be Working on this...
