### ISSUE TITLE
UI : the Registration page Doesnt change to Dark mode..

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#2452]
**Summary:**
the Registration page Doesnt change to Dark mode.

**Steps to reproduce:**

Go to dark mode
go to registration page

**Expected behaviour:**

The registration page should be in dark mode

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**
Pixel 5a

**Screenshots:**
<img src="https://github.com/openMF/mifos-mobile/assets/136256522/dde42363-8e50-4c65-a060-09e5936f5af9" width = 50%
height = 50%/>

**Comment by Thanush66** [comment]
@PratyushSingh07 ig Black Would be good..?

**Comment by pranavkonidena** [comment]
Hi, can I work on this?

**Comment by prabhakar0304** [comment]
This screen is not even in dark mode.

I would like to work on this issue.

**Comment by ghost** [comment]
@prabhakar0304 I wanted to work on this...!

**Comment by ghost** [comment]
@prabhakar0304 Dude the The screen itself Doesn't change to Dark theme..!

**Comment by PratyushSingh07** [comment]
This is a duplicate issue. #1918 deals with the same. The text color or whatever else is needed will be fixed when #1918 gets resolved. 
Also @Thanush66 please check the existing issues before opening a duplicate one.

Hence I'm closing this as a duplicate
