### ISSUE TITLE
Add link from registration to login screen

### ISSUE THREAD

**Issue by pranavkonidena** [openMF/self-service-app#2453]
**Summary:**

No link from the register screen to login screen if user clicks on it by mistake

**Steps to reproduce:**

Open the app, go to register screen by tapping on the create account button

**Expected behaviour:**

Goes to the registration screen but with a button at the end saying if you already have an account , proceed to login

**Observed behaviour:**

Goes to the registration screen without any option except restarting the app to go to the login screen

**Device and Android version:**

I was using an emulator (Pixel XL API 34) for testing purposes

**Screenshots:**
<img width="1512" alt="Screenshot 2023-12-16 at 12 54 04 AM" src="https://github.com/openMF/mifos-mobile/assets/122373207/a6146b14-d458-4584-b757-8079bc74ef3a">

**Comment by pranavkonidena** [comment]
I would like to work on this, can you please assign me this issue? Thanks

**Comment by PratyushSingh07** [comment]
I don't think this is a valid issue. Press back on the registration screen and you will have the option to cancel the registration and then go back to the login screen. Why do you want to have something else ?

**Comment by pranavkonidena** [comment]
Ahh yeah hadn't thought of that.. please go ahead and close this issue
