### ISSUE TITLE
Bug : the state gets forgotten When Refreshed..

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#2454]
**Summary:**
the state gets forgotten When Refreshed..

**Steps to reproduce:**

1. go to accounts
2. select a filter 
3. refresh

**Expected behaviour:**

The state should be remembered

**Observed behaviour:**

The State gets forgotten

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/136256522/e860fc62-8f74-40e8-8ab4-8adc69e81ce8

**Comment by ghost** [comment]
@PratyushSingh07 Is this the correct behaviour or its a bug If its a bug I will work on this...

**Comment by PratyushSingh07** [comment]
This is the expected behaviour. You would want unfiltered list on swipe . So I'll be closing this one
