### ISSUE TITLE
Issue : Filter Selection not working properly

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#2457]
**Summary:**

Filter Selection not working properly

**Steps to reproduce:**

1.Go to accounts
2.select any tranasaction from  account s
3. Go to Transactions
4. select filter

**Expected behaviour:**

It should work properly

**Observed behaviour:**
Not working properly

**Device and Android version:**

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/136256522/5d774147-381c-4d02-9411-334fd46f5ccc

**Comment by ghost** [comment]
@PratyushSingh07 I Will work On this...

**Comment by AbrahamOsmondE** [comment]
hi @Thanush66 are you still working on this?

**Comment by AbrahamOsmondE** [comment]
@PratyushSingh07 I have asked @Thanush66 on Slack if he's ok with me working on this and he says yes. Will raise a pull request to solve this soon
<img width="1023" alt="Screenshot 2024-03-24 at 1 27 00 AM" src="https://github.com/openMF/mifos-mobile/assets/82792334/603bd8e9-80f2-45b1-95c2-8a7c92acd64a">
