### ISSUE TITLE
issue: Progress bar in Recent Transaction

### ISSUE THREAD

**Issue by ufuomaisaac** [openMF/self-service-app#2461]
**Summary:**

Summarize your issue in one sentence (what goes wrong, what did you expect to happen).
On clicking on Recent Transactions in the nav menu, it opens a new screen and loads its data but the progress bar wouldn't stop loading

**Steps to reproduce:**

How can we reproduce the issue?
Click on the menu bar icon
Click on Recent Transaction

**Expected behaviour:**

What did you expect the app to do?
show the progress bar to indicate that it is fetching data and then hide the progress bar when it has fetched and displayed data

**Observed behaviour:**

What did you see instead?  Describe your issue in detail here.
on opening the page, the progress bar continues loading after displaying the data

**Device and Android version:**

version from the manufacturer or a custom ROM?
Device: TECNO PR651H 
Android: 11

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/104263097/8a2a1c96-a329-4884-820e-698cd11a5b4e

**Comment by ufuomaisaac** [comment]
@PratyushSingh07  please check this, can I work on it?

**Comment by PratyushSingh07** [comment]
I am afraid this is a duplicate issue . #2431 has listed the same problem in this screen

**Comment by ufuomaisaac** [comment]
Oh okay, thank you
