### ISSUE TITLE
refactor: Migrate RecentTransaction to compose

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2469]
**Summary:**

No error Ui in recent transaction when the app is deprived of internet connection. 

**Steps to reproduce:**

Switch of the internet and head over to the recent transaction

**Expected behaviour:**

Error UI in case of no internet just like we have in other screens

**Observed behaviour:**

Blank screen

**Device and Android version:**

Device: Pixel 7
Android: 14

**Screenshots:**
![recent transaction](https://github.com/openMF/mifos-mobile/assets/90026952/977e51a5-7c09-4f4d-9db1-50ed7c4c03d2)

**Comment by PratyushSingh07** [comment]
we might as well migrate this screen to compose @therajanmaurya

**Comment by kmanikanta335** [comment]
@PratyushSingh07 hey can i work on this

**Comment by PratyushSingh07** [comment]
i will be working on this @kmanikanta335 and in the process I will migrate this to compose
