### ISSUE TITLE
Empty Snackbar message when making transfer and internet is off

### ISSUE THREAD

**Issue by aj019** [openMF/self-service-app#247]
**Summary:**

The app shows an empty snackbar message when making transfer and internet is off

**Steps to reproduce:**
Open the app
Go to Savings
Select a saving
Go to Transfer
Add details
Turn off internet
Click on Review transfer
Click on Transfer

**Expected behavior:**

The app should show a snackbar with message "No Internet"

**Observed behavior:**

No message in snackbar

**Device and Android version:**

Nexus 5 API 23

**Screenshots:**

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/7893859/24278353/5985c8b4-1069-11e7-9b13-1f16f95fbe7a.gif)

**Comment by sanjeeb-sang** [comment]
**Summary:**
I have fixed the problem by checking for network connection right after the onClick method gets executed.
The app will now show a SnackBar saying "You are not connected to the internet!!" if there is no internet

**Requirement:**
It needs the permission to access network state 
![screenshot_20170325-021423](https://cloud.githubusercontent.com/assets/22350684/24320337/5129cace-1101-11e7-9117-7893c9910ccb.png)

**Comment by sanjeeb9853** [comment]
#250
