### ISSUE TITLE
Bug: Splash screen logo is behave different

### ISSUE THREAD

**Issue by Maan-Sharma** [openMF/self-service-app#2473]
**Summary:**

Splash screen logo is behaving differently

**Expected behaviour:**

It should be fit in screen

**Screenshots:**

![WhatsApp Image 2024-01-06 at 12 30 04 PM](https://github.com/openMF/mifos-mobile/assets/146059379/2749046a-1d14-49c5-b1dc-534d30073f07)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by Maan-Sharma** [comment]
@PratyushSingh07 can I work on this

**Comment by PratyushSingh07** [comment]
Hey @Maan-Sharma this is a duplicate issue . #2463 dealt with the same . Moreover a PR was raised for this issue and it was merged last night. 
Please sync your fork
