### ISSUE TITLE
About Us page section's text not visible properly while in dark mode

### ISSUE THREAD

**Issue by Vikashgathala** [openMF/self-service-app#2474]
**Summary:**

in about us section, while in dark mode, the text is not visible properly.

**Steps to reproduce:**

We can change the text colour to while when the sysytem or app is in dark mode.

**Expected behaviour:**

In dark mode, the text should be white and while in light mode, text should be black.

**Observed behaviour:**

Unable to read the text in dark mode

**Device and Android version:**

Redmi note 9 pro, Android 11, Arrow OS

**Screenshots:**

![Screenshot_20240107-130746](https://github.com/openMF/mifos-mobile/assets/12993867/b1afeb15-f1da-405f-84cc-fc6192709520)

**Comment by Vikashgathala** [comment]
@PratyushSingh07 I'll be working on this

**Comment by Vikashgathala** [comment]
@PratyushSingh07 Have a look at this please.

**Comment by Vikashgathala** [comment]
@PratyushSingh07 Hey, please have a look at this, now this is working fine in all possible theme combinations.

**Comment by Vikashgathala** [comment]
@PratyushSingh07 I fixed the issues as per your suggestions.

**Comment by abhineshchandra1234** [comment]
Hi @Vikashgathala / @PratyushSingh07,

- I am an Android developer with 4 years of experience working with Infosys.
- I would like to contribute to this repository. Please let me know any tasks I can do to help. Thank you.
