### ISSUE TITLE
Progress Dialog shown  for the infinite period of time in recent transactions .

### ISSUE THREAD

**Issue by NiranjanNlc** [openMF/self-service-app#2478]
**Summary:**
When we try to see the recent transactions , all the recent transactions are shown , but the progress indicator will load for the infinite period of time even after all data are loaded . 

**Steps to reproduce:**
1. Open the mifos mobile app 
2. tap into menu 
3. click on recent transactions 

**Expected behaviour:**
The progress indicator should goes away  immediately after all the recent transaction has been loaded .

**Observed behaviour:**

 The progress indicator  is there for infinite period of time. 

**Device and Android version:**
 Redmi 9A, Android 10 

**Screenshots:**
 

https://github.com/openMF/mifos-mobile/assets/25600880/714b0b38-5bfb-4cea-b98e-faa430a16c4a

**Comment by NiranjanNlc** [comment]
I will be working on this

**Comment by PratyushSingh07** [comment]
this is a duplicate issue @NiranjanNlc . #2431 deals with the same . Morevoer we already have a PR for this issue which is #2441 , hence I will need to close down this issue and the PR that you have linked to it. Please make sure that you dont open a duplicate issue as this results in redundant effort

**Comment by PratyushSingh07** [comment]
You can take this issue and reopen your PR in case @Thanush66 doesn't fix PR #2441 which he opened.
