### ISSUE TITLE
Touching helpline number does not load the dialer

### ISSUE THREAD

**Issue by vladimirfomene** [openMF/self-service-app#248]
**Summary:**

When I'm on the Saving Account details activity and I click the support line number it loads the phone dialer but when I touch the support line number on the Saving Account Transaction Activity it does not load the dialer.

**Steps to reproduce:**

Go to the Saving Account Transaction activity. Then touch the support line number.

**Expected behavior:**

To load the phone's dialer.

**Observed behavior:**

When I touch the number nothing happened.

**Device and Android version:**

Alcatel Pop4 Plus
Android version 6.0.1

**Screenshots:**

![screenshot_20170324-221900](https://cloud.githubusercontent.com/assets/11140070/24316047/fccf22a8-10e2-11e7-8d82-519dfebb0b6f.png)

**Comment by vladimirfomene** [comment]
I working on this right away.

**Comment by vladimirfomene** [comment]
@therajanmaurya. Please have a look at this PR.

**Comment by dilpreet96** [comment]
I think clicking `Contact your support line` should not load dialer, clicking phone number already loads the dailer, so this issue is not revelant . @therajanmaurya

**Comment by dilpreet2028** [comment]
This issue was fixed
