### ISSUE TITLE
[Docs] Invalid Links for PR Guide and New desings

### ISSUE THREAD

**Issue by Sagar0-0** [openMF/self-service-app#2480]
**Summary:**

The links in the Readme.md for PR guidelines and New designs are invalid and leads to 404 Page not found.

**Comment by PratyushSingh07** [comment]
Hey @Sagar0-0 I think #2200 has already pointed out this issue. Also the CONTRIBUTION.md file was moved to the root level and that is the reason you get PR guidelines as invalid. We still have to make a few changes to our Readme.md and when the mentor raises a PR for that we will make sure to fix it 

Thus, I'll be closing down this issue as duplicate
