### ISSUE TITLE
Shift Images from mipmap folder to drawables except App Icon

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#25]
Shift Images from mipmap folder to appropriate drawable folder because mipmap folder is only for the app icons not for the drawable.

for more info : http://stackoverflow.com/a/28065664/3176277 and 
http://android-developers.blogspot.in/2014/10/getting-your-apps-ready-for-nexus-6-and.html

**Comment by ashu-dadhich** [comment]
@therajanmaurya can I do it

**Comment by therajanmaurya** [comment]
Yeah @top-gun007.

**Comment by ashu-dadhich** [comment]
ok thanks will send a PR soon

**Comment by therajanmaurya** [comment]
Fixed in #37
