### ISSUE TITLE
Unable to join mifos.slack

### ISSUE THREAD

**Issue by nuke100pr** [openMF/self-service-app#2510]
Joining it requires email of the format
@mifos.org
@vodafone.com
@nasasa.org.za
@newlogic.com

I only have a gmail account.
prakharmaurya700@gmail.com

Please help.

**Comment by AvneetSingh2001** [comment]
Hey, Mifos slack community supports Gmail Account and I have joined using the same. 
Please make sure you have an account on Slack with the same Gmail account, and if still there is an issue, please include the screenshot where you encounter problem.

**Comment by nuke100pr** [comment]
Ok I figured it out.
