### ISSUE TITLE
Mifos logo on login screen doesnt respect dark theme

### ISSUE THREAD

**Issue by Vikashgathala** [openMF/self-service-app#2525]
**Summary:**

Mifos logo on login screen doesn't adapt to the theme.

**Steps to reproduce:**

I can work to fix this. maybe changing to png format with removed background would help.

**Expected behaviour:**

background colour of the mifos logo must change to dark while in dark mode.

**Observed behaviour:**

it stays white even in dark mode, which looks dirty.

**Device and Android version:**

Pixel 7 pro AVD- Android 12.
also observed in redmi note 9 pro in android 11 custom rom.

**Screenshots:**

<img width="374" alt="Screenshot 2024-03-14 at 9 07 32 AM" src="https://github.com/openMF/mifos-mobile/assets/12993867/facaa528-dc11-4e96-aafd-e1c0e9f2fd97">

**Comment by Vikashgathala** [comment]
@PratyushSingh07 I'll be working on this.

**Comment by PratyushSingh07** [comment]
This screenshot isn't from mifos mobile @Vikashgathala

**Comment by PratyushSingh07** [comment]
I had fixed this issue last year. I guess this screenshot is from Android client

**Comment by Vikashgathala** [comment]
Yeah sorry, got confused due to multiple emulators.

**Comment by PratyushSingh07** [comment]
No worries, also make sure that you have updated your fork of Android client. This issue may have been resolved
