### ISSUE TITLE
wiki page contribution guidelines link is broken

### ISSUE THREAD

**Issue by itsPronay** [openMF/self-service-app#2530]
After clicking on contribution guidelines it gives an error.

error-  
the development branch of mifos-mobile does not contain the path `.github/CONTRIBUTING.md.`

![image](https://github.com/openMF/mifos-mobile/assets/78101731/af6f0b75-d831-461c-b155-541b97181751)

![image](https://github.com/openMF/mifos-mobile/assets/78101731/811cb80d-7f52-46d4-8f3b-4083374d36b7)

**Comment by therajanmaurya** [comment]
Thanks for the ticket, I have fixed the link. You are most welcome to create a new ticket for changing the name in https://github.com/openMF/mifos-mobile/blob/development/CONTRIBUTING.md

**Comment by itsPronay** [comment]
@therajanmaurya can you fix the point 4 and 5 ? it's broken as well 
![image](https://github.com/openMF/mifos-mobile/assets/78101731/01e5b25a-0279-4065-bbae-ce5c9e695a91)

**Comment by itsPronay** [comment]
I just discovered this one now. Should I raise an issue or you can just fix? Thanks!!
