### ISSUE TITLE
Help needed - cant join slack channel ( please send me an invitation)

### ISSUE THREAD

**Issue by itsPronay** [openMF/self-service-app#2531]
I tried to create an account using gmail but it gives me an error saying `
The email address must match one of the domains listed below. Please try another email.`

I need further assistance of yours...Thank you!

**Comment by itsPronay** [comment]
![image](https://github.com/openMF/mifos-mobile/assets/78101731/1ff8624c-438e-473c-8cb4-ed4d187cca82)
![image](https://github.com/openMF/mifos-mobile/assets/78101731/b3657b52-5670-4087-9df2-d823d5b2a9aa)
![image](https://github.com/openMF/mifos-mobile/assets/78101731/db310b76-1393-4ae1-a327-da49c52932d3)

**Comment by AvneetSingh2001** [comment]
Hey, @itsPronay  
 do you already have an Account on Slack with the gmail you are trying to login?
 we can send you the invitation, but I want to investigate why is this happening, so we can help future contributors too.

**Comment by itsPronay** [comment]
@AvneetSingh2001 Yes.. I already have an account on slack with the Gmail I am trying to login

**Comment by AvneetSingh2001** [comment]
try this: https://join.slack.com/t/mifos/shared_invite/zt-2f4nr6tk3-ZJlHMi1lc0R19FFEHxdvng

**Comment by itsPronay** [comment]
Tnx! I joined!

**Comment by therajanmaurya** [comment]
Welcome!
