### ISSUE TITLE
Users shouldn't be allowed to type letters in phone number field

### ISSUE THREAD

**Issue by itsPronay** [openMF/self-service-app#2539]
Summary:
I can type letters in the phone number field, and can type more than 10 letters/numbers. 

![image](https://github.com/openMF/mifos-mobile/assets/78101731/ac5da0c1-69b8-4375-9a9b-c7bedd57d558)

What did you expect the app to do?
 
I don't think people should be allowed to type letters in the phone number field. Also maybe we should limit the number input to a maximum 10 digits. ( since a phone number is of 10 digits) 

Possible solutions
------------
1. numeric keyboard only
![image](https://github.com/openMF/mifos-mobile/assets/78101731/2ed388de-9788-4115-b2be-2416f0db6b0a)
 or 

2. shows an error message when a character type  is entered
![image](https://github.com/openMF/mifos-mobile/assets/78101731/319c4f49-5b21-40ef-b36d-28892388b75b)

Maybe we should also implement this for the account number section

**Comment by therajanmaurya** [comment]
@itsPronay have you gone through the readme? please first go through and you are most welcome to send the XML to compose PR.

**Comment by itsPronay** [comment]
Ok brother

**Comment by Akshaykomar890** [comment]
Is this open ?

**Comment by ayush1233** [comment]
is this issue still open? 
 I am willing to work on it

**Comment by itsPronay** [comment]
@ayush1233 hey Ayush, This issue is already resolved.
