### ISSUE TITLE
Migrate Beneficiary Application XML to compose

### ISSUE THREAD

**Issue by UduakUmanah10** [openMF/self-service-app#2553]
Migrate Beneficiary Application XML to compose

**Comment by UduakUmanah10** [comment]
assign this to me

**Comment by itsPronay** [comment]
@UduakUmanah10 Hey bro,

Are you still working on this issue? If not, I would like to take over.

Thanks!

**Comment by UduakUmanah10** [comment]
@itsPronay I am still actively working on this I have some issues with Android studio error, and I am trying to resolve it with @AvneetSingh2001. I would be glad if you can assist @itsPronay

**Comment by itsPronay** [comment]
I will get back to you on slack @UduakUmanah10
