### ISSUE TITLE
Bug: Reversed behaviour of `view-password` icon button

### ISSUE THREAD

**Issue by itsPronay** [openMF/self-service-app#2558]
**Summary:**

The action of the `view-password` icon button is reversed

**Steps to reproduce:**

apk<settings<change password

**Expected behaviour:**

behaviour should be the same

**Observed behaviour:**

they are reversed

**Device and Android version:**

Android 12
A32 Samsung

**Screenshots:**

![image](https://github.com/openMF/mifos-mobile/assets/78101731/1064f25f-f7a1-44f8-adfb-a7c445a5823b)
![image](https://github.com/openMF/mifos-mobile/assets/78101731/edc07ffe-7672-40f3-acba-b9debc51e198)

**Comment by itsPronay** [comment]
I will be working on this, Kindly assign me this one

**Comment by PratyushSingh07** [comment]
I'll be closing this one since, we are looking at compose migration @itsPronay . The behaviour of change password screen should be fixed during the migration.

So if you want to work on this then open an issue for its migration and then fix it.
