### ISSUE TITLE
Bug: Keyboard overlaps  password Textfield content

### ISSUE THREAD

**Issue by itsPronay** [openMF/self-service-app#2560]
**Summary:**

overlaps  password Textfield content

**Steps to reproduce:**

open apk--> create account--> select password and confirm password textfield ( specially confirm password ) --> type anything

**Expected behaviour:**

it(textfield) should scroll up automatically 

**Observed behaviour:**

textfield got hidden by the keyboard

**Device and Android version:**

Android 13 ( Samsung A32)

**Screenshots:**
[Screencast_03_31_2024_12:12:46_AM.webm](https://github.com/openMF/mifos-mobile/assets/78101731/e8bf201c-63fd-4601-830c-eb4d78467ce5)

**Comment by itsPronay** [comment]
@PratyushSingh07 can you assign me this one?

**Comment by PratyushSingh07** [comment]
please add appropriate screenshot here

**Comment by SK3180** [comment]
I'm working on this.

**Comment by itsPronay** [comment]
Hello @SK3180 , this issue is already resolved. 

But if you would like to contribute there's a compose migration going on. 
[here](https://github.com/openMF/android-client)
