### ISSUE TITLE
Form Validation For Transfer

### ISSUE THREAD

**Issue by thecskc** [openMF/self-service-app#257]
**Summary:**

The transfer column can crashes when it takes in a "." character. Moreover, I feel the validation process can be made more effective.

**Steps to reproduce:**

Go to the transfer fragment, enter an amount of "." and do the transfer. The app crashes because of an exception.

**Expected behavior:**

The app shouldn't crash but should say that the character entered is an invalid character. 

**Observed behavior:**

The app crashes.

**Device and Android version:**

Redmi Pro, Android 6.0, running on MIUI

**Comment by thecskc** [comment]
I've solved this issue. 
I added a few additional checks and also used an external library for asynchronous form validation as well! 
@therajanmaurya

**Comment by dilpreet2028** [comment]
@therajanmaurya "." crash issue has already been fixed and instead of showing Snackbar using a external library for prompting user does seems to be a nice idea.

**Comment by dilpreet2028** [comment]
Already Fixed
