### ISSUE TITLE
refactor: Migration of Guarantor details from XML to Compose

### ISSUE THREAD

**Issue by AvneetSingh2001** [openMF/self-service-app#2574]
**Summary:**
 Migration of Guarantor details from XML to Compose

**Comment by AvneetSingh2001** [comment]
I will be working on this.

**Comment by geektan123** [comment]
Hi,I am tanay i am intersested to  work on  this Assign #2574

**Comment by AvneetSingh2001** [comment]
Hey @geektan123  I have already done mostly in this.
