### ISSUE TITLE
Clicking back button on home screen leading to empty screen

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#258]
if you click back button on home screen it is leading to empty screen i,e a layout with no fragment , @therajanmaurya can i fix this issue?
![17572071_701836993311232_743041967_o](https://cloud.githubusercontent.com/assets/14215902/24418462/b3cb8d1a-1409-11e7-87ad-ca08e631958d.png)

**Comment by therajanmaurya** [comment]
yeah, I encounter this bug, to fix this you have to  change this line https://github.com/openMF/self-service-app/blob/development/app/src/main/java/org/mifos/selfserviceapp/ui/activities/HomeActivity.java#L59 with `replaceFragment(HomeFragment.newInstance(clientId), false,  R.id.container);`.
Go ahead and Send PR

**Comment by ghost** [comment]
@therajanmaurya sir, PR sent..

**Comment by therajanmaurya** [comment]
Fix in #259
