### ISSUE TITLE
refactor: migrate TransferProcessFragment to compose screen

### ISSUE THREAD

**Issue by AvneetSingh2001** [openMF/self-service-app#2583]
**Summary:**

migrate TransferProcessFragment to compose screen

**Comment by Saifuddin53** [comment]
Hey @AvneetSingh2001  i would like to start working on these screen

**Comment by Saifuddin53** [comment]
@AvneetSingh2001 can I use the text composable or have to use the MifosTitleDescSingleLine in the compose screen ? Because I have taken reference of your previous migration pull requests

**Comment by AvneetSingh2001** [comment]
@Saifuddin53 feel free to use text

**Comment by Saifuddin53** [comment]
@AvneetSingh2001 can you for now just review the transfer process screen 
<img width="259" alt="Screenshot 2024-05-11 161806" src="https://github.com/openMF/mifos-mobile/assets/112172255/0f7807ae-0291-498e-a4ab-5c6c5347ef19">

**Comment by AvneetSingh2001** [comment]
its fine, you dont need `MifosTitleDescSingleLine `
