### ISSUE TITLE
refactor: migration of RegistrationVerificationFragment to compose screen

### ISSUE THREAD

**Issue by AvneetSingh2001** [openMF/self-service-app#2584]
**Summary:**

migration of RegistrationVerificationFragment to compose screen

**Comment by MasterBlaster99** [comment]
@AvneetSingh2001 Can you please assign it to me ?

**Comment by AvneetSingh2001** [comment]
Go ahead. Please take a reference from some closed PRs also.

**Comment by itsPronay** [comment]
@MasterBlaster99 Hey bro, are you working on this one?
 if not can I?

**Comment by MasterBlaster99** [comment]
@itsPronay 
I have started working on it and will try to complete it by next weekend. Sorry for taking too long but this is my first contri at mifos

**Comment by itsPronay** [comment]
no worries! no need to be sorry @MasterBlaster99
