### ISSUE TITLE
Bug: topbar issue

### ISSUE THREAD

**Issue by itsPronay** [openMF/self-service-app#2599]
**Summary**

Double topbar in `SavingsMakeTransferComposeFragment` && no topbar in `HomeScreen`

**Steps to reproduce:**

1. goto `SavingsMakeTransferComposeFragment` screen
2. Select values and navigate to the next page ( `TransferProcessFragment` )
3. Press the back button of the phone (not the one in the UI). It takes you to `SavingsMakeTransferComposeFragment` where you'll be able to see double topbar
4.  Press back again -> Ignore warning -> There is no Topbar in the Home screen

**Screenshots:**

|SavingsMakeTransferComposeFragment|TransferProcessFragment|
|--------|------|
![image](https://github.com/openMF/mifos-mobile/assets/78101731/e0f4b591-c556-4234-9a86-d8154e70904b) | ![image](https://github.com/openMF/mifos-mobile/assets/78101731/ddb99210-17de-4413-af5e-3d9d0c521703)

**Comment by AvneetSingh2001** [comment]
@itsPronay  can you check if this issue still there?

**Comment by itsPronay** [comment]
@AvneetSingh2001  Not anymore, It was fixed by  `beneficiaryListFragment`.
