### ISSUE TITLE
AutoCompletion feature of username

### ISSUE THREAD

**Issue by ghost** [openMF/self-service-app#260]
It is very uncomfortable for users that they need to enter username every time they wanted to login , instead if the app stores usernames in shared preferences and suggests them accordingly user typing characters @therajanmaurya can i implement this feature... i think it is useful
<img width="180" alt="17622178_701905756637689_2063741492_o" src="https://cloud.githubusercontent.com/assets/14215902/24426376/249359fe-1425-11e7-9f6f-a5d59ce53722.png">

**Comment by ghost** [comment]
@therajanmaurya please tell me ,whether i proceed with this or not..

**Comment by dilpreet2028** [comment]
We might not be needing a autocomplete feature after the implementation of Passcode feature.
@therajanmaurya what do you think?

**Comment by therajanmaurya** [comment]
No, we don't need because of security.
