### ISSUE TITLE
refactor: Some parts of the code still use Color() instead of MaterialTheme colors, making the theme inconsistent.

### ISSUE THREAD

**Issue by Shermine237** [openMF/self-service-app#2636]
**Summary:**

Some parts of the code still use Color() instead of MaterialTheme colors, making the theme inconsistent.

**Steps to reproduce:**

Try changing the theme colors in theme.kt or style.xml and you'll see that some parts of the application remain unchanged. 

**Expected behaviour:**

Use MaterialTheme colors for a uniform theme. This makes it easier to change themes.

**Observed behaviour:**

In some parts of the code, the colors are hard-coded.

**Comment by therajanmaurya** [comment]
Closing in reference of https://github.com/openMF/mifos-mobile/pull/2644
