### ISSUE TITLE
Wrong Toast message on logging in with Username with less than 5 characters

### ISSUE THREAD

**Issue by aj019** [openMF/self-service-app#266]
**Summary:**
When the user enters a username with less than 5 characters and clicks on login. There is a toast message displays the Edittext text rather than the keyword username. For ex :- If i enter user in username the Toast message is "user cannot be less than 5 characters" but instead it should be "Username cannot be less than 5 characters"

**Steps to reproduce:**

Open the app
In Login enter user as your username
Enter password
Click on Login

**Expected behavior:**

A Toast mesage should have appeared saying "Username cannot be less than 5 characters"

**Observed behavior:**

A Toast mesage appeared saying "user cannot be less than 5 characters"

**Device and Android version:**

Nexus 5 API 23

**Screenshots:**
<img width="192" alt="screen shot 2017-03-30 at 6 54 45 am" src="https://cloud.githubusercontent.com/assets/7893859/24483442/cfaa6378-1515-11e7-8bcd-207167709005.png">

**Comment by aj019** [comment]
I would like to work on this issue

**Comment by dilpreet2028** [comment]
@therajanmaurya PR already merged closing issue
