### ISSUE TITLE
Review Transfer Dialog missing spacing between texts

### ISSUE THREAD

**Issue by aj019** [openMF/self-service-app#267]
**Summary:**

The text inside the Review Transfer dialog box are not clear. There is no spacing and the labels and the inputs are separated by a ":" symbol which makes it hard to read. There should be spacing between the texts and the labels should be in bold to differentiate from the input.
Look at the screenshot below for a better understanding.

**Steps to reproduce:**

Open the App
Go to Savings Account
Select a Saving Account
Click on Deposit
Enter details
Click on Review Transfer 

**Expected behavior:**

The labels should be in bold and the text should have some spacing

**Observed behavior:**

Currently the text is somewhat like this "Amount:965" rather than "**Amount** : 965"

**Device and Android version:**

Nexus 5 API 23

**Screenshots:**
<img width="243" alt="screen shot 2017-03-30 at 9 38 29 am" src="https://cloud.githubusercontent.com/assets/7893859/24487762/961cf516-152f-11e7-863e-3a9994de5ae3.png">

**Comment by aj019** [comment]
I would like to work on this issue

**Comment by dilpreet2028** [comment]
@therajanmaurya PR already merged, closing issue
