### ISSUE TITLE
Login Activity Shows Toast when Username has leading or trailing spaces.

### ISSUE THREAD

**Issue by KudzieChase** [openMF/self-service-app#284]
**Summary:**

The Login Activity Shows a toast message informing the user that they have spaces in their username even if that isn't obvious to them due to leading and trailing spaces.

**Steps to reproduce:**

- Open the application, insert the sample test username and insert a leading space.

- Proceed to login and see the issue.

**Expected behavior:**

I feel like the app should ignore all leading and trailing spaces.

**Observed behavior:**

The app shows a toast message when a user mistakenly inserts leading or trailing spaces in their input.

**Device and Android version:**

Android 6.0 Marshmallow on Sony M4 Aqua.

**Comment by thecskc** [comment]
Did you trim the string?

**Comment by KudzieChase** [comment]
Yes, if you checkout the pull request I made.. I've provided that fix @cskc97

**Comment by AbhilashG001** [comment]
Hi, @KudzieChase , I have already reported this issue and have also provided a fix for the same; please view the following -
https://github.com/openMF/self-service-app/pull/197#discussion-diff-106779308L62
https://github.com/openMF/self-service-app/issues/191
