### ISSUE TITLE
"About Us" doesn't work

### ISSUE THREAD

**Issue by thecskc** [openMF/self-service-app#287]
**Summary:**

When the About Us option is clicked from the navigation drawer, no new fragment/activity is opened.

**Steps to reproduce:**
Open the app, click About Us in the navigation drawer.

**Expected behavior:**

Either the option shouldn't exist or there should be something of value displayed to the user.

**Observed behavior:**

I saw the opening screen being replicated again.

**Device and Android version:**

Redmi Pro. MIUI

**Screenshots:**
![17820441_671648723045812_2112178206_o](https://cloud.githubusercontent.com/assets/16009358/24702333/e41d86a8-1a30-11e7-8b56-0212c28dfcea.png)

**Comment by thecskc** [comment]
@edcable  @therajanmaurya I'd like to work on this. Please let me know if I should remove the option or if there needs to be some content going in there. If there is any content that needs to be shown, please send me a txt file.
Thanks!

**Comment by dilpreet2028** [comment]
Issue already exists #127 
@therajanmaurya we should close this issue

**Comment by dilpreet2028** [comment]
Duplicate issue, closing
