### ISSUE TITLE
Status color of overpaid loan  accounts should be purple in stead of black. 

### ISSUE THREAD

**Issue by santoshconflux** [openMF/self-service-app#295]
In self-service-app , go to accounts and click on Loans tab. Check the status colors of accounts 027 and 028

![ss 1](https://cloud.githubusercontent.com/assets/23022667/25271026/49e0738a-26a0-11e7-9991-90e5007baf47.jpg)

On Web demo server for the client Smith W R

![demo](https://cloud.githubusercontent.com/assets/23022667/25271041/5cc58922-26a0-11e7-8b8c-f0a44b091282.png)

**Comment by dilpreet2028** [comment]
Fixed in #302
