### ISSUE TITLE
Listing of Loans Savings and Shares

### ISSUE THREAD

**Issue by santoshconflux** [openMF/self-service-app#298]
In the mobile app, the accounts Loans/Savings/Shares are listed  'old-to-recent' (unlike in web demo server) . Recent accounts should be on top with gradually going in previous dates. It is always good practice to  keep recent accounts on the top with the ease of approving/disbursing, rather than scrolling for some time in order to go to recent accounts.

**Comment by therajanmaurya** [comment]
Thanks @santoshmath, I debug the demo web app, It's calling the same API end point that is calling in self-service and android-client. 
To fix this issue I did not find any end parameter that give us the latest accounts according to time. 
So I think we have to invert the account list and then show.

@santoshmath Do you think, we have any parameter that can make our work easy.

**Comment by santoshconflux** [comment]
@therajanmaurya , I don't have any idea regarding parameter. :)

**Comment by therajanmaurya** [comment]
Ok, I will put this issue on high priority and will fix soon thanks for reporting.

**Comment by dilpreet96** [comment]
I also didnt found any parameter for sorting the accounts, if the endpoint could provide with timestamp for each account then it would be easier to sort accounts otherwise as @therajanmaurya said reversing of list can be done.

**Comment by dilpreet2028** [comment]
Mifos X Client show Loan,Saving and Share list in decreasing order of `id` attribute. https://demo.openmf.org/#/viewclient/1
Will be sending PR soon.
