### ISSUE TITLE
Loan updation implementation

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#303]
#### Steps 
- To update a loan,a new fragment will be created which can use the exisiting fragment_add_application layout as the api allows to update all the elements provided in the UI part of this layout but with a new presenter.
- LoanAccount(model) needs to be passed during the intialization
- ProductId retrieved from loanAccount will be used to call the template which requires ProductId. API used for fetching template:- 
  https://demo.openmf.org/fineract-provider/api/v1/self/loans/template?templateType=individual&clientId=1&productId=1&tenantIdentifier=default&pretty=true
- Existing values from the retrieved LoanAccount(model) will be displayed after fetching loan template.
- After the self service user has made the required changes then existing LoanPayload model can be used for making a (PUT) request to:- https://demo.openmf.org/fineract-provider/api/v1/self/loans/{loanId} 

@therajanmaurya do I need to make any modifications in this implementation?

**Comment by therajanmaurya** [comment]
@dilpreet96 No need to make new Fragment for the feature `update loan application`.  
Here are the things that you can follow during implementation.
1. Make an enum `LoanState` and create CREATE, EDIT inside it.
2. Pass this enum into a contractor.
3. If CREATE: do not do anything create loan application is already written.
4. If EDIT: make new API call to fetch the loan application and set the values in specific fields and make PUT API request while when user will submit the loan.
Note: Pass necessary fields too that is needed to fetch loan application.

Let me know If have any confusion.

**Comment by dilpreet2028** [comment]
Thank you @therajanmaurya . No confusion till now ,i'll ask if any.
