### ISSUE TITLE
Add more details to accounts list

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#306]
**Summary:**
Currently, Accounts List shows limited information, results from the *recent survey* recommends to add more description to each of the list item.
- `Loan Account List` should contain more details such as: Original Loan, Loan Balance and Amount Paid
- `Savings Accounts List` should also display Last Active and Balance
- `Share Accounts List` should also display Approved Shares and Pending for Approval Shares

**Comment by therajanmaurya** [comment]
@dilpreet96 Looks nice, please share this issue on slack channel with @edcable.
