### ISSUE TITLE
Savings charges Endpoint return 404 httpStatusCode

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#308]
**Summary:**

In order to implement Loan and saving charges, following endpoints need to be used:

#### For Loan (Works fine):-
https://demo.openmf.org/fineract-provider/api/v1/self/loans/28/charges?tenantIdentifier=default&pretty=true 

#### For Savings charges (`Problem`):-
Reference: https://demo.openmf.org/api-docs/apiLive.htm#selfsavingscharges
This api`returns httpStatusCode as 404`:- 
https://demo.openmf.org/fineract-provider/api/v1/self/savingsaccounts/38/charges?tenantIdentifier=default&pretty=true

But accountNumber 38 contains 1 charge which can be verfied by sending a request to the following api with admin credentails (Mifos: password)
https://demo.openmf.org/fineract-provider/api/v1/savingsaccounts/38/charges?tenantIdentifier=default&pretty=true 
Or can be checked in mifos X client: https://demo.openmf.org/#/viewsavingaccount/38

**Comment by edcable** [comment]
@nazeer1100126 can you please review this?

**Comment by dilpreet2028** [comment]
Fixed 
Loans and saving charges feature added in #343
