### ISSUE TITLE
Login to app

### ISSUE THREAD

**Issue by KevinGitonga** [openMF/self-service-app#311]
**Summary:**

During login the username should be stored in memory in that on next load the user only enters the password and gets loged in automatically.

**Comment by KevinGitonga** [comment]
Can be implemented using shared preferences.

**Comment by dilpreet2028** [comment]
For security reasons we are not performing this but thinking of implementing a passcode feature you can have a look at it here: #132

**Comment by KevinGitonga** [comment]
That is okay will work better for security reasons thanks @dilpreet96
