### ISSUE TITLE
Enchance Home Screen

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#313]
**Summary:**
Mock: 

<img src="https://user-images.githubusercontent.com/12071739/27262112-9b071016-546d-11e7-88c8-d09fe08064cc.png" height=450 width=250/>

Loan, Saving and share Account cards would give overview to user by:-
- Displaying a pie chart which represents number of accounts that are Pending for approval, active, closed or waiting for disbural with different colours for each type *i.e. account status*
- Displaying total *amount* in each type of account

@edcable @therajanmaurya @puneetkohli521, your reviews regarding this design.

**Comment by droidchef** [comment]
Looks Uber Cool ;)  @dilpreet96

**Comment by dilpreet2028** [comment]
Thankyou @droidchef, then I will start its implementation.
