### ISSUE TITLE
Make image and textview at centre 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#314]
**Summary:**

![](https://user-images.githubusercontent.com/12071739/26891647-681165dc-4bd3-11e7-96d5-013ed9c3e0ed.png)

As you can see the in this GIF, there a image and textview that is on the top but I want those at the centre.

**Comment by dilpreet2028** [comment]
Will send PR by today

**Comment by therajanmaurya** [comment]
Do according to your schedule.
