### ISSUE TITLE
Add Android Code Style 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#33]
Need to add code style in the project. 
@ishan1604 as we have talked earlier about the guidelines.
Please look [Android Code style](https://github.com/android/platform_development/blob/master/ide/intellij/codestyles/AndroidStyle.xml) and what are things that we do not need to follow like 

``` Xml
"FIELD_NAME_PREFIX" value="m" 
```

Need a suggestion which things we do not need to follow in code style.

**Comment by dilpreet2028** [comment]
Added in #326
