### ISSUE TITLE
Move the Toaster to the top right side of the device screen

### ISSUE THREAD

**Issue by ippezshelby** [openMF/self-service-app#385]
A client can not see Toaster Message when Device keyboard is on so it will be better to move the toaster to the top.

**Comment by dilpreet2028** [comment]
Snackbars(Toaster) are meant to be shown on the bottom of the screen and whenever a Snackbar appears the keyboard hides itself and then the snackbar is displayed.
Do you see any place where a snackbar hides below the keyboard ? if yes then please tell

**Comment by dilpreet2028** [comment]
A better validation has been added in #386 and snackbar are shown in bottom of screen.
