### ISSUE TITLE
Dollar sign is displayed after amount in total deposit

### ISSUE THREAD

**Issue by mayank8318** [openMF/self-service-app#399]
**Summary:**
Dollar(currency) is displayed after the amount.
It should be displayed before the amount.
**Steps to reproduce:**
Open any accounts details

**Expected behavior:**
Currency symbol should be displayed before the amount.

**Observed behavior:**
Currency symbol was displayed after the amount
**Device and Android version:**
Samsung Galaxy A5(2016)

**Screenshots:**
![image](https://user-images.githubusercontent.com/22395998/29968368-ff0f0b30-8f38-11e7-821d-82d5d673ba69.png)

**Comment by dilpreet2028** [comment]
@mayank8318 If you want to fix it then go ahead

**Comment by mayank8318** [comment]
@dilpreet96 yes cool I will submit a PR asap :)

**Comment by mayank8318** [comment]
@dilpreet96 I have created the PR.
Please have a look.
Thanks!
