### ISSUE TITLE
Translate Mobile Banking App into the following languages

### ISSUE THREAD

**Issue by edcable** [openMF/self-service-app#403]
A number of languages are most commonly requested by our community. We need the strings translated for the following languages. 

Easy-to-follow instructions on how to Translate Strings for the field office app have been provided by @tarun0 at https://github.com/openMF/android-client/wiki/Translation. The process will be similar here. 

Translations are needed for 

- [ ] Arabic (ar)
- [ ] French (fr)
- [ ] Spanish (es)
- [ ] Portuguese (pt)
- [ ] Simplified Chinese (zh-hans)
- [ ] Khmer (km)
- [x] Hindi (hi)
- [ ] Swahili (sw)
- [ ] Russian (ru)
- [ ] Burmese (my)

Translation files can be found under the res directory: 
https://github.com/openMF/self-service-app/tree/development/app/src/main/res

**Comment by amanjeetsingh150** [comment]
Hey,
@dilpreet96 and @therajanmaurya, Sir I would like to translate these strings for Hindi language. Please assign this to me.
Thanks

**Comment by dilpreet2028** [comment]
You can go ahead @amanjeetsingh150

**Comment by edcable** [comment]
Thanks guys! You are too fast. I was replying...@amanjeetsingh150 Feel free to start with the translation and submit a pull request with the translated file when you've completed the work.
