### ISSUE TITLE
Unable to login in the self service app when i changed it to my local mifos x system

### ISSUE THREAD

**Issue by amasdeogratias** [openMF/self-service-app#411]
When i changed self service app from accessing data from mifos x demo to my local mifos x i installed in my machine(ubuntu), it has stopped to login and fetch clients.

When i click login button, it loads for 15 to 20 seconds then it stop without any errot
Am using the defaults username and password
username = "selfservice"
password = "password"

Am developing self service app in ubuntu 14.04 and also using android studio version 2.3

**Comment by therajanmaurya** [comment]
@amasdeogratias We already added the support for the local backend. If I am not wrong, there is no Self-service user present in your backend with these credentials. If yes then please share the log of the android studio.

**Comment by therajanmaurya** [comment]
@amasdeogratias Please check web app, we have up and running feature to create a new self-service user, So create a self-service user from there and log in again. I am sure that will work. It is fully tested.

If you have any question feel free to open issue again.

**Comment by Jomka-akmoJ** [comment]
> [@amasdeogratias](https://github.com/amasdeogratias) Please check web app, we have up and running feature to create a new self-service user, So create a self-service user from there and log in again. I am sure that will work. It is fully tested.
> 
> If you have any question feel free to open issue again.

The self-service user creation does not work. 

![Image](https://github.com/user-attachments/assets/b6388006-1329-4e0b-96ce-3fbd849abf12)

The "submit" button is unresponsive.

When trying to create a self service user through the client the website is broken.

![Image](https://github.com/user-attachments/assets/9bb745b5-cd7b-46f6-b7a8-77cf8ad16535)

If i make the mifos admin user a self-service user and use the self service app afterwards to log in it is not working.

![Image](https://github.com/user-attachments/assets/35dd2688-31bb-4ab7-b6b3-0bb0f3b280f3)
