### ISSUE TITLE
In Home "contact us " in bottom is overlapping with the button navigation 

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#415]
**Summary:**

On home "Contact Us" in bottom shouldn't overlap with button navigation .  

**Steps to reproduce:**

Open Home 

**Expected behavior:**

They should have  sufficient margin . 

**Observed behavior:**
Both of them are overlapping (Contact us and lower button navigation ).

**Device and Android version:**
Moto G Turbo (6.0.1)

**Screenshots:**

![screenshot_20170922-162144](https://user-images.githubusercontent.com/24601454/30741561-e62d93c2-9fb2-11e7-997e-e2bcac40d5ee.png)

I would like to work on this issue.

**Comment by dilpreet2028** [comment]
Go ahead @ivary43

**Comment by luckyman20** [comment]
@therajanmaurya @dilpreet96 @edcable Can I go ahead with this issue ?

**Comment by dilpreet2028** [comment]
This issue has been fixed due to the new UI for the dashboard
