### ISSUE TITLE
Abrupt opening of "Account Overview" on Home 

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#416]
**Summary:**
There is abrupt opening of "Account view" on click ,there should be a slide animation for opening and closing of that for better view 

**Steps to reproduce:**
Go to Home and click on "Account Overview" .

**Expected behavior:**
There should be slide animation for opening and closing of "Account Overview" on click . 

**Observed behavior:**
There is disrupt opening and closing of "Account Overview " on clicking it .It should be done with slide animation for better view .

**Device and Android version:**
Moto G-3 turbo(6.0.1)

I would like to work on  this issue .

**Comment by therajanmaurya** [comment]
@ivary43 Make sense, I think `android:animateLayoutChanges="true"` is sufficient for this.
Add in LinearLayout that you want to hide and show.

**Comment by ivary43** [comment]
@therajanmaurya I will do it ..🙂

**Comment by ivary43** [comment]
@therajanmaurya android:animateLayoutChanges="true" is not working ...i tried . Should i do it with java ?

**Comment by luckyman20** [comment]
@therajanmaurya Can I work on this issue ?

**Comment by therajanmaurya** [comment]
According to new Dashboard, this issue does not exist anymore.

**Comment by ivary43** [comment]
@therajanmaurya  this issue is present in current UI .So what should i do means should i make a new issue or the downgrading to the current UI is for small duration so should I leave ?
