### ISSUE TITLE
Text colour is not visible inside the button .

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#417]
**Summary:**

Text in the button view is not visible in cancel button  due to same font and background colour .

**Steps to reproduce:**
Drawer item ->Third party transfer -> After filling dummy data in entry 

**Expected behaviour:**

Button theme should match the main theme Color and text inside the button should be visible .

**Observed behavior:**
The cancel  button was of default size and text colour was not visible due to match of text colour with background colour .

**Device and Android version:**
Moto G-3 turbo .(6.0.1)

**Screenshots:**
![screenshot_20170922-201032](https://user-images.githubusercontent.com/24601454/30750648-a8ed6ff6-9fd4-11e7-9080-42b4d9b46387.png)
I would like to work on this issue.

**Comment by therajanmaurya** [comment]
@ivary43 welcome to community, Go ahead send a PR 👍

**Comment by ivary43** [comment]
@therajanmaurya I will do it as soon as possible .

**Comment by luckyman20** [comment]
@therajanmaurya @edcable Can I work on this issue ?

**Comment by dilpreet2028** [comment]
@luckyman000786, @ivary43 is already working on it #427
