### ISSUE TITLE
FAQ doesn't close upon re-clicking 

### ISSUE THREAD

**Issue by mayank8318** [openMF/self-service-app#422]
**Summary:**

When the user clicks on an open FAQ it should close.

**Steps to reproduce:**

Go to help section and open an FAQ.

**Expected behavior:**

The FAQ should close on re-clicking.

**Observed behavior:**

There is no response to the touch event.

**Device and Android version:**

Samsung Galaxy A5(2016)

**Screenshots:**

![21536115_1813174755377997_1040612400488775680_n](https://user-images.githubusercontent.com/22395998/30774494-ed8d686a-a0a0-11e7-9966-09363d7be3ac.gif)

I would like to work on this one.

**Comment by therajanmaurya** [comment]
Go ahead send PR
