### ISSUE TITLE
Wrong drawer item highlighted 

### ISSUE THREAD

**Issue by mayank8318** [openMF/self-service-app#423]
**Summary:**

When user goes to About Us section, Help is highlighted in drawer.

**Steps to reproduce:**

Go to About Us section and open the drawer.

**Expected behavior:**

About Us should be highlighted.

**Observed behavior:**

Help was highlighted.

**Device and Android version:**

Samsung Galaxy A5(2016)

**Screenshots:**

![21536184_1813191605376312_1975594439724236800_n](https://user-images.githubusercontent.com/22395998/30774601-dac404d0-a0a2-11e7-8f69-5e07ce253ef1.gif)

Yes I would like to work on this issue.

**Comment by dilpreet2028** [comment]
Go ahead @mayank8318
