### ISSUE TITLE
Account page is not opening properly while opening from home page.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#424]
**Summary:**

The homepage layout is still floating over the account page when opened while the homepage is still loading .The homepage layout shouldn't be floating above the  account page .

**Steps to reproduce:**

Open the account page when the homepage is still loading .

**Expected behavior:**
Homepage shouldn't be floating over the account page when it is opened while the homepage is still loading .

**Observed behavior:**

When account page was opened from the homepage while home page was still loading ,the account page opened in the background with homepage layout floating over it .

**Device and Android version:**
Moto G-3 turbo (6.0.1)

**Screenshots:**
![screenshot_20170925-190211 1](https://user-images.githubusercontent.com/24601454/30814942-3dbd7aca-a22f-11e7-85c6-424233e40ae9.png)

I would like to work on this issue .

**Comment by dilpreet2028** [comment]
Go ahead 👍

**Comment by luckyman20** [comment]
@dilpreet96 @therajanmaurya I think this issue should be closed now as this is fixed in Pull Request #463.

**Comment by therajanmaurya** [comment]
Yeah, @luckyman000786 thanks, As we have new home dashboard this issue no longer useful.
