### ISSUE TITLE
Improve UI of empty accounts screen

### ISSUE THREAD

**Issue by mayank8318** [openMF/self-service-app#433]
**Summary:**

The current UI of empty accounts has a few bugs.

**Steps to reproduce:**

Open accounts.

**Expected behavior:**

The error view should be centered and the loader should stop.

**Observed behavior:**

The error view was not centered and the loader did not stop.

**Device and Android version:**

Samsung Galaxy A5(2016)

**Screenshots:**

![21753517_1820748477953958_6625945566226415616_n](https://user-images.githubusercontent.com/22395998/31049206-ee46644a-a64b-11e7-80ab-f39c48eccc52.gif)

Yes I would like to work on this one.

**Comment by therajanmaurya** [comment]
I am working on a library to manage this thing, Very soon I will share the library then you can work on the implementation till that I don't think we need to talk more.
