### ISSUE TITLE
Unable to Create New user/account for a client showing the error: Client not found with basic details

### ISSUE THREAD

**Issue by santoshconflux** [openMF/self-service-app#445]
I tried creating new account for this client

https://demo.openmf.org/#/editclient/3326

I tried with client account number 000003326 and also external ID 19000

**Comment by dilpreet2028** [comment]
@santoshmath Please try creating a client on https://mobile.openmf.org/#/ as we are using this instance for debug version of the app.

**Comment by santoshconflux** [comment]
@dilpreet96 , thanks. I am to create the account.

**Comment by dilpreet2028** [comment]
Closing as issue was fixed
