### ISSUE TITLE
End Date datepicker should be initialised to the date of start date

### ISSUE THREAD

**Issue by mayank8318** [openMF/self-service-app#446]
**Summary:**

Currently the end date is not set for the datepicker.

**Steps to reproduce:**

Open end date datepicker in any activity.

**Expected behavior:**

The minimum allowed date on the datepicker should be the start date.

**Observed behavior:**

All the dates were allowed in the end date and the error message was only displayed when the form was submitted.

**Device and Android version:**

Samsung A5(2016)

**Comment by mayank8318** [comment]
@therajanmaurya Can I work on this issue?

**Comment by therajanmaurya** [comment]
Go ahead send PR

**Comment by luckyman20** [comment]
@therajanmaurya @edcable @dilpreet96 Can I work on this issue?

**Comment by srv-twry** [comment]
@therajanmaurya @dilpreet96 can i work on it if it's available ?

**Comment by luckyman20** [comment]
@mayank8318 Please let us know if you are still working on this issue. I am ready with a solution of this issue and ready for firing up the PR.

**Comment by mayank8318** [comment]
@luckyman20 Please go ahead with your PR :)
