### ISSUE TITLE
Currency symbol displayed as null

### ISSUE THREAD

**Issue by mayank8318** [openMF/self-service-app#447]
**Summary:**

Currency symbol is displayed as null in Charges screen.

**Steps to reproduce:**

Open the charges tab.

**Expected behavior:**

It should have the appropriate currency sign.

**Observed behavior:**

null is displayed instead of the currency sign.

**Device and Android version:**

Samsung A5(2016)

**Screenshots:**

![image](https://user-images.githubusercontent.com/22395998/31458159-c9c0b5fa-aedc-11e7-8fcb-4fbfc9331dd2.png)

**Comment by mayank8318** [comment]
@therajanmaurya Certain currencies like Tanzanian Shilling[TZS] for example, don't have a currency symbol, so null is displayed instead.

**Comment by therajanmaurya** [comment]
I think while currency should not be null from the server in any case.

What do you think @edcable  @nazeer1100126 @santoshmath

**Comment by santoshconflux** [comment]
Yes, that's correct. @therajanmaurya , Did you see the same on Web side as  well?

**Comment by therajanmaurya** [comment]
No, Can you send me the link here.

**Comment by mayank8318** [comment]
@therajanmaurya To check which currency it was I displayed the currency label : 
![image](https://user-images.githubusercontent.com/22395998/31539990-fbe30e4c-b027-11e7-9d18-98bcd41f3491.png)

**Comment by therajanmaurya** [comment]
@mayank8318 First, The issue I am opening with labels `GCI 2017` It's for GCI students and We are going to participate, So Please wait if you are GCI student and If you want to resolve some issues, I am going to open issue very soon on mifos android-client that will be available for everyone.

**Comment by therajanmaurya** [comment]
And Second about the Patch you send, It's good but It's temporary according to UX because as Currency name will become out of the box, It will destroy UX, so we will stay to currency symbol.

**Comment by mayank8318** [comment]
@therajanmaurya I am not participating in GCI 2017. So I should leave issues labelled as GCI 2017 right?

**Comment by therajanmaurya** [comment]
Yes, that would be fine. I will create some other issues for you and will mention you if you want to work.

**Comment by mayank8318** [comment]
@therajanmaurya Yes I am interested to work. Please mention me in such an issue:)
Thanks

**Comment by santoshconflux** [comment]
May I know the link of Web side where this screenshot is taken?

**Comment by mayank8318** [comment]
@santoshmath This was taken in the app itself as I wanted to see if the Currency object was valid or not.

**Comment by santoshconflux** [comment]
No. My question was, To which platform(Ex: demo.openmf, mobile.openmf,etc) it  is  coneected? and also the User?

Cc: @therajanmaurya

**Comment by therajanmaurya** [comment]
It is connected to mobile.openmf and with the username: selfservice and Password: password.
