### ISSUE TITLE
Add : LoanAccount Status (Active or not) in LoanAccount list item.

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#45]
In current user is able to see the LoanAccount list but there is no sign to see. what is the status of LoanAccount. it is Active or not.

How to achieve this issue : 
- Add a circular Image view in LoanAccount Item list in Adapter .
- show the status of the LoanAccount.

**Comment by ashu-dadhich** [comment]
can I work on it @therajanmaurya

**Comment by therajanmaurya** [comment]
Yeah,  Go ahead. In which issue you have to add image view in  LoanAccount Adapter.
and UI would be like this. I am talking about the Image for showing the status.
![group 13](https://cloud.githubusercontent.com/assets/5724482/19828665/32f5698a-9dea-11e6-83e4-296d99d73762.png)

**Comment by ashu-dadhich** [comment]
Yeah got it @therajanmaurya  thanks

**Comment by therajanmaurya** [comment]
@top-gun007 You were asking me, how will you get Account status. 
Please look into the LoanAccountListAdapter, you will found `private Status` field.
that will give you the status of the Account. 
Sorry, I have missed getter setter when I was fixing the POJO. So make the getter setter of the LoanAccountListAdapter and you are able to access the Status of the Account.

I want from this issue only : 
- Add Circular ImageView or you can use VIew Class instead because we want to fill the color in the view. So Please Use View.
  For Example : http://stackoverflow.com/a/14209836/3176277.
- Set any random color in Adapter that is already present in colors.xml. Do not need to add any exatra color.

**I will open separate issue for this setting correct color order for account in Adapter for both Savings and Loan.**

**Comment by therajanmaurya** [comment]
Fixed in #54
