### ISSUE TITLE
Show Error Message, If Transfer request failed

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#452]
**Summary:**

Whenever a user is making any type of Transfer and If the request failed due to some reasons like No Internet or Socket Exception etc. It's showing empty Snack Bar without a message. It should show message `Unable to make Transfer, Please Transfer later`

**Steps to reproduce:**

Go to Transfer in Navigation and enter details and disconnect the internet.

**Expected behavior:**

It should show a proper message, So the user should know what happened, why a user can't make transfer right now.

**Observed behavior:**

It's showing empty Snack Bar

**Device and Android version:**

Moto G

**Comment by mdew192837** [comment]
@therajanmaurya See my comment on the pull request. I think that message is better. Sorry for the confusion, I made the comment accidentally on my brother's Github account.

**Comment by therajanmaurya** [comment]
It's ok, @mdew192837 I will see.

**Comment by luckyman20** [comment]
@therajanmaurya @dilpreet96 @edcable This [GCI Task](https://codein.withgoogle.com/tasks/4858216947122176/?sp-organization=6239808655458304) should be closed now

**Comment by mofetej** [comment]
Please how can i get pass the login/register activity to use the app
