### ISSUE TITLE
Cancel Button is not working in "third party transfer". 

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#453]
**Summary:**

Cancel button is not working in "Third Party transfer" section .

**Steps to reproduce:**
Go to navigation Transfer->Third Party Transfer .Fill the details and click on cancel .

**Expected behavior:**
On clicking on cancel it should cancel the transfer and finish the activity .

**Observed behavior:**

On clicking on cancel .Nothing was happening .

**Device and Android version:**
Moto G3 (6.0.1) 

I would like to work on this issue .

**Comment by therajanmaurya** [comment]
To fix this issue  call ` getActivity().getSupportFragmentManager().popBackStack();` on click `Cancel` button.

**Comment by ivary43** [comment]
I have solved it ,should i send a PR ? I am not a GCI student .

**Comment by therajanmaurya** [comment]
@ivary43 Please wait these are issues for GCI student, It's very small, you know that I will open issue for you by tomorrow you can solve them.

**Comment by ivary43** [comment]
Sorry for the trouble i was confused. .

**Comment by sombuddha2016** [comment]
hey I am a GCI student....Can I work on this task?

**Comment by dilpreet2028** [comment]
Hello @sombuddha2016 , yes you can but first you have to claim this task from your google codein dashboard.
