### ISSUE TITLE
Fix Cancel Button Background Borderless in Normal Transfer (SavingsMakeTransferFragment)

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#454]
**Summary:**

When user make the `SavingsMakeTransferFragment` Transfer and after completing the form `Cancel` button is borderless that should not according to UX.

**Steps to reproduce:**

Click on Transfer on Home Dashboard and select `Transfer` and fill the form and you can view `Review` and `Cancel` button

**Expected behavior:**

`Cancel` Button should not border less. 

**Observed behavior:**

`Cancel` Button is border less

**Device and Android version:**

Moto G

**Comment by therajanmaurya** [comment]
To fix this issue go to `fragment_third_party_transfer` layout and in the bottom set `Cancel` button background tint color ` app:backgroundTint="@color/white"` and remote border less style.

**Comment by ivary43** [comment]
Can i Work on this issue @therajanmaurya ?

**Comment by therajanmaurya** [comment]
@ivary43 Please wait, I am creating these issue for GCI 2017 because we are going to participate.
If you wanna work on the issue. I will open issue in Android-client very soon. you can work on these.
