### ISSUE TITLE
Minor  Spelling Mistakes

### ISSUE THREAD

**Issue by santoshconflux** [openMF/self-service-app#455]
When you go to Home page>Accounts>Loan (or Saving or Share) and if client has no accounts , the message shows:
Their is no SavingsAccount associated with you.
Their is no LoanAccount associated with you.
Their is no ShareAccount associated with you.
Their is no transactions associated with you(In Recent Transactions)

It should be 'There' .

You have to correct the spellings from this line: https://github.com/openMF/mifos-mobile/blob/development/app/src/main/res/values/strings.xml#L123 to this line https://github.com/openMF/mifos-mobile/blob/development/app/src/main/res/values/strings.xml#L127

**Comment by ghost** [comment]
I'd like to work on this issue
