### ISSUE TITLE
Add Logout Feature in self service app

### ISSUE THREAD

**Issue by amasdeogratias** [openMF/self-service-app#459]
The logout feature help clients to sign out from the app for security purposes

Logout feature or button can be created in the navigation drawer or as the toolbar 
in the clients profile
Then it will be implemented in java class

**Comment by therajanmaurya** [comment]
@amasdeogratias I think there is some misunderstanding about the current and old code base. It's already implemented. I will recommend you please pull the code base again and build.

Closing this issue for Now.
