### ISSUE TITLE
Feature ShareAccounts.

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#46]
Add feature ShareAccounts in ClientAccountFragment ViewPager.

How to achieve : 
Add ShareAccount Adapter
Add UI for ShareAccount list item.
Add method in ClientAccounts that will update the UI in AccountFragment to show the ShareAccount.
@edcable Can you please suggest, what are the fields we need to show in share account list item.

**Comment by puneetkohli521** [comment]
@therajanmaurya I will take up this, will ask questions if any

**Comment by therajanmaurya** [comment]
Yeah, Go ahead. I have created demo for share accounts 👍 
You have now demo data for testing.

Let me know, if you have need any help.

**Comment by mayank-kgp** [comment]
@puneetkohli521 @therajanmaurya I would like to know the status of task.
If nobody is working on this issue, I would like to work on.

**Comment by therajanmaurya** [comment]
Fixed in #81
