### ISSUE TITLE
In Saving Account Details, when offline, error message is not aligned properly

### ISSUE THREAD

**Issue by luckyman20** [openMF/self-service-app#461]
**Summary:**

If a User is offline, and user goes to Saving Account Details, the error is not aligned well

**Steps to reproduce:**

Home --> Accounts --> Any Saving Accounts

**Expected behavior:**

Error message should be aligned properly.

**Observed behavior:**

Error message is showing at top center position, icon and text are colliding. 

**Device and Android version:**

Coolpad Cool 1 (Android 6.0.1 Marshmallow)

**Screenshots:**

![screenshot_20171015-220345](https://user-images.githubusercontent.com/20682192/31586864-01d73124-b1f5-11e7-9151-23ec5793e0ff.jpg)

@naman14 @therajanmaurya @dilpreet96 Can I work on this issue ?

**Comment by sashank27** [comment]
@luckyman20 @dilpreet96 @therajanmaurya Can I work on this issue if it is still open and available ?
