### ISSUE TITLE
In Saving Account Details, Min. Required Bal. field shouldn't be empty

### ISSUE THREAD

**Issue by luckyman20** [openMF/self-service-app#465]
**Summary:**

When a user is checking a saving account Min Required Balance is empty because it was not specified when creating the account.

**Steps to reproduce:**

Home --> Accounts --> Any Savings Account

**Expected behavior:**

If there was no Min. Required Balance specified at the time of creating the savings account. Then Min. Required Balance should show `Not Applicable`

**Observed behavior:**

The Min. Required Balance is empty in many savings account as it was not specified at time of creating the savings account

**Device and Android version:**

Coolpad Cool 1 (Android 6.0.1 Marshmallow)

**Screenshots:**

![screenshot_20171016-112636 1](https://user-images.githubusercontent.com/20682192/31597271-27e8db90-b265-11e7-93e7-67cb0f0e5c2c.jpg)

@therajanmaurya @dilpreet96 Can I work on this issue ?

**Comment by geekanamika** [comment]
Can I work on this issue if still open and available ? @luckyman20 @dilpreet96 @therajanmaurya

**Comment by dilpreet2028** [comment]
@luckyman20 are you working on this, if not @geekanamika you can take this issue. And incase of showing "Not applicable" hide the heading text i.e. 'Min. Required Bal'

**Comment by geekanamika** [comment]
@dilpreet96 @luckyman20 Thank you , I am working on this issue now :)
