### ISSUE TITLE
Remove "None" from Filter accounts Dialog

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#466]
**Summary:**

Filter Dialog for Savings, Loans and Sharing Accounts now has the option to `Clear Filters` so `None` option should be removed from the list.

Remove `None` from all the lists given in <a href ="https://github.com/openMF/self-service-app/blob/development/app/src/main/java/org/mifos/selfserviceapp/utils/StatusUtils.java">StatusUtils class</a> and logic for checking `None` in `Accounts Presenter class`

**Steps to reproduce:**

Go to Accounts -> Click on top right most icon (3 bars) to see the filter dialog .

**Comment by mkmar01** [comment]
@dilpreet96 may I send a PR for this?

**Comment by luckyman20** [comment]
@batbrain7 Are you participating in this year's GCI?

**Comment by mkmar01** [comment]
@luckyman000786 for next year's gsoc perhaps

**Comment by luckyman20** [comment]
@batbrain7 Sorry, this issue is only available for GCI students as of now

**Comment by mofetej** [comment]
Hello, I claimed this tasked how do i submit. should i create a PR
