### ISSUE TITLE
Feature Recurring Account

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#47]
Add feature Reoccurring Accounts in ClientAccountFragment ViewPager.

How to achieve : 
Add Reoccurring Account Adapter
Add UI for Reoccurring Account list item.
Add method in ClientAccounts that will update the UI in AccountFragment to show the ShareAccount.
@edcable Can you please suggest, what are the fields we need to show in Reoccurring account list item

Till that show the Reoccurring Account name and Account id in the list Item.

**Comment by puneetkohli521** [comment]
@therajanmaurya I will take up this, will ask questions if any

**Comment by edcable** [comment]
@therajanmaurya Sorry i didn't address these comments. I'm trying to get the accounts set up but I'm running into issues with the interest rate charts. However for recurring deposit accounts we should display: 
- Recurring Deposit Amount
- Next Meeting Date
- Meeting frequency
- Nominal Interest Rate
- Current interest earned to date
- Total balance
- Maturity Date

You can reference the mockup for new web app summary at https://openmf.mybalsamiq.com/projects/accountsummaryview/Recurring%20Deposit%20Summary%20Page

**Comment by icancode23** [comment]
@therajanmaurya sir has this feature been implemented..? or can i try this...

**Comment by mkmar01** [comment]
@therajanmaurya May I add this feature?
