### ISSUE TITLE
Give preference to Account Balance shown in Savings and Loan Account Details

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#473]
**Summary:**

Account Balance shown in Savings and Loan Account Details should be given more preference than other things shown.
<img src = "https://user-images.githubusercontent.com/12071739/32075115-5ab04250-bab9-11e7-9bdd-04f00ca07982.png" width = 250 height =400/>
 
Shift Account Balance to the top and increase it's size and make the amount bold.

**Comment by Rish02Sharma** [comment]
@dilpreet96 Can I work on this?

**Comment by luckyman20** [comment]
@dilpreet96 @edcable @therajanmaurya I think this should be closed now as this is solved already

**Comment by fazerlicourice7** [comment]
This [GCI task](https://codein.withgoogle.com/tasks/6144978545803264/?sp-organization=6239808655458304) should be removed.
