### ISSUE TITLE
Ability for clients to Apply for loans

### ISSUE THREAD

**Issue by awasum** [openMF/self-service-app#48]
Client applies for loan using mobile app.
Loan officer approves loan.
Loan disbursed to clients savings account or mobile money account.

**Comment by therajanmaurya** [comment]
@edcable, have a look this issue.

**Comment by awasum** [comment]
Linked to #60 #59 #57 as prerequisites.

**Comment by therajanmaurya** [comment]
I am looking closely all user stories and found that these are related to the validation and adding some extra paramter to validate user and thier accounts.
And after that i have looked the Self-Service REST API for applying loan(https://demo.openmf.org/api-docs/apiLive.htm#selfloanapply). In Present we are authenticating user with access token during fetching accounts, Client Charges etc.

Accourding to Self-Service[ REST API](https://demo.openmf.org/api-docs/apiLive.htm#selfloanapply), we need these paramter to Apply for the Loan Account.
First one Access Token to Authenticate and second one is
```
{
    "dateFormat": "dd MMMM yyyy",
    "locale": "en_GB",
    "clientId": 1,
    "productId": 1,
    "principal": "10,000.00",
    "loanTermFrequency": 12,
    "loanTermFrequencyType": 2,
    "loanType": "individual",
    "numberOfRepayments": 10,
    "repaymentEvery": 1,
    "repaymentFrequencyType": 2,
    "interestRatePerPeriod": 10,
    "amortizationType": 1,
    "interestType": 0,
    "interestCalculationPeriodType": 1,
    "transactionProcessingStrategyId": 1,
    "expectedDisbursementDate": "10 Jun 2013",
    "submittedOnDate": "10 Jun 2013",
    "linkAccountId" : "1",
    "fixedEmiAmount":1100,
    "maxOutstandingLoanBalance":"35000",
    "disbursementData":[{"expectedDisbursementDate":"01 November 2013",
    					"principal":22000,"approvedPrincipal":22000}]
}
```
So I think we are able to implement Apply for loan with current Loan Account [REST API ](https://demo.openmf.org/api-docs/apiLive.htm#selfloanapply).

**Comment by therajanmaurya** [comment]
I am looking closely all user stories and found that these are related to the validation and adding some extra parameter to validate the user and their accounts.
And after that, i have looked the Self-Service REST API for applying loan(https://demo.openmf.org/api-docs/apiLive.htm#selfloanapply). In Present we are authenticating the user with access token during fetching accounts, Client Charges etc.

According to Self-Service[ REST API](https://demo.openmf.org/api-docs/apiLive.htm#selfloanapply), we need these parameters to Apply for the Loan Account.
First, one Access Token to Authenticate user and the second one is this request body.

```
{
    "dateFormat": "dd MMMM yyyy",
    "locale": "en_GB",
    "clientId": 1,
    "productId": 1,
    "principal": "10,000.00",
    "loanTermFrequency": 12,
    "loanTermFrequencyType": 2,
    "loanType": "individual",
    "numberOfRepayments": 10,
    "repaymentEvery": 1,
    "repaymentFrequencyType": 2,
    "interestRatePerPeriod": 10,
    "amortizationType": 1,
    "interestType": 0,
    "interestCalculationPeriodType": 1,
    "transactionProcessingStrategyId": 1,
    "expectedDisbursementDate": "10 Jun 2013",
    "submittedOnDate": "10 Jun 2013",
    "linkAccountId" : "1",
    "fixedEmiAmount":1100,
    "maxOutstandingLoanBalance":"35000",
    "disbursementData":[{"expectedDisbursementDate":"01 November 2013",
                        "principal":22000,"approvedPrincipal":22000}]
}
```

So I think we are able to implement Apply for loan with current Loan Account [REST API ](https://demo.openmf.org/api-docs/apiLive.htm#selfloanapply).

**Comment by therajanmaurya** [comment]
Here you go @DanCarl857 If you need any help feel free to ask 👍

**Comment by therajanmaurya** [comment]
Added in #139
