### ISSUE TITLE
Use annotationProcessor instead of android-apt plugin (deprecated in 3.0)

### ISSUE THREAD

**Issue by mdew192837** [openMF/self-service-app#481]
**Summary:**

android-apt plugin is deprecated in Android-Studio 3

**Steps to reproduce:**

1. Install Android Studio v3.
2. Try to let gradle sync

**Expected behavior:**
1. Gradle should sync

**Observed behavior:**
2. Build yields following error:
- Error:android-apt plugin is incompatible with the Android Gradle plugin.  Please use 'annotationProcessor' configuration instead.

**Comment by therajanmaurya** [comment]
Fix in #480
