### ISSUE TITLE
Reducing Apk Size 

### ISSUE THREAD

**Issue by Rish02Sharma** [openMF/self-service-app#483]
Apk size can be reduced significantly:

Removing unused import statements.

Removing unused XML Schema declaration.

Removing unused property.

and much more which can reduce the apk size a lot.

@therajanmaurya can I work on this??

**Comment by therajanmaurya** [comment]
@Rish02Sharma Please expand, Give me an example because PMD and FindBugs checks check these things.

**Comment by naman14** [comment]
Yeah
Removing unused imports - Checkstyle already takes care of that, there are no unused imports in the app. I am also sure FindBugs also takes care of the unused properties also 

Besides, I think doing changes in code wouldn't have any significant change in the APK size.

**Comment by Rish02Sharma** [comment]
@therajanmaurya @naman14 Yeah I didn't knew much about the FindBugs. But Does proguard work on the resources side? I think it works only for Java side. So if an image in res/drawable is not used, Proguard only strips it’s reference in the R class but keeps the associated image in place.

**Comment by therajanmaurya** [comment]
@Rish02Sharma I don't think there is an unused image in the drawable folder. Please expand and let me know if you find any.

**Comment by Rish02Sharma** [comment]
@therajanmaurya Sure, I'll look into it.

**Comment by luckyman20** [comment]
@therajanmaurya @Rish02Sharma @naman14 How about crunching/compressing the png and jpeg files?

**Comment by Rish02Sharma** [comment]
@luckyman000786 I don't think so there are many large sized png or jpeg files as maximum resource files are made from Android shape drawable which consumes less space than other formats.

**Comment by luckyman20** [comment]
@Rish02Sharma Yes I agree that but we can reduce somewhat by that

**Comment by therajanmaurya** [comment]
I don't think, this discussion needs to carry on because we already using vector drawable and FindBugs, CheckStyle, PMD for code quality. These things take care of everything.

If you have any question feel to open the issue again.
