### ISSUE TITLE
App should open Login Activity when pressed back button in Register Activity

### ISSUE THREAD

**Issue by Rish02Sharma** [openMF/self-service-app#484]
When pressed back button on Register user Activity app should open Login Screen but in reality, back button is closing the app.

**Comment by srv-twry** [comment]
@dilpreet96 @Rish02Sharma Can i take it if it's available

**Comment by dr0pdb** [comment]
@dilpreet96 @Rish02Sharma Is it available ? If yes i would like to work on it.

**Comment by therajanmaurya** [comment]
Good catch.

**Comment by therajanmaurya** [comment]
Feel free to pick issue and send PR.

**Comment by ivary43** [comment]
@therajanmaurya  can I work on this issue?
