### ISSUE TITLE
Can't view account details for share accounts

### ISSUE THREAD

**Issue by edcable** [openMF/self-service-app#486]
**Summary:**
From list of share accounts, I should be able to click each share account and view details of the account. However each link is not clickable. 

**Steps to reproduce:**

Navigate to Accounts, Click Shares, Try to Click any Account from the List regardless of Status

**Expected behavior:**

Link successfully goes to the Account Details/Overview page

**Observed behavior:**

Not able to click the link. 

**Screenshots:**
![screenshot_20171114-164641](https://user-images.githubusercontent.com/823454/32959346-336a670c-cb76-11e7-892c-27923e3bcbdc.jpg)

**Comment by dilpreet2028** [comment]
@edcable we don't have any api for share account details.

**Comment by therajanmaurya** [comment]
Ok, @edcable I have created a ticket for this: https://issues.apache.org/jira/browse/FINERACT-596

**Comment by santoshconflux** [comment]
@edcable , @therajanmaurya , @miPlodder 

API development is done and the ticket is resolved.
 https://issues.apache.org/jira/browse/FINERACT-596

Tested in latest self service apk and it is yet to be implemented in front end self service app.

**Comment by miPlodder** [comment]
@Santosh Math <santosh@confluxtechnologies.com>
Can you share the endpoints for the newly created API's?

Sincerely,
Saksham Handu

**Comment by ShruthiRajaram** [comment]
Share account template -GET https://Domain Name/api/v1/self/shareaccounts/template?clientId={clientId}
Retrieve share account - https://DomainName/api/v1/self/shareaccounts/{accountId}
Submit share account - https://Domain Name/api/v1/self/shareaccounts

**Comment by miPlodder** [comment]
@ShruthiRajaram @santoshconflux Thanks, I will work on it.

**Comment by santoshconflux** [comment]
@miPlodder ,  Is it duplicate ticket of this?
https://github.com/openMF/mifos-mobile/issues/834

which has already PR still open? 

https://github.com/openMF/mifos-mobile/pull/870

**Comment by miPlodder** [comment]
@santoshconflux Yeah, both the issues are same. Regarding, the PR, I created in during the GSoC period using Fake Data Layer.

**Comment by abhin2149** [comment]
Can I work on this issue @miPlodder ?

**Comment by luckyman20** [comment]
Feature already implemented.
