### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by SangramChavan** [openMF/self-service-app#489]
**Summary:**

Executes raw SQL query. Untrusted user input in raw SQL queries can cause SQL Injection. Also sensitive information should be encrypted and written to the database.

**Files:**
BaseQueriable.java 
AndroidDatabase.java 
BaseDatabaseHelper.java 
AndroidDatabaseStatement.java

**Comment by therajanmaurya** [comment]
@SangramChavan Yes we know about it, we will encrypt the database before release, Don't worry.

**Comment by SangramChavan** [comment]
@therajanmaurya Thanks !
