### ISSUE TITLE
Show Valid Message In Recent Transaction.

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#49]
In Recent Transaction show a message, if there is no recent transaction and also If any error occured during fetching the transaction.

**Comment by sagar15795** [comment]
@therajanmaurya  I would like to work on this issue.

**Comment by therajanmaurya** [comment]
Yeah, go ahead.

**Comment by sagar15795** [comment]
This issue only demands to add no recent transaction text view only.
As we are showing all error in the toast. 
Is it ok?

**Comment by therajanmaurya** [comment]
there should be a Image and Text in the center and according to response, If response transaction size is zero then show an Image and text("There is no transaction to show :).") and if failed, show image and text("Failed to load transactions").

**Comment by therajanmaurya** [comment]
You can use drawable images for showing error : https://github.com/openMF/self-service-app/blob/development/app/src/main/res/drawable-hdpi/ic_error_black_24dp.png and for showing empty transaction https://github.com/openMF/self-service-app/blob/development/app/src/main/res/drawable-hdpi/ic_assignment_turned_in_black_24dp.png

**Comment by sagar15795** [comment]
@therajanmaurya thanks

**Comment by therajanmaurya** [comment]
fixed in #88
