### ISSUE TITLE
Incorrect credentials

### ISSUE THREAD

**Issue by nb2998** [openMF/self-service-app#490]
**Summary:**

The demo credentials mentioned in [Wiki](https://github.com/openMF/self-service-app/wiki) are not valid for the api host mobile.openmf.

**Steps to reproduce:**

Enter the credentials mentioned in Wiki i.e,
Username: selfservice
Password: password

**Expected behavior:**

Wiki should be modified with the correct credentials.

**Comment by luckyman20** [comment]
@nb2998 We are not using mobile.openmf as API host anymore, we have shifted it to demo.openmf.
Here I am leaving with you the commit in we shifted - [Commit](https://github.com/openMF/self-service-app/commit/a3ed700eb92b044440d95486f14b140de473312d)

**Comment by dilpreet2028** [comment]
@luckyman000786 We are currently using mobile instance only see here: https://github.com/openMF/self-service-app/blob/development/app/src/debug/java/org/mifos/mobilebanking/api/BaseURL.java#L10

@nb2998 , Thanks for reporting , seems like a backend issue, will be fixed soon.

**Comment by luckyman20** [comment]
@dilpreet96 But what about the commit, I was told by @therajanmaurya and @naman14 that we have shifted to demo.openmf

**Comment by dilpreet2028** [comment]
@luckyman000786 , there are some api's which are not present in the demo instance but these are present in the mobile instance so we had to shift back to the mobile instance.

**Comment by luckyman20** [comment]
@dilpreet96 Okay, Thank you so much for updating me.
