### ISSUE TITLE
Unit tests for RegistrationVerificationPresenter

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#495]
**Summary:**
Write Unit tests for RegistrationVerificationPresenter.

Example for unit testing of <a href="https://github.com/openMF/mifos-mobile/blob/development/app/src/main/java/org/mifos/mobilebanking/presenters/AccountsPresenter.java"> AccountPresenter</a> can be seen in <a href="https://github.com/openMF/mifos-mobile/blob/development/app/src/test/java/org/mifos/mobilebanking/AccountsPresenterTest.java"> AccountsPresenterTest</a>

**Comment by se-ke** [comment]
Hey @dilpreet96 , I'm having some issues squashing my commits before opening a pull request. How should I squash them?

**Comment by dilpreet2028** [comment]
Hello @Boogi56 , have a look at https://gist.github.com/jbub/5766366 and this https://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one/2568581#2568581

**Comment by se-ke** [comment]
@dilpreet96 , I fixed it and created a pull request, thanks for the help
