### ISSUE TITLE
Show Login Form onFailure Response.

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#50]
Whenever a user is trying to login into the app.
If the response comes in the onFailure. In any case like 
- User is log in with credentials 
- The user is fetching client.
  then there is two methods showError(String errorMessage) and showMessage(String errorMessage) that showing the Failure response.

How to achieve this issue:
- Remove the showError(String errorMessage) method and use the showMessage(String errorMessage)  instead. 
- Set Login form Visibility Visible if any Failure occurs by adding 
  `llLogin.setVisibility(View.VISIBLE)` in showMessage(String errorMessage) method.

**Comment by sosnickm** [comment]
I searched, but couldn't find any times the app uses the "showError(String errorMessage)" function. Did you mean another function like "showErrorFetchingClients(String errorMessage)" or "onLoginError(String errorMessage)"?

**Comment by sosnickm** [comment]
Additionally, you want me to create a new function called showMessage(StringerrorMessage) right?

**Comment by therajanmaurya** [comment]
@sosnickm I think you looking with the `master` branch and `master` branch in not working default branch, `development` is main default branch, Please look the `development` branch and you will able to achieve this issue.

 if not Please let me know.

**Comment by sosnickm** [comment]
I switched to the development branch and that helped a lot!

However, I can only find the interface that declares these methods. I can't find the class that implements showMessage() or showError(). Can you help direct me to that?

**Comment by sosnickm** [comment]
Submitted pull request https://github.com/openMF/self-service-app/pull/58
