### ISSUE TITLE
Clicking on HelpLine number doesn't do anything

### ISSUE THREAD

**Issue by Rish02Sharma** [openMF/self-service-app#515]
**Summary:**

Clicking on HelpLine number should open the phone dialer on home screen

**Comment by jb1998** [comment]
Is this issue resolved??
I am beginner here so can I start by resolving this issue?

**Comment by Rish02Sharma** [comment]
@jb1998 I have already sent PR to this issue and now waiting for mentors to respond, still, u can do it your way and if that would be better than mine then mentors will merge that one. No problem with that :smile:

**Comment by jb1998** [comment]
oh..!!!
Not a problem , I will look for other issues : )
