### ISSUE TITLE
Updating Passcode feature absent

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#519]
**Summary:**

No option is provided to used to update/change the 4 digit password

**Expected behavior:**

User should have the option to update/change his 4 digit password.

**Observed behavior:**

No such feature present

**Comment by AkshGautam** [comment]
@edcable @dilpreet96 @tarun0 I would like to do this task.Thanks

**Comment by gururani-abhishek** [comment]
@jawidMuhammadi this can be closed too, with reference to : #1201

**Comment by luckyman20** [comment]
Thanks @gururani-abhishek for reporting. Closing this.
