### ISSUE TITLE
Use NDK abiFilters instead of ABI split 

### ISSUE THREAD

**Issue by S2606** [openMF/self-service-app#525]
**Summary:**

There are some issues when using ABI split for APK size. Instead of this we can shift to NDK abiFilters.

**Comment by therajanmaurya** [comment]
Please expand, @S2606 Please give an idea how you gonna enhance this.

**Comment by S2606** [comment]
@therajanmaurya Sometimes the abi split does not work when people share the app through some other medium such as bluetooth. This means if user with ARM architecture phone shares the application with someone with X86 architecture phone, the application will crash. So we can use NDK abiFilters.

**Comment by ivary43** [comment]
@therajanmaurya , @dilpreet96   can i work on this enhancement.

**Comment by ivary43** [comment]
@therajanmaurya , @dilpreet96  i want to work on this issue.
