### ISSUE TITLE
Notification number box showing even with no Notification

### ISSUE THREAD

**Issue by manki11** [openMF/self-service-app#537]
**Summary:**
The notification icon on the top-right of home screen in toolbar shows a red circle even when there is no Notification.

**Steps to reproduce:**
Close the app, and open again. (The problem resolves itself when the user taps on a given option and returns back to the home screen)

**Expected behavior:**
The red circle next to notification icon should only show-up when there is a notification.

**Observed behavior:**
The red circle next to notification icon shows-up when there is no notification on starting the app.

**Device and Android version:**

Oneplus 5T
Android 7.1.1(Nougat)
Oxygen OS

**Screenshots:**
![whatsapp image 2018-01-19 at 5 46 06 pm](https://user-images.githubusercontent.com/25136650/35150825-e91c3ff6-fd41-11e7-86e2-2d4b704e16a5.jpeg)

**Comment by miPlodder** [comment]
@tarun0 @therajanmaurya I would like to do this task.
