### ISSUE TITLE
Add Intent to Helpline number

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#542]
**Summary:**

Add Intent to Helpline number on the Home Page (done like in case of Email)

**Steps to reproduce:**

Login into the app.
You will see Contact number at the bottom of the Home Activity.
Click on it. (no intent is send to make a call)

**Expected behavior:**

On clicking the Contact number should make a call. (done like in email)

**Observed behavior:**

Nothing happens on clicking it.

**Device and Android version:**

Xiaomi, Android Marshmallow

**Screenshots:**

![31](https://user-images.githubusercontent.com/22195621/35497942-4a069bc4-04f2-11e8-8e77-81dd696ad8ad.png)

**Comment by miPlodder** [comment]
@tarun0  @therajanmaurya I want to work on this issue.

**Comment by AkshGautam** [comment]
@miPlodder This issue is already opened #515  and the Pull request has  already been made #516

**Comment by miPlodder** [comment]
@AkshGautam Thanks for informing.

**Comment by dilpreet2028** [comment]
Closing as it is a duplicate issue
