### ISSUE TITLE
Can't refresh the Saving account ,Loan account ,Share account section after getting the internet connection back .

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#550]
**Summary:**

In saving, loan, share account section I can't refresh the section even the internet connection restores.

**Steps to reproduce:**

Go to Dashboard turn off your internet, Account section, then swipe to either of saving, loan, share section turn on the internet and then swipe. 

**Expected behavior:**
 The App should refresh on swipe refresh showing the data (after the internet connection restores).

**Observed behavior:**

I can't refresh after the internet connection restores to get the data.
**Device and Android version:**
Moto G-3.
Version- 6.0.1 .

**Screenshots:**
![latest](https://user-images.githubusercontent.com/24601454/35686750-0430236a-0793-11e8-86b9-021b90ac2979.gif)
 I would like to work on this issue.

**Comment by miPlodder** [comment]
@ivary43 I tried it, it worked for me. I guess, it didn't worked for you, maybe your internet connection was slow. Can you try again and see that its working or not ?

**Comment by ivary43** [comment]
@miPlodder  you can see it's 4G in the screenshot and my college wifi is pretty good, so maybe that's not the problem.Anyhow I will look at that once again.
