### ISSUE TITLE
Improper UI to show error  on User profile in no data.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#553]
**Summary:**

UI is showing partial data and on top of it render error .

**Steps to reproduce:**

Open the app then open the drawer then click on the profile .

**Expected behavior:**

If it is showing error then it shouldn't show any data and the error message should occupy the whole fragment.

**Observed behavior:**
On the UI some partial data was showing and on top of it, the error message was being displayed.

**Device and Android version:**
Device: Moto G-3.
Android version: 6.0.1.

**Screenshots:**
![screenshot_20180202-004340](https://user-images.githubusercontent.com/24601454/35698572-7cefe28e-07b3-11e8-87c2-29858c9789e0.png)
I would like to work on this issue.

**Comment by ivary43** [comment]
@therajanmaurya , @dilpreet96  should I proceed?

**Comment by roychowdhuryrohit-dev** [comment]
This issue hasn't been fixed yet !
