### ISSUE TITLE
Filters are not working properly on the account page in all section.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#554]
**Summary:**

Filters are not working properly on the account page in all section.

**Steps to reproduce:**

Go to dashboard then click on account section, open filter option than without selecting any options click on filter or select an option click on filter then remove that option then and click filter.
**Expected behavior:**

If none of the options was chosen then on clicking filter it shouldn't filter anything and simply show the whole unfiltered list or when we chose an option for filter then remove that option and click filter then it should show us the whole unfiltered list.

**Observed behavior:**
It simply removes all the data from the fragment until refreshed to get the whole data again.

**Device and Android version:**
Device: Moto G3.
Version: 6.0.1.

**Screenshots:**
![20180202_022350](https://user-images.githubusercontent.com/24601454/35703570-8525f056-07c2-11e8-8e09-7457dd3dd76b.gif)
I would like to work on this issue.

**Comment by luckyman20** [comment]
Redundant Issue
