### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by jindalAnuj** [openMF/self-service-app#557]
**Summary:**

i want to add readme.md. As it has very less information about the project and setup

**Comment by ShivangiSingh17** [comment]
Hello can i work on this issue?

**Comment by jindalAnuj** [comment]
Yeah

**Comment by RajaVamsi11** [comment]
@Starcode71Ooze I am interested in updating READ me file. Can I work on this issue?

**Comment by ShivangiSingh17** [comment]
Yeah you can proceed @RajaVamsi11 .
