### ISSUE TITLE
Continue button is enabled in no internet connection leading to app crash.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#559]
**Summary:**

Continue button should be disabled on no internet connection in tranfer and 3rd party transfer section.

**Steps to reproduce:**

Open the app, turn off the internet open transfer or third party transfer section click on continue and on next section click on continue again.

**Expected behaviour:**

The continue button should be disabled if there is no internet connection because app crashes if we proceed to the next continue in any of the section (transfer or third party transfer).

**Observed behaviour:**

Continue button was enabled on no internet connection and the app crashes if we pressing next continue.

**Device and Android version:**

Device: Moto G-3.
Version: 6.0.2.

**Screenshots:**
![20180203_235549](https://user-images.githubusercontent.com/24601454/35770425-08b82a2c-0941-11e8-9b4e-43c3042ddb6a.gif)
I would like to work on this issue.

**Comment by luckyman20** [comment]
Not able to reproduce this issue.
