### ISSUE TITLE
Date picker not working properly in Apply for Loan section.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#560]
**Summary:**

Unable to select future dates in expected disbursement date in apply for loan section.

**Steps to reproduce:**

Open the app->Apply for loan ->click on expected disbursement date. 

**Expected behaviour:**

Since expected disbursement date is the date till what we want our loan money, so it should be any future date but we can't select a future date in the app.
  
**Observed behaviour:**
Unable to select the future date for expected disbursement date.

**Device and Android version:**

Device: Moto G-3.
Android Version: 6.0.1.

**Screenshots:**

![20180204_024456](https://user-images.githubusercontent.com/24601454/35771765-04546a56-0958-11e8-840e-07615ff229b3.gif)
I would like to work on this issue.

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 I would like to work on this issue.

**Comment by ivary43** [comment]
@miPlodder I already started working on this issue as mentioned in the issue.

**Comment by luckyman20** [comment]
Not able to reproduce this issue.
