### ISSUE TITLE
Feature- Adding Fingerprint Authentication

### ISSUE THREAD

**Issue by srijansoni** [openMF/self-service-app#561]
**Summary:**

Fingerprint Authentication can be added to the app which will work alongside passcode also. It will make the app more secure and convenient to use.

**Steps to reproduce:**

1) Open the app.
2) No fingerprint authentication is present.

**Expected behaviour:**

Fingerprint Authentication can be added to the app which will work alongside passcode also. An option will be present for the user (if the smartphone doesn't have a fingerprint scanner or if the user wants to use passcode only). It will make the app more secure and convenient to use. It is also better than passcode as it cannot be forgotten or lost.

**Observed behaviour:**

Currently, no Fingerprint authentication is present in the app. Only passcode authentication is present.

**Device and Android version:**

Device- Moto G5 Plus
Android Version- 7.0

**Screenshots:**

![image](https://user-images.githubusercontent.com/25769960/35781035-7f54a0ce-0a0a-11e8-8e73-1ed254f9ad18.png)

**Comment by srijansoni** [comment]
May I work on this issue?

**Comment by ivary43** [comment]
@srijansoni  how are you planning to do this because currently verification is done on server.

**Comment by srijansoni** [comment]
@ivary43 Fingerprint authentication has nothing to do with the server. 
1) The user has to register a passcode one time. 
2) Then every time he uses the fingerprint to login, the app will match this fingerprint to the stored one.
3) If the fingerprint is correct, then automatically send the registered passcode and attempt to authenticate the user from the server.
4) All the rest of the process is same as trying to login with a passcode.

**Comment by mohak1712** [comment]
Are you working on this issue? @srijansoni

**Comment by gptshubham595** [comment]
Can I take this?@ivary43

**Comment by gptshubham595** [comment]
For fingerprint

**Comment by justdvnsh** [comment]
@ivary43 @ReCodee I am new to this project. Can I take this issue up ?

**Comment by ReCodee** [comment]
@justdvnsh Mifos passcode library has support for fingerprint authentication however I don't know if it's ready to be implemented in this app, this can be discussed in our community channel and one more thing please seek approvals by tagging project maintainers and mentors, I'm just a contributor like you :)

**Comment by justdvnsh** [comment]
@ReCodee Ohkay. Thanks. My bad ! 😅

**Comment by luckyman20** [comment]
Solved in #691
