### ISSUE TITLE
App Crashes on clicking the "Apply for Loan" Button

### ISSUE THREAD

**Issue by srijansoni** [openMF/self-service-app#563]
**Summary:**

The app is crashing when "Apply for Loan" Button is clicked.

**Steps to reproduce:**

1) Open the app.
2) Enter Login Credentials and then Login.
3) Enter or skip passcode.
4) Click on Apply for Loan.

**Expected behaviour:**

The app should not crash.

**Observed behaviour:**

The app is crashing.

**Device and Android version:**

Device- Moto G5 Plus 
Android Version- 7.0

**GIF:**
![20180205_014931](https://user-images.githubusercontent.com/25769960/35782015-ccb342be-0a17-11e8-8889-2112da2f240e.gif)

**Comment by srijansoni** [comment]
May I work on this issue?

**Comment by sridharjajoo** [comment]
@srijansoni Are you working on this issue?

**Comment by amitYadavDev** [comment]
hi sir @sridharjajoo can i work on this issue?

**Comment by luckyman20** [comment]
Not able to reproduce this issue.
