### ISSUE TITLE
On Submitting Loan, shows the same Activity

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#566]
**Summary:**

On Submitting Loan, shows the same Activity instead show AccountActivity.

**Steps to reproduce:**

1) Click on Accounts from Navigation Drawer.
2) Go to Loan ViewPager.
3) Click on **'+'** Floating Button.
4) Enter Loan Details.
5) Click on Submit Button.

**Expected behaviour:**

After Submit, go to AccountActivity.

**Observed behaviour:**

After Submit, it stays on the same Activity.

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![____1](https://user-images.githubusercontent.com/22195621/35847392-58ce92a2-0b40-11e8-97cc-8b577dddd383.gif)

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 I would like to work on this issue.

**Comment by ivary43** [comment]
@miPlodder  this issue has already been referenced in  #468.

**Comment by miPlodder** [comment]
@ivary43 Thanks for the info.

**Comment by miPlodder** [comment]
@dilpreet96 Please close this issue. ( **Duplicate Issue** )

**Comment by luckyman20** [comment]
@miPlodder You can also close this issue as you have opened the issue. So please do so
