### ISSUE TITLE
User Story - Self-service App Login

### ISSUE THREAD

**Issue by denilap** [openMF/self-service-app#57]
User Story - As a customer, I want to be able to login to the self-service app with my credentials so I can securely access my self-service online account.

Acceptance criteria:
1) Both username and password data-fields are required input data fields:
  If username data field is left blank, show error alert - "Username cannot be left blank"
  If password data field is left blank show error alert - "Password cannot be left blank"

2) Password entry should be masked
Password entry will show the keystroke typed, and then after two seconds the entered character is masked.

3) If username and password entries are invalid, show error alert - "You have entered an incorrect username and/or password"
4) If the username doesn't exist, show error alert - "You have entered an incorrect username and/or password"
5) If username and password entries are valid, route user to the home page

**Comment by dilpreet2028** [comment]
Closing this issue as Login feature has been implemented.
