### ISSUE TITLE
Improper UI render when offline

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#570]
**Summary:**

The UI of the error screen when offline is improper.

**Steps to reproduce:**

1)Run the app
2)Select account
Make sure you are offline.

**Expected behaviour:**

A well aligned UI screen.

**Observed behaviour:**

A misaligned UI screen.

**Device and Android version:**

Android 5.0.2, API 21

**Screenshots:**

![screenshot_2018-02-06-22-45-17](https://user-images.githubusercontent.com/19329788/35873718-8c972f22-0b90-11e8-824a-20f33b1962bd.png)
I want to work on this.

**Comment by AkshGautam** [comment]
@therajanmaurya  @dilpreet96  I am working on this.

**Comment by ivary43** [comment]
@AkshGautam  i have referred this problem in #549 and i started working on this.

**Comment by AkshGautam** [comment]
@therajanmaurya  please close this issue, its been already reported earlier.sorry, i did not notice.

**Comment by luckyman20** [comment]
@AkshGautam As you have opened the issue, you can close the issue. So please do so
