### ISSUE TITLE
App Crashes In third party transfer/transfer in offline mode.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#571]
**Summary:**

The app crashes due to Null Pointer exception in third party transfer/transfer in offline mode.

**Steps to reproduce:**

1)Run the app
2)select third party transfer/transfer in offline mode
3) select continue

**Expected behaviour:**

No crash.

**Observed behaviour:**

App crashes.

**Device and Android version:**

Android 5.0.2, API 21

**Screenshots:**

![20180206_230046](https://user-images.githubusercontent.com/19329788/35874371-5453940a-0b92-11e8-9913-0a45940c850e.gif)

I want to work on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  i want to work on this

**Comment by ivary43** [comment]
@AkshGautam  i already made the same issue #559 and working on this.

**Comment by AkshGautam** [comment]
sorry again.i did not see that. @therajanmaurya  please close this as well.
