### ISSUE TITLE
Snackbar + toast message for same prompt 

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#574]
**Summary:**

Both snackbar and toast messages are displayed simultaneously for the same prompt.

**Steps to reproduce:**

1)Run the app in offline mode
2)Select account/beneficiaries

**Expected behaviour:**

A snackbar message for a more generic behaviour throughout the app since the error screen on activity displays same message as toast so toast should be disabled.

**Observed behaviour:**

toast+snackbar 

**Device and Android version:**

Android 5.0.2,API 21

**Screenshots:**

![screenshot_2018-02-06-23-43-37](https://user-images.githubusercontent.com/19329788/35876392-23944e44-0b98-11e8-93ba-75b91117b111.png)

I am working on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  I am working on this.

**Comment by miPlodder** [comment]
@AkshGautam Snackbar Error message is triggered due to Home Fragment, whereas Toast message is triggered due to Accounts Fragment.

**Comment by therajanmaurya** [comment]
Fixed
