### ISSUE TITLE
style:Using lombok to remove boilerplate code in POJOs

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#575]
**Summary:**

There are lots of boilerplate code inside POJOs.

**Expected behaviour:**

Using [lombok](https://projectlombok.org/) can reduce these codes.

**Comment by ivary43** [comment]
@dilpreet96, @therajanmaurya  can we use Lombok to reduce those codes??

**Comment by luckyman20** [comment]
Issue solved in #863
