### ISSUE TITLE
Data fetched from server is not retaining on orientaion change leading to app crash.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#576]
**Summary:**

Data fetched from server is not retaining on orientation change leading to app crash.

**Steps to reproduce:**

Go to Accounts-> Loan ->Select any closed Loan ->Repayment Schedule then change to landscape mode.

**Expected behaviour:**

The activity should retain the data fetched from the server and shouldn't lose it on change of orientation.
**Observed behaviour:**

Fragment loses the data on change in orientation and repeatedly change in orientation leads to app Crash.

**Device and Android version:**
Moto G-3.
Version:6.0.2.

**Screenshots:**

![20180207_040229](https://user-images.githubusercontent.com/24601454/35888150-bc4976cc-0bbc-11e8-949c-dd4309f0d851.gif)

I am working on this issue.

**Comment by AkshGautam** [comment]
@ivary43  I have sent The PR for #568 and that has solved the crash problem as well as data retention issue. It's not crashing now and data is saved. I have checked it.

**Comment by ivary43** [comment]
@therajanmaurya please this close this issue this has been fixed in PR #569.

**Comment by ivary43** [comment]
@AkshGautam I didn't notice that as per your issue I thought you were doing that for only those activities which require user input.
