### ISSUE TITLE
feat:Reporting of crash while using app absent.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#577]
**Summary:**
Feature of reporting an app crash is currently absent in app.

**Expected behaviour:**

We should send the reports to our organisation desk or somewhere more suitable So that we could analyze and fix the bugs for future updates after the release of the app.

**Observed behaviour:**

This feature is currently not present in the app.

**Comment by ivary43** [comment]
@therajanmaurya, @dilpreet96  can I implement this feature?

**Comment by miPlodder** [comment]
@ivary43 This feature is already implemented in the App. Although the API is not added (#820 )

**Comment by luckyman20** [comment]
@miPlodder Thanks for reporting.
