### ISSUE TITLE
zero amount accepted in transfers/third party transfers

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#578]
**Summary:**

The amount of type 0.0(n times) is accepted as valid amount type in transfers though it is a zero transfer value.

**Steps to reproduce:**

For Instance
1)Run the app
2)Third party transfer
3)select amount of 0.0

**Expected behaviour:**

A snackbar message "amount should be greater than 0" on clicking continue.

**Observed behaviour:**

No message and it is accepted as valid amount.

**Device and Android version:**

Android 5.0.2,API 21

**Screenshots:**

![20180207_102314](https://user-images.githubusercontent.com/19329788/35899330-c2f6ffd2-0bf1-11e8-984a-2a09bf1a622b.gif)

I am working on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  I am working on this.

**Comment by ivary43** [comment]
I am getting an error while making the transfer .You can only review with 0.00 amount but can't make the transfer.Please Check.

**Comment by AkshGautam** [comment]
@ivary43 yes the error is there when making the transfer but why do we need to proceed with the review process when the amount filled is invalid? Try the above process with 0 and you will get invalid amount snack bar. 0 and 0.00 is the same thing so why there should be a dual behavior in both cases. The app should be general for every error. Showing a snack bar in case of 0 and letting the user proceed to review in case 0.0 is not generic. hence the case.
