### ISSUE TITLE
Changing Hidden icon of Account Overview in the Home Section

### ISSUE THREAD

**Issue by apoorvinfo** [openMF/self-service-app#579]
**Summary:**

The Previous icon of Hidden Account Overview is just the faded version of Show icon , which gives less sense to the logic of appearing and disappearing.
**Steps to reproduce:**

Clicking the Show Account Overview on the home page.

**Expected behaviour:**

Having a better icon to imply the details Best.
.

**Device and Android version:**
6.0.1 API 23
**Screenshots:**

Using this icon as Hidden Purpose
![new icon](https://user-images.githubusercontent.com/21074243/35908214-fd5c3920-0c15-11e8-94a4-411b75057f36.PNG)

**Comment by apoorvinfo** [comment]
@tarun0 @therajanmaurya I am working on this issue?

**Comment by therajanmaurya** [comment]
@miPlodder we can do this, this is a valid issue.

**Comment by miPlodder** [comment]
@therajanmaurya Ok, I will take up this issue.
