### ISSUE TITLE
No Change in Post details once selected in Transfer and Third Party Transfer.

### ISSUE THREAD

**Issue by apoorvinfo** [openMF/self-service-app#580]
**Summary:**

Once the detail in single block is selected in Transfer or Third Party Transfer , such as Pay From to next block Beneficiary , Previous Block of Pay From can't be changed, And On Pressing Back Button Moves to the Home Section. And Once the First Block is Selected, The Default Value of Second block is Considered null by the app and Snack is shown for Selected.
**Steps to reproduce:**

1.Open Transfer
2.Open Transfer or Third Party Transfer
3.Enter Starting Details

**Expected behaviour:**
Previous Block can also be active still after the details are already selected. And Default Value of next Block is already Selected or Nothing is Selected in that Block,

**Observed behaviour:**

Previous Block Become Inactive Once the details is Selected.
**Device and Android version:**

6.0.1 API 23

**Screenshots:**
Example such as Pay From to Beneficiary
![27836194_1675550505836330_1595144422_o](https://user-images.githubusercontent.com/21074243/35913445-a1b217ec-0c25-11e8-9e39-c774ebf309cf.png)
, We cannot select "Pay From" again.

**Comment by apoorvinfo** [comment]
@tarun0 I am Working on this issue!

**Comment by miPlodder** [comment]
@therajanmaurya I'm thinking of adding a Refresh Button on the Toolbar, so that user can press it can re-fill the form again. Please tell is this approach workable for this issue.
