### ISSUE TITLE
Survey Section Doesn't Lead to Anywhere

### ISSUE THREAD

**Issue by apoorvinfo** [openMF/self-service-app#582]
**Summary:**

Survey Button in the Home Section doesn't lead to Anywhere.
**Steps to reproduce:**

How can we reproduce the issue?

1.Go to Home.
2.Click on Survey.

What did you expect the app to do?
No Survey class or Acvtivity Used.

**Device and Android version:**

6.0.1 API 23

**Screenshots:**

![27901481_1675555545835826_2124265463_o 1](https://user-images.githubusercontent.com/21074243/35913714-b044f954-0c26-11e8-834d-bf57c853c231.png)

**Comment by apoorvinfo** [comment]
@tarun0 @therajanmaurya Please review and Why the color of Account and Transfer section is white and rest are matching with environment?

**Comment by apoorvinfo** [comment]
@tarun0 @therajanmaurya Please review and Why the color of Account and Transfer section is white and rest are matching with environment?

**Comment by ivary43** [comment]
@apoorvinfo  Survey section is still under construction.

**Comment by apoorvinfo** [comment]
@ivary43 thanku for the information

**Comment by apoorvinfo** [comment]
@ivary43 Are you assigned or ?

**Comment by ivary43** [comment]
@apoorvinfo no this is not assigned to me.

**Comment by deecodesss** [comment]
Can I work on this?

**Comment by luckyman20** [comment]
More detailed desc at #841
