### ISSUE TITLE
Recent Transaction should show more information on Clicking in a brief way.

### ISSUE THREAD

**Issue by apoorvinfo** [openMF/self-service-app#583]
**Summary:**

Recent Transaction shows only the adapter limited details and no action on clicking them. While this should be clickable resulting in dialog box or new frame which the sender name, account details, whom it is send to , price and other details in a brief way. This all improves user experience and make the app friendly.
**Steps to reproduce:**

1.Go to Home
2.Go to Navigation Bar
3.Go to Recent Transactions
**Expected behaviour:**

Open a dialog or new Activity showing all the possible details of the transaction.
**Observed behaviour:**

Only Limited details in the Adapter view result in poor UI.
**Device and Android version:**
6.0.1 API 23

**Screenshots:**

![27902100_1675563629168351_615691467_o](https://user-images.githubusercontent.com/21074243/35914139-37264c9c-0c28-11e8-957c-22861a7b59b2.png)

**Comment by apoorvinfo** [comment]
@tarun0 @therajanmaurya I am working on this issue!

**Comment by ivary43** [comment]
@apoorvinfo  this issue has already been reported in issue #485 and API development is under process.

**Comment by therajanmaurya** [comment]
Duplicate https://github.com/openMF/mifos-mobile/issues/485
