### ISSUE TITLE
Small mistakes in Wiki page 

### ISSUE THREAD

**Issue by geekanamika** [openMF/self-service-app#585]
**Changes Required in wiki page** 
1. android studio set up  description :
buildtoolversion of project is '26.0.2' , whereas in wiki page , it suggests to download 23 to set up the project, It should be fixed.
2. Building up the code step suggests to clone from repo link whereas conventionally approach is to create a fork & then clone.

**Screenshots:**
![screenshot from 2018-02-08 00-07-11](https://user-images.githubusercontent.com/16922933/35935111-7b27ce2e-0c65-11e8-8a0c-720617e5446e.png)
![screenshot from 2018-02-08 00-07-19](https://user-images.githubusercontent.com/16922933/35935112-7b759190-0c65-11e8-9134-7cf9331a03dc.png)

**Comment by ivary43** [comment]
@geekanamika  do you want to fix this issue ?

**Comment by geekanamika** [comment]
@ivary43  Yes, I am waiting for mentors approval :) @dilpreet96 @therajanmaurya Is this valid ?
