### ISSUE TITLE
Unable to refresh after getting the internet connection back in Charges section.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#586]
**Summary:**

Unable to refresh after getting the internet connection back in Charges section.

**Steps to reproduce:**

Open the app->Turn off your internet ->Charges Section (Try to refresh).

**Expected behaviour:**

As soon as i get back my internet i should be able to refresh the activity.

**Observed behaviour:**

I was not able to refresh after internet connection restores.

**Device and Android version:**
Device: Moto G-3.
Version: 6.0.1.

**Screenshots:**

![20180208_021826](https://user-images.githubusercontent.com/24601454/35941215-8b73aafc-0c77-11e8-9789-7d9e28c0f5c2.gif)

 I would like to work on this issue.

**Comment by ivary43** [comment]
@tarun0 , @dilpreet96 , @therajanmaurya  i want to work on this issue.

**Comment by tarun0** [comment]
Did you try clicking on the message? If I remember correctly, the page reloads when the No-Network message is clicked.

**Comment by ivary43** [comment]
@tarun0  after clicking on the icon it refreshes, I think we should add a swipe refresh to reload or refresh because that is what we generally do, and it is present across all such fragments.What's your view on this?
