### ISSUE TITLE
App crashes on Third Party Transfer Activity (Null Pointer Exception)

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#587]
**Summary:**

Null Pointer Exception at **ThirdPartyTransferFragment.java:284**

**Steps to reproduce:**

1) Open Navigation Drawer
2) Open Third Party Transfer from drawer.
3) Continue on Pay From (Empty field gets )
4) Click continue on "**Beneficiary**".

**Expected behaviour:**

App should not crash.

**Observed behaviour:**

App is crashing.

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![_1](https://user-images.githubusercontent.com/22195621/35973619-10cfba86-0cfc-11e8-9858-88417cac7196.gif)

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 I would like to resolve this issue.

**Comment by ivary43** [comment]
@miPlodder  this issue has already been referenced in issue #571 and resolved in PR #584. I Disabled the button to continue so you can't continue or can't select when there is no option.

**Comment by miPlodder** [comment]
@ivary43 Thanks for the info.

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 Please close this issue.
