### ISSUE TITLE
No error message present while logging in if server are down.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#588]
**Summary:**

There should be error message showing the error why the user is not able to log in as per the status code received from the server side.

**Expected behaviour:**

The app should the error why the user is not able to log in (leaving wrong credentials) if it is due to the server side.

**Observed behaviour:**

No Such error message was present.

**Comment by ivary43** [comment]
@dilpreet96 , @tarun0  i would like to work on this issue.

**Comment by tarun0** [comment]
Always add a GIF or video of the issue!

**Comment by ivary43** [comment]
@tarun0 I can't do it right now because the server is up but there is no toast to handle status code 503.Sorry for the inconvenience.
