### ISSUE TITLE
User Story - Registration Screen - Account Validation

### ISSUE THREAD

**Issue by denilap** [openMF/self-service-app#59]
User Story:
As a customer, I want my banking profile and accounts to be located and linked to my self-service online account so I can access them through my self-service app.

Acceptance criteria:

Input data fields  to enter 1) Account number  2) Phone number
Both are  required input data fields:
  If Account number data field is left blank, show error alert - "Account number is required"
  If Phone number data field is left blank show error alert - "Phone number is required"

Account validation by checking both Account number and Phone number against client's account details-
  If account number and phone number combination on client's file do not match, show error alert "Account cannot be located, please contact  <support number> for support"
  If account number is invalid, show error alert  "Account cannot be located, please contact <support number> for support"

If account number and phone number indicates that the user already has a self-service online account, show error alert "Looks like you have already registered in the past. If you need help locating your login please click on Forgot Password or contact <support number> for support"

If account validation is successful, take user to next screen to create username and password

**Comment by therajanmaurya** [comment]
Added in #363
