### ISSUE TITLE
http not showing in licences

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#590]
**Summary:**

Links are not showing "**h**", instead showing "**ttp**" in starting of links in Licenses

**Steps to reproduce:**

1) Open Navigation Drawer.
2) Click About Us
3) Click Licenses

**Expected behaviour:**

Links should show "h" in the starting of the links.

**Observed behaviour:**

Links don't contain leading "h"

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![__2](https://user-images.githubusercontent.com/22195621/36050970-85de8434-0e0e-11e8-9b20-61bc7773eba2.gif)

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 I would like to work on this issue.

**Comment by RajaVamsi11** [comment]
@miPlodder Can I work on this issue?
