### ISSUE TITLE
Bug when language is changed from English to Hindi

### ISSUE THREAD

**Issue by sridharjajoo** [openMF/self-service-app#596]
**Summary**
When language is changed from English to Hindi the language of the toolbar doesn't change.
![screenshot_2018-02-11-17-52-37-046_org mifos mobilebanking](https://user-images.githubusercontent.com/20684618/36073326-aa69f620-0f54-11e8-929a-411a0eed0909.png)

**Steps to reproduce:**
Go to Settings and change the language from English to Hindi.

**Comment by AkshGautam** [comment]
@sridharjajoo do you want to work on this? if yes please ask to do so.

**Comment by sridharjajoo** [comment]
I want to work on this!

**Comment by AkshGautam** [comment]
@sridharjajoo are you still working on this? I would like to take up this task if you are not working on it anymore.

**Comment by sridharjajoo** [comment]
I will submit a pr till tomorrow

**Comment by RajaVamsi11** [comment]
@miPlodder Can I start working on this issue?

**Comment by ShivangiSingh17** [comment]
Hello,can i work on this issue ?

**Comment by luckyman20** [comment]
This issue does not exist anymore.
