### ISSUE TITLE
Bug on screen rotation

### ISSUE THREAD

**Issue by sridharjajoo** [openMF/self-service-app#597]
**Summary:**
When the screen is rotated , the text present on the toolbar is diminished in size.

**Steps to reproduce:**
Go to any activity and rotate the screen.

**Expected behaviour:**
The size of the text shouldn't change.

**Screenshots:**
![screenshot_2018-02-11-17-56-51-333_org mifos mobilebanking](https://user-images.githubusercontent.com/20684618/36073542-90960ac8-0f58-11e8-9fbb-6e1b263fe00a.png)

**Comment by therajanmaurya** [comment]
Already fixed in https://github.com/openMF/mifos-mobile/pull/734
