### ISSUE TITLE
Pull to refresh shows the default progress bar as well.

### ISSUE THREAD

**Issue by pa1pal** [openMF/self-service-app#6]
In all the activities whenever I pull to refresh the default progress bar appear. In login activity as well.

**Comment by sosnickm** [comment]
Is this still a problem? When I pull down to refresh I get the circular arrow refreshing and that's it.

**Comment by therajanmaurya** [comment]
Yeah, to fix this issue you need to replace ProgressDialog to ProgressBar because ProgressBar does not block the UI.

**Comment by ashu-dadhich** [comment]
@therajanmaurya is someone working on it..if not can I?

**Comment by therajanmaurya** [comment]
Actually, this issue is explaining the whole app and that's a bad idea to make the changes in every file in single PR. that will rise the conflicts the others contributor works.

I will open the small issues to fix the ProgressDialog to ProgressBar :)

**Comment by ashu-dadhich** [comment]
ok @therajanmaurya thanks for being for helpful :smile:
