### ISSUE TITLE
Typos in Strings.xml

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#607]
**Summary:**

There are typos in strings.xml

**Steps to reproduce:**

res >> values >> strings.xml

**Expected behaviour:**

Typos should be corrected as they are used in many places.

**Observed behaviour:**

These typos are used in many layouts.

**Comment by ivary43** [comment]
@miPlodder  do you want to work on this issue?

**Comment by miPlodder** [comment]
@ivary43 Yeah, I'm working on it.

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 I working on this issue.

**Comment by ivary43** [comment]
@miPlodder  please use Android lint you can find all the typos using that.
