### ISSUE TITLE
Adding Multi Language Support in Settings

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#609]
**Summary:**

Settings should include multiple languages in options to select other language.

**Steps to reproduce:**

1) Open Nav Drawer
2) Open Setting
3) Choose language

**Expected behaviour:**

What did you expect the app to do?

**Observed behaviour:**

It contains only 2 languages support.

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![settings_issue](https://user-images.githubusercontent.com/22195621/36169102-437d1b3a-1121-11e8-9ddd-baf95d6be496.gif)

**Comment by miPlodder** [comment]
@dilpreet96 @therajanmaurya I would like to work on this issue.

**Comment by AkshGautam** [comment]
@miPlodder What's the point of adding options if the translations do not exist?

**Comment by miPlodder** [comment]
@AkshGautam We just have to add translations in the strings.xml file for each language.

**Comment by AkshGautam** [comment]
I know That as well,one must know a language in order to put the translations in strings.xml. without translations there is no point of giving users a dummy language selection.

**Comment by miPlodder** [comment]
@AkshGautam I'm thinking of adding translation from Google Translate, but they are not always accurate. So, I waiting for reviewer instructions.
