### ISSUE TITLE
 feat: Tutorial Screen for users logging in the app for the first time.

### ISSUE THREAD

**Issue by Rish02Sharma** [openMF/self-service-app#617]
We can highlight some features for users on the first start of app.
@dilpreet96 @therajanmaurya Suggestions? Can I work on this?

**Comment by sridharjajoo** [comment]
@Rish02Sharma How do you plan to do this?

**Comment by Rish02Sharma** [comment]
> How do you plan to do this?

@sridharjajoo Plan as in how will I implement this?

**Comment by sridharjajoo** [comment]
@Rish02Sharma Yes.I meant will you be using any library or implementing this tutorial process on your own?

**Comment by Rish02Sharma** [comment]
Hey @sridharjajoo well it depends upon the mentor's approval and the amount of introductory material we want to provide to the new users , i can hard code for it but GUI of libraries would be more attractive so some of the libraries which i looked for are [apl-devs](https://github.com/apl-devs/AppIntro), [msayan/tutorial-view](https://github.com/msayan/tutorial-view) and [MaterialIntroTutorial](https://github.com/riggaroo/MaterialIntroTutorial).
Rest depends upon the approval. :smile:

**Comment by luckyman20** [comment]
Closing since we have #1383, which gives a better explanation of the same issue.
