### ISSUE TITLE
Apply for Loan Fragment doesn't contain SwipeRefresh Layout

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#632]
**Summary:**

Apply for Loan Fragment doesn't contain SwipeRefresh Layout

**Steps to reproduce:**

Click on Apply to Loan from HomeFragment 

**Expected behaviour:**

SwipeRefresh Layout will help us to restore the fragment's form when internet connection is restored

**Observed behaviour:**

Instead, swiperefresh layout is not present

**Device and Android version:**

Xiaomi, Marshmallow 

**Screenshots:**

![apply_for_loan_no_swipe_refresh_layout](https://user-images.githubusercontent.com/22195621/36241550-11a23d62-123d-11e8-8cf7-ab98276be4dc.gif)

**Comment by miPlodder** [comment]
@dilpreet96 @therajanmaurya I would like to work on this issue.

**Comment by therajanmaurya** [comment]
No this is not perfect workflow. I am closing this PR.
