### ISSUE TITLE
Internet Connectivity Msg not on Layout in Beneficiaries

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#633]
**Summary:**

In Beneficiaries Fragment, Internet Connectivity Msg not shown on layout 

**Steps to reproduce:**

Open Beneficiaries without Internet Connection

**Expected behaviour:**

Internet Connectivity Msg should be shown on layout like other layout

**Observed behaviour:**

Instead, the layout is kept blank (unlike other layouts)

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

(Other Layouts)
![_new_issue_1](https://user-images.githubusercontent.com/22195621/36241780-4ace5b2e-123e-11e8-8a51-547fec2f6519.png)

(Beneficiaries Layout)
![_new_issue_2](https://user-images.githubusercontent.com/22195621/36241781-4b08a4fa-123e-11e8-9d4a-52d9949fab1f.png)

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 I would like to work on this issue.

**Comment by ivary43** [comment]
@miPlodder  this issue has already been reported in #558 and PR has already been sent.

**Comment by miPlodder** [comment]
@ivary43 Thanks for the info.
