### ISSUE TITLE
Ambiguous UI functionality of radio button in Saving Account Transactions

### ISSUE THREAD

**Issue by mohak1712** [openMF/self-service-app#634]
**Summary:**

When using filter with selecting start and end date any previously selected radio buttons should be cleared

**Steps to reproduce:**

Open Saving Account Transaction Screen click any radio button then select start and end date and click the filter button. The radio button doesn't get unchecked.

**Expected behaviour:**

The checked radio button if any must get unchecked on filter button press else it makes the UI ambiguous

**Observed behaviour:**

The checked radio button remains unchecked.

**Device and Android version:**

LeEco2(6.0)

**Screenshots:**

![error](https://user-images.githubusercontent.com/12782512/36262459-7e7d11c8-128d-11e8-8ecf-89db76d551b2.gif)

I  would like to work on this

**Comment by mohak1712** [comment]
I would like to work on this

**Comment by ivary43** [comment]
@mohak1712 I didn't get you what's the issue in this? If the user is selecting the start/end date and he/she would remember according to what params they are filtering, how it is making the UI ambiguous.

**Comment by mohak1712** [comment]
@ivary43 When user is using start and end date for filtering shouldn't any previously checked radio button be unchecked bcoz the filtering is not as per the radio button.
It seems confusing since it shows the checked radio button even if we are using dates for filtering
