### ISSUE TITLE
Move from Observable to Single

### ISSUE THREAD

**Issue by mohak1712** [openMF/self-service-app#636]
**Summary:**

In the `LoginPresenter` when logging in a user `Observable<User>` is used which can be changed to `Single<User>`.
Since there is `Observable<User>` we need to implement 3 methods namely `onNext` `onCompleted` and `onError` and `onCompleted ` is useless since there is only a single emission. If we move to `Single<User>` we just need `onSuccess` and `onError` methods, which is logically more sound since there is only a single emission. This also reduces the code length and makes it more clearer.

**Steps to reproduce:**

Check `LoginPresenter`

**Expected behaviour:**

Use of `Single<User>` rather than `Observable<User>`

**Observed behaviour:**

Use of `Observable<User>` rather than `Single<User>`

**Device and Android version:**

LeEco2(6.0)

**Comment by mohak1712** [comment]
@dilpreet96 @therajanmaurya I would like to know your views on this so that I can work on this !

**Comment by therajanmaurya** [comment]
Nope we will stick with Observable
