### ISSUE TITLE
Add feature to show user details.

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#64]
How to achieve this issue 
1. Add layout in Navigation Header to show logged in user profile image and name. 
2. Onclick profile ImageView opens a Layout that shows the user profile.
    like : User profile image, Name Account Number etc.

**Comment by akmittal006** [comment]
how to get user image?

**Comment by therajanmaurya** [comment]
Here is the API END point https://demo.openmf.org/api-docs/apiLive.htm#selfclientsimages. 
It is giving the Client Image Binary data.

**Comment by akmittal006** [comment]
can i add picasso ??

**Comment by therajanmaurya** [comment]
Yes you can. Go ahead.

**Comment by joydeepsaha05** [comment]
@therajanmaurya Should the profile image and name be added on top of the current Mifos image?

**Comment by hardik124** [comment]
I want to work on this.

**Comment by m-murad** [comment]
Can I work on this

**Comment by therajanmaurya** [comment]
@hardik124 Go ahead 👍. Please try to be quick.

**Comment by therajanmaurya** [comment]
@hardik124  Any update

**Comment by akmittal006** [comment]
I was already working on it . I had my mid terms, so i couldnt update. @therajanmaurya  any other issue i can work on?

![screenshot_4](https://cloud.githubusercontent.com/assets/8525715/23821652/77e1a4c2-065f-11e7-8e06-046348b16f1b.png)

**Comment by hardik124** [comment]
@therajanmaurya  i am not able to retrieve user image please check #187

**Comment by dilpreet2028** [comment]
Added in #338
