### ISSUE TITLE
FloatingActionButton becomes invisible on scrolling

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#642]
**Summary:**

FloatingActionButton becomes invisible on scrolling in Loan Fragment in Accounts

**Steps to reproduce:**

1) Go to Accounts
2) Swipe Left to Loan 
3) Scroll down the list

**Expected behaviour:**

FloatingActionButton should be visible

**Observed behaviour:**

FloatingActionButton becomes invisible and show some strange behaviour

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![plussign](https://user-images.githubusercontent.com/22195621/36340552-b6b413d8-1405-11e8-9061-c3257b82d0de.gif)

**Comment by miPlodder** [comment]
@dilpreet96 @therajanmaurya I would like to work on this issue.

**Comment by mohak1712** [comment]
@miPlodder this doesn't seem like an issue
this looks like a behavior of FAB
`app:layout_behavior="org.mifos.mobilebanking.utils.ScrollFabBehavior"`

**Comment by miPlodder** [comment]
@mohak1712 When we scroll, it's looks good that FAB is invisible. But we stop scrolling, the FAB should be visible but instead it's invisible (this is what end user don't want).  

I guess this behavior can be changed by working on this file,

https://github.com/openMF/mifos-mobile/blob/development/app/src/main/java/org/mifos/mobilebanking/utils/ScrollFabBehavior.java

**Comment by mohak1712** [comment]
ya you can make changes to that file for newer functionality

**Comment by ivary43** [comment]
@miPlodder  i think it's a pretty common behaviour to hide the FAB on scroll to avoid any hinderance to the view on scrolling because if the user is scrolling down the User want to see some data so FAB has no use but when the user is going up he might need to add loan or the user is done searching, so the FAB becomes visible again .
I think there is no issue in that.Please do confirm.

**Comment by miPlodder** [comment]
@ivary43 User can scroll a bit (FAB is gone), and want to add a loan ,but wouldn't find the FAB.
It's not necessary that user will always want to add a loan while Scrolling up.

The best design will be that FAB is invisible only while scrolling, rest of the time it should be visible. This approach will surely enhance the UI/UX .

**Comment by therajanmaurya** [comment]
It is common behavior that we added as a feature, So I don't think we need to remove this.
