### ISSUE TITLE
Dialog box content disappears on screen rotation

### ISSUE THREAD

**Issue by sridharjajoo** [openMF/self-service-app#643]
**Summary:**
On rotating the device when the filter dialog box appears in the accounts section the bottom part of the dialog box which includes options such as ''CLEAR FILTERS'',''CANCEL'',"FILTER" get removed.
 
**Steps to reproduce:**
1) Go to the Accounts section and rotate the screen.
2) Select the filter icon present on the toolbar.
3) A dialog box appears which shows the checkboxes but the bottom part isn't visible. 

**Expected behaviour:**
The options should be visible in this state as well.

**Comment by ivary43** [comment]
@sridharjajoo this issue is same as #568 and PR has already been sent.

**Comment by sridharjajoo** [comment]
@ivary43 My issue is related to the content of the dialog box which remain invisible even after applying the changes made in the previous P.R
![device-2018-02-17-233434](https://user-images.githubusercontent.com/20684618/36344086-2d4f8470-143b-11e8-8d87-4eeb6177f546.png)

**Comment by luckyman20** [comment]
Issue already fixed.
