### ISSUE TITLE
Contact Us Number should be clickable

### ISSUE THREAD

**Issue by codedsun** [openMF/self-service-app#653]
**Summary:**

The phone number provided in the bottom under Home Section, should be clickable

**Steps to reproduce:**

Go to the home section and scroll down to contact us
Click on the phone number.

**Expected behaviour:**

It should be clickable 

**Observed behaviour:**

It's not clickable

**Device and Android version:**

Asus Zenfone Max, Android 6.0

**Comment by ivary43** [comment]
@codedsun  please rebase and check this issue is already reported in #515 and resolved in #516.

**Comment by sridharjajoo** [comment]
@codedsun Kindly close this issue
