### ISSUE TITLE
Adding NA where Min required Balance is not available in accounts section and adding space between contact us and contact number in same fragment

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#657]
**Summary:**

Currently, there is no text displayed under MIn required balance in some cases. Moreover there should be a space between the contact us and the contact number in the same fragment footer.

**Steps to reproduce:**

1)run the app
2) accounts

**Expected behaviour:**

NA should be displayed when No min req balance is available and adding a space between text and number for better clarity.

**Observed behaviour:**

empty space.

**Device and Android version:**

android 5.0.2, api 21

**Screenshots:**

![screenshot_2018-02-20-12-01-07](https://user-images.githubusercontent.com/19329788/36410377-bcb5960c-1636-11e8-892d-2287609adc6f.png)
 I am working on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  i am working on this

**Comment by ivary43** [comment]
@AkshGautam  can you please confirm i was unable to replicate the issue.
![screenshot_20180220-132452](https://user-images.githubusercontent.com/24601454/36412825-ce3881ae-1641-11e8-895f-93954b9dd647.png)

**Comment by AkshGautam** [comment]
@ivary43 It's working fine after pulling the latest code.

**Comment by ivary43** [comment]
@AkshGautam  if you are still adding the space between contact and number can you make a small change that for a closed account(In loan account details )the due date is blank please fill NA there or whatever approach you want and update the issue title.

**Comment by AkshGautam** [comment]
@ivary43 Sure I would do that as well. I'll close this issue and create a new one since once I change the title and description of the issue other readers might be confused.
