### ISSUE TITLE
Text in layout is going out of device screen.

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/self-service-app#66]
**Summary:** 

In detail page of a particular loan or saving account, sometimes the text is going out of device screen.

**Steps to reproduce:** 

Navigate to LOAN ACCOUNTS and click on first account.

**Expected behavior:** 

Space should be automatically adjusted.

**Observed behavior:** 

Product name is going out of device screen.

**Device and Android version:** 

YUREKA with Android 5.1.1

**Screenshots:** 
![15215938_1826630457603918_1231573466_o](https://cloud.githubusercontent.com/assets/11210887/20641053/52baacbc-b415-11e6-8e5e-a7d280f9a85b.png)

**Comment by mayank-kgp** [comment]
@therajanmaurya I would like to work on this issue.

**Comment by ghost** [comment]
I would like to solve this issue

**Comment by therajanmaurya** [comment]
Open new issue for refactoring loan account details here #84
