### ISSUE TITLE
"No Beneficiary" is not shown when list of beneficiary is empty

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#668]
**Summary:**

"No Beneficiary" is not shown when list of beneficiary is empty, instead message should be shown

**Steps to reproduce:**

1) Open Navigation Drawer
2) Click on "Manage Beneficiary"

**Expected behaviour:**

Message "No Beneficiary" should be shown

**Observed behaviour:**

No message is shown on Fragment

**Device and Android version:**

Xioami, Marshmallow

**Screenshots:**

![__empty_list](https://user-images.githubusercontent.com/22195621/36467245-e3e5f712-1703-11e8-9144-4564c05db3dd.png)

**Comment by miPlodder** [comment]
@dilpreet96 @satyan @droidchef I am working on this issue.

**Comment by AkshGautam** [comment]
@miPlodder  is this the same as #558 ? Please check.

**Comment by ivary43** [comment]
@miPlodder  this is same as #658.

**Comment by miPlodder** [comment]
@AkshGautam @ivary43 Thanks for informing.

**Comment by sridharjajoo** [comment]
You can close this issue
