### ISSUE TITLE
App is not displaying account list after coming from another drawer item. 

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/self-service-app#67]
**Summary:** 

Account list is not there if we navigate from another drawer item.

**Steps to reproduce:** 

Navigate to Recent Transactions or Charges in navigation drawer and click on account.

**Expected behavior:** 

Account list should be there after reloading of data.

**Observed behavior:** 

There is no account on screen.

**Device and Android version:** 

YUREKA with Android 5.1.1

**Screenshots:** 
![15216047_1826642670936030_1193983795_o](https://cloud.githubusercontent.com/assets/11210887/20641198/dd094b5a-b418-11e6-86fc-1e08a7cb417c.png)

**Comment by therajanmaurya** [comment]
This issue already fixed. @mayank-kgp Please go through the project wiki first and then change workspace from master to development.

Thanks
