### ISSUE TITLE
Invalid Check and Toast Message on Submiting Loan 

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#674]
**Summary:**

Invalid Toast Message on Submiting Loan 

**Steps to reproduce:**

1) Apply from Loan
2) Change Principal Amount
3) Submit Loan

**Expected behaviour:**

Proper restriction for Principal Amount  should be there and valid Toast message should be shown

**Observed behaviour:**

Improper Check message don't allow User to change Principal Amount of the loan and invalid Toast message is shown

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![issue_invalid_toast](https://user-images.githubusercontent.com/22195621/36634771-ce05ddd0-19cf-11e8-978d-740f56894ed8.gif)

**Comment by miPlodder** [comment]
@dilpreet96 @droidchef @satyan I would like to work on this issue.

**Comment by therajanmaurya** [comment]
@miPlodder this is server default value, It should be like this.
