### ISSUE TITLE
Phone Number not opening Phone Dialer

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#676]
**Summary:**

Phone Number on Home Fragment not opens dialer on clicking

**Steps to reproduce:**

Click on Phone Number on scrolling down

**Expected behaviour:**

Dialer should open

**Observed behaviour:**

Dialer is not opening

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![_phone_dialer_issue](https://user-images.githubusercontent.com/22195621/36646220-d75dde20-1a9a-11e8-998f-0e3f71fa7fed.png)

**Comment by miPlodder** [comment]
@dilpreet96 @droidchef @satyan I would like to work on this PR.

**Comment by therajanmaurya** [comment]
@miPlodder use auto link phone parameter in TextView

**Comment by miPlodder** [comment]
@therajanmaurya It's already there https://github.com/openMF/mifos-mobile/blob/development/app/src/main/res/layout/fragment_home_old.xml#L370
But still its not working in my device.

**Comment by devanshi7799** [comment]
@miPlodder Can i work on this issue?

**Comment by droidchef** [comment]
Yes, you can work on it.

**Comment by som23ya** [comment]
@miPlodder @therajanmaurya @droidchef the phone number is still not opening the phone dialer, can i work on this?

**Comment by ShivangiSingh17** [comment]
@som23ya its working. Once you click on the number, the phone dialer opens. Which device and Android version are you using?

**Comment by luckyman20** [comment]
@ShivangiSingh17 Thanks for reporting. Closing this.
