### ISSUE TITLE
Abrupt opening of "Account Overview" on Home

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#679]
**Summary**
There is abrupt opening of "Account view" on click, there should be a slide animation for opening and closing of that for better view

**Steps to reproduce:**
Go to Home and click on "Account Overview".

**Expected behaviour**
There should be slide animation for opening and closing of "Account Overview" on click.

**Observed behaviour**
There is disrupt opening and closing of "Account Overview " on clicking it.It should be done with slide animation for a better view.

**Device and Android version**
Moto G-3 turbo(6.0.1)

**ScreenShots**
![20180227_234526](https://user-images.githubusercontent.com/24601454/36747555-4d02e81a-1c1b-11e8-9d01-52333f306812.gif)

I would like to work on this issue.

**Comment by luckyman20** [comment]
@ivary43 Instead of slide animation, you can come up with some other beautiful animation as slide animation is mostly used in going through pages and stuff.

**Comment by ivary43** [comment]
@luckyman20  Any suggestion ?? I suggested that because that is mostly found in a dropdown.

**Comment by luckyman20** [comment]
@ivary43 You might like to visit this page - https://developer.android.com/training/transitions/start-activity.html. I would like to suggest `Explode` animation though.

**Comment by ivary43** [comment]
@luckyman20 I think that's better(```Explode```) when you are opening an intent, also I read somewhere the same in Udacity course. I think that might not good here.

**Comment by mohak1712** [comment]
@luckyman20 Explode might be an overkill since user might be changing the visibility more often than we think. You might wanna go with something subtle like a fade or slide

**Comment by luckyman20** [comment]
@mohak1712 I think fade and slide will don't give the richer look to the app. Explode on the other hand is not also so much good for that. 

@ivary43 You can search out for more animations and discuss here.
