### ISSUE TITLE
User Story - Savings Accounts Summary Screen

### ISSUE THREAD

**Issue by denilap** [openMF/self-service-app#68]
User story: As a self-service app user, I should be able to view a list of all my savings accounts, so that I can see the status and summary details of my savings accounts in one place

Acceptance criteria:

1)User will be shown the total available balance (total of available balance across all savings accounts)
2) User will be able to see a list of all savings accounts with the following details for each account:
      a. Account/Product Name
      b.Account Number
      c. Account Balance
      d.Account Status - (Active and above set limit) versus  (Alert/Exception on account)

3) Each savings account listing should have directional caret hyperlink, clicking on which will take the user to detailed screen for that particular savings account

Link to wireframes:
https://openmf.mybalsamiq.com/projects/mifosandroidself-serviceapp/Savings%20Accounts%20Details

**Comment by immabhay** [comment]
@therajanmaurya I would like to work on this issue.

**Comment by dilpreet2028** [comment]
Closing this issue as Savings Accounts Summary Screen has been implemented.
