### ISSUE TITLE
Filter checkbox item requires initial touch to work as expected.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#684]
**Summary:**

The Filter Loan accounts checkbox requires an initial touch (if we touch the item instead of checkbox ) to work as expected

**Steps to reproduce:**

1)Run the app
2)Select Accounts
3)Filter Accounts
4)Click the filter item

**Expected behaviour:**

The item should have been checked on a single touch but it requires one more touch.

**Observed behaviour:**

Item requires an extra touch to work as expected.

**Device and Android version:**

Android 5.0.2,API 21

**Screenshots:**

![20180228_155717](https://user-images.githubusercontent.com/19329788/36783042-e0de5eae-1ca0-11e8-9432-9213360a0ecd.gif)

I would like to work on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  I would like to work on this.

**Comment by ivary43** [comment]
![20180301_181707](https://user-images.githubusercontent.com/24601454/36845568-44c58f00-1d7d-11e8-9254-f1bb7c3ba01d.gif)
@AkshGautam can you please confirm I was not able to replicate the issue.

**Comment by AkshGautam** [comment]
@ivary43  It is not working as expected on my device.

**Comment by luckyman20** [comment]
Not able to reproduce the issue anymore. Similar fix in PR #2095.
