### ISSUE TITLE
Login fails after entering correct passcode for the fourth time after 3 wrong tries.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#688]
**Summary:**

The login to app fails if the user enters the correct passcode after 3 wrong tries.
PS 1234 is the correct passcode here.

**Steps to reproduce:**

1)Run the appp
2)Enter wrong passcode 3 times
3)Enter correct passcode
4)Login fails and login activity is presented

**Expected behaviour:**

The app should login on correct passcode enter on 4th time even if previous 3 were wrong and should open login activity if 4th attempt is also wrong.

**Observed behaviour:**

The app fails to login on correct passcode in 4th try.

**Screenshots:**

![20180228_224613](https://user-images.githubusercontent.com/19329788/36801888-45bb0326-1cd9-11e8-9b08-25d20eee3732.gif)

I am working on this.

**Comment by luckyman20** [comment]
Covered in #1504
