### ISSUE TITLE
Add Home Screen Feature

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#69]
As an authenticated self-service user, upon initial log-in, I want to see a summary of my accounts and relevant details of balances.

Home screen is showing full client details
1. His Savings Share accounts.
2. His Details etc.

See the below screenshot.

<img width="636" alt="screen shot 2016-12-03 at 5 42 35 pm" src="https://cloud.githubusercontent.com/assets/5724482/20859283/fe822308-b97f-11e6-9dd1-47d445e84070.png">

**How to achieve this issue**

1. Add Home in navigation drawer at the top and this home feature will come by default, whenever     
   application will be open.

2. You need to fetch Client Savings, Loan, Share accounts and user details.
    REST API : https://demo.openmf.org/api-docs/apiLive.htm#selfclientsaccounts.
    This REST API will give you client all type of accounts.

3. Fetch-Client Details.
    REST API : https://demo.openmf.org/api-docs/apiLive.htm#selfclient

**Note : Do not add Quick transfer,  Loan Payment, Apply for loan, Customer support in UI, We will add these things in Action Menu bar**

**Comment by sosnickm** [comment]
@therajanmaurya there is no current function to get the picture from the client API. I am confused about how to do this. Is this something that I should do or should I do the update without this and someone else can it in later?

**Comment by sosnickm** [comment]
If no picture is available, then should I show nothing, a blank box, or is there a specific image (like a fake profile)?

**Comment by sosnickm** [comment]
How can I access the data stored for shares? For example I can get the loan / saving account info from the the client account, but I don't see the shares within that. If it is, then what function / input should I use?

**Comment by therajanmaurya** [comment]
[Here](https://github.com/openMF/android-client/blob/master/mifosng-android/src/main/java/com/mifos/mifosxdroid/adapters/ClientNameListAdapter.java) you can find how to access client Image. look the line 73-77

**Comment by therajanmaurya** [comment]
Using this [API](https://demo.openmf.org/api-docs/apiLive.htm#selfclientsaccounts) you will get every type of account loan, savings, and shares.
for Example check this [END_POINT](https://demo.openmf.org/fineract-provider/api/v1/self/clients/1/accounts?tenantIdentifier=default&pretty=true) [Enter the username and password in alert dialog]

**Comment by sosnickm** [comment]
@therajanmaurya So i followed that link to the mifos android client app and it required bringing over a bunch of classes from that code base.

**Comment by sosnickm** [comment]
Also the current sign in doesn't have a client picture, is there a way to add one so that I can see if my code works? Thanks

**Comment by therajanmaurya** [comment]
What about this API END point https://demo.openmf.org/api-docs/apiLive.htm#selfclientsimages. 
It is giving the Client Image Binary data.

**Comment by therajanmaurya** [comment]
any update @sosnickm

**Comment by sosnickm** [comment]
I paused for 2-3 weeks, but will update late next week!

**Comment by therajanmaurya** [comment]
@sosnickm Can you please send the PR.

**Comment by rahulbabbar1** [comment]
@therajanmaurya can I work on this??

**Comment by therajanmaurya** [comment]
Wait, Let me ping @sosnickm. I do not want that two people doing the same thing.

**Comment by rahulbabbar1** [comment]
yeah sure.

**Comment by sosnickm** [comment]
I'm working on this! Will try to send the PR ASAP

**Comment by sosnickm** [comment]
Hey, my Android studio will only run with gradle version 2.14.1, what should i do about this?

**Comment by sosnickm** [comment]
I can't do a gradle sync and was having trouble merging the new commits

**Comment by therajanmaurya** [comment]
what type of trouble you are getting.

**Comment by sosnickm** [comment]
Error:Minimum supported Gradle version is 2.14.1. Current version is 2.10. If using the gradle wrapper, try editing the distributionUrl in /Users/michaelsosnick/AndroidStudioProjects/self-service-app/gradle/wrapper/gradle-wrapper.properties to gradle-2.14.1-all.zip
Fix Gradle wrapper and re-import project

**Comment by sosnickm** [comment]
I've changed it for now because it seems as if you have already changed it as well. I am still having gradle issues with the pull. Will try to post problems here

**Comment by sosnickm** [comment]
@therajanmaurya  How many of each type of account should there be on the home page? 3 saving accounts, 2 loan accounts and 1 star account?

**Comment by sosnickm** [comment]
Also, should the "total saving accounts" be the total of the three accounts that are on the page or of all of the accounts? (the same question applies to the other types of accounts)

**Comment by rahulbabbar1** [comment]
I think it would be better if it shows a scrollable list of accounts in each section. If total no. of shares, saving acc, and loans exceeds 6 then each category must limit 2 account in a single view. Else if total no. Is less than 6 then simply show all entities.
What's your opinion about this @therajanmaurya

**Comment by sosnickm** [comment]
I was thinking that it shouldn't really show all of the accounts for three reasons: one - it would be hard to scroll through that little section and it wouldn't be super usable on a phone. two - if you wanted to look at all the accounts or scroll through them, then it so much easier to just go to the accounts page. three - isn't this supposed to be an overview page? pushing functionality on this page that we have another page specifically for doesn't make so much sense to me.

**Comment by rahulbabbar1** [comment]
Yup sounds right. Just add a option in each section "see all accounts" , on clicking which corresponding activity opens .

**Comment by therajanmaurya** [comment]
@sosnickm Follow this 
![image](https://cloud.githubusercontent.com/assets/5724482/23793587/feeace66-05b1-11e7-8a4e-62d30988e979.png)

OnClick any type of account make Fragment Transaction ClientAccountFragment.class

**Comment by sosnickm** [comment]
@therajanmaurya For the ShareAccount and SavingAccount we store the getApprovedShares and the getAccountBalance, so I only need the List-ShareAccount and the List-SavingAccount to get the total. However, for LoanAccount we do not store getTotalOutstanding. I am having trouble adding up the total for this because each LoanAccount is returning at different times from the data manager. Is there a way to just store the getTotalOutstanding in the LoanAccount?

**Comment by sosnickm** [comment]
@therajanmaurya Which fragment should the Quick Transfer button lead to? and the loan payment fragment requires that you input a loanId before you open it, which loanId should that be?

**Comment by therajanmaurya** [comment]
Right Now show the toast onclick buttons.

Make a PR. I will merge.

**Comment by Rishabhk07** [comment]
@therajanmaurya hey, out of curiosity in the above wireframe what are you planning to show under reports ?

**Comment by therajanmaurya** [comment]
Added in #242
