### ISSUE TITLE
Add support for fingerprint authentication if feasible

### ISSUE THREAD

**Issue by mohak1712** [openMF/self-service-app#691]
**Summary:**

The app does not currently support fingerprint authentication

**Steps to reproduce:**

Only way to login is to enter password

**Expected behaviour:**

The app should support fingerprint authentication

**Observed behaviour:**

The app does not support fingerprint authentication

**Device and Android version:**

LeEco2 (6.0)

**Comment by mohak1712** [comment]
I would like to check if it is feasible and work on it thereafter

**Comment by ivary43** [comment]
@mohak1712 this issue has already been reported in #561. If you want to work please ask there in comment section.

**Comment by mohak1712** [comment]
Ok thanks

**Comment by ivary43** [comment]
@mohak1712  please close this issue.
