### ISSUE TITLE
White screen persisting for a short duration after opening app

### ISSUE THREAD

**Issue by harshitbansal05** [openMF/self-service-app#697]
**Summary:**

When opening the app, a white screen is shown for a certain duration of time.

**Steps to reproduce:**

Open application.

**Expected behaviour:**

The white screen should be replaced by a splash screen containing the logo of the application.

**Observed behaviour:**

The white screen persists.

**Device and Android version:**

Redmi Note 3 Android Version: 5.1.1 Stock

**Comment by ivary43** [comment]
@harshitbansal05  please always attach a screenshot or gif for UI related issues.
