### ISSUE TITLE
Inconsistent check for Password during Signing Up

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#698]
**Summary:**

Inconsistent check for Password during Signing Up

**Steps to reproduce:**

1) Go to Sign Up
2) Enter less than 6 length password
3) Submit the form

**Expected behaviour:**

Instead of trying to connect to Server, first we should validate it locally

**Observed behaviour:**

Whereas it is trying to connect to server
Now, if user creates account successfully with smaller length password, he will not be able to log in (screen short below)

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

**(Not able to login)**

![issue_password_length](https://user-images.githubusercontent.com/22195621/36863398-944ffd62-1daf-11e8-8cde-04a6b357374f.png)

**(Generation of the Issue)**
![issue_password_length_check_2](https://user-images.githubusercontent.com/22195621/36863410-9b75cae0-1daf-11e8-91b1-a6fd600d05a8.gif)

**Comment by miPlodder** [comment]
@dilpreet96 @satyan @droidchef I would like to work on this issue.

**Comment by ivary43** [comment]
@miPlodder  this issue has already been reported in #654.

**Comment by miPlodder** [comment]
@ivary43 Thanks for the info
