### ISSUE TITLE
Password and Confirm Password not checked before submiting Signing Up

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#699]
**Summary:**

Password and Confirm Password not checked before submitting Signing Up

**Steps to reproduce:**

1) Go to Sign Up 
2) Enter details (password and confirm password should not be same)
3) Submit the form

**Expected behaviour:**

User should be informed that both passwords are not matching

**Observed behaviour:**

Instead, its showing message and trying to Sign Up

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![issue_passport_not_validated](https://user-images.githubusercontent.com/22195621/36864072-9ab55bf0-1db1-11e8-8635-8a0c96fce2d3.gif)

**Comment by miPlodder** [comment]
@dilpreet96 @satyan @droidchef I would like to work in this issue.

**Comment by ivary43** [comment]
@miPlodder  please go through the issue #654. I have mentioned the same in the comment section.

**Comment by miPlodder** [comment]
@ivary43 Thanks again for the info.
