### ISSUE TITLE
Remove redundant  casting in the project.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#701]
**Summary**
Remove redundant type cast from the project.In the project at many places we are using redundant type cast  e.g : ``` TextView tv = (TextView)findViewById(R.id.xxxx)```.
I think will be good for code clean up plus we are using butterknife so it will be better to use that.

**Comment by ivary43** [comment]
@therajanmaurya , @dilpreet96 i would like to work on this.

**Comment by Rish02Sharma** [comment]
Hey @ivary43 i think its the same issue as #620 .. Still best of luck :+1:
