### ISSUE TITLE
Inconsistent check for Username during Signing Up

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#702]
**Summary:**

Inconsistent check for Username during Signing Up

**Steps to reproduce:**

1) Go to Sign Up
2) Fill the details (username with spaces)
3) Submit details

**Expected behaviour:**

Instead, error message should be shown.

**Observed behaviour:**

If the form is submitted, new user will not be able login to the app (check for spaces in user name is present in login activity)

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![issue_username_issue_2](https://user-images.githubusercontent.com/22195621/36884685-73355010-1e08-11e8-89fd-ddbe2944335e.png)

![issue_username_space_check](https://user-images.githubusercontent.com/22195621/36884687-762eddea-1e08-11e8-9653-685df400c973.png)

**Comment by miPlodder** [comment]
@dilpreet96 @droidchef @satyan I would like to work on this issue.

**Comment by therajanmaurya** [comment]
Good Catch @miPlodder, yes your are right username doesn't consist any space in between because It is unique identity. Please make the changes I suggested in PR.
