### ISSUE TITLE
App crashes and causes UX issues when user submit or enter fragment for any form in Offline Mode

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#703]
**Summary:**

App crashes and causes UX issues when user submit or enter fragment for any form in Offline Mode (Dropdown contains empty value)

**Steps to reproduce:**

Open Transfer or Beneficiary Form in offline mode

**Expected behaviour:**

I guess, a better approach will be to show "No Internet" message on Screen

**Observed behaviour:**

Instead, it shows the form with no dropdowns which cause Crashing of app

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

**(App crashes)**
![20180302_104012](https://user-images.githubusercontent.com/22195621/36884874-9f01d424-1e09-11e8-86ab-794377b1e75b.gif)

**(User will face difficulty, cause UX issues)**
![issue_beneficiary](https://user-images.githubusercontent.com/22195621/36885081-bec29860-1e0a-11e8-8f86-a24bb4847e28.gif)

**Comment by miPlodder** [comment]
@dilpreet96 @satyan @droidchef I would like to work on this issue.

**Comment by ivary43** [comment]
@miPlodder this is same as #559.

**Comment by miPlodder** [comment]
@ivary43 This issue is not to work to stop the Crash, but to prevent it. You can read my approach in the 1st comment. The approach is to not load the form, when there is no Internet Connection.
