### ISSUE TITLE
Spaces in password field Inconsistency

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#704]
**Summary:**

Spaces in password are not excepted while Logging In

**Steps to reproduce:**

1) Go to Login Screen
2) Enter spaces in password

**Expected behaviour:**

Password should be excepted

**Observed behaviour:**

Password is not accepted

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![issue_spaces_in_password](https://user-images.githubusercontent.com/22195621/36885010-58eebe88-1e0a-11e8-84e3-d9322610bfd1.gif)

**Comment by miPlodder** [comment]
@dilpreet96 @satyan @droidchef I would like to work on this issue.

**Comment by ivary43** [comment]
@miPlodder  spaces are not meant to be in the password only alphabet ,numbers and symbols are accepted in that field.I think it's pretty common in a password field.

**Comment by miPlodder** [comment]
@ivary43 I guess using spaces in passwords adds security strength of a password (prevents Dictionary attack and Brute Force Attack). Moreover, this is a banking app, where security should be our first priority.

**Comment by ivary43** [comment]
@miPlodder  if you are talking about security, I think **only spaces** is a very weak password plus it is not allowing because trailing spaces are trimmed before sending to the server.You can enter spaces in between the alphanumerics.I think that is allowed.

**Comment by miPlodder** [comment]
@ivary43 I never talked of entering all only spaces. In GIF, I entered it to show that spaces are getting trimmed. Consider, a scenario if user entered leading and trailing space, it will trim it, which should not be done.

**Comment by ivary43** [comment]
@miPlodder  leading spaces are not trimmed only trailing ones are trimmed, plus in every input text field, we trim the trailing spaces because we don't know that was intentional or not you can look up the  
 same in the codebase.

**Comment by miPlodder** [comment]
@ivary43  I'm think of showing error (below password), if user adds leading or trailing spaces, because user should know leading and trailing  have to be avoided. And during Sign Up, do the same check on Sign Up.

Somewhat like this which Gmail uses,

![issue_password](https://user-images.githubusercontent.com/22195621/37087959-cdf7eb08-2221-11e8-8c93-152872d7af43.png)
