### ISSUE TITLE
Navigation View Margin Error

### ISSUE THREAD

**Issue by YashishDua** [openMF/self-service-app#708]
**Summary:**

On scrolling down navigation view has an unnecessary margin over top

**Steps to reproduce:**

Reducing the margin relatively

**Expected behaviour:**

No margin at top ( White Color must not be there)

**Observed behaviour:**

When Navigation view scrolled down, there is a margin at top revealing white color over blue. It's not syncing with UI

**Comment by mohak1712** [comment]
@YashishDua can you add a screenshot and I think this is similar to #692

**Comment by therajanmaurya** [comment]
Duplicate of #692
