### ISSUE TITLE
Migrate from RxJava 1 to RxJava 2

### ISSUE THREAD

**Issue by Rish02Sharma** [openMF/self-service-app#709]
**Summary:**

Currently RxJava 1 is being used in the project but Rxjava 1 is a bit outdated now. We should migrate it to RxJava 2 now.

@therajanmaurya @dilpreet96 What do you think about this? Can I start working on this?

**Comment by therajanmaurya** [comment]
Good @Rish02Sharma, I have given my suggestion please make the change and let me know I will review the whole PR then.

**Comment by mohak1712** [comment]
@therajanmaurya I think we can also add changes mentioned in #636. Can you please check
