### ISSUE TITLE
Progress Bar overshadowing Navigation drawer 

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#720]
**Summary:**

Progress bar is currently overshadowing navigation drawer.According to my perception of UX, this should not happen and nav drawer should overshadow the progress bar when the drawer is opened. Currently this gives users the impression of something loading in navbar but actually, the progress bar is intended for the fragment below nav drawer.

**Screenshots:**

![20180312_091450](https://user-images.githubusercontent.com/19329788/37268901-393c31ec-25ee-11e8-81be-0dc63acb999a.gif)

I would like to work on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  I would like to work on this

**Comment by therajanmaurya** [comment]
Fixed
