### ISSUE TITLE
Progress Bar overshadowing activities which does not contain any information which is still loading. 

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#721]
**Summary:**

Currently, the progress bar is overshadowing activities which do not require any data to be loaded and are already in the final state. This need to be improved since this gives the impression to user that the loading is still in progress.

**Screenshots:**
![screenshot_2018-03-12-09-16-10](https://user-images.githubusercontent.com/19329788/37269066-e240ea12-25ee-11e8-8305-f0076722557c.png)

![screenshot_2018-03-12-09-16-02](https://user-images.githubusercontent.com/19329788/37269081-eb19ef4e-25ee-11e8-812f-2891e29d9476.png)

![screenshot_2018-03-12-09-15-50](https://user-images.githubusercontent.com/19329788/37269074-e7fb2742-25ee-11e8-96e9-f054406e1106.png)

I would like to work on this.

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  I would like to work on this.

**Comment by miPlodder** [comment]
@AkshGautam This issue has already been reported #678  and I working on it.
