### ISSUE TITLE
Clicking on Add beneficiary fab button should open new activity  instead of fragment replacement

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#722]
**Summary:**

As suggested by @therajanmaurya  in the PR https://github.com/openMF/mifos-mobile/pull/705 comments that clicking the fab button while adding beneficiary should open a new activity instead of fragment replace.

I am working on it.

**Comment by AkshGautam** [comment]
@therajanmaurya Why do we need a new activity instead of the fragment replacement? As an android developer, how do we make the tradeoff between a new activity or a fragment? I went through the https://stackoverflow.com/questions/20306091/dilemma-when-to-use-fragments-vs-activities post and it had several viewpoints. what do you think,which one to use when?

PS: I would like to work on this task

**Comment by therajanmaurya** [comment]
@AkshGautam because of UX.

**Comment by therajanmaurya** [comment]
Go ahead and send PR.
