### ISSUE TITLE
App crashes in User Profile Section

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#729]
**Summary:**

App crashes on opening User Profile Section

**Steps to reproduce:**

Open User Profile from Navigation Drawer by clicking on Personal Image

**Expected behaviour:**

App should not crash

**Observed behaviour:**

App crashes

**Device and Android version:**

Xiaomi

**Screenshots:**

![issue_user_profile_crashes](https://user-images.githubusercontent.com/22195621/37343540-de6cac00-26ed-11e8-9334-4c76fc6a75a5.gif)

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 @satyan @droidchef I would like to work on this PR.

**Comment by ivary43** [comment]
@miPlodder  did you rebase ?? I think this should get resolved in #605 ..anyhow please check

**Comment by miPlodder** [comment]
@ivary43 I did.
