### ISSUE TITLE
Adding translations which exists in strings.xml

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#742]
**Summary:**

Translations of some string already exist in string.xml file but are not applied in parts such as drop down.

**Screenshots:**
![screenshot_2018-03-18-03-07-38](https://user-images.githubusercontent.com/19329788/37560219-7b218d9e-2a5a-11e8-924e-c9d4ecec1ff8.png)

![screenshot_2018-03-18-03-09-37](https://user-images.githubusercontent.com/19329788/37560222-7ea97170-2a5a-11e8-9cba-0aba3c4d784b.png)

Both **savings account** and **loan account** have translations for hindi available in strings.xml

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  I would like to work on this

**Comment by ShivangiSingh17** [comment]
May I please work on this issue?

**Comment by geekanamika** [comment]
List of all strings which need translation : 
![translation](https://user-images.githubusercontent.com/16922933/66715848-cc285600-ede5-11e9-9333-4622cae2bc6f.gif)

@ShivangiSingh17 @AkshGautam  Since it's been for a long time, I would like to work on this issue.

**Comment by ShivangiSingh17** [comment]
@geekanamika Sure..Go ahead!!
