### ISSUE TITLE
Message in case of no beneficiaries

### ISSUE THREAD

**Issue by sridharjajoo** [openMF/self-service-app#745]
**Summary**
If no beneficiary is added then the screen should show an appropriate message.

**Steps to reproduce:**
Go to the benfeciary section of the app.

**Expected behaviour:**
The screen is blank.

**Screenshots:**

![screenshot_2018-03-18-12-03-45-464_org mifos mobilebanking](https://user-images.githubusercontent.com/20684618/37563947-218aaf74-2ab2-11e8-9cb6-9b5586298f90.png)

**Comment by sridharjajoo** [comment]
@therajanmaurya @droidchef I want to work on this issue.

**Comment by ivary43** [comment]
@sridharjajoo this is same as #658.
