### ISSUE TITLE
App Crashes on Updating Loan

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#746]
**Summary:**

App Crashes on Updating Loan

**Steps to reproduce:**

1) Go to Accounts
2) Go to Loans Section
3) Open any Pending Loan
4) Update it from the Toolbar

**Expected behaviour:**

App should not crash, and update Loan form should be loaded.

**Observed behaviour:**

Instead, App crashes

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![issue_update_loan](https://user-images.githubusercontent.com/22195621/37563938-e406a586-2ab1-11e8-850e-a0c99642fe13.gif)

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 @droidchef @satyan I would like to work on this issue.

**Comment by sridharjajoo** [comment]
@miPlodder Same as #728

**Comment by miPlodder** [comment]
@sridharjajoo Thanks for the info.
