### ISSUE TITLE
No error message on Login In when wrong API end is changed

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#748]
**Summary:**

No error message on Login In when wrong API end is changed

**Steps to reproduce:**

1) Change API Endpoint
2) Enter Credentials and try to Log In

**Expected behaviour:**

User should be shown Error message, that Invalid requests are made 

**Observed behaviour:**

User is not informed about what's going wrong

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![issue_no_msg](https://user-images.githubusercontent.com/22195621/37564010-7d7f7660-2ab3-11e8-947a-d1a5ac71e8b2.gif)

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 @droidchef @satyan I would like to work on this issue.

**Comment by PratyushSingh07** [comment]
Can i take up this issue?

**Comment by luckyman20** [comment]
Already solved.
