### ISSUE TITLE
Keyboard persists during 3rd party transfer

### ISSUE THREAD

**Issue by sridharjajoo** [openMF/self-service-app#752]
**Summary:**
Under 3rd party transfer when the remarks are entered and the review is selected , the keyboard doesn't get dismissed. 

**Steps to reproduce:**
Go to 3rd party transfer and add the remarks and select REVIEW.

**Screenshot**
![device-2018-03-18-144442](https://user-images.githubusercontent.com/20684618/37564390-1626fddc-2abb-11e8-9623-6607f6ed8178.gif)

**Expected behaviour:**
The keyboard should be dismissed.

**Comment by sridharjajoo** [comment]
@therajanmaurya @droidchef I want to work on this issue.

**Comment by miPlodder** [comment]
@sridharjajoo Please Add Screenshots or GIF for this issue.

**Comment by sridharjajoo** [comment]
@miPlodder Added the gif

**Comment by therajanmaurya** [comment]
@sridharjajoo Please make change on PR.
