### ISSUE TITLE
Closed filter not working as expected

### ISSUE THREAD

**Issue by mohak1712** [openMF/self-service-app#754]
**Summary:**

Using the closed filter on Loan doesn't filter all the items

**Steps to reproduce:**

Open the loan fragment and use the close filter

**Expected behaviour:**

It should show all the closed loans

**Observed behaviour:**

It just shows one closed loan.

**Device and Android version:**

LeEco2(6.0)

**Screenshots:**

![whatsapp image 2018-03-18 at 19 36 35 2](https://user-images.githubusercontent.com/12782512/37566814-12a31726-2ae4-11e8-93e5-40509d309fc5.jpeg)
![whatsapp image 2018-03-18 at 19 36 35](https://user-images.githubusercontent.com/12782512/37566817-181ee306-2ae4-11e8-8204-ce61e96f0f23.jpeg)
![whatsapp image 2018-03-18 at 19 36 35 1](https://user-images.githubusercontent.com/12782512/37566816-1513f462-2ae4-11e8-82f6-4a1e59dc7eb4.jpeg)

**Comment by mohak1712** [comment]
I would like to work on this

**Comment by mohak1712** [comment]
@dilpreet96  @therajanmaurya there is one case where none of the status types is true. However, when setting data to adapter it sets the type to close if others are false without checking if it actually is closed. So that is why the filter is failing in that case. Should I add another category like `others` or update the filter

```
status: {
id: 400,
code: "loanStatusType.withdrawn.by.client",
value: "Withdrawn by applicant",
pendingApproval: false,
waitingForDisbursal: false,
active: false,
closedObligationsMet: false,
closedWrittenOff: false,
closedRescheduled: false,
closed: false,
overpaid: false
}
```

```
if (loanAccount.getStatus().getActive() && loanAccount.getInArrears()) {

            } else if (loanAccount.getStatus().getActive()) {

            } else if (loanAccount.getStatus().getWaitingForDisbursal()) {

            } else if (loanAccount.getStatus().getPendingApproval()) {

            }  else if (loanAccount.getStatus().getOverpaid()) {

            } else {
                setLoanAccountsGeneralDetails(holder, R.color.black, context.getString(R.string.
                        string_and_string, context.getString(R.string.closed), DateHelper
                        .getDateAsString(loanAccount.getTimeline().getClosedOnDate())));
            }
```

**Comment by therajanmaurya** [comment]
Go ahead and send PR.
