### ISSUE TITLE
feature : Add missing filter for Waiting for Disburse in Loan

### ISSUE THREAD

**Issue by mohak1712** [openMF/self-service-app#755]
**Summary:**

Currently, there is no way to filter `Waiting for Disburse` in Loan fragment

**Steps to reproduce:**

Open the filter in Loan fragment.

**Expected behaviour:**

There should be a filter so that user can filter these loans also.

**Observed behaviour:**

There is no filter available

**Device and Android version:**

LeEco2 (6.0)

**Screenshots:**

![whatsapp image 2018-03-18 at 19 36 35 4](https://user-images.githubusercontent.com/12782512/37566876-ec65f208-2ae4-11e8-8337-3716a8970477.jpeg)
![whatsapp image 2018-03-18 at 19 36 35 3](https://user-images.githubusercontent.com/12782512/37566879-eea7fa34-2ae4-11e8-97b0-8f29cd6adfb2.jpeg)

**Comment by mohak1712** [comment]
I would like to work on this

**Comment by ivary43** [comment]
@mohak1712 please rebase it has been fixed.

**Comment by mohak1712** [comment]
@ivary43 thanks
