### ISSUE TITLE
Error in displaying Total Deposit amount

### ISSUE THREAD

**Issue by sridharjajoo** [openMF/self-service-app#758]
**Summary:**
The total deposit amount in the SavingsAccountDetailsFragment.java doesn't show the amount in a formatted manner i.e the commas aren't placed as they are present under Total Withdrawls.

**Steps to reproduce:**
Go to Accounts -> Savings.

**Screenshots:**
![screenshot_2018-03-18-23-29-22-333_org mifos mobilebanking](https://user-images.githubusercontent.com/20684618/37569182-9d374d10-2b04-11e8-8d83-f3495bf813b4.png)

**Comment by sridharjajoo** [comment]
@therajanmaurya @dilpreet96 I want to work on this issue.

**Comment by therajanmaurya** [comment]
Go ahead and send PR.
