### ISSUE TITLE
Adding Butterknife to existing code

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#763]
**Summary:**

Currently, the file such [as](https://github.com/openMF/mifos-mobile/blob/development/app/src/main/java/org/mifos/mobilebanking/utils/ConfigurationDialogFragmentCompat.java) does not contain Butterknife whereas the projects uses butterknife extensively. I would like to work on adding butterknife support to all such files do not use it.

**Comment by AkshGautam** [comment]
@therajanmaurya @dilpreet96  May i work on this?

**Comment by therajanmaurya** [comment]
Go ahead and send PR.
