### ISSUE TITLE
Adding Numeric Softkeyboard for Account Number

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#764]
**Summary:**

Adding Numeric Softkeyboard for Account Number

**Steps to reproduce:**

Go to Log In Screen

**Expected behaviour:**

Numeric Softkeyboard should be displayed

**Observed behaviour:**

Instead, Normal Softkeyboard is displayed

**Device and Android version:**

Xiaomi, Marshmallow

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 @droidchef @satyan I would like to work on it.

**Comment by luckyman20** [comment]
@miPlodder In Mifos, Account Number can be alpha numeric
