### ISSUE TITLE
The app crashes on API 19

### ISSUE THREAD

**Issue by shobhit1997** [openMF/self-service-app#772]
The app crashes while launching on API 19 ( Kitkat ).
(Tested on Redmi 2)

The minSdkVersion mentioned is 15 so ,the app should run on API 19.

**Comment by therajanmaurya** [comment]
@shobhit1997 It is an issue of support library. Please see the log. still not resolved and the app is running on API 15, 16, 17, 18, not 19 and 20, 21, 22, 23 +. 

As the support library issue will be resolved. It is vector drawable issue.
