### ISSUE TITLE
Adding sweet-error library support across the application.

### ISSUE THREAD

**Issue by AkshGautam** [openMF/self-service-app#774]
**Summary:**

Addition of library [Sweet error Library](https://github.com/therajanmaurya/Sweet-Error) across the application in order to avoid manual handling of UI handling error.

**Comment by AkshGautam** [comment]
@therajanmaurya I would like to be a part of this task.

**Comment by ivary43** [comment]
@therajanmaurya  me too.

**Comment by ivary43** [comment]
@AkshGautam  can you please make a to-do list of all the fragments where we need to add this library so we can figure out where we have to work.
