### ISSUE TITLE
Adding check for network connection in activities and fragments.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#782]
**Summary:**

In many fragments, while showing error, network connectivity is not checked which leads to a less suitable error message like "error loading in {Feature name}" whereas the message should reflect that there is no internet connection.

**Screenshots:**

![screenshot_20180323-070210](https://user-images.githubusercontent.com/24601454/37806976-f7132022-2e68-11e8-9643-499a4d35e6b3.png)

**Comment by ivary43** [comment]
@therajanmaurya , @dilpreet96  I would like to work on this issue.

**Comment by luckyman20** [comment]
Already solved.
