### ISSUE TITLE
feat: adding recylerview instead of tables in repayment Schedule and other section of app.

### ISSUE THREAD

**Issue by ivary43** [openMF/self-service-app#795]
**Summary:**

Currently, table layout is used in the repayment schedule and other section which is a not good UI wise, I think we should replace that with recyclerview.

**Steps to reproduce:**

Loan->Any active loan ->Repayment schedule.

**Expected behaviour:**

There should be recycler view instead of table layout.

**Observed behaviour:**

Table layout was present instead of recyclerview.

**Device and Android version:**
Moto G-3(6.0.1)

**Screenshots:**

![screenshot_20180402-202013](https://user-images.githubusercontent.com/24601454/38201041-5f83da18-36b4-11e8-97d4-0dee67a3d56e.png)

**Comment by ivary43** [comment]
@therajanmaurya ,  @dilpreet96 , @droidchef  I would like to work on this issue.

**Comment by RajaVamsi11** [comment]
@ivary43 @therajanmaurya @miPlodder I would like to work on this issue. can you please assign this issue to me.

**Comment by prashantkh19** [comment]
Duplicate #113
