### ISSUE TITLE
Spinner Prompt Message not showing in Add Beneficiary

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#806]
**Summary:**

Spinner Prompt Message not showing in Add Beneficiary

**Steps to reproduce:**

Go to **Beneficiary > Click FAB > Click Add** 
Now, **Select Account Type**

**Expected behaviour:**

Spinner Prompt Message should be visible like other Spinner's in app

**Observed behaviour:**

Instead, Spinner Prompt Message is not visible

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![_issue_prompt_header](https://user-images.githubusercontent.com/22195621/38772018-f16d99ce-404a-11e8-94dd-b34d548bc6ab.png)

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 @droidchef @satyan I would like to work on this issue.

**Comment by therajanmaurya** [comment]
Yeah go ahead and remove this prompt message and use simple spinner.
