### ISSUE TITLE
Wrong message on loan payment screen

### ISSUE THREAD

**Issue by edcable** [openMF/self-service-app#807]
**Summary:**

Screen reads Transfer to Savings when it should read Payment from Savings or Payment to Loan

**Steps to reproduce:**

Repay an active loan from savings account.

**Expected behaviour:**

What 

**Observed behaviour:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

LeEco Android 6.0.1

**Screenshots:**

**Comment by edcable** [comment]
![screenshot_20180415-075546](https://user-images.githubusercontent.com/823454/38779924-15b40366-4084-11e8-844a-51dffab61421.jpg)

**Comment by miPlodder** [comment]
@edcable I would like to work on this issue.

**Comment by edcable** [comment]
@miPlodder certainly please take it up.

**Comment by luckyman20** [comment]
@miPlodder Are you still working on this?

**Comment by miPlodder** [comment]
@luckyman20 Yes, I'm.
