### ISSUE TITLE
Loan repayment should pre-populate with amount due like in Web App

### ISSUE THREAD

**Issue by edcable** [openMF/self-service-app#808]
**Summary:**

When repaying a loan, the amount due should pre-populate with the current amount due like in the web app.

**Steps to reproduce:**

Navigate to a loan, click to repay.

**Expected behaviour:**

Value in the payment field pre- populated with the amount due, i.e. current installment plus any amount overdue, penalties, etc.

This should be a value in the database. See what is returned in web app to know the database values

**Observed behaviour:**

Just a blank value of zero.

**Screenshots:**
![screenshot_20180415-075524](https://user-images.githubusercontent.com/823454/38780640-d0f40072-408e-11e8-983d-3d7584a3087a.jpg)

**Comment by ivary43** [comment]
@edcable  I would like to work on this.

**Comment by dilpreet2028** [comment]
Go ahead @ivary43

**Comment by ivary43** [comment]
@dilpreet96  please review the PR.
