### ISSUE TITLE
App crashes when submitting loan repayment

### ISSUE THREAD

**Issue by edcable** [openMF/self-service-app#813]
**Summary**

All crashes when submitting a loan repayment

**Steps to reproduce:**
Navigate to loan, pay from account that has enough funds. 

**Expected behaviour:**

Successfully submit payment and display receipt of sorts.

**Observed behaviour:**
Crashes app ( see screenshot)

**Device and Android version:**

Android 6.0.1
![screenshot_20180421-005313](https://user-images.githubusercontent.com/823454/39081955-b10f611e-44ff-11e8-92a4-02d1753dae6c.jpg)

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by AkshGautam** [comment]
@edcable sir, May I work on this?
