### ISSUE TITLE
Refactor Saving Account Summary 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#82]
This is the Savings Account feature. In which you have to refactor the SavingAccount Feature.
![image](https://cloud.githubusercontent.com/assets/5724482/23248645/69fa78d4-f9c6-11e6-8ace-e54712d246d2.png)

**Comment by ghost** [comment]
i would like to work on this issue

**Comment by therajanmaurya** [comment]
Go ahead.

**Comment by therajanmaurya** [comment]
@prashanthkomuravelli Any update

**Comment by ghost** [comment]
@therajanmaurya I will send PR till day after tomorrow,sorry for late

**Comment by therajanmaurya** [comment]
implemented in #125
