### ISSUE TITLE
NumberFormatException exception while adding Beneficiary

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#829]
**Summary:**

NumberFormatException exception while adding Beneficiary

**Steps to reproduce:**

Add beneficiary

**Expected behaviour:**

Integer value should be send to the server

**Observed behaviour:**

Instead, we are sending Double to the server

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![screenshot 158](https://user-images.githubusercontent.com/22195621/40022018-62820af4-57e4-11e8-83d6-97f06b82a1a3.png)

**Comment by miPlodder** [comment]
@therajanmaurya I working on this.

**Comment by ivary43** [comment]
@miPlodder I think this a server-side issue ..I guess transfer limit should be double.

**Comment by miPlodder** [comment]
@ivary43 It's server side issue, because we are sending double, but the server expects int. Due to which, in the release user wouldn't be able to Add Beneficiary.

**Comment by ivary43** [comment]
I am saying that this is a server-side bug since the transfer limit is an amount, so it can be double. So instead of making a changing our value from double to int, it is better to make an issue in the server side code to change from int to double.

**Comment by miPlodder** [comment]
@ivary43 Yeah, that's good solution.

**Comment by divyank00** [comment]
![IllegalException](https://user-images.githubusercontent.com/50913976/107004414-4091c000-67b4-11eb-975c-55509629acc3.png)

@miPlodder This issue is not solved at the backend-side. So should we solve it in the frontend?
