### ISSUE TITLE
Feature Savings Account Transaction

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#83]
This is the Savings Account Transaction feature 
![image](https://cloud.githubusercontent.com/assets/5724482/23249550/e4dc99ac-f9ca-11e6-833e-a44954d7f20b.png)

You can use this END POINT: https://demo.openmf.org/fineract-provider/api/v1/self/savingsaccounts/21?associations=transactions for implementing the feature

In which you can pass the savingsaccountId: 21 for now and an item in Navigation Drawer with name "Transactions." This feature should be written in the fragment.

**Note: Add Toolbar Menu Item for "Transactions" and open a new TransactionFragment on click the menu item button**

**Comment by singhalok641** [comment]
I want to work on this issue

**Comment by singhalok641** [comment]
You can use this END POINT: https://demo.openmf.org/fineract-provider/api/v1/self/savingsaccounts/21?associations=transactions for implementing the feature. 
The link shows an error .

**Comment by therajanmaurya** [comment]
@singhalok641 Here is documentation for testing the demo request in postman
https://github.com/openMF/self-service-app/wiki/Test-Mifos-API-in-Postman

**Comment by dilpreet2028** [comment]
I would like to work on this

**Comment by therajanmaurya** [comment]
Go ahead.

**Comment by dilpreet2028** [comment]
@therajanmaurya PR sent #136

**Comment by therajanmaurya** [comment]
Added in #136

**Comment by Habeebu** [comment]
I am trying to use the API, this method https://domain.com/fineract-provider/api/v1/savingsaccounts/227/transactions/11128
But I received this error,
{
  "timestamp": 1579618103606,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "org.springframework.dao.EmptyResultDataAccessException",
    "message": "Incorrect result size: expected 1, actual 0"
}
Any help, I checked and there is accountId and transactionId.

**Comment by tiwariritesh1700** [comment]
same Problem
