### ISSUE TITLE
Support for viewing, applyling Share Accounts

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#834]
**Details :**

Similar to Saving Accounts, and Loan Accounts, I will be using the same UI design for Share
Accounts, that’s adding Floating Action Button at the bottom of the fragment. Moreover,
currently on clicking a Share Account item, nothing happens, so will be working on adding
functionality to view Share Accounts.

**Comment by ivary43** [comment]
@miPlodder did you talk with Rajan for this?? We are on same project.

**Comment by ivary43** [comment]
Yes or no ??

**Comment by miPlodder** [comment]
@ivary43 I had a talk with @therajanmaurya today. He was having some issue on his side regarding number of Android Interns. Although, I told him about you, it would be better if you mail him.

**Comment by luckyman20** [comment]
We already have this feature.
