### ISSUE TITLE
Support for Customer Support/Chat

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#836]
**Details :**

I found this Chat SDK (https://github.com/chat-sdk/chat-sdk-android) which is an Open Source Project and free to use. We can integrate this in project, for providing Chat Support to the Customers.
Apart, from that we can even make the Customer Support Chat from scratch using Firebase Realtime Database. On the server side, we can add basic Web Interface for the staff to respond to the queries and messages from the users. Web Interface will require MFI staff’s login and view the queries from the User and reply them with solutions. 

Now, coming to the Client side, we will keep consistency in the UI, that is we will keep UI
design that will be similar to that of other Chat Application, so the UX is good and user wouldn’t
face much issues in using the Support/Chat functionality.

**Mockups :**

![image](https://user-images.githubusercontent.com/22195621/40178218-866562ec-59fe-11e8-83a2-be3bd9a601fd.png)
(Flow Architeture)
![image](https://user-images.githubusercontent.com/22195621/40178226-899987ae-59fe-11e8-875b-928db8fe2f0b.png)
(UI Design)

**Comment by RajaVamsi11** [comment]
@therajanmaurya @miPlodder I am interested in implementing this feature. What do you think about this? I had worked on Firebase before.
