### ISSUE TITLE
Refactor LoanAccount details

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#84]
![image](https://cloud.githubusercontent.com/assets/5724482/23249735/d1182b38-f9cb-11e6-8f93-14bb876bd5bf.png)

In this feature there is three button for now you have to show toast onclick button.

**Comment by sgatibaru** [comment]
Hi @therajanmaurya , there are many things I'm not getting with the self service app... I'm not the best java programmer but I'm very determined to contribute as i learn both android and java.

I'm figuring out a way to:
a) register a new user in the system who will have to be activated before he can use the app
b) Where i can get the app shown in the images above. The one i can see when i run the app is different from the one i can see.

I'll appreciate your help @therajanmaurya

**Comment by therajanmaurya** [comment]
@SkylerGatibaru  you do not have to make user. Here the demo credentials https://github.com/openMF/self-service-app/wiki. 
You have to implement this feature including the UI and logic.

**Comment by sgatibaru** [comment]
@therajanmaurya, thats for experimental purposes & i wanted to create a user and registration page that would link each user with the corresponding account.

**Comment by therajanmaurya** [comment]
@SkylerGatibaru  There is some complication during creating the self-service user. 
I am working on it. I will write some documentation as I will be done. Till that you can work with this credential.

**Comment by therajanmaurya** [comment]
@SkylerGatibaru Any update

**Comment by therajanmaurya** [comment]
fixed in #93
