### ISSUE TITLE
Add reCAPTCHA

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#844]
**Details :**

We can add reCAPTCHA during the Login process to enhance the Security of the app.
I have worked on two approaches to implement it. Firstly by generating random alphanumeric
characters, and then displaying then on a view, and validating them when user enters it.
Secondly, by using SafetyNet API (https://developer.android.com/training/safetynet/recaptcha)
​

**Comment by jaindiv26** [comment]
@miPlodder At the time of sign-up we do collect user mobile number, so instead of implementing reCAPTCHA the more secure way is to authenticate the user using the registered mobile number.

**Comment by luckyman20** [comment]
@jaindiv26 We are implementing this for not getting spam registrations, I think we have API in process for mobile verification.

@miPlodder Are you working on this already? If not I would like to work on it.

**Comment by miPlodder** [comment]
@luckyman20 This functionality requires some changes on server-side. You can talk to @edcable regarding those changes and then work on it. Or you can choose another API for reCaptcha which does not require server-side configuration, but before working on it get the API's you want to work on accepted by the Community Members.

**Comment by luckyman20** [comment]
@miPlodder I don't know if you have checked out this official reCaptcha API from Google - [Link of the API](https://developer.android.com/training/safetynet/recaptcha)

**Comment by miPlodder** [comment]
@luckyman20 Refer this blog post - [Link](https://www.androidhive.info/2018/04/android-recaptcha-safetynet/)

**Comment by luckyman20** [comment]
@miPlodder So I think we can go ahead with this API. Right?

**Comment by shiv07tiwari** [comment]
@miPlodder Can I implement this ?

**Comment by devansh-299** [comment]
@luckyman20 @miPlodder 
Should we close this issue as suggested here 
https://github.com/openMF/mobile-wallet/issues/336#issuecomment-466892192

if not, I would like to work on it as I too think implementing it during the self service client registration process is a nice idea

**Comment by miPlodder** [comment]
@devansh-299 Yep, correct, its a bad UI experience
