### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#846]
**Details :**

**(1) Adding Gradients**
We can add Colour Gradient, preferably bluish on screens where there is lesser textual content,
for instance Splash Activity, Passcode activity, or even on Widgets etc.

**(2) Submit Button at bottom**
One UI Enhancements that I have learnt by working on and using other Android Application, is
that adding full width Submit Button for the form improves the User Interface of the whole
activity. We can add similar buttons in various forms such as Sign In, Sign Up, Apply for loan,
etc.

![image](https://user-images.githubusercontent.com/22195621/40179868-ee8ea7c6-5a02-11e8-9925-42496e66eea8.png)

**(3) Limiting transaction Amount**
Currently, forms in app can accept amounts having no limit which causes many Crashes ( as it’s
not be in int/float limit). Instead of this, we can limit the amount entered dynamically,  up to 6
integer places and up to 2 decimal places (can be changed as per Organisation Convenience).
This approach is similar to that used in many payments like Google’s Tez Android App.

**Comment by drish1001** [comment]
May I work on this issue?

**Comment by devanshi7799** [comment]
@miPlodder i would like to work on this
