### ISSUE TITLE
Username and Image should be shown when Internet is not there in Home Fragment

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#847]
**Details :**

Currently, what happens is that in Home Fragment, Username’s TextView is blank, because it’s
being fetched for some time. Similarly, Total Savings and Total Loan Amount fields are also
empty. It’s a bad UI design in case of no or slow Internet.
Instead, we can store them in the Shared Preference and show them when Internet Connection is
slow, and update the Shared Prefs and data on the fields when the response from the Server is
fetched.

![_image](https://user-images.githubusercontent.com/22195621/40180088-98295ff6-5a03-11e8-818a-5a4646fe20ff.png)

We can atleast store and use Username, and Account Number for the Logged In user. We can
use Shared Preference for storing and clean them when the User logs out.
Moreover, ImageView shows “M” that means it uses Mifos as username when username is not
fetched. Instead we can use first character of the user name (that we have stored in Shared
Preference) and display it. And update the ImageView when the image is fetched. Even we can
cache the image and display it on ImageView.

**Comment by nikhil-sachdeva** [comment]
Can I work on this issue if it's still open?

**Comment by shiv07tiwari** [comment]
@miPlodder This is an important issue. Can I take this ?

**Comment by devansh-299** [comment]
@miPlodder @luckyman20  Can I work on this issue?

**Comment by luckyman20** [comment]
Covered in #1122
