### ISSUE TITLE
Add Social Auth Support for Login/SignUp

### ISSUE THREAD

**Issue by luckyman20** [openMF/self-service-app#880]
**Summary:**

There should social auth like Facebook, LinkedIn, Twitter etc. to ease up the process of registration and login process.

**Expected behaviour:**

Social Auth Options for registration and login.

**Observed behaviour:**

No Social Auth Options for registration and login.

@therajanmaurya May I start working on this?

**Comment by miPlodder** [comment]
@luckyman20 I think for Security Purpose this use-case is not relevant. You can ask the community regarding this in the mailing list.

**Comment by luckyman20** [comment]
@miPlodder Could you please elaborate how can this affect security of the app?

Let me tell discuss the approach too - 

When the user will click on the social auth button, he/she will be redirected to the Authentication page of that respective Social Media App (in case he/she is not already authenticated) then we will fetch all the necessary details from that Social Media App and then we will fill in the blanks from the detail we have got. After that user will have full right to edit it and then submit it.

**Comment by miPlodder** [comment]
@luckyman20 Since, Social Media information are public and are visible to everyone, even attacker. Moreover, you wouldn't find any Banking App asking for Social Authentication, it because of Privacy and Security concerns.

**Comment by luckyman20** [comment]
@miPlodder It Seems that I missed the security aspect. Thanks for pointing out.
