### ISSUE TITLE
Survey Button on the main dashboard is not producing any effect

### ISSUE THREAD

**Issue by kalpesh30** [openMF/self-service-app#881]
**Summary:**
The survey button in the main dashboard not working.

**Steps to reproduce:**

1. Open the app.
2. Log in to the app.
3. In the dashboard when we click on the survey button in the account options button nothing happens.

**Expected behaviour:**
Even if there are no surveys active at the current moment, it should display a message or survey activity or fragment should open.

**Observed behaviour:**
It's not showing any visible effect.

**Device and Android version:**

Model: Lenovo K6 Note
Android Version : Android Nougat 7.0

**Comment by kalpesh30** [comment]
May I please work on this issue?

**Comment by miPlodder** [comment]
@kalpesh30 This is a redundant issue. (https://github.com/openMF/mifos-mobile/issues/840) And PR for this issue has been created. (Only API integration work is left). 

You can remove this issue.
