### ISSUE TITLE
App getting crash in the Loan account list activity

### ISSUE THREAD

**Issue by kalpesh30** [openMF/self-service-app#882]
**Summary:**
When we open the Loan Account List in the app and scroll down, the app crashes.

**Steps to reproduce:**

1. Open the app and Login.
2. Open the Loan account List by clicking on the Loan Amount.
3. when we scroll down the list, the app crashes. 

**Expected behaviour:**

The app should not crash and should display the list properly.

**Observed behaviour:**

The app crashes.

**Device and Android version:**

Model: Lenovo K6 Note
Version: Android Nougat 7.0 (Stock Android)

**Screenshots:**

<img src="https://user-images.githubusercontent.com/35650966/45692245-ef97b780-bb77-11e8-80f1-d87a8dc01de9.png" width="250" height="400" />

<img src="https://user-images.githubusercontent.com/35650966/45691868-0ab5f780-bb77-11e8-8cec-3b9a06380965.png" width="250" height="400" />

**Comment by kalpesh30** [comment]
I would like to work on this issue. May I work on this issue?

**Comment by miPlodder** [comment]
@kalpesh30 The issue is relevant, you can work on it.

**Comment by kalpesh30** [comment]
@miPlodder  Can you please review this PR about this issue?
