### ISSUE TITLE
App crashes on pressing SUBMIT BENEFICIARY button of Update Beneficiary in the side menu.

### ISSUE THREAD

**Issue by e-qui-nox** [openMF/self-service-app#885]
**Summary:**

In the Beneficiary details page when Update Beneficiary is being selected from the side menu and after making the changes or without making any changes when the Submit Beneficiary button is being clicked, the app crashes.

**Steps to reproduce:**

1. Open the app and Login.
2. Click on Beneficiaries in Home Page.
3. Click on one of the entities.
4. Click on the side menu.
5. Click on Update Beneficiary.
6. After making changes or even without, Click on Submit Beneficiary.

**Expected behavior:**

It should Update the changes if made any or else get back to the Beneficiary Detail page 

**Observed behavior:**

The app crashes

**Device and Android version:**

Model: Samsung On Nxt
Version: Android Nougat 7.0

**Screenshots:**

![issue-gif](https://user-images.githubusercontent.com/40480466/45923412-dfc6fd00-bf02-11e8-8d2f-a7b11bab6ebd.gif)

**Comment by e-qui-nox** [comment]
May I please work on this issue?

**Comment by miPlodder** [comment]
@e-qui-nox It's a relevant issue. Although it's not happening on my device. You can start to work on it.

**Comment by migueldinisdev** [comment]
@miPlodder 
@e-qui-nox 

https://github.com/openMF/mifos-mobile/issues/931 same issue here.

Fixed in #933
