### ISSUE TITLE
Cannot Resolve Symbol: MifosNotification_Table Symbol

### ISSUE THREAD

**Issue by jmsperu** [openMF/self-service-app#888]
Hi, 

When editing on androi studio I see an error: "Cannot Resolve Symbol" "MifosNotification_Table Symbol"
and import org.mifos.mobilebanking.models.notification.MifosNotification_Table; is underlined. 
Path to file: mifos-mobile-1.0.0\app\src\main\java\org\mifos\mobilebanking\api\local\DatabaseHelper.java

**Comment by luckyman20** [comment]
@jmsperu Please clarify your issue in detail. Closing it. Will reopen if substantial detail is found.
