### ISSUE TITLE
Error text beneath EditText should be shown for all the EditText on clicking the Login Button

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#895]
**Summary:**

Error text beneath EditText should be shown for all the EditText on clicking the Login Button

**Steps to reproduce:**

Log into app without entering credentials

**Expected behaviour:**

Errors for all the EditText should be shown like shown in other apps like Paypal

**Observed behaviour:**

Error text are not shown for all the EditText

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![20181020_122512](https://user-images.githubusercontent.com/22195621/47252571-923ba280-d464-11e8-8f28-192c3e94d9f9.gif)

**Comment by letelete** [comment]
I'm working on it.

**Comment by letelete** [comment]
Waiting for review. BTW, I couldn't find this task on the GCI site, why is that?
