### ISSUE TITLE
Error text beneath EditText should be shown for all the EditText on clicking the Sign Up Button

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#896]
**Summary:**

Error text beneath EditText should be shown for all the EditText on clicking the Sign Up Button

**Steps to reproduce:**

Sign Up without entering any details

**Expected behaviour:**

Errors for all the EditText should be shown like shown in other apps like Paypal

**Observed behaviour:**

Error text are not shown for all the EditText

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![20181020_122528](https://user-images.githubusercontent.com/22195621/47252635-96b48b00-d465-11e8-8ba8-911709489845.gif)

**Comment by letelete** [comment]
I'll take this issue

**Comment by letelete** [comment]
Review ready! https://github.com/openMF/mifos-mobile/pull/907

**Comment by shiv07tiwari** [comment]
@miPlodder Can I work on this issue.
I am interested in contributing to this organisation .

**Comment by shiv07tiwari** [comment]
@letelete  Hello. Can I take up this issue or this is still under process ?
