### ISSUE TITLE
Working of DatePicker on creating Loans are causing Inconsistency

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#898]
**Summary:**

Working of Calender on creating Loans are causing Inconsistency

**Steps to reproduce:**

Create a new loan

**Expected behaviour:**

Submission date should show the "Present Date" and ImageView should be removed
Whereas for Expected Disbursement should show the dates after "Present Date" as selectable, and previos dates as non-selectable.

**Observed behaviour:**

Both Datepickers are selectable to previous dates of "Present Date"

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![20181020_122608](https://user-images.githubusercontent.com/22195621/47252686-615c6d00-d466-11e8-8311-a116f28ed107.gif)

**Comment by migueldinisdev** [comment]
Update: working on this

**Comment by etlhsu** [comment]
@miPlodder I am not working on this task, but to clarify, the submission date should not be selectable with a DatePicker.

**Comment by migueldinisdev** [comment]
@ethan627hsu I thought about that too, it was on my to-do list :p 

Thanks for pointing out!

**Comment by miPlodder** [comment]
Yeah, that what I have written. Present date should be shown means no date picker, just text.

**Comment by etlhsu** [comment]
@miPlodder Thanks for the clarification, it is good to make sure contributors are reading clear documentation, and don't waste their time on an obsolete implementation.
