### ISSUE TITLE
Recent Transaction Fragment shows Snackbar every time on opening

### ISSUE THREAD

**Issue by miPlodder** [openMF/self-service-app#899]
**Summary:**

Recent Transaction Fragment shows Snackbar every time on opening

**Steps to reproduce:**

Go to Navigation Drawer > Recent Tranactions

**Expected behaviour:**

Snackbar should not pop up everytime. (no need to show the snackbar)

**Observed behaviour:**

Instead, it pops up everytime

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

![20181020_122636](https://user-images.githubusercontent.com/22195621/47252761-78e82580-d467-11e8-84ba-1b6f2970dc85.gif)

**Comment by migueldinisdev** [comment]
@miPlodder 

Hi! I can fix this. But I'm not understand what's the expected behaviour. The snackbar is showing up everytime and it shouldn't. But when should it appear exactly? 

Thanks !

**Comment by miPlodder** [comment]
@MigDinny This task is for GCI students.

**Comment by migueldinisdev** [comment]
@miPlodder And I am a GCI student. I just didn't claim the task yet, was going to do it in a few minutes...

EDIT: claimed it right now.

**Comment by miPlodder** [comment]
@MigDinny Sure, hurry up and claim the task then you are good to go.

I have updated the expected behaviour above.

**Comment by migueldinisdev** [comment]
@miPlodder I did it :)

**Comment by migueldinisdev** [comment]
@miPlodder I'm sorry but I'm not understanding again... Do you mean TextView? Because I cannot see any EditText present in **row_recent_transaction.xml** and in **fragment_recent_transactions.xml**

Could you be more clear? Thanks!!

**Comment by miPlodder** [comment]
@MigDinny We need not show any Snackbar, just like other UI's where we fetch a list of item, no Snackbar or Toast is shown when the fetch is completed. (updated above too)

**Comment by migueldinisdev** [comment]
@miPlodder I got it now! Thanks for the answer. Will work on it.
