### ISSUE TITLE
Redundant code for ProgressDialog

### ISSUE THREAD

**Issue by dilpreet2028** [openMF/self-service-app#90]
**Summary:**

LoanAccountsDetailActivity and SavingAccountDetailActivity **initializes another progress dialog** and does not use the progress dialog already initialized in the BaseActivity.

Already working on it .

**Comment by therajanmaurya** [comment]
@dilpreet96 There is no class with name `LoanAccountsDetailActivity` and `LoanAccountsDetailActivity` Can you please give me link.

**Comment by therajanmaurya** [comment]
Yes, It is. Some of the contributors are working on issue refactoring and implementing the new mockups.

**Comment by dilpreet2028** [comment]
yes , here's the link :- https://github.com/openMF/self-service-app/blob/development/app/src/main/java/org/mifos/selfserviceapp/ui/activities/LoanAccountsDetailActivity.java

**Comment by therajanmaurya** [comment]
@dilpreet96  I got it I was thinking about the android-client app Sorry for that.
Here is the issue #84 and #82

**Comment by dilpreet2028** [comment]
So Should , I send a quick PR ?

**Comment by therajanmaurya** [comment]
I do not think so you will break some work. If you wanna work I can make you a issue.

**Comment by therajanmaurya** [comment]
Let me know.

**Comment by dilpreet2028** [comment]
Yes I am interested in solving other issues

**Comment by therajanmaurya** [comment]
Wait for some time. Let me look.

**Comment by therajanmaurya** [comment]
Let me make some mockup.

**Comment by dilpreet2028** [comment]
Okay :) , till then i will search for more bugs

**Comment by therajanmaurya** [comment]
Here you go @dilpreet96  #91

**Comment by therajanmaurya** [comment]
I am closing this issue for now. No make sense. 
Thanks and Welcome in the community.

**Comment by therajanmaurya** [comment]
Please comment If you want to work in this issue.

**Comment by dilpreet2028** [comment]
Yes, I want to work on this issue
