### ISSUE TITLE
Loan Account Summary Feature

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#91]
**Summary:**

This is the Loan Account summary for the LoanAccount feature
This is the [API](https://demo.openmf.org/api-docs/apiLive.htm#selfloan). 
You can use Loan Account Number: 29 and put this static for now in the contractor. 
When we compile the whole feature we will make dynamic 

**Expected behavior:**

Should be a page for Loan Account Summary.

**Observed behavior:**

There are no summary options.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**
![image](https://cloud.githubusercontent.com/assets/5724482/23317396/49247888-faf4-11e6-8d7b-bd77fab97b09.png)

**Note: Make this feature in fragment and add this fragment in Navigation Drawer. Add a item in navigation drawer with "LoanAccout Summary" and onclick make fragment transaction with this fragment.**

**Comment by dilpreet2028** [comment]
I want to work on this

**Comment by therajanmaurya** [comment]
@dilpreet96 Go ahead. We are looking forward to your contribution.

**Comment by therajanmaurya** [comment]
I know these mockups are old So please Use CardView and other Material Design tools that you want.

**Comment by dilpreet2028** [comment]
Okay :)

**Comment by therajanmaurya** [comment]
If You need any help ask me on Gitter channel. 
Best of Luck 👍

**Comment by therajanmaurya** [comment]
Added in #92
