### ISSUE TITLE
Bug: Unresolved dependencies error while building app

### ISSUE THREAD

**Issue by letelete** [openMF/self-service-app#910]
**Summary:**

Can't build the app, because of compiler unresolved dependencies errors, such as:

> Failed to resolve: multidex
> Failed to resolve: multidex-instrumentation

**Steps to reproduce:** 

1. Clone development branch
2. Open project in your IDE
3. Build project

**Expected behaviour:**

Complete build

**Observed behaviour:**

As I mentioned before, there are unresolved dependencies errors:

![image](https://user-images.githubusercontent.com/18665370/47484032-f7174400-d83a-11e8-9c3b-0e94987db872.png)

Running `./gradlew --debug check` logs:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:getDependencies'.
Could not find multidex.jar 
```
For more details, check pastebin where I've posted more details from logs
 https://pastebin.com/XiXbYFAW

**Device and Android version:**

Mobile device doesn't matter here, so I'll just say that I'm using Android Studio as an IDE

**Screenshots:**

![image](https://user-images.githubusercontent.com/18665370/47484124-42c9ed80-d83b-11e8-9905-b47ad510db7f.png)

**Comment by letelete** [comment]
@miPlodder  This issue appears in #907, #908. Fix for this issue might be #909

**Comment by migueldinisdev** [comment]
I was having this issue in my project after cloning it. I actually solved it by changing some stuff in **build.gradle**. I added it to **.gitignore** though.

UPDATE:

What I did was a temporary workaround in my computer. I increased **minSdkVersion** to **21** and removed multidex library dependency.

As described [here](https://developer.android.com/studio/build/multidex), projects with minSdkVersion >= 21 do NOT require multidex library to be imported in build.gradle. That way I avoided that error.

_This is only a temporary solution working as a workaround_

**Comment by m-sameer** [comment]
@miPlodder I'm able to fix this issue by updating the `compileSdkVersion` and some dependencies. Can you please add this as a GCI task?
