### ISSUE TITLE
App shuts down after PIN Code

### ISSUE THREAD

**Issue by migueldinisdev** [openMF/self-service-app#918]
**Summary:**

The app shuts down after typing the PIN Code.

**Steps to reproduce:**

1. `git checkout development`
2. `git pull origin` (make sure the development branch is updated with upstream's)
3. Open the app
4. Type your PIN
5. The exact moment you touch on the last digit, a FATAL Exception is triggered

**Expected behaviour:**

Log in normally

**Observed behaviour:**

The app just shuts down with no report or message.

**Device and Android version:**

Emulator Android 9
Pixel 2
API 28

**Screenshots:**

![image](https://user-images.githubusercontent.com/6632800/47623937-91fb7100-db0e-11e8-939e-e2d999a3b43b.png)

**Note:** I suspect it has to do with build.gradle. I'm not sure if this problem is happening only with me but it is happening with _development_ branch checked out and updated with no staged/unstaged modified files. Logcat says something about some kind of a String implementation not being found in passcode library. I went to that repo to check if it was updated and it wasn't... so, I don't know if this is only happening with me.

**Can anyone try to reproduce this and tell me something?**

**Comment by etlhsu** [comment]
@MigDinny The error is that the method that is unable to run is "native". This means that the method is implemented in a separate C file with the JNI (Java Native Interface). But Android cannot find the C implementation of the method. Read more [here](https://stackoverflow.com/questions/6101311/what-is-the-native-keyword-in-java-for).

**Comment by migueldinisdev** [comment]
**SOLVED**

I deleted my local repo and cloned it again.
