### ISSUE TITLE
Adapter Attachment Error in RecyclerView when viewing "Charges" and "Accounts" pages

### ISSUE THREAD

**Issue by etlhsu** [openMF/self-service-app#919]
**Summary:**

When opening the main pages for viewing accounts and charges, an error log is written speaking of how a recyclerview handled a case where no adapter is attached to it. I decided to have this issue scope both "Accounts" and "Charges" pages as the exact same log is sent out with a very similar entry point.  

**Steps to reproduce:**

1. Run the Mifos Mobile app through an IDE, and validate that the device is able to log information through Logcat.
2. While in the Logcat view, filter the logs to tag `E/RecyclerView` by typing the tag into the search bar, this will help show the error log clearly rather than combined with other log messages.
2. Go through the splash screen with the password login.
3. At the main home screen, click on the "Charges" or "Accounts" button.
4. Observe the new error log that has been added to Logcat.

**Expected behaviour:**

The app should not be reporting this kind of error, adapters should be attached to their respective RecyclerViews, and RecyclerViews with no adapter should be dealt with in a way that causes no error. 

**Observed behaviour:**

Adapters from the "Charges" and "Accounts" pages are not being attached to respective RecyclerViews when opened, the RecyclerViews log an error message signifying the behavior:

`E/RecyclerView: No adapter attached; skipping layout`

**Device and Android version:**

Google Pixel, Physical Device and Emulator. Android 9.0 Pie.

**Comment by luckyman20** [comment]
Issue does not exist anymore.
