### ISSUE TITLE
Transfer funds between own savings accounts

### ISSUE THREAD

**Issue by edcable** [openMF/self-service-app#94]
**Summary:**

As a self-service user, I want to transfer funds between savings accounts between two different accounts that belong to me. 

See

![screen shot 2017-02-27 at 5 32 47 pm](https://cloud.githubusercontent.com/assets/823454/23387717/304e552e-fd13-11e6-8891-d2fe2985ca15.png)

See https://demo.openmf.org/api-docs/apiLive.htm#selftransfertemplate

**Comment by mayank-kgp** [comment]
@therajanmaurya I would like to work on this.

**Comment by therajanmaurya** [comment]
Added in #169
