### ISSUE TITLE
Lint errors and warnings

### ISSUE THREAD

**Issue by m-sameer** [openMF/self-service-app#940]
**Summary:**
It is a good practice to keep the codebase free of lint warnings, to make it more robust, performant, and readable.

**Steps to reproduce:**
Go to Analyze -> Inspect Code... -> select Whole project

**Screenshot:**
![screenshot from 2018-11-20 23-17-18](https://user-images.githubusercontent.com/28915865/48792549-8c163b80-ed1a-11e8-8d38-9fdabbb5da96.png)

**Expected behaviour:**
Minimised number of warnings, leaving only those whose fixation would crash the app itself.

**Observed behaviour:**
Following warnings and errors are present in the codebase:
- Android - 170 errors and 1010 warnings
- Groovy - 2 warnings
- Java - 2 errors
- Kotlin - 25 warnings
- XML - 4 errors and 5 warnings

**Comment by RajaVamsi11** [comment]
@therajanmaurya @miPlodder Working on this issue.

**Comment by RajaVamsi11** [comment]
As of now lint warnings and errors have been increased.
- Android - 100 errors and 5178 warnings
- Groovy -  2 warnings
- Java - 2 errors and 1395 warnings
- Kotlin - 24 warnings, 3 weak warnings and 1 info
- Properties Files - 2 warnings
- Spellings - 1000 typos
- XML - 4 errors and 6 warnings

![screenshot from 2019-01-29 15-50-28](https://user-images.githubusercontent.com/30550059/51901836-9de12280-23de-11e9-92fe-c36ca00ad149.png)
