### ISSUE TITLE
Resource compilation failed while setting up

### ISSUE THREAD

**Issue by nikhil-sachdeva** [openMF/self-service-app#967]
**Summary:**

Compilation failed while running the app on device with the following error.

Android resource compilation failed
Output:  /Users/Nikhil/AndroidStudioProjects/mifos-mobile/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fr/values-fr.xml:6: error: unescaped apostrophe in string
"Pour afficher les transactions dans votre compte d'épargne, allez à la section Comptes, cliquez sur le compte d'épargne requis, cliquez sur les trois points présents dans le coin supérieur droit et sélectionnez l'option Transaction.".
/Users/Nikhil/AndroidStudioProjects/mifos-mobile/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fr/values-fr.xml:6: error: could not parse array item.
/Users/Nikhil/AndroidStudioProjects/mifos-mobile/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fr/values-fr.xml:8: error: unescaped apostrophe in string
"Pour créer un héritier, allez à l'héritier sur la page principale de l'application, puis cliquez sur le bouton dans le coin inférieur droit, sélectionnez l'option de numérisation qui ouvrira la caméra de l'appareil, scannez le code QR de la personne pour laquelle vous souhaitez créer un héritier, après avoir rempli les données requises, créer des héritiers en utilisant le code QR".
/Users/Nikhil/AndroidStudioProjects/mifos-mobile/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fr/values-fr.xml:8: error: could not parse array item.
/Users/Nikhil/AndroidStudioProjects/mifos-mobile/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fr/values-fr.xml:9: error: unescaped apostrophe in string
...........

**Steps to reproduce:**

Setting up the app on a device/emulator.

**Device and Android version:**

Redmi Note 3 API 23

**Comment by miPlodder** [comment]
@nikhil-sachdeva If you are still facing some issue, then you can clone delete the fork, fork again and clone the repo. Try again fresh and send PR for this.
