### ISSUE TITLE
Add checks for login fields

### ISSUE THREAD

**Issue by joydeepsaha05** [openMF/self-service-app#97]
**Summary:**

A progress dialog is seen on the login screen even when the Username and Password field is left blank and the login button is selected.

**Steps to reproduce:**

How can we reproduce the issue?

**Expected behavior:**

Prompt the user to input username and/or password. Although a prompt is seen, the progress dialog shouldn't.

**Observed behavior:**

A toast message along with the progress dialog saying "Logging in" is seen.

**Device and Android version:**

Nexus 5X API 24 (Emulator)

**Screenshot:**

![screenshot_1488390593](https://cloud.githubusercontent.com/assets/12814192/23473308/bac0f356-fed5-11e6-826c-714c1b8cd1e0.png)

**Comment by joydeepsaha05** [comment]
Just saw this issue: #57 
Is this part of some other, bigger code changes?

**Comment by therajanmaurya** [comment]
@joydeepsaha05 Go ahead and fix this issue.

**Comment by therajanmaurya** [comment]
@joydeepsaha05 Community discussion is not the issue. It is the normal discussion.

**Comment by Pritom14** [comment]
Please review #100 . I have added the checks for login field and the progress dialog won't show up if either the username is empty or password field is empty, instead it will prompt the user to re-enter the fields.

![17036726_1741282042850565_2080568137_o](https://cloud.githubusercontent.com/assets/16569570/23494713/7184e07a-ff3a-11e6-89f7-3faeef16cb59.jpg)

**Comment by Pritom14** [comment]
@therajanmaurya can you please review it

**Comment by Pritom14** [comment]
I have fixed all the issues and submitted a pull request again #101 , can you please review it @therajanmaurya

**Comment by therajanmaurya** [comment]
fixed in #118
