### ISSUE TITLE
Fix grammar mistakes and translate missing strings in portuguese strings.xml

### ISSUE THREAD

**Issue by IgorWilbert** [openMF/self-service-app#975]
**Summary:**

As a native portuguese speaker, I noticed typos and grammar mistakes in the **strings.xml** file for Portuguese translation. Also, there are some strings which still hasn't been translated from English to Portuguese

**Expected behaviour:**

There should not be any grammar mistakes or typos in the Portuguese translation and all strings that can be meaningfully translated from English to Portuguese should be translated.

**Comment by IgorWilbert** [comment]
I want to work on this issue, as soon as #962 gets merged

**Comment by jmig5776** [comment]
I will take up this issue

**Comment by IgorWilbert** [comment]
@jmig5776 #962 wasn't merged yet, it is bad practice to have multiple PRs for the same part of the code.

**Comment by jmig5776** [comment]
Ohh okk okk you work on it.

**Comment by ShivangiSingh17** [comment]
Please can I  work on this issue ?
