### ISSUE TITLE
Filter icon is not aligned properly while using Search in Account

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#976]
**Summary:**

Filter icon is displaced while using search option, which leads to bad UI.

**Steps to reproduce:**

1. Go to Accounts.
2. Open search bar

**Expected behaviour:**

Either this should be fixed, or maybe we can remove the filter option while user is using the search bar.

**Observed behaviour:**

![e1a3c282-2213-481b-b7a9-231849bf1033](https://user-images.githubusercontent.com/38163725/50855396-b1840500-13ad-11e9-95b8-9131c8cc79ae.jpeg)

**Screenshots:**
Added.
***Phone**
Redmi Note5 pro 
Android 8.1.0

**Comment by shiv07tiwari** [comment]
@luckyman20 @miPlodder  Can I work on this issue ?

**Comment by luckyman20** [comment]
Go ahead on fixing this.

**Comment by shiv07tiwari** [comment]
@luckyman20 I have some Issues regarding this.
If the user is using the search option, then I guess he/she doesn't need the filter option.
    
What's happening is that we need to set the size for the search bar as per device width, for which we will have to override the SearchView methods. 
So instead of that we can use "ifRoom" for FilterOptions.
