### ISSUE TITLE
Filters still enabled after Search in Accounts Section

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#978]
Summarize your issue in one sentence (what goes wrong, what did you expect to happen).
In Accounts, the filters are still clicked, even after the user uses search option, which basically removes all the filters.
**Steps to reproduce:**
1. Apply any filter.(Suppose closed)
2. Use search and type something in search bar, then cancel the search option (List is now unfiltered)
3. Open filters
You will see that "closed" is still checked.
**Expected behaviour:**
Filters should be removed as the list is now showing unfiltered items.

**Comment by shiv07tiwari** [comment]
@luckyman20  @miPlodder   Can I work on this issue ?

**Comment by vaibhav2203** [comment]
hey, can i work on this issue? @luckyman20 @miPlodder

**Comment by shiv07tiwari** [comment]
@vaibhav2203  I am already fixing this.

**Comment by luckyman20** [comment]
@shiv07tiwari We just discussed on the previous issue that user might want to search from a filtered list. The issue would be that if filters are applied then they should not get removed when user clicks on search button.

**Comment by shiv07tiwari** [comment]
@luckyman20 What I am saying is that when we do the steps I wrote above, the filter option is still clicked, but the filter is not applied. So yes I get your point, we should retain the filter while searching.
Working on this. !
