### ISSUE TITLE
App crashes on clicking transaction in closed saving account.

### ISSUE THREAD

**Issue by jsuyash1514** [openMF/self-service-app#979]
**Summary:**

When the user clicks on "Transactions" in the closed saving account details, app crashes.

**Steps to reproduce:**

1.) Go to the accounts tab.
2.) Then select the closed account 000000031.
3.) Then click on "Transactions".

**Expected behaviour:**

If the transaction list is empty, it should display "No recent transactions".

**Observed behaviour:**

As I clicked on "Transaction", it opened "SavingAccountTransactionFragment" and then the app crashed. 

**Device and Android version:**

Xiaomi Redmi Note 3
Android 6.0.1, API 23

**Screenshots:**

![screenshot_2019-01-13-15-30-14-452_org mifos mobilebanking](https://user-images.githubusercontent.com/32803444/51084131-02e41980-174b-11e9-8c95-0b2ea8d7714d.png)

**Comment by jsuyash1514** [comment]
@luckyman20  Can I work on this issue?

**Comment by luckyman20** [comment]
Yeah, go ahead.
