### ISSUE TITLE
Strings in row_client_charge.xml are Hardcoded

### ISSUE THREAD

**Issue by lokeshkvn** [openMF/self-service-app#98]
**Summary:**

Strings in Relative layout of row_client_charge.xml are Hardcoded 

**Steps to reproduce:**

N.A

**Expected behavior:**

These strings must be added in strings.xml file instead of hardcoding it.

**Observed behavior:**

N.A

**Device and Android version:**

N.A

**Screenshots:**

N.A

**Comment by lokeshkvn** [comment]
I am a beginner to the open-source community and I would like to work on it.

**Comment by Pritom14** [comment]
The strings are already present in strings.xml file

**Comment by lokeshkvn** [comment]
Hi, can you please review the PR #99 ?

**Comment by therajanmaurya** [comment]
fixed in #99
