### ISSUE TITLE
Search account by account number

### ISSUE THREAD

**Issue by jsuyash1514** [openMF/self-service-app#980]
**Summary:**

In the accounts tab, the search bar gives the result only if the "product name" contains the input string.
A new feature can be added, to search by "account number".   

**Steps to reproduce:**

In the accounts tab, enter "44" in the search bar. It should return the list of accounts with a/c number containing "44". 

@luckyman20  Should I work on this?

**Comment by luckyman20** [comment]
You can, but after solving the previous issue. I would recommend working on one issue at a time.
