### ISSUE TITLE
DatePicker's highlighted date is set to current date even after user selects a different date.

### ISSUE THREAD

**Issue by ravi-kishan** [openMF/self-service-app#983]
**Summary:**

DatePicker's highlighted date is set to current date even after user selects a different date.

**Steps to reproduce:**
Goto->Accounts->Loan fragment
Choose floating action button to apply for loan
Set expected disbursement date to future value and open datepicker dialog again.

**Expected behaviour:**

DatePickers highlighted date should be the date selected by user previously

**Observed behaviour:**

DatePickers highlighted date is current date always

**Device and Android version:**

Motorola Moto G4 (Android 7.0,API 24)
**Screenshots:**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31040431/51192109-d88d8a00-190b-11e9-843f-528bf4b063ab.gif)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by ravi-kishan** [comment]
@luckyman20 I would like to work on this.

**Comment by luckyman20** [comment]
@ravi-kishan Go ahead.

**Comment by abhin2149** [comment]
Can I work on this issue?

**Comment by ravi-kishan** [comment]
Yes you can. @luckyman20 sorry for not solving it in time.

**Comment by abhin2149** [comment]
I have fixed the issue in my forked repo in a different branch but not committed yet.How should i proceed?
