### ISSUE TITLE
Account list is null if no filter is selected

### ISSUE THREAD

**Issue by shiv07tiwari** [openMF/self-service-app#985]
**Summary:**
When the user opens filter options, and if he/she doesn't select any options and clicks filter, then the list is null 
**Steps to reproduce:**
1. Open accounts
2. Open filters, don't select any option and click filter
3. We see that the list disappears.

**Expected behaviour:**
If no filter is selected, all the accounts should be displayed.

**Observed behaviour:**

Blank page

**Comment by shaliniv16** [comment]
@shiv07tiwari can I work on this issue?

**Comment by shiv07tiwari** [comment]
Actually i opened this issue so that I can work on it @shaliniv16 .
At least you should have waited for my response before opening a PR.
@luckyman20

**Comment by luckyman20** [comment]
@shiv07tiwari You can go ahead on solving this.

**Comment by shaliniv16** [comment]
@luckyman20 @shiv07tiwari I will keep that in mind from next time.

**Comment by geekanamika** [comment]
Fixed in #1200
