### ISSUE TITLE
Missing some translation in hindi language

### ISSUE THREAD

**Issue by ShivangiSingh17** [openMF/self-service-app#987]
**Summary:**

The application is missing some translation in Hindi language

**Steps to reproduce the issue:**

1. Go to settings.
1. Change language to hindi.

**Expected behaviour:**

All strings should be translated to Hindi.  

**Observed behaviour:**

Some strings do not have Hindi tranlation.

**Device and Android version:**

Vivo 1724 
Android 8.1.0
Funtouch OS 4.0

**Comment by ShivangiSingh17** [comment]
May I please work on this issue?

**Comment by refactor-droidyy** [comment]
can I work on this issue?

**Comment by geekanamika** [comment]
@refactor-droidyy Added GCI label on it :)

**Comment by devanshi7799** [comment]
@geekanamika can i work on this? or is it just for GCI?

**Comment by luckyman20** [comment]
Covered in #1913
