### ISSUE TITLE
Fab appears and disappears abruptly in Accounts Section

### ISSUE THREAD

**Issue by rahul-jha98** [openMF/self-service-app#988]
**Summary:**

Fab appears and disappears abruptly when switching from loan to other fragment in accounts

**Steps to reproduce:**

From home go to Accounts section and then swipe to Loan and then to Share.

**Expected behaviour:**

The Add Loan Fab should animate and grow on appear.

**Observed behaviour:**

The fab will appear in a snap. Like in one frame its there and in just next its gone.

**Device and Android version:**

Moto G5 Plus, Android 8.1

**Screenshots:**
Original Behaviour

![original](https://user-images.githubusercontent.com/29267275/51434734-c9049d00-1c8d-11e9-864f-390f6c55a937.gif)

Expected Behaviour
![modified](https://user-images.githubusercontent.com/29267275/51434739-d883e600-1c8d-11e9-8827-143d9ae0c18e.gif)

**Comment by rahul-jha98** [comment]
@luckyman20 Since it was only 2 lines of change I took the liberty to open the pull request without asking whether I should work on it. 
If you don't need the new animated fab entry and exit then I shall close the PR. :)

**Comment by luckyman20** [comment]
@rahul-jha98 We very much need your contribution but there are some contribution guidelines which you need to follow. 

Now Since you have made the PR for this issue, it is okay. But please remember to ask for it before working on the issue even if it is a one line code change.

**Comment by rahul-jha98** [comment]
Sorry. As I am new to open source I made the silly mistake. 
Henceforth, I shall follow the guidelines strictly.
