### ISSUE TITLE
Wrong title in Help Section

### ISSUE THREAD

**Issue by rahul-jha98** [openMF/self-service-app#993]
**Summary:**

Going to the Help Section in the app shows Home as title instead of Help

**Steps to reproduce:**

Going to Help Section of the app

**Expected behaviour:**
Title should be Help

**Observed behaviour:**
Title is Home

**Device and Android version:**
Moto G5 Plus, Android 8.1

**Screenshots:**

![screenshot_20190120-205913](https://user-images.githubusercontent.com/29267275/51441380-d013c580-1cf6-11e9-81a8-064eb73dcf11.png)

**Comment by rahul-jha98** [comment]
@luckyman20 Can I begin working on this issue?

**Comment by harrycode007** [comment]
Can I begin working on this issue?
