### ISSUE TITLE
Search Bar not occupying whole screen space in landscape

### ISSUE THREAD

**Issue by rahul-jha98** [openMF/self-service-app#997]
**Summary:**

In the help section in landscape mode the search view expands to only around half the screen which looks kind of inconsistent with portrait mode. 

**Steps to reproduce:**

Go to Help Section, rotate device to landscape, then on expanding search view its is only half the length of screen.

**Expected behaviour:**

It should take whole of the screen width.

**Device and Android version:**

Moto G5 Plus, Android 8.1 Oreo

**Screenshots:**

![screenshot_20190121-124927](https://user-images.githubusercontent.com/29267275/51458700-2840db00-1d7c-11e9-995c-ecbf0330bc98.png)

**Comment by rahul-jha98** [comment]
@luckyman20 Should I start working on the issue

**Comment by luckyman20** [comment]
@rahul-jha98 We should not focus on landscape things as there is no utility of landscape (you can refer to other apps like this which are out in the market). Rather you can create a issue of fixing all the screens to portrait.

**Comment by luckyman20** [comment]
@rahul-jha98 Close this issue.
